function Test = test_detailed_cyclo_stage5(Input, R, Thy)
%TEST_DETAILED_CYCLO_STAGE5
% Test bridge states, individual thyristor currents,
% converter-group input currents, and transformer currents.

%% =========================================================
% Stage 1: Prepare parameters
%% =========================================================

P = prepare_cyclo_simulation_inputs( ...
    Input, ...
    R, ...
    Thy);

%% =========================================================
% Stage 2: Firing reference and voltage synthesis
%% =========================================================

Ref = ...
    generate_cyclo_firing_reference(P);

[Voltage, State] = ...
    synthesize_cyclo_voltage( ...
        P, ...
        Ref);

%% =========================================================
% Stage 3: Zero-current intervals
%% =========================================================

[Voltage, Zero] = ...
    apply_cyclo_zero_intervals( ...
        P, ...
        Voltage);

%% =========================================================
% Stage 4: Motor current
%% =========================================================

Current = ...
    calculate_cyclo_motor_current( ...
        P, ...
        Voltage, ...
        Zero);

%% =========================================================
% Stage 5: Device currents
%% =========================================================

Device = ...
    calculate_cyclo_device_currents( ...
        P, ...
        State, ...
        Current);
Harmonics = ...
    calculate_cyclo_source_harmonics( ...
        P, ...
        Voltage, ...
        Device);
Loss = ...
    calculate_cyclo_converter_losses( ...
        P, ...
        Voltage, ...
        Current, ...
        Device, ...
        Thy);
%% =========================================================
% Analytical CycloTool harmonic reference
%% =========================================================

AnalyticalHarmonics = ...
    harmonic_calculation( ...
        Input, ...
        R);
%% =========================================================
% Physical ABB topology diagnostics
%% =========================================================

thyristorsPerPhaseGroup = ...
    Device.numberOfThyristorsPerBridgePair;

physicalThyristorCount = ...
    Device.totalPhysicalThyristors;

expectedThyristorCount = ...
    Device.expectedPhysicalThyristors;

positiveBridgeDeviceCount = ...
    size( ...
        Device.positiveBridgeState, ...
        2);

negativeBridgeDeviceCount = ...
    size( ...
        Device.negativeBridgeState, ...
        2);

%% =========================================================
% Representative thyristor diagnostics
%% =========================================================

representativeThyristorRms = ...
    Device.thyristorRmsCurrent(1,1,1);

representativeThyristorAverage = ...
    Device.thyristorAverageCurrent(1,1,1);

representativeThyristorPeak = ...
    Device.thyristorPeakCurrent(1,1,1);

representativeTurnOnCount = ...
    Device.turnOnCount(1,1,1);

representativeTurnOffCount = ...
    Device.turnOffCount(1,1,1);
%% =========================================================
% Representative negative-bridge thyristor diagnostics
%% =========================================================
%
% Device column 7 is the first thyristor position in the
% negative converter bridge:
%
%   Column 1 = PT1 = T111
%   Column 7 = NT1 = T211
%
% Indices:
%   First index  = thyristor position
%   Second index = converter group
%   Third index  = motor output phase

representativeNegativeThyristorRms = ...
    Device.thyristorRmsCurrent(7,1,1);

representativeNegativeThyristorAverage = ...
    Device.thyristorAverageCurrent(7,1,1);

representativeNegativeThyristorPeak = ...
    Device.thyristorPeakCurrent(7,1,1);

representativeNegativeTurnOnCount = ...
    Device.turnOnCount(7,1,1);

representativeNegativeTurnOffCount = ...
    Device.turnOffCount(7,1,1);

%% =========================================================
% Group current diagnostics
%% =========================================================

groupCurrentRmsA = ...
    Device.representativeGroupSourceCurrentRms(1,:);

groupCurrentRmsB = ...
    Device.representativeGroupSourceCurrentRms(2,:);

groupCurrentRmsC = ...
    Device.representativeGroupSourceCurrentRms(3,:);

groupCurrentMeanRms = ...
    mean( ...
        Device.representativeGroupSourceCurrentRms, ...
        1);
%% =========================================================
% Source-current magnitude diagnostic
%% =========================================================
%
% P.Itr is mapped from:
%
%   R.I1S
%
% and represents the dimensioned transformer secondary
% fundamental RMS current.
%
% groupCurrentMeanRms contains one mean RMS value for each
% converter transformer secondary group.

dimensionedSecondaryCurrent = ...
    P.Itr;

sourceCurrentRatio = ...
    groupCurrentMeanRms ...
    / dimensionedSecondaryCurrent;

sourceCurrentErrorPercent = ...
    100 ...
    * ( ...
    groupCurrentMeanRms ...
    - dimensionedSecondaryCurrent) ...
    / dimensionedSecondaryCurrent;

groupCurrentUnbalancePercent = ...
    zeros(1,P.TC);

for groupNumber = 1:P.TC

    groupPhaseRms = ...
        Device.representativeGroupSourceCurrentRms( ...
            :, ...
            groupNumber);

    groupMean = ...
        mean(groupPhaseRms);

    if groupMean > 0

        groupCurrentUnbalancePercent(groupNumber) = ...
            100 ...
            * ( ...
            max(groupPhaseRms) ...
            - min(groupPhaseRms) ...
            ) ...
            / groupMean;

    else

        groupCurrentUnbalancePercent(groupNumber) = NaN;

    end

end


%% =========================================================
% Conduction-state diagnostics
%% =========================================================

totalThyristorStates = ...
    numel(Device.thyristorState);

activeThyristorStates = ...
    nnz(Device.thyristorState);

thyristorConductionFraction = ...
    activeThyristorStates ...
    / totalThyristorStates;

%% =========================================================
% Positive and negative bridge interlock diagnostic
%% =========================================================

positiveBridgeActive = ...
    any( ...
        Device.positiveBridgeState, ...
        2);

negativeBridgeActive = ...
    any( ...
        Device.negativeBridgeState, ...
        2);

simultaneousBridgeSamples = ...
    nnz( ...
        positiveBridgeActive ...
        & negativeBridgeActive);
%% =========================================================
% Active physical-device count diagnostics
%% =========================================================

positiveDeviceCount = ...
    sum( ...
        Device.positiveBridgeState, ...
        2);

negativeDeviceCount = ...
    sum( ...
        Device.negativeBridgeState, ...
        2);

maximumPositiveDeviceCount = ...
    max( ...
        positiveDeviceCount(:));

maximumNegativeDeviceCount = ...
    max( ...
        negativeDeviceCount(:));

invalidPositiveDeviceSamples = ...
    nnz( ...
        positiveDeviceCount(:) ~= 0 ...
        & positiveDeviceCount(:) ~= 2);

invalidNegativeDeviceSamples = ...
    nnz( ...
        negativeDeviceCount(:) ~= 0 ...
        & negativeDeviceCount(:) ~= 2);

inactiveCurrentSamples = ...
    nnz( ...
        Device.thyristorCurrent( ...
            ~Device.thyristorState) ...
        ~= 0);

%% =========================================================
% Console report
%% =========================================================

fprintf('\n');
fprintf('============================================\n');
fprintf('DETAILED CYCLO SIMULATION - STAGE 5 TEST\n');
fprintf('============================================\n');

fprintf('Thyristor             : %s\n', ...
    P.thyristorType);

fprintf('Network case          : %s\n', ...
    P.networkCase);

fprintf('Pulse number          : %d\n', ...
    P.pulseNumber);

fprintf('Converter groups      : %d\n', ...
    P.TC);
fprintf('Thyristors/phase/group: %d\n', ...
    thyristorsPerPhaseGroup);

fprintf('Positive bridge devices: %d\n', ...
    positiveBridgeDeviceCount);

fprintf('Negative bridge devices: %d\n', ...
    negativeBridgeDeviceCount);

fprintf('Physical thyristors   : %d\n', ...
    physicalThyristorCount);

fprintf('Expected ABB count    : %d\n', ...
    expectedThyristorCount);
fprintf('Simulation samples    : %d\n', ...
    Device.numberOfSamples);

fprintf('\n');

fprintf('Motor Iu RMS          : %.3f A\n', ...
    Current.iuRms);

fprintf('Motor Iv RMS          : %.3f A\n', ...
    Current.ivRms);

fprintf('Motor Iw RMS          : %.3f A\n', ...
    Current.iwRms);

fprintf('\n');
fprintf('ABB/SCILAB REPRESENTATIVE SOURCE CURRENT\n');
fprintf('--------------------------------------------\n');

for groupNumber = 1:P.TC

    fprintf('Group %d IA RMS       : %.3f A\n', ...
        groupNumber, ...
        groupCurrentRmsA(groupNumber));

    fprintf('Group %d IB RMS       : %.3f A\n', ...
        groupNumber, ...
        groupCurrentRmsB(groupNumber));

    fprintf('Group %d IC RMS       : %.3f A\n', ...
        groupNumber, ...
        groupCurrentRmsC(groupNumber));

    fprintf('Group %d mean RMS     : %.3f A\n', ...
        groupNumber, ...
        groupCurrentMeanRms(groupNumber));

    fprintf('Group %d unbalance    : %.3f %%\n', ...
        groupNumber, ...
        groupCurrentUnbalancePercent(groupNumber));

    fprintf('Dimensioned I1S ref.  : %.3f A\n', ...
        dimensionedSecondaryCurrent);

    fprintf('Group %d/I1S ratio    : %.6f\n', ...
        groupNumber, ...
        sourceCurrentRatio(groupNumber));
    
    fprintf('Group %d/I1S error    : %.3f %%\n', ...
        groupNumber, ...
        sourceCurrentErrorPercent(groupNumber));

end
%% =========================================================
% Representative source-current harmonic diagnostics
%% =========================================================

groupToDisplay = ...
    1;

G = ...
    Harmonics.Group(groupToDisplay);

fprintf('\n');
fprintf('ABB/SCILAB REPRESENTATIVE SOURCE HARMONICS\n');
fprintf('--------------------------------------------\n');

fprintf('FFT samples           : %d\n', ...
    G.Record.numberOfSamples);

fprintf('FFT resolution        : %.6f Hz\n', ...
    G.Record.frequencyResolution);

fprintf('Representative A RMS  : %.3f A\n', ...
    G.rmsA);

fprintf('Representative B RMS  : %.3f A\n', ...
    G.rmsB);

fprintf('Representative C RMS  : %.3f A\n', ...
    G.rmsC);

fprintf('\n');
fprintf('Order     Frequency [Hz]     Amplitude [A]     Percent\n');

for orderIndex = 1:numel(G.harmonicOrders)

    fprintf('%5d     %14.3f     %13.3f     %7.3f %%\n', ...
        G.harmonicOrders(orderIndex), ...
        G.peakFrequencyA(orderIndex), ...
        G.amplitudeA(orderIndex), ...
        G.percentA(orderIndex));

end
%% =========================================================
% CycloTool versus detailed-simulation harmonics
%% =========================================================

G = ...
    Harmonics.Group(1);

commonOrders = ...
    intersect( ...
        AnalyticalHarmonics.HOrder, ...
        G.harmonicOrders, ...
        'stable');

fprintf('\n');
fprintf('CYCLOTOOL / DETAILED SIM HARMONIC COMPARISON\n');
fprintf('----------------------------------------------------------\n');
fprintf(['Order   Tool RMS [A]   Sim RMS [A]   ', ...
         'Difference [%%]   Peak [Hz]\n']);

for orderIndex = 1:numel(commonOrders)

    harmonicOrder = ...
        commonOrders(orderIndex);

    analyticalIndex = ...
        find( ...
            AnalyticalHarmonics.HOrder ...
            == harmonicOrder, ...
            1);

    simulationIndex = ...
        find( ...
            G.harmonicOrders ...
            == harmonicOrder, ...
            1);

    analyticalRms = ...
        AnalyticalHarmonics.IL( ...
            analyticalIndex);

    simulationRms = ...
        G.amplitudeA( ...
            simulationIndex) ...
        / sqrt(2);

    if analyticalRms > 0

        differencePercent = ...
            100 ...
            * ( ...
            simulationRms ...
            - analyticalRms) ...
            / analyticalRms;

    else

        differencePercent = ...
            NaN;

    end

    fprintf( ...
        '%5d   %12.3f   %11.3f   %14.3f   %9.3f\n', ...
        harmonicOrder, ...
        analyticalRms, ...
        simulationRms, ...
        differencePercent, ...
        G.peakFrequencyA(simulationIndex));

end

fprintf('----------------------------------------------------------\n');
fprintf('Tool model : Analytical VBA dimensioning method\n');
fprintf('Sim model  : ABB/Scilab representative branch FFT\n');
fprintf('Interpretation        : REPRESENTATIVE BRANCH\n');
fprintf('\n');

fprintf('T111 RMS current      : %.3f A\n', ...
    representativeThyristorRms);

fprintf('T111 average current  : %.3f A\n', ...
    representativeThyristorAverage);

fprintf('T111 peak current     : %.3f A\n', ...
    representativeThyristorPeak);

fprintf('T111 turn-on count    : %d\n', ...
    representativeTurnOnCount);

fprintf('T111 turn-off count   : %d\n', ...
    representativeTurnOffCount);

fprintf('\n');

fprintf('T211 RMS current      : %.3f A\n', ...
    representativeNegativeThyristorRms);

fprintf('T211 average current  : %.3f A\n', ...
    representativeNegativeThyristorAverage);

fprintf('T211 peak current     : %.3f A\n', ...
    representativeNegativeThyristorPeak);

fprintf('T211 turn-on count    : %d\n', ...
    representativeNegativeTurnOnCount);

fprintf('T211 turn-off count   : %d\n', ...
    representativeNegativeTurnOffCount);

fprintf('\n');
%% =========================================================
% Converter-loss diagnostics
%% =========================================================

fprintf('\n');
fprintf('CONVERTER LOSS DIAGNOSTICS\n');
fprintf('--------------------------------------------\n');

fprintf('Modeled thyristors    : %d\n', ...
    Loss.totalModeledThyristors);

fprintf('Expected thyristors   : %d\n', ...
    Loss.expectedPhysicalThyristors);

fprintf('\n');

fprintf('Conduction loss       : %.3f kW\n', ...
    Loss.totalConductionPowerkW);

fprintf('Turn-on loss          : %.3f kW\n', ...
    Loss.totalTurnOnPowerkW);

fprintf('Turn-off loss         : %.3f kW\n', ...
    Loss.totalTurnOffPowerkW);

fprintf('Snubber loss          : %.3f kW\n', ...
    Loss.snubberPowerkW);

fprintf('Total converter loss  : %.3f kW\n', ...
    Loss.totalConverterPowerkW);

fprintf('\n');

fprintf('T111 conduction loss  : %.3f W\n', ...
    Loss.T111.conductionPower);

fprintf('T111 turn-on loss     : %.3f W\n', ...
    Loss.T111.turnOnPower);

fprintf('T111 turn-off loss    : %.3f W\n', ...
    Loss.T111.turnOffPower);

fprintf('T111 total loss       : %.3f W\n', ...
    Loss.T111.totalPower);

fprintf('\n');

fprintf('Scilab conduction ratio: %.6f\n', ...
    Loss.conductionScaleRatio);

fprintf('Scilab turn-on ratio   : %.6f\n', ...
    Loss.turnOnScaleRatio);

fprintf('Scilab turn-off ratio  : %.6f\n', ...
    Loss.turnOffScaleRatio);

fprintf('\n');

fprintf('Explicit turn-on events: %d\n', ...
    Loss.explicitTurnOnEventCount);

fprintf('Scaled turn-on events  : %d\n', ...
    Loss.scilabScaledTurnOnEventCount);

fprintf('Explicit turn-off events: %d\n', ...
    Loss.explicitTurnOffEventCount);

fprintf('Scaled turn-off events : %d\n', ...
    Loss.scilabScaledTurnOffEventCount);

fprintf('--------------------------------------------\n');

fprintf('Conduction fraction   : %.6f\n', ...
    thyristorConductionFraction);

fprintf('Simultaneous bridges  : %d\n', ...
    simultaneousBridgeSamples);
fprintf('Max positive devices  : %d\n', ...
    maximumPositiveDeviceCount);

fprintf('Max negative devices  : %d\n', ...
    maximumNegativeDeviceCount);

fprintf('Invalid positive count: %d\n', ...
    invalidPositiveDeviceSamples);

fprintf('Invalid negative count: %d\n', ...
    invalidNegativeDeviceSamples);
fprintf('Inactive current      : %d\n', ...
    inactiveCurrentSamples);

fprintf('============================================\n');

%% =========================================================
% Stage 5 validation
%% =========================================================

%% =========================================================
% Numerical validation
%% =========================================================

finiteDeviceCurrentPass = ...
    all(isfinite(Device.thyristorCurrent(:))) ...
    && all(isfinite(Device.thyristorCurrentSigned(:)));

finiteRepresentativeSourceCurrentPass = ...
    all( ...
        isfinite( ...
            Device.representativeSourceCurrent(:))) ...
    && all( ...
        isfinite( ...
            Device.representativeGroupSourceCurrentRms(:)));

bridgeInterlockPass = ...
    simultaneousBridgeSamples == 0;

inactiveCurrentPass = ...
    inactiveCurrentSamples == 0;

%% =========================================================
% Representative device-current allocation validation
%% =========================================================
%
% T111 represents a positive-bridge device position.
% T211 represents a negative-bridge device position.
%
% This check validates current allocation within the present
% natural source-phase selection model. It does not validate
% the final physical commutation sequence.

representativeDeviceCurrentPass = ...
    representativeThyristorRms > 0 ...
    && representativeThyristorAverage >= 0 ...
    && representativeThyristorPeak > 0 ...
    && representativeNegativeThyristorRms > 0 ...
    && representativeNegativeThyristorAverage >= 0 ...
    && representativeNegativeThyristorPeak > 0;

%% =========================================================
% Representative switching-event diagnostic
%% =========================================================
%
% This is a diagnostic only. The transition counts do not
% yet represent independently validated physical firing and
% commutation events.

representativeSwitchingDiagnosticPass = ...
    representativeTurnOnCount > 0 ...
    && representativeTurnOffCount > 0 ...
    && representativeNegativeTurnOnCount > 0 ...
    && representativeNegativeTurnOffCount > 0;

%% =========================================================
% Provisional source-current numerical diagnostic
%% =========================================================
%
% A finite or nonzero source current is not sufficient to
% establish physical validity.
%
% The current source-phase selections are repeated across
% U, V, and W, so physical source-current validation is not
% presently available.

representativeSourceCurrentNumericalPass = ...
    finiteRepresentativeSourceCurrentPass ...
    && all( ...
        Device.representativeGroupSourceCurrentRms(:) >= 0);

sourceCurrentPhysicalValidationAvailable = ...
    false;

sourceCurrentPhysicalPass = ...
    false;

sourceCurrentValidationStatus = ...
    'REPRESENTATIVE BRANCH';

sourceSideModelPass = ...
    sourceCurrentPhysicalValidationAvailable ...
    && sourceCurrentPhysicalPass;

%% =========================================================
% Conduction-state availability
%% =========================================================

statePass = ...
    activeThyristorStates > 0;

%% =========================================================
% Physical topology validation
%% =========================================================

thyristorCountPass = ...
    physicalThyristorCount ...
    == expectedThyristorCount;

thyristorsPerPhaseGroupPass = ...
    thyristorsPerPhaseGroup == 12;

physicalBridgeSizePass = ...
    positiveBridgeDeviceCount == 6 ...
    && negativeBridgeDeviceCount == 6;

%% =========================================================
% Physical conducting-device count validation
%% =========================================================
%
% Each active physical six-pulse bridge must contain exactly:
%
%   one conducting upper thyristor
%   one conducting lower thyristor

conductingDeviceCountPass = ...
    maximumPositiveDeviceCount == 2 ...
    && maximumNegativeDeviceCount == 2 ...
    && invalidPositiveDeviceSamples == 0 ...
    && invalidNegativeDeviceSamples == 0;

%% =========================================================
% Stage 5A: Physical topology and device allocation
%% =========================================================

physicalTopologyPass = ...
    finiteDeviceCurrentPass ...
    && bridgeInterlockPass ...
    && inactiveCurrentPass ...
    && representativeDeviceCurrentPass ...
    && statePass ...
    && thyristorCountPass ...
    && thyristorsPerPhaseGroupPass ...
    && physicalBridgeSizePass ...
    && conductingDeviceCountPass;

%% =========================================================
% Store validation results
%% =========================================================

Test.Validation = struct();

%% Stage 5A results

Test.Validation.finiteDeviceCurrentPass = ...
    finiteDeviceCurrentPass;

Test.Validation.bridgeInterlockPass = ...
    bridgeInterlockPass;

Test.Validation.inactiveCurrentPass = ...
    inactiveCurrentPass;

Test.Validation.representativeDeviceCurrentPass = ...
    representativeDeviceCurrentPass;

Test.Validation.statePass = ...
    statePass;

Test.Validation.thyristorCountPass = ...
    thyristorCountPass;

Test.Validation.thyristorsPerPhaseGroupPass = ...
    thyristorsPerPhaseGroupPass;

Test.Validation.physicalBridgeSizePass = ...
    physicalBridgeSizePass;

Test.Validation.conductingDeviceCountPass = ...
    conductingDeviceCountPass;

Test.Validation.physicalTopologyPass = ...
    physicalTopologyPass;

%% Switching diagnostic

Test.Validation.representativeSwitchingDiagnosticPass = ...
    representativeSwitchingDiagnosticPass;

%% Stage 5B source-side results

Test.Validation.finiteRepresentativeSourceCurrentPass = ...
    finiteRepresentativeSourceCurrentPass;

Test.Validation.representativeSourceCurrentNumericalPass = ...
    representativeSourceCurrentNumericalPass;

Test.Validation.sourceCurrentPhysicalValidationAvailable = ...
    sourceCurrentPhysicalValidationAvailable;

Test.Validation.sourceCurrentPhysicalPass = ...
    sourceCurrentPhysicalPass;

Test.Validation.sourceSideModelPass = ...
    sourceSideModelPass;

%% =========================================================
% Overall Stage 5 result
%% =========================================================
%
% The backward-compatible overall result represents only the
% validated physical topology and device-current allocation.
%
% The provisional source-side model is reported separately.

Test.Validation.overallPass = ...
    physicalTopologyPass;

if physicalTopologyPass

    Test.Status = ...
        'PASS';

    Test.PhysicalTopologyStatus = ...
        'VALIDATED';

else

    Test.Status = ...
        'FAIL';

    Test.PhysicalTopologyStatus = ...
        'FAILED';

end

Test.SourceSideStatus = ...
    sourceCurrentValidationStatus;

Test.SourceHarmonicStatus = ...
    'NOT VALIDATED';

Test.LossStatus = ...
    'VALIDATED WITHIN ABB/SCILAB MODEL';

%% =========================================================
% Model-validation status report
%% =========================================================

fprintf('\n');
fprintf('MODEL VALIDATION STATUS\n');
fprintf('--------------------------------------------\n');

fprintf('Output voltage model  : %s\n', ...
    Device.outputVoltageModelStatus);

fprintf('Motor current model   : %s\n', ...
    Device.motorCurrentModelStatus);

fprintf('Physical topology     : %s\n', ...
    Test.PhysicalTopologyStatus);

fprintf('Device-current model  : %s\n', ...
    Device.thyristorCurrentStatus);

fprintf('Input conduction state: %s\n', ...
    Device.inputConductionStateStatus);

fprintf('Source-current model  : %s\n', ...
    Test.SourceSideStatus);

fprintf('Source harmonics      : %s\n', ...
    Test.SourceHarmonicStatus);

fprintf('Loss model            : %s\n', ...
    Test.LossStatus);

%% =========================================================
% Stage 5A physical-topology report
%% =========================================================

fprintf('\n');
fprintf('STAGE 5A - PHYSICAL TOPOLOGY VALIDATION\n');
fprintf('--------------------------------------------\n');

fprintf('Finite device currents : %s\n', ...
    passFailText(finiteDeviceCurrentPass));

fprintf('Bridge interlock       : %s\n', ...
    passFailText(bridgeInterlockPass));

fprintf('Inactive-device current: %s\n', ...
    passFailText(inactiveCurrentPass));

fprintf('Device-current allocation: %s\n', ...
    passFailText(representativeDeviceCurrentPass));

fprintf('Conduction states      : %s\n', ...
    passFailText(statePass));

fprintf('Thyristor count        : %s\n', ...
    passFailText(thyristorCountPass));

fprintf('Devices/phase/group    : %s\n', ...
    passFailText(thyristorsPerPhaseGroupPass));

fprintf('Physical bridge size   : %s\n', ...
    passFailText(physicalBridgeSizePass));

fprintf('Conducting-device count: %s\n', ...
    passFailText(conductingDeviceCountPass));

fprintf('Switching diagnostic   : %s\n', ...
    passFailText( ...
        representativeSwitchingDiagnosticPass));

fprintf('--------------------------------------------\n');

fprintf('STAGE 5A STATUS        : %s\n', ...
    Test.PhysicalTopologyStatus);

%% =========================================================
% Stage 5B source-side report
%% =========================================================

fprintf('\n');
fprintf('STAGE 5B - SOURCE-SIDE MODEL STATUS\n');
fprintf('--------------------------------------------\n');

fprintf('Finite representative current: %s\n', ...
    passFailText( ...
        finiteRepresentativeSourceCurrentPass));

fprintf('Representative numerical data: %s\n', ...
    passFailText( ...
        representativeSourceCurrentNumericalPass));

fprintf('Physical validation    : %s\n', ...
    availabilityText( ...
        sourceCurrentPhysicalValidationAvailable));

fprintf('Source-current status  : %s\n', ...
    Test.SourceSideStatus);

fprintf('Source harmonics       : %s\n', ...
    Test.SourceHarmonicStatus);

fprintf('Loss calculations      : %s\n', ...
    Test.LossStatus);

fprintf('--------------------------------------------\n');

fprintf(['The representative source current follows ', ...
    'the original ABB/Scilab phase-U branch model.\n']);

fprintf(['The complete simultaneous U/V/W transformer ', ...
    'current has not been reconstructed.\n']);

fprintf('============================================\n');

%% =========================================================
% Store results
%% =========================================================

Test.Parameters = ...
    P;

Test.Reference = ...
    Ref;

Test.Voltage = ...
    Voltage;

Test.State = ...
    State;

Test.Zero = ...
    Zero;

Test.Current = ...
    Current;

Test.Device = ...
    Device;
Test.Harmonics = ...
    Harmonics;
Test.AnalyticalHarmonics = ...
    AnalyticalHarmonics;
Test.Loss = ...
    Loss;
%% =========================================================
% Store source-current diagnostics
%% =========================================================

Test.Diagnostics.groupCurrentMeanRms = ...
    groupCurrentMeanRms;

Test.Diagnostics.dimensionedSecondaryCurrent = ...
    dimensionedSecondaryCurrent;

Test.Diagnostics.sourceCurrentRatio = ...
    sourceCurrentRatio;

Test.Diagnostics.sourceCurrentErrorPercent = ...
    sourceCurrentErrorPercent;

Test.Diagnostics.groupCurrentUnbalancePercent = ...
    groupCurrentUnbalancePercent;


%% =========================================================
% Store topology diagnostics
%% =========================================================

Test.Diagnostics.thyristorConductionFraction = ...
    thyristorConductionFraction;

Test.Diagnostics.simultaneousBridgeSamples = ...
    simultaneousBridgeSamples;

Test.Diagnostics.inactiveCurrentSamples = ...
    inactiveCurrentSamples;

Test.Diagnostics.thyristorsPerPhaseGroup = ...
    thyristorsPerPhaseGroup;

Test.Diagnostics.physicalThyristorCount = ...
    physicalThyristorCount;

Test.Diagnostics.expectedThyristorCount = ...
    expectedThyristorCount;

Test.Diagnostics.positiveBridgeDeviceCount = ...
    positiveBridgeDeviceCount;

Test.Diagnostics.negativeBridgeDeviceCount = ...
    negativeBridgeDeviceCount;

Test.Diagnostics.maximumPositiveDeviceCount = ...
    maximumPositiveDeviceCount;

Test.Diagnostics.maximumNegativeDeviceCount = ...
    maximumNegativeDeviceCount;

Test.Diagnostics.invalidPositiveDeviceSamples = ...
    invalidPositiveDeviceSamples;

Test.Diagnostics.invalidNegativeDeviceSamples = ...
    invalidNegativeDeviceSamples;

%% =========================================================
% Store separated model statuses
%% =========================================================

Test.Diagnostics.physicalTopologyPass = ...
    physicalTopologyPass;

Test.Diagnostics.finiteRepresentativeSourceCurrentPass = ...
    finiteRepresentativeSourceCurrentPass;

Test.Diagnostics.representativeSourceCurrentNumericalPass = ...
    representativeSourceCurrentNumericalPass;

Test.Diagnostics.sourceCurrentPhysicalValidationAvailable = ...
    sourceCurrentPhysicalValidationAvailable;

Test.Diagnostics.sourceCurrentPhysicalPass = ...
    sourceCurrentPhysicalPass;

Test.Diagnostics.sourceSideModelPass = ...
    sourceSideModelPass;

Test.Diagnostics.sourceCurrentStatus = ...
    Test.SourceSideStatus;

Test.Diagnostics.sourceHarmonicStatus = ...
    Test.SourceHarmonicStatus;

Test.Diagnostics.lossStatus = ...
    Test.LossStatus;

end

function statusText = passFailText(condition)

if condition

    statusText = 'PASS';

else

    statusText = 'FAIL';

end

end
function statusText = availabilityText(condition)

if condition

    statusText = ...
        'AVAILABLE';

else

    statusText = ...
        'NOT AVAILABLE';

end

end