"""Render a BusbarCheckResult as a Word document, laid out like the
reference 'Thermal Busbar Design' report (see the project README for the
mapping from that report's tables to this tool's fields).

Deliberately shows BOTH the Bare and Painted tables rather than picking
one finish per section: the reference report appears to show a single
table whose finish-selection convention (which section is bare vs.
painted in the as-built design) is not recoverable from the PDF alone.
Showing both, plus the AllOK/PaintRequired verdict, is a strict superset
of that information and does not require guessing which finish was
actually installed on a given section.
"""

from __future__ import annotations

from datetime import datetime, timezone

from app.calc.busbar.busbar_check import BusbarCheckResult
from app.reports.docx_utils import (
    COLOR_FAIL_TEXT,
    ProjectMeta,
    add_bullets,
    add_data_table,
    add_footer_note,
    add_meta_table,
    add_note,
    add_section_heading,
    add_title,
    new_document,
    render_bytes,
)


def _rows_for(finish_rows) -> tuple[list[list[str]], list[bool]]:
    rows = [
        [
            r.section_en,
            f"{r.i_load_a:.0f}",
            f"{r.f_hz:.1f}",
            r.band,
            f"{r.k1:.2f}",
            f"{r.k2:.2f}",
            f"{r.k3:.2f}",
            f"{r.k4:.2f}",
            f"{r.k5:.3f}",
            r.profile,
            f"{r.i_max_a:.0f}",
            f"{r.reserve_pu:.2f}",
        ]
        for r in finish_rows
    ]
    status = [r.ok for r in finish_rows]
    return rows, status


def render_busbar_report_docx(
    result: BusbarCheckResult, project: ProjectMeta | None = None
) -> bytes:
    project = project or ProjectMeta()
    doc = new_document(landscape=True)

    add_title(doc, "Thermal Busbar Design")
    add_meta_table(
        doc,
        project,
        extra_rows=[
            ("Location", result.location),
            ("Site altitude", f"{result.altitude_m:.0f} m.a.s.l."),
            ("Minimum reserve", f"{result.threshold:.2f} p.u."),
            ("Overall result", "PASS" if result.all_ok else "FAIL"),
        ],
    )

    add_bullets(
        doc,
        [
            "Semiconductors and snubber circuits are water-cooled and therefore not affected.",
            "Copper busbars; standard for continuous current: DIN 43671.",
            (
                "No IEC/IEEE requirement found for this item. Base ratings and "
                "k-factors are BBC/ABB Schaltanlagen-Handbuch, chapter 13 "
                "(manufacturer/industry practice, not a standard requirement). "
                "Load currents use the uL,min undervoltage current basis (IM/u_L)."
            ),
        ],
    )

    headers = [
        "Busbar section",
        "Current [A]",
        "Freq [Hz]",
        "Band",
        "k1",
        "k2",
        "k3",
        "k4",
        "k5",
        "Cross section",
        "Max thermal capacity [A]",
        "Margin [p.u.]",
    ]

    for finish_name, finish_rows in [("Bare finish", result.bare), ("Painted finish", result.painted)]:
        add_section_heading(doc, finish_name)
        rows, status = _rows_for(finish_rows)
        add_data_table(doc, headers, rows, row_status=status)

    add_note(
        doc,
        (
            f"I(motor) = {result.currents.i_motor_formula} = "
            f"{result.currents.i_motor_a:.0f} A   |   "
            f"I(line) = {result.currents.i_line_formula} = "
            f"{result.currents.i_line_a:.0f} A   |   "
            f"I(stack) = {result.currents.i_stack_formula} = "
            f"{result.currents.i_stack_a:.0f} A"
        ),
    )

    if result.paint_required:
        add_note(doc, result.paint_required_note, color=COLOR_FAIL_TEXT, bold=True)

    if result.warnings:
        add_section_heading(doc, "Warnings")
        add_bullets(doc, result.warnings)

    add_footer_note(
        doc,
        (
            f"Generated by CycloTool Web — "
            f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}. "
            "Methodology: BBC/ABB Schaltanlagen-Handbuch ch. 13. Not an "
            "IEC/IEEE requirement; engineering practice reproduced from the "
            "original Schienenueberpruefung.xlsx workbook."
        ),
    )

    return render_bytes(doc)
