"""Render an Engineering Data Word document, laid out like the reference
'Engineering Data' report (3BHS857641): nameplate ratings, then one BOM
table per section. Every part number in the BOM sections is exactly what
the user entered/edited -- this report does not look anything up.
"""

from __future__ import annotations

from datetime import datetime, timezone

from app.calc.engineering_data.engineering_data import (
    BomSection,
    NameplateRatings,
    VoltageDutyInput,
    calculate_voltage_duty,
)
from app.reports.docx_utils import (
    ProjectMeta,
    add_data_table,
    add_footer_note,
    add_meta_table,
    add_note,
    add_section_heading,
    add_title,
    new_document,
    render_bytes,
)


def render_engineering_data_report_docx(
    nameplate: NameplateRatings,
    test_voltage_input: VoltageDutyInput,
    bom_sections: list[BomSection],
    project: ProjectMeta | None = None,
) -> bytes:
    project = project or ProjectMeta()
    doc = new_document(landscape=False)

    add_title(doc, "Engineering Data")
    add_meta_table(doc, project, extra_rows=[])

    add_section_heading(doc, "Nameplate ratings")
    add_data_table(
        doc,
        ["Item", "Value"],
        [
            ["Input phases", nameplate.input_phases],
            [
                "Input voltage",
                f"{nameplate.input_voltage_count} x {nameplate.input_voltage_v:g} V",
            ],
            ["Input current (rms)", f"{nameplate.input_current_a:g} A"],
            ["Input frequency", f"{nameplate.input_frequency_hz:g} Hz"],
            [
                "Input apparent power",
                f"{nameplate.input_apparent_power_count} x "
                f"{nameplate.input_apparent_power_kva:g} kVA",
            ],
            [
                "Output voltage",
                (
                    f"{nameplate.output_voltage_min_v:g} ... "
                    f"{nameplate.output_voltage_base_v:g} ... "
                    f"{nameplate.output_voltage_max_v:g} V"
                ),
            ],
            ["Output current (rms)", f"{nameplate.output_current_a:g} A"],
            [
                "Output frequency",
                (
                    f"{nameplate.output_frequency_min_hz:g} ... "
                    f"{nameplate.output_frequency_base_hz:g} ... "
                    f"{nameplate.output_frequency_max_hz:g} Hz"
                ),
            ],
            ["Output apparent power", f"{nameplate.output_apparent_power_kva:g} kVA"],
            [
                "Overload",
                f"{nameplate.overload_cycles}, {nameplate.overload_pu:.2f} p.u.",
            ],
            ["Excitation input voltage", f"{nameplate.excitation_input_voltage_v:g} V"],
            ["Excitation input frequency", f"{nameplate.excitation_input_frequency_hz:g} Hz"],
            [
                "Excitation input apparent power",
                f"{nameplate.excitation_input_apparent_power_kva:g} kVA",
            ],
            ["Excitation output voltage", f"{nameplate.excitation_output_voltage_v:g} V"],
            ["Excitation output current", f"{nameplate.excitation_output_current_a:g} A"],
            [
                "Excitation output overload current",
                f"{nameplate.excitation_output_overload_current_a:g} A",
            ],
        ],
        first_col_left_align=True,
    )

    add_section_heading(doc, "Test voltage (Kurzschliesser, Wandler, Pruefspannung)")
    tv = calculate_voltage_duty(test_voltage_input)
    add_note(doc, tv.formula)
    add_note(
        doc,
        (
            f"Utest = {test_voltage_input.utest_kv_rms:g} kVrms, "
            f"{test_voltage_input.utest_frequency_hz:g} Hz, "
            f"{test_voltage_input.utest_duration_s:g} s "
            "(IEC 61800-5-1 Table 23 not digitised in this tool -- Utest is "
            "an editable field, not a computed lookup; confirm against the "
            "standard for the actual project.)"
        ),
    )

    for section in bom_sections:
        add_section_heading(doc, section.title)
        add_data_table(
            doc,
            ["Qty", "Description", "Part number", "Note"],
            [[i.quantity, i.description, i.part_number, i.note] for i in section.items],
            first_col_left_align=False,
        )

    add_footer_note(
        doc,
        (
            f"Generated by CycloTool Web — "
            f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}. "
            "Part numbers, quantities and descriptions above are user-entered "
            "and NOT validated against a parts catalog -- this tool has none. "
            "Test voltage duty cycle per IEC 61800-5-1; Utest itself is a "
            "user-supplied value, not computed from the standard's table."
        ),
    )

    return render_bytes(doc)
