function Report = build_cyclo_design_report_model(DesignData)
%BUILD_CYCLO_DESIGN_REPORT_MODEL
% Convert a consolidated CycloTool DesignData structure into
% tables and figure definitions for Design Data generation.
%
% This function performs no engineering calculations. It only
% organizes previously calculated and validated CycloTool data.
%
% Input:
%   DesignData
%       Consolidated structure created by:
%       build_cyclo_design_data
%
% Output:
%   Report
%       Formatted report tables, figure definitions, metadata,
%       status information, and model limitations.

arguments
    DesignData (1,1) struct
end

%% =========================================================
% Validate required top-level sections
%% =========================================================

requiredSections = { ...
    'Document', ...
    'Project', ...
    'Input', ...
    'Dimensioning', ...
    'OperatingPoint', ...
    'Harmonics', ...
    'Characteristic', ...
    'FiringAngle', ...
    'Excitation', ...
    'Protection', ...
    'DetailedSimulation', ...
    'Supply', ...
    'Converter', ...
    'Motor', ...
    'Simulation', ...
    'Validation'};

for sectionIndex = 1:numel(requiredSections)

    sectionName = ...
        requiredSections{sectionIndex};

    if ~isfield(DesignData, sectionName)

        error( ...
            'Cyclo:MissingDesignReportSection', ...
            'DesignData is missing required section %s.', ...
            sectionName);

    end

end

Report = struct();

%% =========================================================
% Report metadata
%% =========================================================

Report.Metadata = struct();

Report.Metadata.Title = ...
    string(DesignData.Document.Title);

Report.Metadata.DocumentNumber = ...
    string(DesignData.Document.Number);

Report.Metadata.Revision = ...
    string(DesignData.Document.Revision);

Report.Metadata.Status = ...
    getText( ...
        DesignData.Project, ...
        'DocumentStatus');

Report.Metadata.Confidentiality = ...
    getText( ...
        DesignData.Project, ...
        'Confidentiality');

Report.Metadata.Language = ...
    string(DesignData.Document.Language);

Report.Metadata.Date = ...
    string(DesignData.Document.Date);

Report.Metadata.PreparedBy = ...
    string(DesignData.Document.PreparedBy);

Report.Metadata.ApprovedBy = ...
    string(DesignData.Document.ApprovedBy);

Report.Metadata.Generator = ...
    "CycloTool Development 1.1";

Report.Metadata.CalculationBaseline = ...
    string(DesignData.Validation.release);

%% =========================================================
% Section titles
%% =========================================================

Report.SectionTitles = struct();

Report.SectionTitles.ProjectIdentification = ...
    "Project and Document Identification";

Report.SectionTitles.Supply = ...
    "Main Supply Data";

Report.SectionTitles.Converter = ...
    "Converter and Converter Transformer";

Report.SectionTitles.Motor = ...
    "Motor Data";

Report.SectionTitles.MotorCharacteristic = ...
    "Motor Voltage and Current Characteristic";

Report.SectionTitles.FiringAngle = ...
    "Control and Firing-Angle Characteristic";

Report.SectionTitles.Harmonics = ...
    "Analytical Multi-Pulse Harmonics";

Report.SectionTitles.Excitation = ...
    "Excitation System";

Report.SectionTitles.Protection = ...
    "Overvoltage Protection and Protective Settings";

Report.SectionTitles.DetailedSimulation = ...
    "Detailed Simulation Summary";

Report.SectionTitles.Validation = ...
    "Calculation Status and Model Limitations";

%% =========================================================
% Section 1: Document identification
%% =========================================================

Report.DocumentIdentification = {
    'Parameter',                'Value', 'Unit'
    'Document title',           string(DesignData.Document.Title), ''
    'Document number',          string(DesignData.Document.Number), ''
    'Revision',                 string(DesignData.Document.Revision), ''
    'Language',                 string(DesignData.Document.Language), ''
    'Document date',            string(DesignData.Document.Date), ''
    'Prepared by',              string(DesignData.Document.PreparedBy), ''
    'Approved by',              string(DesignData.Document.ApprovedBy), ''
    'Revision description',     getText(DesignData.Project, ...
                               'RevisionDescription'), ''
    'Responsible department',   getText(DesignData.Project, ...
                               'ResponsibleDepartment'), ''
    };

%% =========================================================
% Section 2: Project identification
%% =========================================================

Report.ProjectIdentification = {
    'Parameter',                    'Value', 'Unit'
    'Project',                      getText(DesignData.Project, ...
                                    'ProjectName'), ''
    'Client',                       getText(DesignData.Project, ...
                                    'Client'), ''
    'Contractor',                   getText(DesignData.Project, ...
                                    'Contractor'), ''
    'ABB project number',           getText(DesignData.Project, ...
                                    'ABBProjectNumber'), ''
    'Customer PO number',           getText(DesignData.Project, ...
                                    'CustomerPONumber'), ''
    'Customer document number',     getText(DesignData.Project, ...
                                    'CustomerDocumentNumber'), ''
    'Equipment name',               getText(DesignData.Project, ...
                                    'EquipmentName'), ''
    'Equipment tag',                getText(DesignData.Project, ...
                                    'EquipmentTag'), ''
    'Location',                     getText(DesignData.Project, ...
                                    'Location'), ''
    'Application',                  getText(DesignData.Project, ...
                                    'Application'), ''
    };

%% =========================================================
% Section 3: Main supply data
%% =========================================================

minimumLineVoltageFactor = ...
    DesignData.Supply.minimumLineVoltageFactor;

negativeLineVoltageVariationPercent = ...
    -100 ...
    * (1 - minimumLineVoltageFactor);

Report.Supply = {
    'Parameter',                          'Symbol', 'Value', 'Unit'
    'Line frequency',                     'fL', ...
    DesignData.Supply.frequencyHz,         'Hz'
    'Minimum line-voltage factor',        'uL,min', ...
    minimumLineVoltageFactor,              'p.u.'
    'Negative line-voltage variation',    'Delta uL', ...
    negativeLineVoltageVariationPercent,   '%'
    'Minimum short-circuit power',        'SSC,min', ...
    DesignData.Supply.minimumShortCircuitPowerVA/1e6, 'MVA'
    'Maximum short-circuit power',        'SSC,max', ...
    DesignData.Supply.maximumShortCircuitPowerVA/1e6, 'MVA'
    };

%% =========================================================
% Converter transformer and converter data
%% =========================================================
D = ...
    DesignData.Dimensioning;
Report.Converter = {
    'Parameter', ...
    'Symbol', ...
    'Value', ...
    'Unit'

    'Pulse number', ...
    'p', ...
    DesignData.Converter.pulseNumber, ...
    '-'

    'Converter groups', ...
    'TC', ...
    DesignData.Converter.numberOfGroups, ...
    '-'

    'Physical thyristors', ...
    'NT', ...
    DesignData.Converter.physicalThyristorCount, ...
    '-'

    'Thyristor type', ...
    '', ...
    string(DesignData.Converter.thyristorType), ...
    ''

    'Rated converter no-load voltage', ...
    'Uv0', ...
    DesignData.Converter.noLoadVoltageV, ...
    'V'

    'Transformer secondary current', ...
    'I1S', ...
    DesignData.Converter.secondaryCurrentA, ...
    'A RMS'

    'Calculated apparent power per group', ...
    'Scalc,g', ...
    DesignData.Converter. ...
    transformerCalculatedPowerPerGroupMVA, ...
    'MVA'

    'Calculated total apparent power', ...
    'Scalc', ...
    DesignData.Converter. ...
    transformerCalculatedPowerTotalMVA, ...
    'MVA'

    'Transformer rating factor', ...
    'kTr', ...
    DesignData.Converter. ...
    transformerRatingFactor, ...
    '-'

    'Required converter-transformer rating', ...
    'STr', ...
    DesignData.Converter. ...
    transformerSelectedPowerMVA, ...
    'MVA'

    'Nominal secondary current', ...
    'I1S,nom', ...
    getNumeric( ...
        DesignData.Dimensioning, ...
        'I1S_nom'), ...
    'A RMS'

    'Overload secondary current', ...
    'I1S,ovld', ...
    getNumeric( ...
        DesignData.Dimensioning, ...
        'I1S_ovld'), ...
    'A RMS'

    'Startup secondary current', ...
    'I1S,start', ...
    getNumeric( ...
        DesignData.Dimensioning, ...
        'I1S_start'), ...
    'A RMS'

    'Maximum converter current', ...
    'IkN', ...
    getNumeric( ...
        DesignData.Dimensioning, ...
        'IkN'), ...
    'A'

    'Converter current factor', ...
    'kN', ...
    getNumeric( ...
        DesignData.Dimensioning, ...
        'k_N'), ...
    '-'

    'Transformer reactance', ...
    'exT', ...
    getNumeric( ...
        DesignData.Dimensioning, ...
        'exT'), ...
    'p.u.'

    'Transformer voltage ratio', ...
    'ur', ...
    getNumeric( ...
        DesignData.Dimensioning, ...
        'u_r'), ...
    '-'

    'Total calculated converter loss', ...
    'PLoss', ...
    DesignData.Converter.totalLosskW, ...
    'kW'
    };

%% =========================================================
% Section 5: Converter current ratings
%% =========================================================

Report.ConverterCurrents = {
    'Parameter',                         'Symbol', 'Value', 'Unit'
    'Device RMS current',                'Id,eff', ...
    getNumeric(D, 'Id_DBeff'),            'A'
    'Device peak current',               'Id,peak', ...
    getNumeric(D, 'Id_DBpeak'),           'A'
    'Nominal device RMS current',        'Id,eff,nom', ...
    getNumeric(D, 'Id_DBeff_nom'),        'A'
    'Nominal device peak current',       'Id,peak,nom', ...
    getNumeric(D, 'Id_DBpeak_nom'),       'A'
    'Overload device RMS current',       'Id,eff,ovld', ...
    getNumeric(D, 'Id_DBeff_ovld'),       'A'
    'Overload device peak current',      'Id,peak,ovld', ...
    getNumeric(D, 'Id_DBpeak_ovld'),      'A'
    'Maximum device current',            'Id,max', ...
    getNumeric(D, 'Id_DBmax'),            'A'
    'Silicon current',                   'ISi', ...
    getNumeric(D, 'ISi'),                 'A'
    };

%% =========================================================
% Section 6: Thermal and thyristor results
%% =========================================================

Report.Thermal = {
    'Parameter',                    'Symbol', 'Value', 'Unit'
    'Thyristor loss',               'PLTh', ...
    getNumeric(D, 'PLTh'),           'W'
    'Additional converter loss',    'PVS', ...
    getNumeric(D, 'PVS'),            'W'
    'Junction temperature',         'Tj', ...
    getNumeric(D, 'Tj'),             'degC'
    'Turn-off time',                'tq', ...
    1e6*getNumeric(D, 'tq_actual'),  'us'
    'Calculated di/dt',             'di/dt', ...
    getNumeric(D, 'didtv'),          'A/us'
    'Calculated di/dt at 90 deg',   'di/dt90', ...
    getNumeric(D, 'didt90'),         'A/us'
    };

%% =========================================================
% Section 7: Motor data
%% =========================================================

motorFrequencyMinimum = ...
    DesignData.Motor.polePairs ...
    * DesignData.Motor.minimumSpeedRpm ...
    / 60;

motorFrequencyNominal = ...
    DesignData.Motor.polePairs ...
    * DesignData.Motor.nominalSpeedRpm ...
    / 60;

motorFrequencyMaximum = ...
    DesignData.Motor.polePairs ...
    * DesignData.Motor.maximumSpeedRpm ...
    / 60;

Report.Motor = {
    'Parameter',                 'Symbol', 'Value', 'Unit'
    'Rated motor voltage',       'UM', ...
    DesignData.Motor.voltageV,    'V'
    'Rated motor current',       'IM', ...
    DesignData.Motor.currentA,    'A RMS'
    'Power factor',              'cos phi', ...
    DesignData.Motor.powerFactor, '-'
    'Efficiency',                'eta', ...
    100*DesignData.Motor.efficiency, '%'
    'Minimum speed',             'nmin', ...
    DesignData.Motor.minimumSpeedRpm, 'rpm'
    'Nominal speed',             'nN', ...
    DesignData.Motor.nominalSpeedRpm, 'rpm'
    'Maximum speed',             'nmax', ...
    DesignData.Motor.maximumSpeedRpm, 'rpm'
    'Pole pairs',                'pp', ...
    DesignData.Motor.polePairs,   '-'
    'Minimum motor frequency',   'fM,min', ...
    motorFrequencyMinimum,        'Hz'
    'Nominal motor frequency',   'fM,N', ...
    motorFrequencyNominal,        'Hz'
    'Maximum motor frequency',   'fM,max', ...
    motorFrequencyMaximum,        'Hz'
    };

%% =========================================================
% Section 8: Motor operating currents
%% =========================================================

Report.MotorCurrents = {
    'Parameter',                       'Symbol', 'Value', 'Unit'
    'Motor current at minimum voltage','IM/uL', ...
    getNumeric(D, 'IM_uL'),             'A RMS'
    'Motor overload current',          'IM,ovld', ...
    getNumeric(D, 'IM_ovld'),           'A RMS'
    'Overload current at minimum voltage', ...
    'IM,ovld/uL', ...
    getNumeric(D, 'IM_ovld_uL'),        'A RMS'
    'Motor startup current',           'IM,start', ...
    getNumeric(D, 'IM_start'),          'A RMS'
    };

%% =========================================================
% Section 9: Operating-point data
%% =========================================================

OP = ...
    DesignData.OperatingPoint;

Report.OperatingPoint = {
    'Parameter',                  'Symbol', 'Value', 'Unit'
    'Device RMS current',         'Id,eff', ...
    getNumeric(OP, 'Id_DBeff'),    'A'
    'Device peak current',        'Id,peak', ...
    getNumeric(OP, 'Id_DBpeak'),   'A'
    'Maximum converter current',  'IkN', ...
    getNumeric(OP, 'IkN'),         'A'
    'No-load voltage',            'Uv0', ...
    getNumeric(OP, 'Uv0N'),        'V'
    'Thyristor loss',             'PLTh', ...
    getNumeric(OP, 'PLTh'),        'W'
    'Junction temperature',       'Tj', ...
    getNumeric(OP, 'Tj'),          'degC'
    'Turn-off time',              'tq', ...
    1e6*getNumeric(OP, 'tq_actual'), 'us'
    };

%% =========================================================
% Section 10: Motor characteristic support points
%% =========================================================

C = ...
    DesignData.Characteristic;

numberOfSupportPoints = ...
    numel(C.Speed);

Report.MotorCharacteristic = ...
    cell(numberOfSupportPoints + 1, 9);

Report.MotorCharacteristic(1,:) = { ...
    'Point', ...
    'Speed [rpm]', ...
    'Frequency [Hz]', ...
    'UM nominal [V]', ...
    'UM at uL,min [V]', ...
    'IM nominal [A]', ...
    'IM at uL,min [A]', ...
    'IM overload [A]', ...
    'IM overload at uL,min [A]'};

for pointIndex = 1:numberOfSupportPoints

    Report.MotorCharacteristic(pointIndex+1,:) = { ...
        pointIndex, ...
        C.Speed(pointIndex), ...
        C.Frequency(pointIndex), ...
        C.UM_nom(pointIndex), ...
        C.UM_uLmin(pointIndex), ...
        C.IM_nom(pointIndex), ...
        C.IM_uLmin(pointIndex), ...
        C.IM_ovld_nom(pointIndex), ...
        C.IM_ovld_uLmin(pointIndex)};

end

%% =========================================================
% Section 11: Firing-angle characteristic
%% =========================================================

F = ...
    DesignData.FiringAngle;

firingSupportCurrent = ...
    [0, 0.5, 1, 1.5, 2, 2.5, 3];

Report.FiringAngle = ...
    cell(numel(firingSupportCurrent) + 1, 5);

Report.FiringAngle(1,:) = { ...
    'Current [p.u.]', ...
    'Worst case [deg]', ...
    'Allowable [deg]', ...
    'Setting [deg]', ...
    'Tolerance [deg]'};

for pointIndex = 1:numel(firingSupportCurrent)

    currentPu = ...
        firingSupportCurrent(pointIndex);

    Report.FiringAngle(pointIndex+1,:) = { ...
        currentPu, ...
        interp1(F.Ipu, F.WorstCase, currentPu), ...
        interp1(F.Ipu, F.Allowed, currentPu), ...
        interp1(F.Ipu, F.Setting, currentPu), ...
        interp1(F.Ipu, F.Tolerance, currentPu)};

end

Report.FiringAngleSummary = {
    'Parameter',                     'Value', 'Unit'
    'Minimum commutation margin',    F.gamma0, 'deg'
    'Network reactance',             F.xL, 'p.u.'
    };

%% =========================================================
% Section 12: Analytical harmonics
%% =========================================================

H = ...
    DesignData.Harmonics;

numberOfHarmonics = ...
    numel(H.HOrder);

Report.Harmonics = ...
    cell(numberOfHarmonics + 1, 4);

Report.Harmonics(1,:) = { ...
    'Order', ...
    'Current [%]', ...
    'Current [A RMS]', ...
    'Voltage [%]'};

for harmonicIndex = 1:numberOfHarmonics

    Report.Harmonics(harmonicIndex+1,:) = { ...
        H.HOrder(harmonicIndex), ...
        H.KI(harmonicIndex), ...
        H.IL(harmonicIndex), ...
        H.KU(harmonicIndex)};

end

Report.HarmonicSummary = {
    'Parameter',                   'Value', 'Unit'
    'Voltage distortion to 25th', H.ku25, '%'
    'Total voltage distortion',    H.kuTot, '%'
    'Current THD',                 H.THDi, '%'
    };

%% =========================================================
% Section 13: Excitation system
%% =========================================================
E = ...
    DesignData.Excitation;

Report.Excitation = {
    'Parameter', ...
    'Value', ...
    'Unit'

    'Calculated no-load voltage', ...
    E.UV0_calc, ...
    'V AC'

    'Selected no-load voltage', ...
    E.UV0_selected, ...
    'V AC'

    'Oversized no-load voltage', ...
    E.UV0_oversized, ...
    'V AC'

    'DCS880 type', ...
    string(E.DCS_Type), ...
    ''

    'DCS880 size', ...
    string(E.DCS_Size), ...
    ''

    'DCS880 voltage class', ...
    E.DCS_UV0, ...
    'V'

    'Converter rated current', ...
    E.Imax_Converter, ...
    'A'

    'Converter utilization', ...
    E.DCS_Utilization, ...
    '%'

    'Converter current margin', ...
    E.DCS_Margin, ...
    'A'

    'Converter margin', ...
    E.DCS_MarginPercent, ...
    '%'

    'Fan type', ...
    string(E.FanType), ...
    ''

    'Fan voltage', ...
    E.FanVoltage, ...
    'V AC'

    'Fan frequency', ...
    E.FanFrequency, ...
    'Hz'

    'Fan power', ...
    E.FanPower, ...
    'W'

    'Fan current', ...
    E.FanCurrent, ...
    'A'

    'Fan blocking current', ...
    E.FanBlockingCurrent, ...
    'A'

    'Calculated excitation apparent power', ...
    E.transformerCalculatedPowerkVA, ...
    'kVA'

    'Excitation transformer rating factor', ...
    E.transformerRatingFactor, ...
    '-'

    'Required excitation transformer rating', ...
    E.transformerSelectedPowerkVA, ...
    'kVA'

    'Existing selected transformer rating', ...
    E.existingTransformerRatingkVA, ...
    'kVA'

    'Existing transformer selection ratio', ...
    E.transformerRatingRatio, ...
    '-'

    'Existing transformer selection status', ...
    statusText( ...
        E.existingTransformerMeetsRequirement), ...
    ''

    'Transformer primary current', ...
    E.I1P, ...
    'A'

    'Calculated surge arrester', ...
    E.Arrester_Calculated, ...
    'V'

    'Selected surge arrester', ...
    E.Arrester_Selected, ...
    'V'

    'Oversized surge arrester', ...
    E.Arrester_Oversized, ...
    'V'

    'Warning', ...
    string(E.Warning), ...
    ''
    };

%% =========================================================
% Section 14: Overvoltage protection
%% =========================================================

P = ...
    DesignData.Protection;

Report.Protection = {
    'Parameter',                         'Value', 'Unit'
    'Permissible thyristor current',     P.ITh_zul, 'A'
    'Maximum machine current',           P.IMmax, 'A'
    'Half machine current',              P.IMmax_half, 'A'
    'Thermal margin',                    P.ThermalMargin, 'A'
    'Thermal check',                     statusText(P.Thermal_OK), ''
    'Stator BOD minimum voltage',        P.UBoD_min, 'V'
    'Stator BOD maximum voltage',        P.UBoD_max, 'V'
    'Selected stator BOD voltage',       P.UBoD_selected, 'V'
    'Stator BOD check',                  statusText(P.BOD_OK), ''
    'Stator crowbar resistance',         P.RKS, 'ohm'
    'Stator effective current',          P.Ieff, 'A'
    'Stator crowbar energy',             P.EKS, 'kWs'
    'Rotor BOD minimum voltage',         P.UBoD_min_Rotor, 'V'
    'Rotor BOD maximum voltage',         P.UBoD_max_Rotor, 'V'
    'Selected rotor BOD voltage',        P.UBoD_selected_Rotor, 'V'
    'Rotor BOD check',                   statusText(P.BOD_OK_Rotor), ''
    'Rotor crowbar resistance',          P.RKS_Rotor, 'ohm'
    'Rotor effective current',           P.Ieff_Rotor, 'A'
    'Rotor crowbar energy',              P.EKS_Rotor, 'kWs'
    };

%% =========================================================
% Section 15: Protection settings
%% =========================================================

Report.ProtectiveSettings = {
    'Parameter',                    'Symbol', 'Value', 'Unit'
    'Current setting A',            'IGA', ...
    P.IGA,                           'A'
    'Current setting B',            'IGB', ...
    P.IGB,                           'A'
    'Maximum protection current',   'IG,max', ...
    P.IGmax,                         'A'
    'Current at 1.15 p.u.',         'I1.15', ...
    P.I115,                          'A'
    'Current at 1.35 p.u.',         'I1.35', ...
    P.I135,                          'A'
    'Characteristic frequency',     'fc', ...
    P.fc,                            'Hz'
    'Half characteristic time',     'Tc/2', ...
    P.Tc2,                           's'
    'Current limit',                'Ilimit', ...
    P.ILimit,                        'A'
    };

%% =========================================================
% Section 16: Detailed Simulation group currents
%% =========================================================

S = ...
    DesignData.DetailedSimulation;

representativeRms = ...
    S.Device.representativeGroupSourceCurrentRms;

numberOfGroups = ...
    size(representativeRms, 2);

Report.RepresentativeGroupCurrents = ...
    cell(numberOfGroups + 1, 7);

Report.RepresentativeGroupCurrents(1,:) = { ...
    'Group', ...
    'Phase A RMS [A]', ...
    'Phase B RMS [A]', ...
    'Phase C RMS [A]', ...
    'Mean RMS [A]', ...
    'I1S Ratio [-]', ...
    'I1S Error [%]'};

for groupIndex = 1:numberOfGroups

    groupPhaseRms = ...
        representativeRms(:,groupIndex);

    groupMeanRms = ...
        mean(groupPhaseRms);

    currentRatio = ...
        groupMeanRms ...
        / DesignData.Converter.secondaryCurrentA;

    currentErrorPercent = ...
        100 ...
        * ( ...
        groupMeanRms ...
        - DesignData.Converter.secondaryCurrentA) ...
        / DesignData.Converter.secondaryCurrentA;

    Report.RepresentativeGroupCurrents(groupIndex+1,:) = { ...
        groupIndex, ...
        groupPhaseRms(1), ...
        groupPhaseRms(2), ...
        groupPhaseRms(3), ...
        groupMeanRms, ...
        currentRatio, ...
        currentErrorPercent};

end

%% =========================================================
% Section 17: Detailed Simulation summary
%% =========================================================

Report.DetailedSimulation = {
    'Parameter',                    'Value', 'Unit'
    'Pulse number',                 S.Parameters.pulseNumber, '-'
    'Converter groups',             S.Parameters.TC, '-'
    'Simulation samples',           S.Device.numberOfSamples, '-'
    'Motor phase-U RMS current',    S.Current.iuRms, 'A'
    'Motor phase-V RMS current',    S.Current.ivRms, 'A'
    'Motor phase-W RMS current',    S.Current.iwRms, 'A'
    'Physical thyristors',          S.Device.totalPhysicalThyristors, '-'
    'Conduction loss',              S.Loss.totalConductionPowerkW, 'kW'
    'Turn-on loss',                 S.Loss.totalTurnOnPowerkW, 'kW'
    'Turn-off loss',                S.Loss.totalTurnOffPowerkW, 'kW'
    'Snubber loss',                 S.Loss.snubberPowerkW, 'kW'
    'Total converter loss',         S.Loss.totalConverterPowerkW, 'kW'
    'Physical topology status',     string(S.PhysicalTopologyStatus), ''
    'Source-current status',        string(S.SourceSideStatus), ''
    'Source-harmonic status',       string(S.SourceHarmonicStatus), ''
    'Loss status',                  string(S.LossStatus), ''
    };

%% =========================================================
% Section 18: Validation status
%% =========================================================

Report.ValidationStatus = {
    'Calculation area',             'Status'
    'Physical topology',            string(S.PhysicalTopologyStatus)
    'Source-current model',         string(S.SourceSideStatus)
    'Source-harmonic model',        string(S.SourceHarmonicStatus)
    'Converter-loss model',         string(S.LossStatus)
    'Overall Stage 5 result',       string(S.Status)
    };

%% =========================================================
% Figure definitions
%% =========================================================

Report.Figures = struct();
Report.Figures.Overview = ...
    struct( ...
        'Title', ...
        "Cycloconverter Overview Diagram", ...
        'Enabled', ...
        true, ...
        'FileName', ...
        "cycloconverter_overview.png");
Report.Figures.MotorCharacteristic = struct( ...
    'Title', ...
    "Motor Voltage and Current Characteristic", ...
    'Enabled', ...
    true, ...
    'FileName', ...
    "motor_characteristic.png");

Report.Figures.FiringAngle = struct( ...
    'Title', ...
    "Maximum Inverter Firing Angle versus Load Current", ...
    'Enabled', ...
    true, ...
    'FileName', ...
    "firing_angle_characteristic.png");

Report.Figures.AnalyticalHarmonics = struct( ...
    'Title', ...
    "Analytical Multi-Pulse Harmonic Spectrum", ...
    'Enabled', ...
    true, ...
    'FileName', ...
    "analytical_harmonics.png");

Report.Figures.DetailedFft = struct( ...
    'Title', ...
    "ABB/Scilab Representative Secondary-Group FFT", ...
    'Enabled', ...
    true, ...
    'FileName', ...
    "representative_group_fft.png");

Report.Figures.ConverterLosses = struct( ...
    'Title', ...
    "Converter Loss Breakdown", ...
    'Enabled', ...
    true, ...
    'FileName', ...
    "converter_losses.png");
Report.Figures.SimulationMotorCurrents = ...
    struct( ...
        'Title', ...
        "Detailed Simulation Motor Phase Currents", ...
        'Enabled', ...
        true, ...
        'FileName', ...
        "simulation_motor_currents.png");

Report.Figures.SimulationVoltages = ...
    struct( ...
        'Title', ...
        "Detailed Simulation Converter Output Voltages", ...
        'Enabled', ...
        true, ...
        'FileName', ...
        "simulation_output_voltages.png");

Report.Figures.SimulationSwitching = ...
    struct( ...
        'Title', ...
        "Detailed Simulation Switching-State Overview", ...
        'Enabled', ...
        true, ...
        'FileName', ...
        "simulation_switching_states.png");

Report.Figures.SimulationDeviceCurrents = ...
    struct( ...
        'Title', ...
        "Detailed Simulation Physical Thyristor Currents", ...
        'Enabled', ...
        true, ...
        'FileName', ...
        "simulation_device_currents.png");
%% =========================================================
% Model limitations
%% =========================================================

Report.ModelLimitations = ...
    DesignData.Validation.notReconstructed;

Report.DetailedFftInterpretation = ...
    string( ...
        DesignData.Validation.detailedFftInterpretation);

%% =========================================================
% Final validation
%% =========================================================

validateReportModel(Report);

end

function value = getText(S, fieldName)

if isfield(S, fieldName) && ...
        strlength(string(S.(fieldName))) > 0

    value = ...
        string(S.(fieldName));

else

    value = ...
        "";

end

end


function value = getNumeric(S, fieldName)

if isfield(S, fieldName) && ...
        ~isempty(S.(fieldName))

    value = ...
        S.(fieldName);

else

    value = ...
        NaN;

end

end

function value = statusText(condition)
%STATUSTEXT Convert a logical or numeric status to report text.

if ~isscalar(condition)
    error( ...
        'Cyclo:InvalidReportStatus', ...
        'The report status must be a scalar value.');
end
if islogical(condition)
    statusIsTrue = ...
        condition;
elseif isnumeric(condition) && ...
        isfinite(condition) && ...
        ismember(condition, [0, 1])
    statusIsTrue = ...
        logical(condition);
else
    error( ...
        'Cyclo:InvalidReportStatus', ...
        ['The report status must be a logical scalar ', ...
         'or numeric 0 or 1.']);
end
if statusIsTrue
    value = ...
        "PASS";
else
    value = ...
        "REVIEW REQUIRED";
end
end

function validateReportModel(Report)

requiredTables = { ...
    'DocumentIdentification', ...
    'ProjectIdentification', ...
    'Supply', ...
    'Converter', ...
    'ConverterCurrents', ...
    'Thermal', ...
    'Motor', ...
    'MotorCurrents', ...
    'OperatingPoint', ...
    'MotorCharacteristic', ...
    'FiringAngle', ...
    'Harmonics', ...
    'Excitation', ...
    'Protection', ...
    'ProtectiveSettings', ...
    'RepresentativeGroupCurrents', ...
    'DetailedSimulation', ...
    'ValidationStatus'};

for tableIndex = 1:numel(requiredTables)

    tableName = ...
        requiredTables{tableIndex};

    if ~isfield(Report, tableName) || ...
            isempty(Report.(tableName))

        error( ...
            'Cyclo:MissingDesignReportTable', ...
            'The report model is missing table %s.', ...
            tableName);

    end

end

if ~isfield(Report, 'Metadata') || ...
        isempty(fieldnames(Report.Metadata))

    error( ...
        'Cyclo:MissingDesignReportMetadata', ...
        'The report model contains no metadata.');

end

if ~isfield(Report, 'Figures') || ...
        isempty(fieldnames(Report.Figures))

    error( ...
        'Cyclo:MissingDesignReportFigures', ...
        'The report model contains no figure definitions.');

end

figureNames = ...
    fieldnames(Report.Figures);

for figureIndex = 1:numel(figureNames)

    figureName = ...
        figureNames{figureIndex};

    figureDefinition = ...
        Report.Figures.(figureName);

    if ~isfield(figureDefinition, 'Title') || ...
            ~isfield(figureDefinition, 'Enabled') || ...
            ~isfield(figureDefinition, 'FileName')

        error( ...
            'Cyclo:InvalidDesignReportFigure', ...
            'Figure definition %s is incomplete.', ...
            figureName);

    end

end

if isempty(Report.ModelLimitations)

    error( ...
        'Cyclo:MissingDesignReportLimitations', ...
        'The report model contains no model limitations.');

end

end