function DesignData = build_cyclo_design_data( ...
    Project, ...
    Input, ...
    Dimensioning, ...
    OperatingPoint, ...
    Harmonics, ...
    Characteristic, ...
    FiringAngle, ...
    Excitation, ...
    Protection, ...
    DetailedSimulation)
%BUILD_CYCLO_DESIGN_DATA
% Consolidate CycloTool inputs and calculated results into one
% validated structure for engineering document generation.
%
% This function does not repeat engineering calculations.
% It only organizes already calculated and validated results.
%
% Inputs:
%   Project             Project and document identification
%   Input               CycloTool engineering inputs
%   Dimensioning        Main cycloconverter dimensioning result
%   OperatingPoint      Selected operating-point result
%   Harmonics           Analytical multi-pulse harmonic result
%   Characteristic      Motor voltage/current characteristic
%   FiringAngle         Current-dependent firing-angle result
%   Excitation          Excitation-system result
%   Protection          Overvoltage-protection result
%   DetailedSimulation  Validated Detailed Simulation result
%
% Output:
%   DesignData          Consolidated document-data structure

arguments
    Project             (1,1) struct
    Input               (1,1) struct
    Dimensioning        (1,1) struct
    OperatingPoint      (1,1) struct
    Harmonics           (1,1) struct
    Characteristic      (1,1) struct
    FiringAngle         (1,1) struct
    Excitation          (1,1) struct
    Protection          (1,1) struct
    DetailedSimulation  (1,1) struct
end

%% =========================================================
% Document and project identification
%% =========================================================

DesignData.Document = struct();

DesignData.Document.Title = ...
    getOptionalField( ...
        Project, ...
        'DocumentTitle', ...
        'Cycloconverter Design Data');

DesignData.Document.Number = ...
    getOptionalField( ...
        Project, ...
        'DocumentNumber', ...
        '');

DesignData.Document.Revision = ...
    getOptionalField( ...
        Project, ...
        'Revision', ...
        'A');

DesignData.Document.Language = ...
    getOptionalField( ...
        Project, ...
        'Language', ...
        'en');

DesignData.Document.PreparedBy = ...
    getOptionalField( ...
        Project, ...
        'PreparedBy', ...
        '');

DesignData.Document.ApprovedBy = ...
    getOptionalField( ...
        Project, ...
        'ApprovedBy', ...
        '');

DesignData.Document.Date = ...
    getOptionalField( ...
        Project, ...
        'DocumentDate', ...
        string(datetime('today')));

DesignData.Project = ...
    Project;

%% =========================================================
% Source calculation structures
%% =========================================================

DesignData.Input = ...
    Input;

DesignData.Dimensioning = ...
    Dimensioning;

DesignData.OperatingPoint = ...
    OperatingPoint;

DesignData.Harmonics = ...
    Harmonics;

DesignData.Characteristic = ...
    Characteristic;

DesignData.FiringAngle = ...
    FiringAngle;

DesignData.Excitation = ...
    Excitation;

%% =========================================================
% Excitation-transformer apparent-power rating
%% =========================================================
%
% Excitation.SEx is the calculated excitation-system apparent
% power in kVA.
%
% The required transformer rating is:
%
%   STr,required = kTr,exc * SEx
%
% The original Excitation.STr result is retained separately
% so the existing selection can be compared with the new
% project-specific rating rule.

excitationTransformerFactor = ...
    getOptionalNumericField( ...
        Project, ...
        'ExcitationTransformerRatingFactor', ...
        1.90);
if excitationTransformerFactor < 1.85 || ...
        excitationTransformerFactor > 1.90
    error( ...
        'Cyclo:InvalidExcitationTransformerFactor', ...
        ['The excitation-transformer rating factor must be ', ...
         'between 1.85 and 1.90.']);
end
if ~isfield(Excitation, 'SEx') || ...
        isempty(Excitation.SEx) || ...
        ~isnumeric(Excitation.SEx) || ...
        ~isscalar(Excitation.SEx) || ...
        ~isfinite(Excitation.SEx) || ...
        Excitation.SEx <= 0
    error( ...
        'Cyclo:InvalidExcitationCalculatedPower', ...
        ['Excitation.SEx must contain a positive finite ', ...
         'calculated apparent power in kVA.']);
end
DesignData.Excitation.transformerCalculatedPowerkVA = ...
    Excitation.SEx;
DesignData.Excitation.transformerRatingFactor = ...
    excitationTransformerFactor;
DesignData.Excitation.transformerSelectedPowerkVA = ...
    excitationTransformerFactor ...
    * DesignData.Excitation. ...
    transformerCalculatedPowerkVA;
%% Preserve the existing excitation-transformer selection
if isfield(Excitation, 'STr') && ...
        ~isempty(Excitation.STr) && ...
        isnumeric(Excitation.STr) && ...
        isscalar(Excitation.STr) && ...
        isfinite(Excitation.STr)
    DesignData.Excitation.existingTransformerRatingkVA = ...
        Excitation.STr;
else
    DesignData.Excitation.existingTransformerRatingkVA = ...
        NaN;
end
%% Compare the existing selection with calculated power
if isfinite( ...
        DesignData.Excitation. ...
        existingTransformerRatingkVA)
    DesignData.Excitation.transformerRatingDifferencekVA = ...
        DesignData.Excitation. ...
        existingTransformerRatingkVA ...
        - DesignData.Excitation. ...
        transformerSelectedPowerkVA;
    DesignData.Excitation.transformerRatingRatio = ...
        DesignData.Excitation. ...
        existingTransformerRatingkVA ...
        / DesignData.Excitation. ...
        transformerCalculatedPowerkVA;
    DesignData.Excitation.existingTransformerMeetsRequirement = ...
        DesignData.Excitation. ...
        existingTransformerRatingkVA ...
        >= DesignData.Excitation. ...
        transformerSelectedPowerkVA;
else
    DesignData.Excitation.transformerRatingDifferencekVA = ...
        NaN;
    DesignData.Excitation.transformerRatingRatio = ...
        NaN;
    DesignData.Excitation.existingTransformerMeetsRequirement = ...
        false;
end

DesignData.Protection = ...
    Protection;

DesignData.DetailedSimulation = ...
    DetailedSimulation;

%% =========================================================
% Main supply data
%% =========================================================

DesignData.Supply = struct();

DesignData.Supply.frequencyHz = ...
    Input.fL;

DesignData.Supply.minimumShortCircuitPowerVA = ...
    Input.SC_min;

DesignData.Supply.maximumShortCircuitPowerVA = ...
    Input.SC_max;

DesignData.Supply.minimumLineVoltageFactor = ...
    Input.u_L;

%% =========================================================
% Converter data
%% =========================================================

DesignData.Converter = struct();

DesignData.Converter.pulseNumber = ...
    Input.PulseNumber;

DesignData.Converter.numberOfGroups = ...
    Input.PulseNumber ...
    / 6;

DesignData.Converter.thyristorType = ...
    Input.Thy.Type;

DesignData.Converter.physicalThyristorCount = ...
    DetailedSimulation.Device.totalPhysicalThyristors;

DesignData.Converter.noLoadVoltageV = ...
    Dimensioning.Uv0N;

DesignData.Converter.secondaryCurrentA = ...
    Dimensioning.I1S;

%% =========================================================
% Converter-transformer apparent-power rating
%% =========================================================

converterTransformerFactor = ...
    getOptionalNumericField( ...
        Project, ...
        'ConverterTransformerRatingFactor', ...
        1.90);

if converterTransformerFactor < 1.85 || ...
        converterTransformerFactor > 1.90

    error( ...
        'Cyclo:InvalidConverterTransformerFactor', ...
        ['The converter-transformer rating factor must be ', ...
         'between 1.85 and 1.90.']);

end

converterGroupCount = ...
    DesignData.Converter.numberOfGroups;

converterSecondaryVoltageV = ...
    DesignData.Converter.noLoadVoltageV;

converterSecondaryCurrentA = ...
    DesignData.Converter.secondaryCurrentA;
%% Validate converter-transformer calculation inputs

if ~isnumeric(converterSecondaryVoltageV) || ...
        ~isscalar(converterSecondaryVoltageV) || ...
        ~isfinite(converterSecondaryVoltageV) || ...
        converterSecondaryVoltageV <= 0
    error( ...
        'Cyclo:InvalidConverterTransformerVoltage', ...
        ['The converter-transformer secondary voltage must ', ...
         'be a positive finite numeric scalar.']);
end
if ~isnumeric(converterSecondaryCurrentA) || ...
        ~isscalar(converterSecondaryCurrentA) || ...
        ~isfinite(converterSecondaryCurrentA) || ...
        converterSecondaryCurrentA <= 0
    error( ...
        'Cyclo:InvalidConverterTransformerCurrent', ...
        ['The converter-transformer secondary current must ', ...
         'be a positive finite numeric scalar.']);
end
if ~isnumeric(converterGroupCount) || ...
        ~isscalar(converterGroupCount) || ...
        ~isfinite(converterGroupCount) || ...
        converterGroupCount < 1 || ...
        converterGroupCount ~= round(converterGroupCount)
    error( ...
        'Cyclo:InvalidConverterTransformerGroupCount', ...
        ['The converter-transformer group count must be a ', ...
         'positive integer.']);
end

DesignData.Converter.transformerCalculatedPowerPerGroupVA = ...
    sqrt(3) ...
    * converterSecondaryVoltageV ...
    * converterSecondaryCurrentA;

DesignData.Converter.transformerCalculatedPowerTotalVA = ...
    converterGroupCount ...
    * DesignData.Converter. ...
    transformerCalculatedPowerPerGroupVA;

DesignData.Converter.transformerRatingFactor = ...
    converterTransformerFactor;

DesignData.Converter.transformerSelectedPowerVA = ...
    converterTransformerFactor ...
    * DesignData.Converter. ...
    transformerCalculatedPowerTotalVA;

DesignData.Converter.transformerCalculatedPowerPerGroupMVA = ...
    DesignData.Converter. ...
    transformerCalculatedPowerPerGroupVA ...
    / 1e6;

DesignData.Converter.transformerCalculatedPowerTotalMVA = ...
    DesignData.Converter. ...
    transformerCalculatedPowerTotalVA ...
    / 1e6;

DesignData.Converter.transformerSelectedPowerMVA = ...
    DesignData.Converter. ...
    transformerSelectedPowerVA ...
    / 1e6;

DesignData.Converter.totalLosskW = ...
    DetailedSimulation.Loss.totalConverterPowerkW;

%% =========================================================
% Motor data
%% =========================================================

DesignData.Motor = struct();

DesignData.Motor.voltageV = ...
    Input.UM;

DesignData.Motor.currentA = ...
    Input.IM;

DesignData.Motor.minimumSpeedRpm = ...
    Input.n_min;

DesignData.Motor.nominalSpeedRpm = ...
    Input.n_nom;

DesignData.Motor.maximumSpeedRpm = ...
    Input.n_max;

DesignData.Motor.polePairs = ...
    Input.PolePairs;

DesignData.Motor.powerFactor = ...
    Input.cosphi_M;

DesignData.Motor.efficiency = ...
    Input.eta_M;

%% =========================================================
% Detailed Simulation summary
%% =========================================================

DesignData.Simulation = struct();

DesignData.Simulation.motorCurrentRmsA = [ ...
    DetailedSimulation.Current.iuRms, ...
    DetailedSimulation.Current.ivRms, ...
    DetailedSimulation.Current.iwRms];

DesignData.Simulation.representativeSourceCurrentRmsA = ...
    DetailedSimulation.Device. ...
    representativeGroupSourceCurrentRms;

DesignData.Simulation.physicalTopologyStatus = ...
    DetailedSimulation.PhysicalTopologyStatus;

DesignData.Simulation.sourceCurrentStatus = ...
    DetailedSimulation.SourceSideStatus;

DesignData.Simulation.sourceHarmonicStatus = ...
    DetailedSimulation.SourceHarmonicStatus;

DesignData.Simulation.lossStatus = ...
    DetailedSimulation.LossStatus;

%% =========================================================
% Model boundary
%% =========================================================

DesignData.Validation = struct();

DesignData.Validation.release = ...
    'CycloTool Release 1.0 calculation baseline';

DesignData.Validation.validatedConfigurations = { ...
    '6-pulse SCmin', ...
    '6-pulse SCmax', ...
    '12-pulse SCmin', ...
    '12-pulse SCmax', ...
    '18-pulse SCmin', ...
    '18-pulse SCmax'};

DesignData.Validation.detailedFftInterpretation = ...
    [ ...
    'ABB/Scilab representative transformer-secondary ', ...
    'group spectrum. Not the combined transformer-primary ', ...
    'spectrum.' ...
    ];

DesignData.Validation.notReconstructed = { ...
    'Combined transformer-primary current waveform', ...
    'Combined transformer-primary FFT', ...
    'Detailed physical commutation overlap', ...
    'Thyristor reverse-recovery dynamics'};

%% =========================================================
% Final validation
%% =========================================================

validateDesignData( ...
    DesignData);

end


function value = getOptionalField( ...
    S, ...
    fieldName, ...
    defaultValue)

if isfield(S, fieldName) && ...
        ~isempty(S.(fieldName))
    value = ...
        S.(fieldName);
else
    value = ...
        defaultValue;
end
end


function validateDesignData(DesignData)

if DesignData.Converter.pulseNumber < 6 || ...
        mod(DesignData.Converter.pulseNumber, 6) ~= 0

    error( ...
        'Cyclo:InvalidDocumentPulseNumber', ...
        ['The Design Data structure contains an invalid ', ...
         'converter pulse number.']);

end

expectedThyristorCount = ...
    DesignData.Converter.pulseNumber ...
    * 6;

if DesignData.Converter.physicalThyristorCount ~= ...
        expectedThyristorCount

    error( ...
        'Cyclo:InvalidDocumentThyristorCount', ...
        ['The Design Data physical thyristor count does ', ...
         'not match the converter pulse number.']);

end

if any( ...
        ~isfinite( ...
            DesignData.Simulation.motorCurrentRmsA))
    error( ...
        'Cyclo:InvalidDocumentMotorCurrent', ...
        ['The Design Data structure contains invalid ', ...
         'motor-current values.']);
end
if ~isfinite(DesignData.Converter.totalLosskW) || ...
        DesignData.Converter.totalLosskW < 0
    error( ...
        'Cyclo:InvalidDocumentConverterLoss', ...
        ['The Design Data structure contains an invalid ', ...
         'converter-loss value.']);
end
%% =========================================================
% Converter-transformer rating validation
%% =========================================================

if ~isfinite( ...
        DesignData.Converter. ...
        transformerCalculatedPowerPerGroupVA) || ...
        DesignData.Converter. ...
        transformerCalculatedPowerPerGroupVA <= 0
    error( ...
        'Cyclo:InvalidConverterTransformerGroupPower', ...
        ['The calculated converter-transformer apparent ', ...
         'power per group must be positive and finite.']);
end
if ~isfinite( ...
        DesignData.Converter. ...
        transformerCalculatedPowerTotalVA) || ...
        DesignData.Converter. ...
        transformerCalculatedPowerTotalVA <= 0
    error( ...
        'Cyclo:InvalidConverterTransformerPower', ...
        ['The calculated total converter-transformer ', ...
         'apparent power must be positive and finite.']);
end
if DesignData.Converter.transformerRatingFactor < 1.85 || ...
        DesignData.Converter.transformerRatingFactor > 1.90
    error( ...
        'Cyclo:InvalidConverterTransformerRatingFactor', ...
        ['The converter-transformer rating factor must be ', ...
         'between 1.85 and 1.90.']);
end
expectedConverterTransformerRatingVA = ...
    DesignData.Converter.transformerRatingFactor ...
    * DesignData.Converter. ...
    transformerCalculatedPowerTotalVA;
converterRatingToleranceVA = ...
    1e-9 ...
    * max( ...
        1, ...
        expectedConverterTransformerRatingVA);
if abs( ...
        DesignData.Converter. ...
        transformerSelectedPowerVA ...
        - expectedConverterTransformerRatingVA) ...
        > converterRatingToleranceVA
    error( ...
        'Cyclo:InconsistentConverterTransformerRating', ...
        ['The required converter-transformer rating is ', ...
         'inconsistent with the calculated apparent power ', ...
         'and rating factor.']);
end
expectedPowerPerGroupMVA = ...
    DesignData.Converter. ...
    transformerCalculatedPowerPerGroupVA ...
    / 1e6;
expectedTotalPowerMVA = ...
    DesignData.Converter. ...
    transformerCalculatedPowerTotalVA ...
    / 1e6;
expectedSelectedPowerMVA = ...
    DesignData.Converter. ...
    transformerSelectedPowerVA ...
    / 1e6;
if abs( ...
        DesignData.Converter. ...
        transformerCalculatedPowerPerGroupMVA ...
        - expectedPowerPerGroupMVA) ...
        > 1e-12
    error( ...
        'Cyclo:InvalidConverterGroupPowerConversion', ...
        'Converter group power VA-to-MVA conversion is invalid.');
end
if abs( ...
        DesignData.Converter. ...
        transformerCalculatedPowerTotalMVA ...
        - expectedTotalPowerMVA) ...
        > 1e-12
    error( ...
        'Cyclo:InvalidConverterTotalPowerConversion', ...
        'Converter total power VA-to-MVA conversion is invalid.');
end
if abs( ...
        DesignData.Converter. ...
        transformerSelectedPowerMVA ...
        - expectedSelectedPowerMVA) ...
        > 1e-12
    error( ...
        'Cyclo:InvalidConverterSelectedPowerConversion', ...
        'Converter selected power VA-to-MVA conversion is invalid.');
end
%% =========================================================
% Excitation-transformer rating validation
%% =========================================================

if ~isfinite( ...
        DesignData.Excitation. ...
        transformerCalculatedPowerkVA) || ...
        DesignData.Excitation. ...
        transformerCalculatedPowerkVA <= 0

    error( ...
        'Cyclo:InvalidExcitationTransformerPower', ...
        ['The calculated excitation-transformer apparent ', ...
         'power must be positive and finite.']);

end

if DesignData.Excitation.transformerRatingFactor < 1.85 || ...
        DesignData.Excitation.transformerRatingFactor > 1.90

    error( ...
        'Cyclo:InvalidExcitationTransformerRatingFactor', ...
        ['The excitation-transformer rating factor must be ', ...
         'between 1.85 and 1.90.']);

end

expectedExcitationTransformerRatingkVA = ...
    DesignData.Excitation.transformerRatingFactor ...
    * DesignData.Excitation. ...
    transformerCalculatedPowerkVA;

excitationRatingTolerancekVA = ...
    1e-9 ...
    * max( ...
        1, ...
        expectedExcitationTransformerRatingkVA);

if abs( ...
        DesignData.Excitation. ...
        transformerSelectedPowerkVA ...
        - expectedExcitationTransformerRatingkVA) ...
        > excitationRatingTolerancekVA

    error( ...
        'Cyclo:InconsistentExcitationTransformerRating', ...
        ['The required excitation-transformer rating is ', ...
         'inconsistent with the calculated apparent power ', ...
         'and rating factor.']);

end
%% Validate existing excitation-transformer comparison

if isfinite( ...
        DesignData.Excitation. ...
        existingTransformerRatingkVA)

    expectedExistingSelectionStatus = ...
        DesignData.Excitation. ...
        existingTransformerRatingkVA ...
        >= DesignData.Excitation. ...
        transformerSelectedPowerkVA;

    if DesignData.Excitation. ...
            existingTransformerMeetsRequirement ~= ...
            expectedExistingSelectionStatus

        error( ...
            'Cyclo:InconsistentExistingExcitationSelection', ...
            ['The existing excitation-transformer selection ', ...
             'status is inconsistent with the required rating.']);

    end

end
end
function value = getOptionalNumericField( ...
    S, ...
    fieldName, ...
    defaultValue)

if isfield(S, fieldName) && ...
        ~isempty(S.(fieldName))

    value = ...
        S.(fieldName);

else

    value = ...
        defaultValue;

end

if ~isnumeric(value) || ...
        ~isscalar(value) || ...
        ~isfinite(value)

    error( ...
        'Cyclo:InvalidOptionalNumericField', ...
        'Field %s must be a finite numeric scalar.', ...
        fieldName);

end

end