function Project = create_cyclo_project_metadata()
%CREATE_CYCLO_PROJECT_METADATA
% Create project and document identification data for the
% CycloTool Design Data document.
%
% This function contains document metadata only.
% It does not perform engineering calculations and does not
% read values from CycloGUI.

%% =========================================================
% Document identification
%% =========================================================

Project.DocumentTitle = ...
    'Cycloconverter Design Data';

Project.DocumentNumber = ...
    'TEST-DOCUMENT-001';

Project.Revision = ...
    'A';

Project.Language = ...
    'en';

Project.DocumentDate = ...
    string(datetime('today'));

Project.PreparedBy = ...
    'Leon Essama Onana';

Project.ApprovedBy = ...
    '';
Project.DocumentStatus = ...
    'For Review';

Project.Confidentiality = ...
    'ABB internal and authorized project use only';
%% =========================================================
% Project identification
%% =========================================================

Project.ProjectName = ...
    'CycloTool Test Project';

Project.Client = ...
    'Aktogay GMD Stator';

Project.Contractor = ...
    'KAL';

Project.ABBProjectNumber = ...
    'TEST-ABB-001';

Project.CustomerPONumber = ...
    'TEST-PO-001';

Project.CustomerDocumentNumber = ...
    'TEST-CUSTOMER-DOC-001';

%% =========================================================
% Equipment identification
%% =========================================================

Project.EquipmentName = ...
    'Cycloconverter';

Project.EquipmentTag = ...
    'TEST-CYC-001';

Project.Location = ...
    '';

Project.Application = ...
    'Synchronous RingMotor Cycloconverter drive';

%% =========================================================
% Revision information
%% =========================================================

Project.RevisionDescription = ...
    'Initial CycloTool generated Design Data document';

Project.ResponsibleDepartment = ...
    '';
%% =========================================================
% Transformer rating selection factors
%% =========================================================
%
% Project-specific design factors used to convert calculated
% apparent power into selected transformer rated power.
%
% These factors are configurable engineering-selection inputs.
% They are not fixed universal IEC coefficients.

Project.ConverterTransformerRatingFactor = ...
    1.90;

Project.ExcitationTransformerRatingFactor = ...
    1.90;
%% =========================================================
% Validation
%% =========================================================

requiredTextFields = { ...
    'DocumentTitle', ...
    'DocumentNumber', ...
    'Revision', ...
    'Language', ...
    'DocumentStatus', ...
    'Confidentiality', ...
    'ProjectName', ...
    'EquipmentTag', ...
    'PreparedBy'};

for fieldIndex = 1:numel(requiredTextFields)

    fieldName = ...
        requiredTextFields{fieldIndex};

    if ~isfield(Project, fieldName) || ...
            strlength( ...
                strtrim( ...
                    string(Project.(fieldName)))) == 0

        error( ...
            'Cyclo:MissingProjectMetadata', ...
            'Required project metadata field %s is empty.', ...
            fieldName);

    end

end

%% Validate transformer selection factors

transformerRatingFactors = [ ...
    Project.ConverterTransformerRatingFactor, ...
    Project.ExcitationTransformerRatingFactor];

if any( ...
        ~isfinite(transformerRatingFactors)) || ...
        any(transformerRatingFactors < 1.85) || ...
        any(transformerRatingFactors > 1.90)

    error( ...
        'Cyclo:InvalidTransformerRatingFactor', ...
        ['Transformer rating factors must be between ', ...
         '1.85 and 1.90.']);

end

%% Validate document status

allowedDocumentStatuses = { ...
    'Draft', ...
    'For Review', ...
    'For Approval', ...
    'Approved', ...
    'As Built'};

if ~any( ...
        strcmpi( ...
            Project.DocumentStatus, ...
            allowedDocumentStatuses))

    error( ...
        'Cyclo:InvalidDocumentStatus', ...
        ['DocumentStatus must be Draft, For Review, ', ...
         'For Approval, Approved, or As Built.']);

end

%% Validate language

allowedLanguages = { ...
    'en', ...
    'de', ...
    'fr', ...
    'es'};

if ~any( ...
        strcmpi( ...
            Project.Language, ...
            allowedLanguages))

    error( ...
        'Cyclo:InvalidDocumentLanguage', ...
        'Document language must be en, de, fr, or es.');

end


end