function Release = cyclotool_release_info()
%CYCLOTOOL_RELEASE_INFO Return CycloTool release information.

Release = ...
    struct();

Release.Product = ...
    'CycloTool';

Release.Version = ...
    '1.1';

Release.ReleaseName = ...
    'CycloTool Release 1.1';

Release.ReleaseDate = ...
    '2026-08-21';

Release.CalculationBaseline = ...
    'CycloTool Release 1.0';

Release.ReportGenerator = ...
    'Design Data Report Generation 1.1';

Release.ValidatedPulseNumbers = ...
    [6, 12, 18];

Release.ValidatedNetworkCases = { ...
    'SCmin', ...
    'SCmax'};

Release.TransformerRatingFactorRange = ...
    [1.85, 1.90];

Release.DefaultTransformerRatingFactor = ...
    1.90;

Release.ReportFigureCount = ...
    10;

Release.Status = ...
    'Release candidate pending final acceptance';

end