function documentFile = ...
    generate_cyclo_design_document( ...
        Report, ...
        figureFolder, ...
        outputFolder)
%GENERATE_CYCLO_DESIGN_DOCUMENT
% Generate a CycloTool Design Data Word document.
%
% Initial document-generation smoke test:
%   - Cover page
%   - Document identification
%   - Project identification
%   - Main supply data
%   - Converter and transformer data
%
% Engineering calculations are not repeated in this function.

arguments
    Report       (1,1) struct
    figureFolder (1,1) string
    outputFolder (1,1) string
end

import mlreportgen.dom.*

%% =========================================================
% Required-data validation
%% =========================================================

requiredReportFields = { ...
    'Metadata', ...
    'DocumentIdentification', ...
    'ProjectIdentification', ...
    'Supply', ...
    'Converter', ...
    'ConverterCurrents', ...
    'Thermal', ...
    'Motor', ...
    'MotorCurrents', ...
    'OperatingPoint', ...
    'MotorCharacteristic', ...
    'FiringAngleSummary', ...
    'FiringAngle', ...
    'HarmonicSummary', ...
    'Harmonics', ...
    'Excitation', ...
    'Protection', ...
    'ProtectiveSettings', ...
    'DetailedSimulation', ...
    'RepresentativeGroupCurrents', ...
    'DetailedFftInterpretation', ...
    'ValidationStatus', ...
    'ModelLimitations', ...
    'Figures'};

for fieldIndex = 1:numel(requiredReportFields)

    fieldName = ...
        requiredReportFields{fieldIndex};

    if ~isfield(Report, fieldName) || ...
            isempty(Report.(fieldName))

        error( ...
            'Cyclo:MissingWordReportField', ...
            'The report model is missing field %s.', ...
            fieldName);

    end

end

if ~isfolder(outputFolder)

    mkdir(outputFolder);

end

if ~isfolder(figureFolder)

    error( ...
        'Cyclo:MissingWordFigureFolder', ...
        'The Design Data figure folder does not exist.');

end

%% =========================================================
% Initialize output path
%% =========================================================

documentName = ...
    createDocumentName( ...
        Report.Metadata);

documentBasePath = ...
    fullfile( ...
        outputFolder, ...
        documentName);

documentFile = ...
    documentBasePath ...
    + ".docx";

if isfile(documentFile)

    delete(documentFile);

end

%% =========================================================
% Create Word document
%% =========================================================
document = ...
    Document( ...
        documentBasePath, ...
        'docx');

open(document);

documentCleanup = ...
    onCleanup( ...
        @() closeDocumentSafely(document));
%% =========================================================
% Configure page layout
%% =========================================================

section = ...
    document.CurrentPageLayout;

section.PageSize.Orientation = ...
    'portrait';

section.PageMargins.Top = ...
    '18mm';

section.PageMargins.Bottom = ...
    '18mm';

section.PageMargins.Left = ...
    '18mm';

section.PageMargins.Right = ...
    '18mm';
section.PageMargins.Header = ...
    '8mm';

section.PageMargins.Footer = ...
    '8mm';
%% =========================================================
% Document-control header and footer
%% =========================================================

appendDocumentControl( ...
    section, ...
    Report);
%% =========================================================
% Create document styles
%% =========================================================

styles = ...
    createDocumentStyles();

%% =========================================================
% Cover page
%% =========================================================

appendCoverPage( ...
    document, ...
    Report, ...
    styles);

append( ...
    document, ...
    PageBreak());

%% =========================================================
% Table of contents
%% =========================================================

contentsHeading = ...
    Paragraph( ...
        'Contents');

contentsHeading.Style = ...
    styles.Heading1;

append( ...
    document, ...
    contentsHeading);

tableOfContents = ...
    TOC(2);

append( ...
    document, ...
    tableOfContents);

contentsNote = ...
    Paragraph( ...
        ['If the table of contents does not display page ', ...
         'numbers immediately, right-click the table in ', ...
         'Microsoft Word and select Update Field, then ', ...
         'Update Entire Table.']);

contentsNote.Style = ...
    styles.Note;

append( ...
    document, ...
    contentsNote);

append( ...
    document, ...
    PageBreak());

%% =========================================================
% 1. Overview diagram
%% =========================================================

appendHeading( ...
    document, ...
    '1. Overview Diagram', ...
    styles.Heading1);

appendReportFigure( ...
    document, ...
    figureFolder, ...
    Report.Figures.Overview.FileName, ...
    'Figure 1. Cycloconverter overview diagram', ...
    ['Functional overview of the converter transformer, ', ...
     'cycloconverter, synchronous motor, and static ', ...
     'excitation system.'], ...
    "150mm");

append( ...
    document, ...
    PageBreak());

%% =========================================================
% 2. Main data
%% =========================================================

appendHeading( ...
    document, ...
    '2. Main Data', ...
    styles.Heading1);

mainDataIntroduction = ...
    Paragraph( ...
        ['This section summarizes the principal electrical ', ...
         'ratings and selected equipment for the cycloconverter ', ...
         'drive system.']);

mainDataIntroduction.Style = ...
    styles.Body;

append( ...
    document, ...
    mainDataIntroduction);

%% =========================================================
% 2.1 Document and project identification
%% =========================================================

appendHeading( ...
    document, ...
    '2.1 Project and Equipment Identification', ...
    styles.Heading2,...
    2);

appendCellTable( ...
    document, ...
    Report.ProjectIdentification, ...
    styles, ...
    [0.42, 0.43, 0.15]);

%% =========================================================
% 2.2 Supply
%% =========================================================

appendHeading( ...
    document, ...
    '2.2 Supply', ...
    styles.Heading2, ...
    2);

appendCellTable( ...
    document, ...
    Report.Supply, ...
    styles, ...
    [0.48, 0.15, 0.22, 0.15]);

%% =========================================================
% 2.3 Converter transformer and converter
%% =========================================================

appendHeading( ...
    document, ...
    '2.3 Converter Transformer and Converter', ...
    styles.Heading2, ...
    2);

appendCellTable( ...
    document, ...
    Report.Converter, ...
    styles, ...
    [0.48, 0.15, 0.22, 0.15]);

%% =========================================================
% 2.4 Converter ratings
%% =========================================================

appendHeading( ...
    document, ...
    '2.4 Converter Current and Thermal Ratings', ...
    styles.Heading2, ...
    2);

appendCellTable( ...
    document, ...
    Report.ConverterCurrents, ...
    styles, ...
    [0.48, 0.15, 0.22, 0.15]);

appendCellTable( ...
    document, ...
    Report.Thermal, ...
    styles, ...
    [0.48, 0.15, 0.22, 0.15]);

append( ...
    document, ...
    PageBreak());

%% =========================================================
% 2.5 Motor
%% =========================================================

appendHeading( ...
    document, ...
    '2.5 Motor', ...
    styles.Heading2, ...
    2);

appendCellTable( ...
    document, ...
    Report.Motor, ...
    styles, ...
    [0.48, 0.15, 0.22, 0.15]);

%% =========================================================
% 2.6 Motor overload and operating point
%% =========================================================

appendHeading( ...
    document, ...
    '2.6 Motor Overload and Operating Point', ...
    styles.Heading2, ...
    2);

appendCellTable( ...
    document, ...
    Report.MotorCurrents, ...
    styles, ...
    [0.48, 0.15, 0.22, 0.15]);

appendCellTable( ...
    document, ...
    Report.OperatingPoint, ...
    styles, ...
    [0.48, 0.15, 0.22, 0.15]);

%% =========================================================
% 2.7 Excitation system
%% =========================================================

appendHeading( ...
    document, ...
    '2.7 Excitation System', ...
    styles.Heading2, ...
    2);

appendCellTable( ...
    document, ...
    Report.Excitation, ...
    styles, ...
    [0.55, 0.27, 0.18]);

append( ...
    document, ...
    PageBreak());

%% =========================================================
% 3. Motor characteristic
%% =========================================================

appendHeading( ...
    document, ...
    '3. Motor Voltage and Current as a Function of Line-Voltage Variation', ...
    styles.Heading1);
appendCellTable( ...
    document, ...
    Report.MotorCharacteristic, ...
    styles, ...
    [ ...
    0.06, ...
    0.11, ...
    0.11, ...
    0.12, ...
    0.12, ...
    0.12, ...
    0.12, ...
    0.12, ...
    0.12]);

appendReportFigure( ...
    document, ...
    figureFolder, ...
    Report.Figures.MotorCharacteristic.FileName, ...
    ['Figure 2. Motor voltage and current as a function ', ...
     'of line-voltage variation'], ...
    ['Nominal, minimum line-voltage, and overload ', ...
     'characteristics calculated by CycloTool.'], ...
    "130mm");

append( ...
    document, ...
    PageBreak());

%% =========================================================
% 4. Control characteristics
%% =========================================================

appendHeading( ...
    document, ...
    '4. Control Characteristics', ...
    styles.Heading1);

appendHeading( ...
    document, ...
    '4.1 Maximum Inverter Firing Angle versus Load Current', ...
    styles.Heading2, ...
    2);

appendCellTable( ...
    document, ...
    Report.FiringAngleSummary, ...
    styles, ...
    [0.55, 0.25, 0.20]);

appendCellTable( ...
    document, ...
    Report.FiringAngle, ...
    styles, ...
    [0.20, 0.20, 0.20, 0.20, 0.20]);

appendReportFigure( ...
    document, ...
    figureFolder, ...
    Report.Figures.FiringAngle.FileName, ...
    ['Figure 3. Maximum inverter firing angle versus ', ...
     'load current'], ...
    ['The recommended setting includes the specified ', ...
     'commutation margin and network-reactance influence.'], ...
    "130mm");

append( ...
    document, ...
    PageBreak());

%% =========================================================
% 5. Protective settings
%% =========================================================

appendHeading( ...
    document, ...
    '5. Protective Settings', ...
    styles.Heading1);

appendHeading( ...
    document, ...
    '5.1 Overvoltage Protection', ...
    styles.Heading2, ...
    2);

appendCellTable( ...
    document, ...
    Report.Protection, ...
    styles, ...
    [0.55, 0.27, 0.18]);

appendHeading( ...
    document, ...
    '5.2 Converter and Motor Protection Settings', ...
    styles.Heading2, ...
    2);

appendCellTable( ...
    document, ...
    Report.ProtectiveSettings, ...
    styles, ...
    [0.48, 0.15, 0.22, 0.15]);

append( ...
    document, ...
    PageBreak());

%% =========================================================
% 6. Revision history
%% =========================================================

appendHeading( ...
    document, ...
    '6. Revision History', ...
    styles.Heading1);

revisionTable = {
    'Revision', ...
    'Description', ...
    'Date', ...
    'Prepared by'
    string(Report.Metadata.Revision), ...
    findTableValue( ...
        Report.DocumentIdentification, ...
        'Revision description'), ...
    string(Report.Metadata.Date), ...
    string(Report.Metadata.PreparedBy)
    };

appendCellTable( ...
    document, ...
    revisionTable, ...
    styles, ...
    [0.12, 0.48, 0.18, 0.22]);

append( ...
    document, ...
    PageBreak());

%% =========================================================
% Appendix A: Analytical harmonics
%% =========================================================

appendHeading( ...
    document, ...
    'Appendix A. Analytical Multi-Pulse Harmonics', ...
    styles.Heading1);

harmonicNote = ...
    Paragraph( ...
        ['The analytical harmonic calculation represents the ', ...
         'multi-pulse system-level dimensioning model, including ', ...
         'the applicable transformer-group cancellation factors.']);

harmonicNote.Style = ...
    styles.Note;

append( ...
    document, ...
    harmonicNote);

appendCellTable( ...
    document, ...
    Report.HarmonicSummary, ...
    styles, ...
    [0.55, 0.25, 0.20]);

appendCellTable( ...
    document, ...
    Report.Harmonics, ...
    styles, ...
    [0.18, 0.27, 0.30, 0.25]);

appendReportFigure( ...
    document, ...
    figureFolder, ...
    Report.Figures.AnalyticalHarmonics.FileName, ...
    'Figure A-1. Analytical multi-pulse harmonic spectrum', ...
    ['Analytical dimensioning spectrum including the ', ...
     'pulse-number cancellation assumptions.'], ...
    "135mm");

append( ...
    document, ...
    PageBreak());

%% =========================================================
% Appendix B: Detailed Simulation
%% =========================================================

appendHeading( ...
    document, ...
    'Appendix B. Detailed Simulation Summary', ...
    styles.Heading1);

simulationNote = ...
    Paragraph( ...
        ['The Detailed Simulation uses the validated ', ...
         'ABB/Scilab natural-selection model and explicitly ', ...
         'represents every modeled physical thyristor.']);

simulationNote.Style = ...
    styles.Note;

append( ...
    document, ...
    simulationNote);

appendCellTable( ...
    document, ...
    Report.DetailedSimulation, ...
    styles, ...
    [0.55, 0.27, 0.18]);

appendHeading( ...
    document, ...
    'B.1 Representative Converter-Group Currents', ...
    styles.Heading2, ...
    2);

appendCellTable( ...
    document, ...
    Report.RepresentativeGroupCurrents, ...
    styles, ...
    [ ...
    0.08, ...
    0.15, ...
    0.15, ...
    0.15, ...
    0.16, ...
    0.14, ...
    0.17]);
append( ...
    document, ...
    PageBreak());

%% =========================================================
% Figure B-1: Motor phase currents
%% =========================================================

appendHeading( ...
    document, ...
    'B.2 Motor Phase-Current Waveforms', ...
    styles.Heading2, ...
    2);

appendReportFigure( ...
    document, ...
    figureFolder, ...
    Report.Figures.SimulationMotorCurrents.FileName, ...
    'Figure B-1. Detailed Simulation motor phase currents', ...
    ['Reconstructed motor phase-current waveforms and ', ...
     'reference currents from the validated Detailed ', ...
     'Simulation model.'], ...
    "135mm");

append( ...
    document, ...
    PageBreak());

%% =========================================================
% Figure B-2: Converter output voltages
%% =========================================================

appendHeading( ...
    document, ...
    'B.3 Converter Output-Voltage Waveforms', ...
    styles.Heading2, ...
    2);

appendReportFigure( ...
    document, ...
    figureFolder, ...
    Report.Figures.SimulationVoltages.FileName, ...
    'Figure B-2. Detailed Simulation converter output voltages', ...
    ['Motor phase and line-to-line voltage waveforms from ', ...
     'the validated Detailed Simulation model.'], ...
    "135mm");

append( ...
    document, ...
    PageBreak());

%% =========================================================
% Figure B-3: Switching states
%% =========================================================

appendHeading( ...
    document, ...
    'B.4 Switching-State Overview', ...
    styles.Heading2, ...
    2);

appendReportFigure( ...
    document, ...
    figureFolder, ...
    Report.Figures.SimulationSwitching.FileName, ...
    'Figure B-3. Detailed Simulation switching-state overview', ...
    ['Output-phase polarity selection, physical-device ', ...
     'conduction states, and representative T111 and T211 ', ...
     'switching states.'], ...
    "135mm");

append( ...
    document, ...
    PageBreak());

%% =========================================================
% Figure B-4: Physical thyristor currents
%% =========================================================

appendHeading( ...
    document, ...
    'B.5 Physical Thyristor Current Allocation', ...
    styles.Heading2, ...
    2);

appendReportFigure( ...
    document, ...
    figureFolder, ...
    Report.Figures.SimulationDeviceCurrents.FileName, ...
    'Figure B-4. Physical thyristor current allocation', ...
    ['Representative thyristor-current waveforms, complete ', ...
     '12-device current allocation, current statistics, ', ...
     'and switching counts for converter group 1 and ', ...
     'motor output phase U.'], ...
    "135mm");
append( ...
    document, ...
    PageBreak());

%% =========================================================
% Appendix C: Representative FFT
%% =========================================================

appendHeading( ...
    document, ...
    'Appendix C. Representative Secondary-Group FFT', ...
    styles.Heading1);

fftBoundaryNote = ...
    Paragraph( ...
        string(Report.DetailedFftInterpretation));

fftBoundaryNote.Style = ...
    styles.Note;

append( ...
    document, ...
    fftBoundaryNote);

appendReportFigure( ...
    document, ...
    figureFolder, ...
    Report.Figures.DetailedFft.FileName, ...
    ['Figure C-1. ABB/Scilab representative ', ...
     'secondary-group FFT'], ...
    ['Individual converter-secondary group diagnostic. ', ...
     'This figure is not the combined transformer-primary ', ...
     'harmonic spectrum.'], ...
    "135mm");

append( ...
    document, ...
    PageBreak());

%% =========================================================
% Appendix D: Converter losses
%% =========================================================

appendHeading( ...
    document, ...
    'Appendix D. Converter Loss Breakdown', ...
    styles.Heading1);

appendReportFigure( ...
    document, ...
    figureFolder, ...
    Report.Figures.ConverterLosses.FileName, ...
    'Figure D-1. Converter loss breakdown', ...
    ['Explicit physical-device loss summation validated ', ...
     'within the ABB/Scilab model.'], ...
    "115mm");

append( ...
    document, ...
    PageBreak());

%% =========================================================
% Appendix E: Validation and limitations
%% =========================================================
appendHeading( ...
    document, ...
    'Appendix E. Validation Status and Model Limitations', ...
    styles.Heading1);
appendCellTable( ...
    document, ...
    Report.ValidationStatus, ...
    styles, ...
    [0.55, 0.45]);
limitationsIntroduction = ...
    Paragraph( ...
        ['The following functions are outside the validated ', ...
         'scope of the present CycloTool release:']);
limitationsIntroduction.Style = ...
    styles.Body;
append( ...
    document, ...
    limitationsIntroduction);
for limitationIndex = 1:numel(Report.ModelLimitations)
    limitationParagraph = ...
        Paragraph();
    limitationParagraph.Style = ...
        styles.Body;
    append( ...
        limitationParagraph, ...
        Text( ...
            "• " ...
            + string( ...
                Report.ModelLimitations{limitationIndex})));
    append( ...
        document, ...
        limitationParagraph);
end
finalNote = ...
    Paragraph( ...
        ['Generated using CycloTool Development 1.1 from the ', ...
         'validated CycloTool Release 1.0 calculation baseline.']);
finalNote.Style = ...
    styles.Note;
append( ...
    document, ...
    finalNote);
%% =========================================================
% Close document
%% =========================================================

close(document);
documentCleanup = [];
if ~isfile(documentFile)

    error( ...
        'Cyclo:WordDocumentExportFailure', ...
        'The CycloTool Design Data Word document was not created.');

end

end


function documentName = createDocumentName(Metadata)

documentNumber = ...
    sanitizeFileName( ...
        string(Metadata.DocumentNumber));

revision = ...
    sanitizeFileName( ...
        string(Metadata.Revision));

if strlength(documentNumber) == 0

    documentNumber = ...
        "CycloTool_Design_Data";

end

if strlength(revision) == 0

    revision = ...
        "A";

end

documentName = ...
    documentNumber ...
    + "_Rev" ...
    + revision;

end


function value = sanitizeFileName(value)

value = ...
    string(value);

invalidCharacters = ...
    ["<", ">", ":", """", "/", "\", "|", "?", "*"];

for characterIndex = 1:numel(invalidCharacters)

    value = ...
        replace( ...
            value, ...
            invalidCharacters(characterIndex), ...
            "_");

end

value = ...
    strip(value);

end


function styles = createDocumentStyles()

import mlreportgen.dom.*

styles = ...
    struct();

styles.Title = { ...
    FontFamily('Arial'), ...
    FontSize('24pt'), ...
    Bold(true), ...
    Color('#1F4E79'), ...
    HAlign('center')};

styles.Subtitle = { ...
    FontFamily('Arial'), ...
    FontSize('14pt'), ...
    Bold(true), ...
    Color('#444444'), ...
    HAlign('center')};

styles.CoverMetadata = { ...
    FontFamily('Arial'), ...
    FontSize('11pt'), ...
    HAlign('center')};

styles.Heading1 = { ...
    FontFamily('Arial'), ...
    FontSize('15pt'), ...
    Bold(true), ...
    Color('#1F4E79'), ...
    HAlign('left')};

styles.Heading2 = { ...
    FontFamily('Arial'), ...
    FontSize('12pt'), ...
    Bold(true), ...
    Color('#365F91'), ...
    HAlign('left')};

styles.Body = { ...
    FontFamily('Arial'), ...
    FontSize('10pt'), ...
    HAlign('left')};

styles.Note = { ...
    FontFamily('Arial'), ...
    FontSize('9pt'), ...
    Italic(true), ...
    Color('#666666'), ...
    HAlign('left')};

styles.TableHeader = { ...
    FontFamily('Arial'), ...
    FontSize('9pt'), ...
    Bold(true), ...
    Color('#FFFFFF'), ...
    HAlign('center')};

styles.TableDescription = { ...
    FontFamily('Arial'), ...
    FontSize('9pt'), ...
    HAlign('left')};

styles.TableValue = { ...
    FontFamily('Arial'), ...
    FontSize('9pt'), ...
    HAlign('center')};

end


function appendCoverPage(document, Report, styles)

import mlreportgen.dom.*

for spacerIndex = 1:5

    spacer = ...
        Paragraph(' ');

    append( ...
        document, ...
        spacer);

end

titleParagraph = ...
    Paragraph( ...
        string(Report.Metadata.Title));

titleParagraph.Style = ...
    styles.Title;

append( ...
    document, ...
    titleParagraph);

projectName = ...
    findTableValue( ...
        Report.ProjectIdentification, ...
        'Project');

projectParagraph = ...
    Paragraph( ...
        projectName);

projectParagraph.Style = ...
    styles.Subtitle;

append( ...
    document, ...
    projectParagraph);

equipmentTag = ...
    findTableValue( ...
        Report.ProjectIdentification, ...
        'Equipment tag');

if strlength(equipmentTag) > 0

    equipmentParagraph = ...
        Paragraph( ...
            "Equipment: " ...
            + equipmentTag);

    equipmentParagraph.Style = ...
        styles.CoverMetadata;

    append( ...
        document, ...
        equipmentParagraph);

end

metadataLines = { ...
    "Document number: " ...
    + string(Report.Metadata.DocumentNumber), ...
    "Revision: " ...
    + string(Report.Metadata.Revision), ...
    "Document status: " ...
    + string(Report.Metadata.Status), ...
    "Language: " ...
    + upper( ...
        string(Report.Metadata.Language)), ...
    "Date: " ...
    + string(Report.Metadata.Date), ...
    "Prepared by: " ...
    + string(Report.Metadata.PreparedBy), ...
    "Approved by: " ...
    + optionalDisplayText( ...
        Report.Metadata.ApprovedBy, ...
        'Pending')};
%% =========================================================
% Cover document-control table
%% =========================================================

for spacerIndex = 1:2

    append( ...
        document, ...
        Paragraph(' '));

end

coverControlData = {
    'Document', ...
    'Revision', ...
    'Status', ...
    'Language'

    string(Report.Metadata.DocumentNumber), ...
    string(Report.Metadata.Revision), ...
    string(Report.Metadata.Status), ...
    upper( ...
        string(Report.Metadata.Language))
    };

appendCellTable( ...
    document, ...
    coverControlData, ...
    styles, ...
    [0.40, 0.15, 0.30, 0.15]);
for lineIndex = 1:numel(metadataLines)

    metadataParagraph = ...
        Paragraph( ...
            metadataLines{lineIndex});

    metadataParagraph.Style = ...
        styles.CoverMetadata;

    append( ...
        document, ...
        metadataParagraph);

end

baselineParagraph = ...
    Paragraph( ...
        string( ...
            Report.Metadata.CalculationBaseline));

for spacerIndex = 1:3

    spacer = ...
        Paragraph(' ');

    append( ...
        document, ...
        spacer);

end

baselineParagraph.Style = { ...
    FontFamily('Arial'), ...
    FontSize('9pt'), ...
    Italic(true), ...
    Color('#666666'), ...
    HAlign('center')};

append( ...
    document, ...
    baselineParagraph);
%% =========================================================
% Confidentiality notice
%% =========================================================

confidentialityParagraph = ...
    Paragraph( ...
        string( ...
            Report.Metadata.Confidentiality));

confidentialityParagraph.Style = { ...
    FontFamily('Arial'), ...
    FontSize('8pt'), ...
    Bold(true), ...
    Color('#666666'), ...
    HAlign('center')};

append( ...
    document, ...
    confidentialityParagraph);
end


function appendHeading( ...
    document, ...
    headingText, ...
    headingStyle, ...
    headingLevel)
%APPENDHEADING Add a real Word heading to the document.
%
% headingLevel:
%   1 = main section
%   2 = subsection

import mlreportgen.dom.*

%% Use Heading 1 when no level is provided

if nargin < 4

    headingLevel = ...
        1;

end

%% Validate heading level

if ~isnumeric(headingLevel) || ...
        ~isscalar(headingLevel) || ...
        ~isfinite(headingLevel) || ...
        ~ismember(headingLevel, [1, 2])

    error( ...
        'Cyclo:InvalidWordHeadingLevel', ...
        'The Word heading level must be numeric 1 or 2.');

end

%% Create a real Word heading

heading = ...
    Heading( ...
        headingLevel, ...
        char(string(headingText)));

heading.Style = ...
    headingStyle;

append( ...
    document, ...
    heading);

end


function appendCellTable( ...
    document, ...
    cellData, ...
    styles, ...
    widthFractions)

import mlreportgen.dom.*

numberOfRows = ...
    size(cellData, 1);

numberOfColumns = ...
    size(cellData, 2);

if numberOfRows < 1 || ...
        numberOfColumns < 1

    error( ...
        'Cyclo:EmptyWordTable', ...
        'A Design Data Word table is empty.');

end

if numel(widthFractions) ~= ...
        numberOfColumns

    error( ...
        'Cyclo:InvalidWordTableWidths', ...
        ['The number of table-width fractions does not ', ...
         'match the number of columns.']);

end

if abs(sum(widthFractions) - 1) > 1e-9

    error( ...
        'Cyclo:InvalidWordTableWidthSum', ...
        'The table-width fractions must sum to one.');

end

tableObject = ...
    Table();

tableObject.Width = ...
    '100%';

tableObject.Border = ...
    'solid';

tableObject.BorderWidth = ...
    '0.5pt';

tableObject.ColSep = ...
    'solid';

tableObject.RowSep = ...
    'solid';

for rowIndex = 1:numberOfRows

    tableRow = ...
        TableRow();

    for columnIndex = 1:numberOfColumns

        tableEntry = ...
            TableEntry();

        tableEntry.Style = { ...
            OuterMargin( ...
                '3pt', ...
                '3pt', ...
                '3pt', ...
                '3pt')};

        cellParagraph = ...
            Paragraph();

        cellValue = ...
            formatCellValue( ...
                cellData{rowIndex,columnIndex});

        append( ...
            cellParagraph, ...
            Text(cellValue));

        if rowIndex == 1

            cellParagraph.Style = ...
                styles.TableHeader;

            tableEntry.Style = [ ...
                tableEntry.Style, ...
                {BackgroundColor('#1F4E79')}];

        elseif columnIndex == 1

            cellParagraph.Style = ...
                styles.TableDescription;

            tableEntry.Style = [ ...
                tableEntry.Style, ...
                {BackgroundColor('#D9EAF7')}];

        else

            cellParagraph.Style = ...
                styles.TableValue;

        end

        append( ...
            tableEntry, ...
            cellParagraph);

        append( ...
            tableRow, ...
            tableEntry);

    end

    append( ...
        tableObject, ...
        tableRow);

end

append( ...
    document, ...
    tableObject);

tableSpacer = ...
    Paragraph(' ');

append( ...
    document, ...
    tableSpacer);

end
function appendReportFigure( ...
    document, ...
    figureFolder, ...
    figureFileName, ...
    captionText, ...
    noteText, ...
    imageWidth)

import mlreportgen.dom.*
%% Use a default width when no width is provided

if nargin < 6 || ...
        strlength(string(imageWidth)) == 0

    imageWidth = ...
        "130mm";

end
%% Validate source image

figurePath = ...
    fullfile( ...
        figureFolder, ...
        string(figureFileName));

if ~isfile(figurePath)

    error( ...
        'Cyclo:MissingWordReportFigure', ...
        'The report figure does not exist: %s', ...
        figurePath);

end

figureInformation = ...
    dir(figurePath);

if figureInformation.bytes <= 0

    error( ...
        'Cyclo:EmptyWordReportFigure', ...
        'The report figure is empty: %s', ...
        figurePath);

end

%% Insert figure

%% Read the original PNG dimensions

imageInformation = ...
    imfinfo( ...
        char(figurePath));

sourceWidthPixels = ...
    double(imageInformation.Width);

sourceHeightPixels = ...
    double(imageInformation.Height);

if sourceWidthPixels <= 0 || ...
        sourceHeightPixels <= 0

    error( ...
        'Cyclo:InvalidWordReportFigureDimensions', ...
        'The report figure has invalid pixel dimensions.');

end

%% Convert requested Word width from millimetres

imageWidthText = ...
    string(imageWidth);

if ~endsWith( ...
        lower(imageWidthText), ...
        "mm")

    error( ...
        'Cyclo:InvalidWordImageWidthUnit', ...
        'The Word image width must be specified in millimetres.');

end

imageWidthMillimetres = ...
    str2double( ...
        erase( ...
            lower(imageWidthText), ...
            "mm"));

if ~isfinite(imageWidthMillimetres) || ...
        imageWidthMillimetres <= 0

    error( ...
        'Cyclo:InvalidWordImageWidth', ...
        'The Word image width must be finite and positive.');

end

%% Preserve the original image aspect ratio

aspectRatio = ...
    sourceHeightPixels ...
    / sourceWidthPixels;

imageHeightMillimetres = ...
    imageWidthMillimetres ...
    * aspectRatio;

%% Insert image with explicit width and height

imageObject = ...
    Image( ...
        char(figurePath));

imageObject.Width = ...
    sprintf( ...
        '%.2fmm', ...
        imageWidthMillimetres);

imageObject.Height = ...
    sprintf( ...
        '%.2fmm', ...
        imageHeightMillimetres);
fprintf( ...
    ['Word figure: %s\n', ...
     '  Source: %d x %d pixels\n', ...
     '  Display: %.2f x %.2f mm\n'], ...
    char(string(figureFileName)), ...
    sourceWidthPixels, ...
    sourceHeightPixels, ...
    imageWidthMillimetres, ...
    imageHeightMillimetres);

imageParagraph = ...
    Paragraph();

imageParagraph.Style = { ...
    HAlign('center')};

append( ...
    imageParagraph, ...
    imageObject);

append( ...
    document, ...
    imageParagraph);

%% Insert caption

captionParagraph = ...
    Paragraph();

captionParagraph.Style = { ...
    FontFamily('Arial'), ...
    FontSize('9pt'), ...
    Bold(true), ...
    HAlign('center')};

append( ...
    captionParagraph, ...
    Text( ...
        string(captionText)));

append( ...
    document, ...
    captionParagraph);

%% Insert optional note

if strlength(string(noteText)) > 0

    noteParagraph = ...
        Paragraph();

    noteParagraph.Style = { ...
        FontFamily('Arial'), ...
        FontSize('8pt'), ...
        Italic(true), ...
        Color('#666666'), ...
        HAlign('center')};

    append( ...
        noteParagraph, ...
        Text( ...
            string(noteText)));

    append( ...
        document, ...
        noteParagraph);

end

%% Add spacing after figure

append( ...
    document, ...
    Paragraph(' '));

end

function textValue = formatCellValue(value)

if isempty(value)

    textValue = ...
        "";

elseif isnumeric(value)

    if isscalar(value)

        if isnan(value)

            textValue = ...
                "";

        elseif abs(value) >= 1000

            textValue = ...
                sprintf( ...
                    '%.0f', ...
                    value);

        elseif abs(value) >= 100

            textValue = ...
                sprintf( ...
                    '%.1f', ...
                    value);

        elseif abs(value) >= 1

            textValue = ...
                sprintf( ...
                    '%.3f', ...
                    value);

        else

            textValue = ...
                sprintf( ...
                    '%.4f', ...
                    value);

        end

    else

        textValue = ...
            string(value);

    end

elseif islogical(value)

    if value

        textValue = ...
            "PASS";

    else

        textValue = ...
            "FAIL";

    end

else

    textValue = ...
        string(value);

end

end


function value = findTableValue(tableData, parameterName)

value = ...
    "";

for rowIndex = 2:size(tableData,1)

    rowName = ...
        string( ...
            tableData{rowIndex,1});

    if strcmpi( ...
            strtrim(rowName), ...
            strtrim(parameterName))

        value = ...
            string( ...
                tableData{rowIndex,2});

        return

    end

end

end
function value = optionalDisplayText( ...
    sourceValue, ...
    defaultValue)
%OPTIONALDISPLAYTEXT
% Return a default display value when report metadata is empty.

sourceText = ...
    strtrim( ...
        string(sourceValue));

if strlength(sourceText) == 0

    value = ...
        string(defaultValue);

else

    value = ...
        sourceText;

end

end
function closeDocumentSafely(document)

try

    if strcmpi( ...
            string(document.OpenStatus), ...
            "open")

        close(document);

    end

catch

    % Preserve the original document-generation error.

end

end
function appendDocumentControl(pageLayout, Report)
%APPENDDOCUMENTCONTROL
% Add repeated document-control information to a DOCX page
% layout using DOCXPageHeader and DOCXPageFooter objects.

import mlreportgen.dom.*

%% =========================================================
% Validate page layout
%% =========================================================

if isempty(pageLayout) || ...
        ~isa( ...
            pageLayout, ...
            'mlreportgen.dom.DOCXPageLayout')

    error( ...
        'Cyclo:InvalidDocumentPageLayout', ...
        ['A valid mlreportgen.dom.DOCXPageLayout object ', ...
         'is required for the header and footer.']);

end

%% =========================================================
% Default page header
%% =========================================================

pageHeader = ...
    DOCXPageHeader('default');

headerTable = ...
    Table();

headerTable.Width = ...
    '100%';

headerTable.Border = ...
    'solid';

headerTable.BorderWidth = ...
    '0.5pt';

headerTable.ColSep = ...
    'solid';

headerTable.RowSep = ...
    'solid';

headerRow = ...
    TableRow();

%% Left header cell

leftHeaderEntry = ...
    TableEntry();

leftHeaderParagraph = ...
    Paragraph();

leftHeaderParagraph.Style = { ...
    FontFamily('Arial'), ...
    FontSize('8pt'), ...
    Bold(true), ...
    Color('#1F4E79'), ...
    HAlign('left')};

append( ...
    leftHeaderParagraph, ...
    Text( ...
        string(Report.Metadata.Title)));

append( ...
    leftHeaderEntry, ...
    leftHeaderParagraph);

append( ...
    headerRow, ...
    leftHeaderEntry);

%% Right header cell

rightHeaderEntry = ...
    TableEntry();

rightHeaderParagraph = ...
    Paragraph();

rightHeaderParagraph.Style = { ...
    FontFamily('Arial'), ...
    FontSize('8pt'), ...
    HAlign('right')};

headerControlText = ...
    string(Report.Metadata.DocumentNumber) ...
    + "  |  Rev. " ...
    + string(Report.Metadata.Revision) ...
    + "  |  " ...
    + string(Report.Metadata.Status);

append( ...
    rightHeaderParagraph, ...
    Text(headerControlText));

append( ...
    rightHeaderEntry, ...
    rightHeaderParagraph);

append( ...
    headerRow, ...
    rightHeaderEntry);

%% Complete header

append( ...
    headerTable, ...
    headerRow);

append( ...
    pageHeader, ...
    headerTable);

pageLayout.PageHeaders = ...
    pageHeader;

%% =========================================================
% Default page footer
%% =========================================================

pageFooter = ...
    DOCXPageFooter('default');

footerTable = ...
    Table();

footerTable.Width = ...
    '100%';

footerTable.Border = ...
    'solid';

footerTable.BorderWidth = ...
    '0.5pt';

footerTable.ColSep = ...
    'solid';

footerTable.RowSep = ...
    'solid';

footerRow = ...
    TableRow();

%% Prepared-by footer cell

preparedEntry = ...
    TableEntry();

preparedParagraph = ...
    Paragraph();

preparedParagraph.Style = { ...
    FontFamily('Arial'), ...
    FontSize('6.5pt'), ...
    HAlign('left')};

preparedFooterText = ...
    "Prepared: " ...
    + string(Report.Metadata.PreparedBy) ...
    + " | Approved: " ...
    + optionalDisplayText( ...
        Report.Metadata.ApprovedBy, ...
        'Pending');

append( ...
    preparedParagraph, ...
    Text(preparedFooterText));

append( ...
    preparedEntry, ...
    preparedParagraph);

append( ...
    footerRow, ...
    preparedEntry);

%% Document-control footer cell

documentEntry = ...
    TableEntry();

documentParagraph = ...
    Paragraph();

documentParagraph.Style = { ...
    FontFamily('Arial'), ...
    FontSize('7pt'), ...
    HAlign('center')};

append( ...
    documentParagraph, ...
    Text( ...
        string(Report.Metadata.DocumentNumber) ...
        + " / Rev. " ...
        + string(Report.Metadata.Revision) ...
        + " / " ...
        + upper( ...
            string(Report.Metadata.Language))));

append( ...
    documentEntry, ...
    documentParagraph);

append( ...
    footerRow, ...
    documentEntry);

%% Page-number footer cell

pageEntry = ...
    TableEntry();

pageParagraph = ...
    Paragraph();

pageParagraph.Style = { ...
    FontFamily('Arial'), ...
    FontSize('7pt'), ...
    HAlign('right')};

append( ...
    pageParagraph, ...
    Text('Page '));

append( ...
    pageParagraph, ...
    Page());

append( ...
    pageEntry, ...
    pageParagraph);

append( ...
    footerRow, ...
    pageEntry);

%% Complete footer

append( ...
    footerTable, ...
    footerRow);

append( ...
    pageFooter, ...
    footerTable);

pageLayout.PageFooters = ...
    pageFooter;

end