function figureFile = ...
    generate_cyclo_firing_angle_figure( ...
        DesignData, ...
        Report, ...
        outputFolder)
%GENERATE_CYCLO_FIRING_ANGLE_FIGURE
% Generate the current-dependent inverter firing-angle figure
% for the CycloTool Design Data document.
%
% This function performs no engineering calculations. It plots
% the firing-angle results already stored in DesignData.

arguments
    DesignData   (1,1) struct
    Report       (1,1) struct
    outputFolder (1,1) string
end

%% =========================================================
% Required-data validation
%% =========================================================

if ~isfield(DesignData, 'FiringAngle')

    error( ...
        'Cyclo:MissingFiringAngleForFigure', ...
        'DesignData.FiringAngle is required.');

end

if ~isfield(Report, 'Figures') || ...
        ~isfield( ...
            Report.Figures, ...
            'FiringAngle')

    error( ...
        'Cyclo:MissingFiringAngleFigureDefinition', ...
        ['The report model does not contain the firing-angle ', ...
         'figure definition.']);

end

F = ...
    DesignData.FiringAngle;

requiredFields = { ...
    'Ipu', ...
    'WorstCase', ...
    'Allowed', ...
    'Setting', ...
    'Tolerance', ...
    'gamma0', ...
    'xL'};

for fieldIndex = 1:numel(requiredFields)

    fieldName = ...
        requiredFields{fieldIndex};

    if ~isfield(F, fieldName)

        error( ...
            'Cyclo:MissingFiringAngleFigureField', ...
            'Firing-angle data is missing field %s.', ...
            fieldName);

    end

    if isnumeric(F.(fieldName)) && ...
            any(~isfinite(F.(fieldName)(:)))

        error( ...
            'Cyclo:InvalidFiringAngleFigureField', ...
            'Firing-angle field %s contains invalid values.', ...
            fieldName);

    end

end

numberOfCurrentPoints = ...
    numel(F.Ipu);

curveFields = { ...
    'WorstCase', ...
    'Allowed', ...
    'Setting', ...
    'Tolerance'};

for fieldIndex = 1:numel(curveFields)

    fieldName = ...
        curveFields{fieldIndex};

    if numel(F.(fieldName)) ~= ...
            numberOfCurrentPoints

        error( ...
            'Cyclo:FiringAngleFigureLengthMismatch', ...
            ['Firing-angle curve %s does not match the ', ...
             'current-grid length.'], ...
            fieldName);

    end

end

%% =========================================================
% Initialize output path
%% =========================================================

if ~isfolder(outputFolder)

    mkdir(outputFolder);

end

figureFile = ...
    fullfile( ...
        outputFolder, ...
        string( ...
            Report.Figures. ...
            FiringAngle.FileName));

%% =========================================================
% Create figure
%% =========================================================

figureHandle = ...
    figure( ...
        'Visible', ...
        'off', ...
        'Color', ...
        'white', ...
        'Position', ...
        [100, 100, 1400, 800]);

axesHandle = ...
    axes( ...
        figureHandle, ...
        'Position', ...
        [0.09, 0.12, 0.76, 0.79]);

axesHandle.FontName = ...
    'Arial';

axesHandle.FontSize = ...
    11;

axesHandle.LineWidth = ...
    1.0;

axesHandle.Color = ...
    'white';

hold( ...
    axesHandle, ...
    'on');

grid( ...
    axesHandle, ...
    'on');

box( ...
    axesHandle, ...
    'on');

%% =========================================================
% Main firing-angle curves
%% =========================================================

worstCaseHandle = ...
    plot( ...
        axesHandle, ...
        F.Ipu, ...
        F.WorstCase, ...
        'r-', ...
        'LineWidth', ...
        2.0);

allowedHandle = ...
    plot( ...
        axesHandle, ...
        F.Ipu, ...
        F.Allowed, ...
        'k-', ...
        'LineWidth', ...
        2.0);

settingHandle = ...
    plot( ...
        axesHandle, ...
        F.Ipu, ...
        F.Setting, ...
        'g-', ...
        'LineWidth', ...
        2.0);

toleranceHandle = ...
    plot( ...
        axesHandle, ...
        F.Ipu, ...
        F.Tolerance, ...
        'b--', ...
        'LineWidth', ...
        2.0);

%% =========================================================
% Original support points
%% =========================================================

supportCurrent = ...
    [0, 0.5, 1, 1.5, 2, 2.5, 3];

worstCaseSupport = ...
    interp1( ...
        F.Ipu, ...
        F.WorstCase, ...
        supportCurrent);

allowedSupport = ...
    interp1( ...
        F.Ipu, ...
        F.Allowed, ...
        supportCurrent);

settingSupport = ...
    interp1( ...
        F.Ipu, ...
        F.Setting, ...
        supportCurrent);

toleranceSupport = ...
    interp1( ...
        F.Ipu, ...
        F.Tolerance, ...
        supportCurrent);

plot( ...
    axesHandle, ...
    supportCurrent, ...
    worstCaseSupport, ...
    'ro', ...
    'MarkerFaceColor', ...
    'r', ...
    'HandleVisibility', ...
    'off');

plot( ...
    axesHandle, ...
    supportCurrent, ...
    allowedSupport, ...
    'ko', ...
    'MarkerFaceColor', ...
    'k', ...
    'HandleVisibility', ...
    'off');

plot( ...
    axesHandle, ...
    supportCurrent, ...
    settingSupport, ...
    'go', ...
    'MarkerFaceColor', ...
    'g', ...
    'HandleVisibility', ...
    'off');

plot( ...
    axesHandle, ...
    supportCurrent, ...
    toleranceSupport, ...
    'bo', ...
    'MarkerFaceColor', ...
    'b', ...
    'HandleVisibility', ...
    'off');

%% =========================================================
% Axes formatting
%% =========================================================

xlabel( ...
    axesHandle, ...
    'DC Current [p.u.]');

ylabel( ...
    axesHandle, ...
    'Firing Angle [deg]');

titleText = ...
    sprintf( ...
        '%s, \\gamma_0 = %.1f deg', ...
        char( ...
            Report.Figures. ...
            FiringAngle.Title), ...
        F.gamma0);

title( ...
    axesHandle, ...
    titleText, ...
    'Interpreter', ...
    'tex');
axesHandle.Title.FontWeight = ...
    'bold';

axesHandle.Title.FontSize = ...
    14;

legend( ...
    axesHandle, ...
    [ ...
    worstCaseHandle, ...
    allowedHandle, ...
    settingHandle, ...
    toleranceHandle], ...
    { ...
    'AlphaGrenz, limit', ...
    'AlphaZul, allowable', ...
    'AlphaEinstell, recommended', ...
    'AlphaMax, tolerance'}, ...
    'Location', ...
    'northeast');

%% =========================================================
% Plot limits
%% =========================================================

minimumCurrent = ...
    min(F.Ipu);

maximumCurrent = ...
    max(F.Ipu);

currentRange = ...
    maximumCurrent ...
    - minimumCurrent;

if currentRange <= 0

    currentRange = ...
        1;

end

xlim( ...
    axesHandle, ...
    [ ...
    minimumCurrent, ...
    maximumCurrent + 0.12*currentRange ...
    ]);

allAngles = [ ...
    F.WorstCase(:)
    F.Allowed(:)
    F.Setting(:)
    F.Tolerance(:)];

minimumAngle = ...
    min(allAngles);

maximumAngle = ...
    max(allAngles);

angleRange = ...
    maximumAngle ...
    - minimumAngle;

if angleRange <= 0

    angleRange = ...
        1;

end

lowerAngleLimit = ...
    floor( ...
        (minimumAngle - 0.10*angleRange)/5) ...
    * 5;

upperAngleLimit = ...
    ceil( ...
        (maximumAngle + 0.10*angleRange)/5) ...
    * 5;

ylim( ...
    axesHandle, ...
    [ ...
    lowerAngleLimit, ...
    upperAngleLimit ...
    ]);

%% =========================================================
% Curve-end labels
%% =========================================================

labelOffsetX = ...
    0.025 ...
    * currentRange;

text( ...
    axesHandle, ...
    maximumCurrent + labelOffsetX, ...
    F.WorstCase(end), ...
    'AlphaGrenz', ...
    'Color', ...
    'r', ...
    'FontWeight', ...
    'bold', ...
    'VerticalAlignment', ...
    'middle');

text( ...
    axesHandle, ...
    maximumCurrent + labelOffsetX, ...
    F.Allowed(end), ...
    'AlphaZul', ...
    'Color', ...
    'k', ...
    'FontWeight', ...
    'bold', ...
    'VerticalAlignment', ...
    'middle');

text( ...
    axesHandle, ...
    maximumCurrent + labelOffsetX, ...
    F.Setting(end), ...
    'AlphaEinstell', ...
    'Color', ...
    [0, 0.6, 0], ...
    'FontWeight', ...
    'bold', ...
    'VerticalAlignment', ...
    'middle');

text( ...
    axesHandle, ...
    maximumCurrent + labelOffsetX, ...
    F.Tolerance(end), ...
    'AlphaMax', ...
    'Color', ...
    'b', ...
    'FontWeight', ...
    'bold', ...
    'VerticalAlignment', ...
    'middle');

%% =========================================================
% Information annotation
%% =========================================================

informationText = { ...
    sprintf( ...
        '\\gamma_0 = %.1f deg', ...
        F.gamma0), ...
    sprintf( ...
        'x_L = %.4f p.u.', ...
        F.xL)};

text( ...
    axesHandle, ...
    0.02, ...
    0.04, ...
    informationText, ...
    'Units', ...
    'normalized', ...
    'Interpreter', ...
    'tex', ...
    'VerticalAlignment', ...
    'bottom', ...
    'BackgroundColor', ...
    'white', ...
    'EdgeColor', ...
    [0.6, 0.6, 0.6], ...
    'Margin', ...
    6);

hold( ...
    axesHandle, ...
    'off');

%% =========================================================
% Export PNG
%% =========================================================

exportgraphics( ...
    figureHandle, ...
    figureFile, ...
    'Resolution', ...
    300, ...
    'BackgroundColor', ...
    'white');

close( ...
    figureHandle);

if ~isfile(figureFile)

    error( ...
        'Cyclo:FiringAngleFigureExportFailure', ...
        'The firing-angle figure was not exported.');

end

end