function figureFile = ...
    generate_cyclo_converter_losses_figure( ...
        DesignData, ...
        Report, ...
        outputFolder)
%GENERATE_CYCLO_CONVERTER_LOSSES_FIGURE
% Generate the converter-loss breakdown figure for the
% CycloTool Design Data document.
%
% The function displays:
%   - Conduction loss
%   - Turn-on loss
%   - Turn-off loss
%   - Snubber loss
%   - Total converter loss
%
% This function performs no loss calculation. It only plots
% the validated values stored in DesignData.

arguments
    DesignData   (1,1) struct
    Report       (1,1) struct
    outputFolder (1,1) string
end

%% =========================================================
% Required-data validation
%% =========================================================

if ~isfield(DesignData, 'DetailedSimulation')

    error( ...
        'Cyclo:MissingDetailedSimulationForLossFigure', ...
        'DesignData.DetailedSimulation is required.');

end

if ~isfield( ...
        DesignData.DetailedSimulation, ...
        'Loss')

    error( ...
        'Cyclo:MissingLossDataForFigure', ...
        'DesignData.DetailedSimulation.Loss is required.');

end

if ~isfield(Report, 'Figures') || ...
        ~isfield( ...
            Report.Figures, ...
            'ConverterLosses')

    error( ...
        'Cyclo:MissingConverterLossFigureDefinition', ...
        ['The report model does not contain the converter-loss ', ...
         'figure definition.']);

end

Loss = ...
    DesignData.DetailedSimulation.Loss;

requiredLossFields = { ...
    'totalConductionPowerkW', ...
    'totalTurnOnPowerkW', ...
    'totalTurnOffPowerkW', ...
    'snubberPowerkW', ...
    'totalConverterPowerkW', ...
    'totalModeledThyristors', ...
    'expectedPhysicalThyristors'};

for fieldIndex = 1:numel(requiredLossFields)

    fieldName = ...
        requiredLossFields{fieldIndex};

    if ~isfield(Loss, fieldName)

        error( ...
            'Cyclo:MissingConverterLossFigureField', ...
            'Converter-loss data is missing field %s.', ...
            fieldName);

    end

    if any( ...
            ~isfinite( ...
                Loss.(fieldName)(:)))

        error( ...
            'Cyclo:InvalidConverterLossFigureField', ...
            'Converter-loss field %s contains invalid values.', ...
            fieldName);

    end

end

lossValueskW = [ ...
    Loss.totalConductionPowerkW, ...
    Loss.totalTurnOnPowerkW, ...
    Loss.totalTurnOffPowerkW, ...
    Loss.snubberPowerkW];

if any(lossValueskW < 0) || ...
        Loss.totalConverterPowerkW < 0

    error( ...
        'Cyclo:NegativeConverterLossFigureValue', ...
        'Converter-loss values must be non-negative.');

end

componentTotalPowerkW = ...
    sum(lossValueskW);

lossBalanceTolerancekW = ...
    1e-6 ...
    * max( ...
        1, ...
        Loss.totalConverterPowerkW);

if abs( ...
        componentTotalPowerkW ...
        - Loss.totalConverterPowerkW) ...
        > lossBalanceTolerancekW

    error( ...
        'Cyclo:ConverterLossFigureBalanceError', ...
        ['The converter-loss components do not equal the ', ...
         'reported total converter loss.']);

end

if Loss.totalModeledThyristors ~= ...
        Loss.expectedPhysicalThyristors

    error( ...
        'Cyclo:ConverterLossFigureThyristorCountMismatch', ...
        ['The modeled thyristor count does not match the ', ...
         'expected physical thyristor count.']);

end

%% =========================================================
% Initialize output path
%% =========================================================

if ~isfolder(outputFolder)

    mkdir(outputFolder);

end

figureFile = ...
    fullfile( ...
        outputFolder, ...
        string( ...
            Report.Figures. ...
            ConverterLosses.FileName));

%% =========================================================
% Create figure
%% =========================================================

figureHandle = ...
    figure( ...
        'Visible', ...
        'off', ...
        'Color', ...
        'white', ...
        'Position', ...
        [100, 100, 1400, 800]);

axesHandle = ...
    axes( ...
        figureHandle, ...
        'Position', ...
        [0.09, 0.12, 0.76, 0.79]);

axesHandle.FontName = ...
    'Arial';

axesHandle.FontSize = ...
    11;

axesHandle.LineWidth = ...
    1.0;

axesHandle.Color = ...
    'white';

grid( ...
    axesHandle, ...
    'on');

box( ...
    axesHandle, ...
    'on');

hold( ...
    axesHandle, ...
    'on');

%% =========================================================
% Loss bar chart
%% =========================================================

lossLabels = { ...
    'Conduction', ...
    'Turn-on', ...
    'Turn-off', ...
    'Snubber'};

barHandle = ...
    bar( ...
        axesHandle, ...
        lossValueskW, ...
        0.68);

barHandle.FaceColor = ...
    'flat';

barHandle.EdgeColor = ...
    [0.25, 0.25, 0.25];

barHandle.LineWidth = ...
    0.8;

barHandle.CData = [ ...
    0.00, 0.45, 0.74
    0.47, 0.67, 0.19
    0.85, 0.33, 0.10
    0.49, 0.18, 0.56];

%% =========================================================
% Axes formatting
%% =========================================================

xticks( ...
    axesHandle, ...
    1:numel(lossLabels));

xticklabels( ...
    axesHandle, ...
    lossLabels);

xlabel( ...
    axesHandle, ...
    'Loss Component');

ylabel( ...
    axesHandle, ...
    'Loss [kW]');

titleText = ...
    sprintf( ...
        '%s, Total = %.3f kW', ...
        char( ...
            Report.Figures. ...
            ConverterLosses.Title), ...
        Loss.totalConverterPowerkW);

title( ...
    axesHandle, ...
    titleText, ...
    'Interpreter', ...
    'none');

axesHandle.Title.FontWeight = ...
    'bold';

axesHandle.Title.FontSize = ...
    14;

%% =========================================================
% Vertical-axis range
%% =========================================================

maximumLoss = ...
    max(lossValueskW);

if maximumLoss <= 0

    maximumLoss = ...
        1;

end

ylim( ...
    axesHandle, ...
    [0, 1.22*maximumLoss]);

xlim( ...
    axesHandle, ...
    [0.4, numel(lossLabels) + 1.25]);

%% =========================================================
% Numerical labels above bars
%% =========================================================

labelOffset = ...
    0.035 ...
    * maximumLoss;

for lossIndex = 1:numel(lossValueskW)

    text( ...
        axesHandle, ...
        lossIndex, ...
        lossValueskW(lossIndex) + labelOffset, ...
        sprintf( ...
            '%.3f kW', ...
            lossValueskW(lossIndex)), ...
        'HorizontalAlignment', ...
        'center', ...
        'VerticalAlignment', ...
        'bottom', ...
        'FontWeight', ...
        'bold', ...
        'FontSize', ...
        10, ...
        'Interpreter', ...
        'none');

end

%% =========================================================
% Percentage labels inside bars
%% =========================================================

if Loss.totalConverterPowerkW > 0

    lossPercentages = ...
        100 ...
        * lossValueskW ...
        / Loss.totalConverterPowerkW;

else

    lossPercentages = ...
        zeros(size(lossValueskW));

end

for lossIndex = 1:numel(lossValueskW)

    if lossValueskW(lossIndex) > 0

        insideLabelHeight = ...
            0.50 ...
            * lossValueskW(lossIndex);

        text( ...
            axesHandle, ...
            lossIndex, ...
            insideLabelHeight, ...
            sprintf( ...
                '%.1f %%', ...
                lossPercentages(lossIndex)), ...
            'HorizontalAlignment', ...
            'center', ...
            'VerticalAlignment', ...
            'middle', ...
            'Color', ...
            'white', ...
            'FontWeight', ...
            'bold', ...
            'FontSize', ...
            10, ...
            'Interpreter', ...
            'none');

    end

end

%% =========================================================
% Validation annotation
%% =========================================================

if isfield( ...
        DesignData.DetailedSimulation, ...
        'LossStatus')

    lossStatus = ...
        string( ...
            DesignData.DetailedSimulation.LossStatus);

else

    lossStatus = ...
        "Status not available";

end

pulseNumber = ...
    getPulseNumber(DesignData);

numberOfGroups = ...
    getNumberOfGroups(DesignData);

validationText = { ...
    sprintf( ...
        'Pulse number: %d', ...
        pulseNumber), ...
    sprintf( ...
        'Converter groups: %d', ...
        numberOfGroups), ...
    sprintf( ...
        'Physical thyristors: %d', ...
        Loss.totalModeledThyristors), ...
    sprintf( ...
        'Loss status: %s', ...
        char(lossStatus))};

text( ...
    axesHandle, ...
    0.99, ...
    0.97, ...
    validationText, ...
    'Units', ...
    'normalized', ...
    'HorizontalAlignment', ...
    'right', ...
    'VerticalAlignment', ...
    'top', ...
    'Interpreter', ...
    'none', ...
    'FontSize', ...
    9, ...
    'BackgroundColor', ...
    'white', ...
    'EdgeColor', ...
    [0.60, 0.60, 0.60], ...
    'Margin', ...
    6);

%% =========================================================
% Model annotation
%% =========================================================

modelText = { ...
    'Explicit physical-device summation', ...
    'Validated within ABB/Scilab model'};

text( ...
    axesHandle, ...
    0.99, ...
    0.72, ...
    modelText, ...
    'Units', ...
    'normalized', ...
    'HorizontalAlignment', ...
    'right', ...
    'VerticalAlignment', ...
    'top', ...
    'Interpreter', ...
    'none', ...
    'FontSize', ...
    9, ...
    'BackgroundColor', ...
    'white', ...
    'EdgeColor', ...
    [0.75, 0.75, 0.75], ...
    'Margin', ...
    6);

hold( ...
    axesHandle, ...
    'off');

%% =========================================================
% Export PNG
%% =========================================================

exportgraphics( ...
    figureHandle, ...
    figureFile, ...
    'Resolution', ...
    300, ...
    'BackgroundColor', ...
    'white');

close( ...
    figureHandle);

if ~isfile(figureFile)

    error( ...
        'Cyclo:ConverterLossFigureExportFailure', ...
        'The converter-loss figure was not exported.');

end

end


function pulseNumber = getPulseNumber(DesignData)

if isfield(DesignData, 'Converter') && ...
        isfield( ...
            DesignData.Converter, ...
            'pulseNumber') && ...
        ~isempty( ...
            DesignData.Converter.pulseNumber)

    pulseNumber = ...
        DesignData.Converter.pulseNumber;

elseif isfield(DesignData, 'Input') && ...
        isfield( ...
            DesignData.Input, ...
            'PulseNumber') && ...
        ~isempty( ...
            DesignData.Input.PulseNumber)

    pulseNumber = ...
        DesignData.Input.PulseNumber;

else

    pulseNumber = ...
        NaN;

end

end


function numberOfGroups = getNumberOfGroups(DesignData)

if isfield(DesignData, 'Converter') && ...
        isfield( ...
            DesignData.Converter, ...
            'numberOfGroups') && ...
        ~isempty( ...
            DesignData.Converter.numberOfGroups)

    numberOfGroups = ...
        DesignData.Converter.numberOfGroups;

elseif isfield( ...
        DesignData, ...
        'DetailedSimulation') && ...
        isfield( ...
            DesignData.DetailedSimulation, ...
            'Parameters') && ...
        isfield( ...
            DesignData.DetailedSimulation.Parameters, ...
            'TC')

    numberOfGroups = ...
        DesignData.DetailedSimulation.Parameters.TC;

else

    numberOfGroups = ...
        NaN;

end

end