function figureFile = ...
    generate_cyclo_overview_figure( ...
        DesignData, ...
        Report, ...
        outputFolder)
%GENERATE_CYCLO_OVERVIEW_FIGURE
% Generate the functional cycloconverter system overview used
% as Figure 1 in the CycloTool Design Data document.
%
% The figure uses validated DesignData values but performs no
% additional engineering calculations.

arguments
    DesignData   (1,1) struct
    Report       (1,1) struct
    outputFolder (1,1) string
end

%% =========================================================
% Input validation
%% =========================================================

requiredSections = { ...
    'Supply', ...
    'Converter', ...
    'Motor', ...
    'Excitation'};

for sectionIndex = 1:numel(requiredSections)

    sectionName = ...
        requiredSections{sectionIndex};

    if ~isfield(DesignData, sectionName)

        error( ...
            'Cyclo:MissingOverviewSection', ...
            'DesignData is missing section %s.', ...
            sectionName);

    end

end

if ~isfield(Report, 'Figures') || ...
        ~isfield(Report.Figures, 'Overview')

    error( ...
        'Cyclo:MissingOverviewDefinition', ...
        'The Report overview figure definition is missing.');

end

pulseNumber = ...
    DesignData.Converter.pulseNumber;

numberOfGroups = ...
    DesignData.Converter.numberOfGroups;

physicalThyristorCount = ...
    DesignData.Converter.physicalThyristorCount;

if ~ismember(pulseNumber, [6, 12, 18])

    error( ...
        'Cyclo:UnsupportedOverviewPulseNumber', ...
        'The overview supports 6, 12, and 18 pulses.');

end

if numberOfGroups ~= pulseNumber/6

    error( ...
        'Cyclo:OverviewGroupMismatch', ...
        ['The converter group count does not match the ', ...
         'pulse number.']);

end

if physicalThyristorCount ~= 6*pulseNumber

    error( ...
        'Cyclo:OverviewThyristorMismatch', ...
        ['The physical thyristor count does not match the ', ...
         'pulse number.']);

end

%% =========================================================
% Output path
%% =========================================================

if ~isfolder(outputFolder)

    mkdir(outputFolder);

end

figureFile = ...
    fullfile( ...
        outputFolder, ...
        string( ...
            Report.Figures.Overview.FileName));

%% =========================================================
% Create figure
%% =========================================================

figureHandle = ...
    figure( ...
        'Visible', ...
        'off', ...
        'Color', ...
        'white', ...
        'Position', ...
        [100, 100, 2400, 1350]);

axesHandle = ...
    axes( ...
        figureHandle, ...
        'Position', ...
        [0.03, 0.05, 0.94, 0.88]);

hold( ...
    axesHandle, ...
    'on');

axis( ...
    axesHandle, ...
    [0, 100, 0, 100]);

axis( ...
    axesHandle, ...
    'off');

%% =========================================================
% Colors
%% =========================================================

supplyColor = ...
    [0.12, 0.32, 0.52];

transformerColor = ...
    [0.15, 0.50, 0.70];

converterColor = ...
    [0.85, 0.40, 0.10];

motorColor = ...
    [0.15, 0.55, 0.30];

excitationColor = ...
    [0.48, 0.28, 0.62];

connectionColor = ...
    [0.18, 0.18, 0.18];

%% =========================================================
% Block positions
%% =========================================================

supplyPosition = ...
    [3, 61, 15, 25];

transformerPosition = ...
    [23, 54, 20, 39];

converterPosition = ...
    [49, 54, 20, 39];

motorPosition = ...
    [76, 61, 20, 25];

excitationPosition = ...
    [72, 14, 24, 24];

%% =========================================================
% Supply
%% =========================================================

drawBlock( ...
    axesHandle, ...
    supplyPosition, ...
    supplyColor, ...
    'MEDIUM-VOLTAGE SUPPLY');

supplyText = { ...
    sprintf( ...
        'Frequency: %.1f Hz', ...
        DesignData.Supply.frequencyHz), ...
    sprintf( ...
        'SC min: %.1f MVA', ...
        DesignData.Supply. ...
        minimumShortCircuitPowerVA/1e6), ...
    sprintf( ...
        'SC max: %.1f MVA', ...
        DesignData.Supply. ...
        maximumShortCircuitPowerVA/1e6)};

drawBlockText( ...
    axesHandle, ...
    supplyPosition, ...
    supplyText);

%% =========================================================
% Converter transformer
%% =========================================================

drawBlock( ...
    axesHandle, ...
    transformerPosition, ...
    transformerColor, ...
    'CONVERTER TRANSFORMER');

transformerText = { ...
    sprintf( ...
        'Secondary groups: %d', ...
        numberOfGroups), ...
    sprintf( ...
        'Uv0: %.0f V', ...
        DesignData.Converter.noLoadVoltageV), ...
    sprintf( ...
        'I1S: %.0f A RMS', ...
        DesignData.Converter.secondaryCurrentA), ...
    sprintf( ...
        'Scalc: %.2f MVA', ...
        DesignData.Converter. ...
        transformerCalculatedPowerTotalMVA), ...
    sprintf( ...
        'STr required: %.2f MVA', ...
        DesignData.Converter. ...
        transformerSelectedPowerMVA)};

drawBlockText( ...
    axesHandle, ...
    transformerPosition, ...
    transformerText);

%% =========================================================
% Cycloconverter
%% =========================================================

drawBlock( ...
    axesHandle, ...
    converterPosition, ...
    converterColor, ...
    'CYCLOCONVERTER');

converterText = { ...
    sprintf( ...
        '%d-pulse system', ...
        pulseNumber), ...
    sprintf( ...
        'Groups: %d', ...
        numberOfGroups), ...
    sprintf( ...
        'Thyristors: %d', ...
        physicalThyristorCount), ...
    sprintf( ...
        'Type: %s', ...
        char( ...
            string( ...
                DesignData.Converter.thyristorType)))};

drawBlockText( ...
    axesHandle, ...
    converterPosition, ...
    converterText);

%% =========================================================
% Motor
%% =========================================================

drawBlock( ...
    axesHandle, ...
    motorPosition, ...
    motorColor, ...
    'SYNCHRONOUS MOTOR');

motorText = { ...
    sprintf( ...
        'UM: %.0f V', ...
        DesignData.Motor.voltageV), ...
    sprintf( ...
        'IM: %.0f A RMS', ...
        DesignData.Motor.currentA), ...
    sprintf( ...
        'nN: %.2f rpm', ...
        DesignData.Motor.nominalSpeedRpm), ...
    sprintf( ...
        'nmax: %.2f rpm', ...
        DesignData.Motor.maximumSpeedRpm)};

drawBlockText( ...
    axesHandle, ...
    motorPosition, ...
    motorText);

%% =========================================================
% Static excitation
%% =========================================================

drawBlock( ...
    axesHandle, ...
    excitationPosition, ...
    excitationColor, ...
    'STATIC EXCITATION');

excitationText = { ...
    sprintf( ...
        'DCS880: %s', ...
        char( ...
            string( ...
                DesignData.Excitation.DCS_Type))), ...
    sprintf( ...
        'Power calc.: %.1f kVA', ...
        DesignData.Excitation. ...
        transformerCalculatedPowerkVA), ...
    sprintf( ...
        'STr required: %.1f kVA', ...
        DesignData.Excitation. ...
        transformerSelectedPowerkVA), ...
    sprintf( ...
        'Existing STr: %.1f kVA', ...
        DesignData.Excitation. ...
        existingTransformerRatingkVA)};

drawBlockText( ...
    axesHandle, ...
    excitationPosition, ...
    excitationText);

%% =========================================================
% Main power-flow arrows
%% =========================================================

drawArrow( ...
    axesHandle, ...
    [18, 73], ...
    [23, 73], ...
    connectionColor);

drawArrow( ...
    axesHandle, ...
    [43, 73], ...
    [49, 73], ...
    connectionColor);

drawArrow( ...
    axesHandle, ...
    [69, 73], ...
    [76, 73], ...
    connectionColor);

text( ...
    axesHandle, ...
    72.5, ...
    76, ...
    'U, V, W', ...
    'HorizontalAlignment', ...
    'center', ...
    'FontName', ...
    'Arial', ...
    'FontSize', ...
    13, ...
    'FontWeight', ...
    'bold');

%% =========================================================
% Transformer secondary groups
%% =========================================================

if numberOfGroups == 1

    groupYPositions = ...
        72;

else

    groupYPositions = ...
        linspace( ...
            63, ...
            84, ...
            numberOfGroups);

end

for groupIndex = 1:numberOfGroups

    groupY = ...
        groupYPositions(groupIndex);

    plot( ...
        axesHandle, ...
        [43, 49], ...
        [groupY, groupY], ...
        '-', ...
        'Color', ...
        transformerColor, ...
        'LineWidth', ...
        2.0);

    text( ...
        axesHandle, ...
        46, ...
        groupY + 1.0, ...
        sprintf( ...
            'G%d', ...
            groupIndex), ...
        'HorizontalAlignment', ...
        'center', ...
        'VerticalAlignment', ...
        'bottom', ...
        'FontName', ...
        'Arial', ...
        'FontSize', ...
        10, ...
        'FontWeight', ...
        'bold', ...
        'Color', ...
        transformerColor);

end

%% =========================================================
% Excitation connection to motor rotor
%% =========================================================

plot( ...
    axesHandle, ...
    [84, 84], ...
    [38, 61], ...
    '-', ...
    'Color', ...
    excitationColor, ...
    'LineWidth', ...
    2.5);

drawArrow( ...
    axesHandle, ...
    [84, 38], ...
    [84, 60.5], ...
    excitationColor);

text( ...
    axesHandle, ...
    86, ...
    49.5, ...
    'Rotor field', ...
    'Rotation', ...
    90, ...
    'HorizontalAlignment', ...
    'center', ...
    'VerticalAlignment', ...
    'bottom', ...
    'FontName', ...
    'Arial', ...
    'FontSize', ...
    11, ...
    'Color', ...
    excitationColor);

%% =========================================================
% Converter topology note
%% =========================================================

converterTopologyNote = { ...
    'Per motor phase and group:', ...
    'Positive 6-device bridge', ...
    'Negative 6-device bridge'};

text( ...
    axesHandle, ...
    59, ...
    48, ...
    converterTopologyNote, ...
    'HorizontalAlignment', ...
    'center', ...
    'VerticalAlignment', ...
    'top', ...
    'FontName', ...
    'Arial', ...
    'FontSize', ...
    11, ...
    'Color', ...
    converterColor, ...
    'Interpreter', ...
    'none');

%% =========================================================
% Title and note
%% =========================================================

title( ...
    axesHandle, ...
    string( ...
        Report.Figures.Overview.Title), ...
    'FontName', ...
    'Arial', ...
    'FontSize', ...
    17, ...
    'FontWeight', ...
    'bold', ...
    'Color', ...
    supplyColor);

text( ...
    axesHandle, ...
    50, ...
    5, ...
    ['Functional system overview. Detailed winding, ', ...
     'protection, and auxiliary interfaces are documented ', ...
     'in the associated Design Data sections.'], ...
    'HorizontalAlignment', ...
    'center', ...
    'VerticalAlignment', ...
    'middle', ...
    'FontName', ...
    'Arial', ...
    'FontSize', ...
    10, ...
    'FontAngle', ...
    'italic', ...
    'Color', ...
    [0.40, 0.40, 0.40], ...
    'Interpreter', ...
    'none');

hold( ...
    axesHandle, ...
    'off');

%% =========================================================
% Export PNG
%% =========================================================

exportgraphics( ...
    figureHandle, ...
    figureFile, ...
    'Resolution', ...
    300, ...
    'BackgroundColor', ...
    'white');

close( ...
    figureHandle);

if ~isfile(figureFile)

    error( ...
        'Cyclo:OverviewFigureExportFailure', ...
        'The cycloconverter overview figure was not exported.');

end

end


function drawBlock( ...
    axesHandle, ...
    position, ...
    edgeColor, ...
    blockTitle)

lightFill = ...
    0.92 ...
    * [1, 1, 1] ...
    + 0.08 ...
    * edgeColor;

rectangle( ...
    axesHandle, ...
    'Position', ...
    position, ...
    'Curvature', ...
    0.04, ...
    'FaceColor', ...
    lightFill, ...
    'EdgeColor', ...
    edgeColor, ...
    'LineWidth', ...
    2.2);

text( ...
    axesHandle, ...
    position(1) + position(3)/2, ...
    position(2) + position(4) - 3.5, ...
    blockTitle, ...
    'HorizontalAlignment', ...
    'center', ...
    'VerticalAlignment', ...
    'middle', ...
    'FontName', ...
    'Arial', ...
    'FontSize', ...
    12, ...
    'FontWeight', ...
    'bold', ...
    'Color', ...
    edgeColor, ...
    'Interpreter', ...
    'none');

end


function drawBlockText( ...
    axesHandle, ...
    position, ...
    textLines)

text( ...
    axesHandle, ...
    position(1) + position(3)/2, ...
    position(2) + position(4)/2 - 2, ...
    textLines, ...
    'HorizontalAlignment', ...
    'center', ...
    'VerticalAlignment', ...
    'middle', ...
    'FontName', ...
    'Arial', ...
    'FontSize', ...
    10, ...
    'Color', ...
    [0.10, 0.10, 0.10], ...
    'Interpreter', ...
    'none');

end


function drawArrow( ...
    axesHandle, ...
    startPoint, ...
    endPoint, ...
    arrowColor)

quiver( ...
    axesHandle, ...
    startPoint(1), ...
    startPoint(2), ...
    endPoint(1) - startPoint(1), ...
    endPoint(2) - startPoint(2), ...
    0, ...
    'Color', ...
    arrowColor, ...
    'LineWidth', ...
    2.5, ...
    'MaxHeadSize', ...
    0.8);

end