function Ref = generate_cyclo_firing_reference(P)
%GENERATE_CYCLO_FIRING_REFERENCE
% Generate the three output-phase firing-angle references
% according to the ABB Scilab cycloconverter algorithm.

arguments
    P (1,1) struct
end

%% =========================================================
% Converter reference intervals
%% =========================================================

numberOfIntervals = P.numberOfIntervals;

intervalIndex = 1:numberOfIntervals;

Ref.converterAngle = ...
    2*pi ...
    / numberOfIntervals ...
    .* (intervalIndex - 0.5);

%% =========================================================
% Voltage-to-firing-angle gain
%% =========================================================

Ref.voltageGain = ...
    pi ...
    / (3 * P.U1 * sqrt(3)) ...
    * P.Uo ...
    / P.TC;

%% =========================================================
% Output phase voltage ratios
%% =========================================================

Ref.ratioU = ...
    Ref.voltageGain ...
    .* cos(Ref.converterAngle);

Ref.ratioV = ...
    Ref.voltageGain ...
    .* cos( ...
        Ref.converterAngle ...
        - 2*pi/3);

Ref.ratioW = ...
    Ref.voltageGain ...
    .* cos( ...
        Ref.converterAngle ...
        + 2*pi/3);

%% =========================================================
% Preserve and limit firing-angle ratios
%% =========================================================
%
% acos requires its argument to remain inside [-1, 1].
%
% Preserve the original values so genuine overmodulation can
% be distinguished from insignificant numerical roundoff.

Ref.ratioURaw = ...
    Ref.ratioU;

Ref.ratioVRaw = ...
    Ref.ratioV;

Ref.ratioWRaw = ...
    Ref.ratioW;

ratioTolerance = ...
    1e-12;

Ref.maximumRawRatioMagnitude = ...
    max( ...
        abs( ...
            [ ...
            Ref.ratioURaw(:)
            Ref.ratioVRaw(:)
            Ref.ratioWRaw(:)]));

Ref.overmodulationDetected = ...
    Ref.maximumRawRatioMagnitude ...
    > 1 + ratioTolerance;

%% Limit ratios to the valid acos domain

Ref.ratioU = ...
    max( ...
        -1, ...
        min( ...
            1, ...
            Ref.ratioURaw));

Ref.ratioV = ...
    max( ...
        -1, ...
        min( ...
            1, ...
            Ref.ratioVRaw));

Ref.ratioW = ...
    max( ...
        -1, ...
        min( ...
            1, ...
            Ref.ratioWRaw));

%% =========================================================
% Firing angles
%% =========================================================

Ref.alphaU = acos(Ref.ratioU);
Ref.alphaV = acos(Ref.ratioV);
Ref.alphaW = acos(Ref.ratioW);

%% Apply minimum firing angle

Ref.alphaU = max(Ref.alphaU, P.alphaMin);
Ref.alphaV = max(Ref.alphaV, P.alphaMin);
Ref.alphaW = max(Ref.alphaW, P.alphaMin);

%% =========================================================
% Converter source phase progression
%% =========================================================

Ref.phiConverter = ...
    2*pi ...
    / P.pulseNumber ...
    .* (intervalIndex - 1);

%% =========================================================
% Standardize vector orientation
%% =========================================================

Ref.converterAngle = Ref.converterAngle(:);

Ref.ratioU = Ref.ratioU(:);
Ref.ratioV = Ref.ratioV(:);
Ref.ratioW = Ref.ratioW(:);

Ref.alphaU = Ref.alphaU(:);
Ref.alphaV = Ref.alphaV(:);
Ref.alphaW = Ref.alphaW(:);

Ref.phiConverter = Ref.phiConverter(:);

%% =========================================================
% Degree outputs for GUI and diagnostics
%% =========================================================

Ref.converterAngleDeg = ...
    rad2deg(Ref.converterAngle);

Ref.alphaUDeg = ...
    rad2deg(Ref.alphaU);

Ref.alphaVDeg = ...
    rad2deg(Ref.alphaV);

Ref.alphaWDeg = ...
    rad2deg(Ref.alphaW);

Ref.phiConverterDeg = ...
    rad2deg(Ref.phiConverter);

%% =========================================================
% Validation
%% =========================================================

if any(~isfinite(Ref.alphaU)) || ...
        any(~isfinite(Ref.alphaV)) || ...
        any(~isfinite(Ref.alphaW))

    error( ...
        'Cyclo:InvalidFiringReference', ...
        'Firing-angle calculation produced non-finite values.');

end

if any(Ref.alphaU < P.alphaMin) || ...
        any(Ref.alphaV < P.alphaMin) || ...
        any(Ref.alphaW < P.alphaMin)

    error( ...
        'Cyclo:AlphaMinimumViolation', ...
        'Minimum firing-angle constraint was violated.');

end

end