function figureFile = ...
    generate_cyclo_motor_characteristic_figure( ...
        DesignData, ...
        Report, ...
        outputFolder)
%GENERATE_CYCLO_MOTOR_CHARACTERISTIC_FIGURE
% Generate the motor voltage and current characteristic figure
% for the CycloTool Design Data document.
%
% This function performs no engineering calculations. It plots
% the characteristic values already stored in DesignData.

arguments
    DesignData   (1,1) struct
    Report       (1,1) struct
    outputFolder (1,1) string
end

%% =========================================================
% Initialize output path
%% =========================================================

figureFile = ...
    fullfile( ...
        outputFolder, ...
        string( ...
            Report.Figures. ...
            MotorCharacteristic.FileName));

%% =========================================================
% Required-data validation
%% =========================================================

if ~isfield(DesignData, 'Characteristic')

    error( ...
        'Cyclo:MissingCharacteristicForFigure', ...
        'DesignData.Characteristic is required.');

end

if ~isfield(DesignData, 'Input')

    error( ...
        'Cyclo:MissingInputForCharacteristicFigure', ...
        'DesignData.Input is required.');

end

if ~isfield(Report, 'Figures') || ...
        ~isfield( ...
            Report.Figures, ...
            'MotorCharacteristic')

    error( ...
        'Cyclo:MissingMotorCharacteristicFigureDefinition', ...
        ['The report model does not contain the motor ', ...
         'characteristic figure definition.']);

end

if ~isfolder(outputFolder)

    mkdir(outputFolder);

end

C = ...
    DesignData.Characteristic;

Input = ...
    DesignData.Input;

requiredCharacteristicFields = { ...
    'Speed', ...
    'UM_nom', ...
    'UM_uLmin', ...
    'IM_nom', ...
    'IM_uLmin', ...
    'IM_ovld_nom', ...
    'IM_ovld_uLmin', ...
    'nCurve', ...
    'UM_curve', ...
    'UM_uL_curve', ...
    'IM_curve', ...
    'IM_uL_curve', ...
    'IM_ovld_curve', ...
    'IM_ovld_uL_curve'};

for fieldIndex = 1:numel(requiredCharacteristicFields)

    fieldName = ...
        requiredCharacteristicFields{fieldIndex};

    if ~isfield(C, fieldName)

        error( ...
            'Cyclo:MissingCharacteristicFigureField', ...
            'Characteristic data is missing field %s.', ...
            fieldName);

    end

    if any( ...
            ~isfinite( ...
                C.(fieldName)(:)))

        error( ...
            'Cyclo:InvalidCharacteristicFigureField', ...
            'Characteristic field %s contains invalid values.', ...
            fieldName);

    end

end

%% =========================================================
% Create figure
%% =========================================================

figureHandle = ...
    figure( ...
        'Visible', ...
        'off', ...
        'Color', ...
        'white', ...
        'Position', ...
        [100, 100, 1400, 800]);

axesHandle = ...
    axes( ...
        figureHandle, ...
        'Position', ...
        [0.08, 0.11, 0.78, 0.80]);
axesHandle.FontName = ...
    'Arial';

axesHandle.FontSize = ...
    11;

axesHandle.LineWidth = ...
    1.0;

axesHandle.Color = ...
    'white';

hold( ...
    axesHandle, ...
    'on');

grid( ...
    axesHandle, ...
    'on');

box( ...
    axesHandle, ...
    'on');

%% =========================================================
% Motor-voltage curves
%% =========================================================

yyaxis( ...
    axesHandle, ...
    'left');

voltageNominalHandle = ...
    plot( ...
        axesHandle, ...
        C.nCurve, ...
        C.UM_curve, ...
        'k-', ...
        'LineWidth', ...
        2.0);

voltageMinimumHandle = ...
    plot( ...
        axesHandle, ...
        C.nCurve, ...
        C.UM_uL_curve, ...
        'k--', ...
        'LineWidth', ...
        2.0);

plot( ...
    axesHandle, ...
    C.Speed, ...
    C.UM_nom, ...
    'ko', ...
    'MarkerFaceColor', ...
    'k', ...
    'HandleVisibility', ...
    'off');

plot( ...
    axesHandle, ...
    C.Speed, ...
    C.UM_uLmin, ...
    'ks', ...
    'MarkerFaceColor', ...
    'white', ...
    'HandleVisibility', ...
    'off');

ylabel( ...
    axesHandle, ...
    'Motor Voltage [V]');

voltageMinimum = ...
    min( ...
        [ ...
        C.UM_curve(:)
        C.UM_uL_curve(:)]);

voltageMaximum = ...
    max( ...
        [ ...
        C.UM_curve(:)
        C.UM_uL_curve(:)]);

if voltageMaximum <= voltageMinimum

    voltageMinimum = ...
        0;

    voltageMaximum = ...
        max( ...
            1, ...
            voltageMaximum);

end

voltageRange = ...
    voltageMaximum ...
    - voltageMinimum;

voltageLowerLimit = ...
    max( ...
        0, ...
        voltageMinimum ...
        - 0.10*voltageRange);

voltageUpperLimit = ...
    voltageMaximum ...
    + 0.15*voltageRange;

ylim( ...
    axesHandle, ...
    [ ...
    voltageLowerLimit, ...
    voltageUpperLimit ...
    ]);
%% =========================================================
% Motor-current curves
%% =========================================================

yyaxis( ...
    axesHandle, ...
    'right');

currentNominalHandle = ...
    plot( ...
        axesHandle, ...
        C.nCurve, ...
        C.IM_curve, ...
        'b-', ...
        'LineWidth', ...
        4.0);

currentMinimumHandle = ...
    plot( ...
        axesHandle, ...
        C.nCurve, ...
        C.IM_uL_curve, ...
        'b--', ...
        'LineWidth', ...
        4.0);

overloadNominalHandle = ...
    plot( ...
        axesHandle, ...
        C.nCurve, ...
        C.IM_ovld_curve, ...
        'r-', ...
        'LineWidth', ...
        2.0);

overloadMinimumHandle = ...
    plot( ...
        axesHandle, ...
        C.nCurve, ...
        C.IM_ovld_uL_curve, ...
        'r--', ...
        'LineWidth', ...
        2.0);

plot( ...
    axesHandle, ...
    C.Speed, ...
    C.IM_nom, ...
    'bo', ...
    'MarkerFaceColor', ...
    'b', ...
    'HandleVisibility', ...
    'off');

plot( ...
    axesHandle, ...
    C.Speed, ...
    C.IM_uLmin, ...
    'bs', ...
    'MarkerFaceColor', ...
    'white', ...
    'HandleVisibility', ...
    'off');

plot( ...
    axesHandle, ...
    C.Speed, ...
    C.IM_ovld_nom, ...
    'ro', ...
    'MarkerFaceColor', ...
    'r', ...
    'HandleVisibility', ...
    'off');

plot( ...
    axesHandle, ...
    C.Speed, ...
    C.IM_ovld_uLmin, ...
    'rs', ...
    'MarkerFaceColor', ...
    'white', ...
    'HandleVisibility', ...
    'off');

ylabel( ...
    axesHandle, ...
    'Motor Current [A]');

currentMinimum = ...
    min( ...
        [ ...
        C.IM_curve(:)
        C.IM_uL_curve(:)
        C.IM_ovld_curve(:)
        C.IM_ovld_uL_curve(:)]);

currentMaximum = ...
    max( ...
        [ ...
        C.IM_curve(:)
        C.IM_uL_curve(:)
        C.IM_ovld_curve(:)
        C.IM_ovld_uL_curve(:)]);

if currentMaximum <= currentMinimum

    currentMinimum = ...
        0;

    currentMaximum = ...
        max( ...
            1, ...
            currentMaximum);

end

currentRange = ...
    currentMaximum ...
    - currentMinimum;

currentLowerLimit = ...
    max( ...
        0, ...
        currentMinimum ...
        - 0.10*currentRange);

currentUpperLimit = ...
    currentMaximum ...
    + 0.15*currentRange;

ylim( ...
    axesHandle, ...
    [ ...
    currentLowerLimit, ...
    currentUpperLimit ...
    ]);

%% =========================================================
% Operating-region markers
%% =========================================================

nominalSpeed = ...
    Input.n_nom;

minimumVoltageBaseSpeed = ...
    Input.u_L ...
    * Input.n_nom;

xline( ...
    axesHandle, ...
    nominalSpeed, ...
    'k:', ...
    'n_N', ...
    'LineWidth', ...
    1.2, ...
    'LabelVerticalAlignment', ...
    'bottom', ...
    'HandleVisibility', ...
    'off');

xline( ...
    axesHandle, ...
    minimumVoltageBaseSpeed, ...
    'k--', ...
    'u_L n_N', ...
    'LineWidth', ...
    1.2, ...
    'LabelVerticalAlignment', ...
    'bottom', ...
    'HandleVisibility', ...
    'off');

%% =========================================================
% Axes labels and title
%% =========================================================

xlabel( ...
    axesHandle, ...
    'Motor Speed [rpm]');

title( ...
    axesHandle, ...
    string( ...
        Report.Figures. ...
        MotorCharacteristic.Title));
axesHandle.Title.FontWeight = ...
    'bold';

axesHandle.Title.FontSize = ...
    14;
%% =========================================================
% Legend
%% =========================================================

legend( ...
    axesHandle, ...
    [ ...
    voltageNominalHandle, ...
    voltageMinimumHandle, ...
    currentNominalHandle, ...
    currentMinimumHandle, ...
    overloadNominalHandle, ...
    overloadMinimumHandle], ...
    { ...
    'Motor Voltage, uL = 1', ...
    'Motor Voltage, uL = minimum', ...
    'Motor Current, uL = 1', ...
    'Motor Current, uL = minimum', ...
    'Overload Current, uL = 1', ...
    'Overload Current, uL = minimum'}, ...
    'Location', ...
    'northwest');

%% =========================================================
% Horizontal-axis range
%% =========================================================

minimumCurveSpeed = ...
    min(C.nCurve);

maximumCurveSpeed = ...
    max(C.nCurve);

speedRange = ...
    maximumCurveSpeed ...
    - minimumCurveSpeed;

if speedRange <= 0

    speedRange = ...
        1;

end

labelOffsetX = ...
    0.015 ...
    * speedRange;

xlim( ...
    axesHandle, ...
    [ ...
    minimumCurveSpeed, ...
    maximumCurveSpeed + 0.10*speedRange ...
    ]);

%% =========================================================
% Voltage end-value labels
%% =========================================================

yyaxis( ...
    axesHandle, ...
    'left');

text( ...
    axesHandle, ...
    maximumCurveSpeed + labelOffsetX, ...
    C.UM_curve(end), ...
    sprintf( ...
        '%.0f V', ...
        C.UM_curve(end)), ...
    'Color', ...
    'k', ...
    'HorizontalAlignment', ...
    'left', ...
    'VerticalAlignment', ...
    'middle');

text( ...
    axesHandle, ...
    maximumCurveSpeed + labelOffsetX, ...
    C.UM_uL_curve(end), ...
    sprintf( ...
        '%.0f V', ...
        C.UM_uL_curve(end)), ...
    'Color', ...
    'k', ...
    'HorizontalAlignment', ...
    'left', ...
    'VerticalAlignment', ...
    'middle');

%% =========================================================
% Current end-value labels
%% =========================================================

yyaxis( ...
    axesHandle, ...
    'right');

text( ...
    axesHandle, ...
    maximumCurveSpeed + labelOffsetX, ...
    C.IM_curve(end), ...
    sprintf( ...
        '%.0f A', ...
        C.IM_curve(end)), ...
    'Color', ...
    'b', ...
    'HorizontalAlignment', ...
    'left', ...
    'VerticalAlignment', ...
    'middle');

text( ...
    axesHandle, ...
    maximumCurveSpeed + labelOffsetX, ...
    C.IM_uL_curve(end), ...
    sprintf( ...
        '%.0f A', ...
        C.IM_uL_curve(end)), ...
    'Color', ...
    'b', ...
    'HorizontalAlignment', ...
    'left', ...
    'VerticalAlignment', ...
    'middle');

text( ...
    axesHandle, ...
    maximumCurveSpeed + labelOffsetX, ...
    C.IM_ovld_curve(end), ...
    sprintf( ...
        '%.0f A', ...
        C.IM_ovld_curve(end)), ...
    'Color', ...
    'r', ...
    'HorizontalAlignment', ...
    'left', ...
    'VerticalAlignment', ...
    'middle');

text( ...
    axesHandle, ...
    maximumCurveSpeed + labelOffsetX, ...
    C.IM_ovld_uL_curve(end), ...
    sprintf( ...
        '%.0f A', ...
        C.IM_ovld_uL_curve(end)), ...
    'Color', ...
    'r', ...
    'HorizontalAlignment', ...
    'left', ...
    'VerticalAlignment', ...
    'middle');

%% =========================================================
% Operating-region labels
%% =========================================================

currentAxisLimits = ...
    ylim(axesHandle);

regionLabelHeight = ...
    currentAxisLimits(1) ...
    + 0.08 ...
    * ( ...
    currentAxisLimits(2) ...
    - currentAxisLimits(1));

constantTorqueStart = ...
    Input.n_min;

constantTorqueEnd = ...
    minimumVoltageBaseSpeed;

constantPowerStart = ...
    nominalSpeed;

constantPowerEnd = ...
    Input.n_max;

text( ...
    axesHandle, ...
    (constantTorqueStart + constantTorqueEnd)/2, ...
    regionLabelHeight, ...
    'Constant Torque', ...
    'HorizontalAlignment', ...
    'center', ...
    'VerticalAlignment', ...
    'bottom', ...
    'FontWeight', ...
    'bold');

text( ...
    axesHandle, ...
    (constantPowerStart + constantPowerEnd)/2, ...
    regionLabelHeight, ...
    'Constant Power', ...
    'HorizontalAlignment', ...
    'center', ...
    'VerticalAlignment', ...
    'bottom', ...
    'FontWeight', ...
    'bold');

hold( ...
    axesHandle, ...
    'off');

%% =========================================================
% Export PNG
%% =========================================================

exportgraphics( ...
    figureHandle, ...
    figureFile, ...
    'Resolution', ...
    300, ...
    'BackgroundColor', ...
    'white');

close( ...
    figureHandle);

if ~isfile(figureFile)

    error( ...
        'Cyclo:MotorCharacteristicFigureExportFailure', ...
        'The motor-characteristic figure was not exported.');

end

end
