%% =========================================================
% Regenerate all CycloTool Design Data figures
%% =========================================================

clear generate_cyclo_overview_figure
clear generate_cyclo_motor_characteristic_figure
clear generate_cyclo_firing_angle_figure
clear generate_cyclo_analytical_harmonics_figure
clear generate_cyclo_representative_fft_figure
clear generate_cyclo_converter_losses_figure
rehash

%% Validate calculation structures

assert( ...
    exist('DesignData', 'var') == 1 && ...
    isstruct(DesignData), ...
    'DesignData is missing or invalid.');

assert( ...
    exist('Report', 'var') == 1 && ...
    isstruct(Report), ...
    'Report is missing or invalid.');

assert( ...
    isfield(Report, 'Figures'), ...
    'Report.Figures is missing.');

assert( ...
    isfield(Report.Figures, 'Overview'), ...
    'Report.Figures.Overview is missing.');

%% Define output folder

figureOutputFolder = ...
    string( ...
        fullfile( ...
            pwd, ...
            'DesignData_Figures'));

if ~isfolder(figureOutputFolder)

    mkdir(figureOutputFolder);

end

%% Define expected output files

figureFileNames = { ...
    'cycloconverter_overview.png', ...
    'motor_characteristic.png', ...
    'firing_angle_characteristic.png', ...
    'analytical_harmonics.png', ...
    'representative_group_fft.png', ...
    'converter_losses.png'};

%% Delete previous figures

fprintf('\n');
fprintf('REMOVING PREVIOUS REPORT FIGURES\n');
fprintf('----------------------------------------------------------\n');

for figureIndex = 1:numel(figureFileNames)

    previousFigureFile = ...
        fullfile( ...
            figureOutputFolder, ...
            figureFileNames{figureIndex});

    if isfile(previousFigureFile)

        delete(previousFigureFile);

        fprintf( ...
            '%d. DELETED: %s\n', ...
            figureIndex, ...
            figureFileNames{figureIndex});

    else

        fprintf( ...
            '%d. NOT PRESENT: %s\n', ...
            figureIndex, ...
            figureFileNames{figureIndex});

    end

end

fprintf('----------------------------------------------------------\n');

%% Generate Figure 1: Overview diagram

fprintf('\nGenerating Figure 1: overview diagram...\n');

overviewFigureFile = ...
    generate_cyclo_overview_figure( ...
        DesignData, ...
        Report, ...
        figureOutputFolder);

%% Generate Figure 2: Motor characteristic

fprintf('Generating Figure 2: motor characteristic...\n');

motorCharacteristicFile = ...
    generate_cyclo_motor_characteristic_figure( ...
        DesignData, ...
        Report, ...
        figureOutputFolder);

%% Generate Figure 3: Firing-angle characteristic

fprintf('Generating Figure 3: firing-angle characteristic...\n');

firingAngleFile = ...
    generate_cyclo_firing_angle_figure( ...
        DesignData, ...
        Report, ...
        figureOutputFolder);

%% Generate Appendix A figure: Analytical harmonics

fprintf('Generating Figure A-1: analytical harmonics...\n');

analyticalHarmonicFile = ...
    generate_cyclo_analytical_harmonics_figure( ...
        DesignData, ...
        Report, ...
        figureOutputFolder);

%% Generate Appendix C figure: Representative FFT

groupToDisplay = ...
    1;

fprintf( ...
    'Generating Figure C-1: representative FFT, group %d...\n', ...
    groupToDisplay);

representativeFftFile = ...
    generate_cyclo_representative_fft_figure( ...
        DesignData, ...
        Report, ...
        figureOutputFolder, ...
        groupToDisplay);

%% Generate Appendix D figure: Converter losses

fprintf('Generating Figure D-1: converter losses...\n');

converterLossFile = ...
    generate_cyclo_converter_losses_figure( ...
        DesignData, ...
        Report, ...
        figureOutputFolder);
%% Generate Appendix B Detailed Simulation figures

fprintf('Generating Figure B-1: motor phase currents...\n');

simulationMotorCurrentFile = ...
    generate_cyclo_simulation_motor_currents_figure( ...
        DesignData, ...
        Report, ...
        figureOutputFolder);

fprintf('Generating Figure B-2: converter output voltages...\n');

simulationVoltageFile = ...
    generate_cyclo_simulation_voltages_figure( ...
        DesignData, ...
        Report, ...
        figureOutputFolder);

fprintf('Generating Figure B-3: switching-state overview...\n');

simulationSwitchingFile = ...
    generate_cyclo_simulation_switching_figure( ...
        DesignData, ...
        Report, ...
        figureOutputFolder);

fprintf('Generating Figure B-4: physical thyristor currents...\n');

simulationDeviceCurrentFile = ...
    generate_cyclo_simulation_device_currents_figure( ...
        DesignData, ...
        Report, ...
        figureOutputFolder);

%% Verify all generated figures

generatedFigureFiles = { ...
    overviewFigureFile, ...
    motorCharacteristicFile, ...
    firingAngleFile, ...
    analyticalHarmonicFile, ...
    simulationMotorCurrentFile, ...
    simulationVoltageFile, ...
    simulationSwitchingFile, ...
    simulationDeviceCurrentFile, ...
    representativeFftFile, ...
    converterLossFile};

fprintf('\n');
fprintf('GENERATED REPORT FIGURES\n');
fprintf('==========================================================\n');

for figureIndex = 1:numel(generatedFigureFiles)

    figurePath = ...
        string( ...
            generatedFigureFiles{figureIndex});

    assert( ...
        strlength(figurePath) > 0, ...
        'Figure %d returned an empty file path.', ...
        figureIndex);

    assert( ...
        isfile(figurePath), ...
        'Generated figure is missing: %s', ...
        figurePath);

    fileInformation = ...
        dir(figurePath);

    assert( ...
        fileInformation.bytes > 0, ...
        'Generated figure is empty: %s', ...
        figurePath);

    imageInformation = ...
        imfinfo( ...
            char(figurePath));

    fprintf( ...
        '%d. %s\n', ...
        figureIndex, ...
        fileInformation.name);

    fprintf( ...
        '   Resolution : %d x %d pixels\n', ...
        imageInformation.Width, ...
        imageInformation.Height);

    fprintf( ...
        '   File size  : %.1f kB\n', ...
        fileInformation.bytes/1024);

end

fprintf('==========================================================\n');
fprintf('All Design Data figures regenerated: PASS\n');