function [Project, accepted] = ...
    request_cyclo_report_metadata(defaultProject)
%REQUEST_CYCLO_REPORT_METADATA
% Open a modal dialog for entering project and document
% information before generating the CycloTool Design Data report.
%
% Input:
%   defaultProject
%       Existing project metadata used as initial values.
%
% Outputs:
%   Project
%       Updated project metadata when the user selects
%       Generate Report.
%
%   accepted
%       true  when Generate Report is selected.
%       false when Cancel is selected or the window is closed.

arguments
    defaultProject (1,1) struct
end

%% =========================================================
% Initialize outputs
%% =========================================================

Project = ...
    defaultProject;

accepted = ...
    false;

%% =========================================================
% Create modal dialog
%% =========================================================

dialogFigure = ...
    uifigure( ...
        'Name', ...
        'CycloTool Design Data Information', ...
        'Position', ...
        [300, 80, 760, 820], ...
        'Resize', ...
        'on');

dialogFigure.CloseRequestFcn = ...
    @cancelDialog;

%% =========================================================
% Main layout
%% =========================================================

mainGrid = ...
    uigridlayout( ...
        dialogFigure, ...
        [18, 3]);

mainGrid.ColumnWidth = { ...
    220, ...
    '1x', ...
    100};

mainGrid.RowHeight = { ...
    42, ...
    32, 32, 32, 32, 32, ...
    32, 32, 32, 32, 32, 32, ...
    32, 32, 32, 32, ...
    82, ...
    44};

mainGrid.Padding = ...
    [16, 16, 16, 16];

mainGrid.RowSpacing = ...
    7;

mainGrid.ColumnSpacing = ...
    8;

%% =========================================================
% Dialog title
%% =========================================================

titleLabel = ...
    uilabel( ...
        mainGrid, ...
        'Text', ...
        'Project and Document Information', ...
        'FontSize', ...
        17, ...
        'FontWeight', ...
        'bold', ...
        'HorizontalAlignment', ...
        'center');

titleLabel.Layout.Row = ...
    1;

titleLabel.Layout.Column = ...
    [1, 3];

%% =========================================================
% Document information
%% =========================================================

documentTitleField = ...
    addTextField( ...
        mainGrid, ...
        2, ...
        'Document title', ...
        getText( ...
            defaultProject, ...
            'DocumentTitle'));

documentNumberField = ...
    addTextField( ...
        mainGrid, ...
        3, ...
        'Document number', ...
        getText( ...
            defaultProject, ...
            'DocumentNumber'));

revisionField = ...
    addTextField( ...
        mainGrid, ...
        4, ...
        'Revision', ...
        getText( ...
            defaultProject, ...
            'Revision'));

statusDropdown = ...
    addDropdownField( ...
        mainGrid, ...
        5, ...
        'Document status', ...
        { ...
        'Draft', ...
        'For Review', ...
        'For Approval', ...
        'Approved', ...
        'As Built'}, ...
        getText( ...
            defaultProject, ...
            'DocumentStatus'));

languageDropdown = ...
    addDropdownField( ...
        mainGrid, ...
        6, ...
        'Language', ...
        { ...
        'en', ...
        'de', ...
        'fr', ...
        'es'}, ...
        getText( ...
            defaultProject, ...
            'Language'));

%% =========================================================
% Project information
%% =========================================================

projectNameField = ...
    addTextField( ...
        mainGrid, ...
        7, ...
        'Project name', ...
        getText( ...
            defaultProject, ...
            'ProjectName'));

clientField = ...
    addTextField( ...
        mainGrid, ...
        8, ...
        'Client', ...
        getText( ...
            defaultProject, ...
            'Client'));

contractorField = ...
    addTextField( ...
        mainGrid, ...
        9, ...
        'Contractor', ...
        getText( ...
            defaultProject, ...
            'Contractor'));

abbProjectField = ...
    addTextField( ...
        mainGrid, ...
        10, ...
        'ABB project number', ...
        getText( ...
            defaultProject, ...
            'ABBProjectNumber'));

customerPOField = ...
    addTextField( ...
        mainGrid, ...
        11, ...
        'Customer PO number', ...
        getText( ...
            defaultProject, ...
            'CustomerPONumber'));

customerDocumentField = ...
    addTextField( ...
        mainGrid, ...
        12, ...
        'Customer document number', ...
        getText( ...
            defaultProject, ...
            'CustomerDocumentNumber'));

%% =========================================================
% Equipment and responsibility information
%% =========================================================

equipmentNameField = ...
    addTextField( ...
        mainGrid, ...
        13, ...
        'Equipment name', ...
        getText( ...
            defaultProject, ...
            'EquipmentName'));

equipmentTagField = ...
    addTextField( ...
        mainGrid, ...
        14, ...
        'Equipment tag', ...
        getText( ...
            defaultProject, ...
            'EquipmentTag'));

preparedByField = ...
    addTextField( ...
        mainGrid, ...
        15, ...
        'Prepared by', ...
        getText( ...
            defaultProject, ...
            'PreparedBy'));

approvedByField = ...
    addTextField( ...
        mainGrid, ...
        16, ...
        'Approved by', ...
        getText( ...
            defaultProject, ...
            'ApprovedBy'));

%% =========================================================
% Transformer rating factors
%% =========================================================

factorPanel = ...
    uipanel( ...
        mainGrid, ...
        'Title', ...
        'Transformer Rating Factors');

factorPanel.Layout.Row = ...
    17;

factorPanel.Layout.Column = ...
    [1, 3];

factorGrid = ...
    uigridlayout( ...
        factorPanel, ...
        [2, 4]);

factorGrid.RowHeight = { ...
    26, ...
    26};

factorGrid.ColumnWidth = { ...
    220, ...
    90, ...
    220, ...
    90};

factorGrid.Padding = ...
    [8, 4, 8, 4];

factorGrid.RowSpacing = ...
    4;

factorGrid.ColumnSpacing = ...
    8;

converterFactorLabel = ...
    uilabel( ...
        factorGrid, ...
        'Text', ...
        'Converter transformer kTr');

converterFactorLabel.Layout.Row = ...
    1;

converterFactorLabel.Layout.Column = ...
    1;

converterFactorField = ...
    uieditfield( ...
        factorGrid, ...
        'numeric', ...
        'Limits', ...
        [1.85, 1.90], ...
        'Value', ...
        getNumeric( ...
            defaultProject, ...
            'ConverterTransformerRatingFactor', ...
            1.90));

converterFactorField.Layout.Row = ...
    1;

converterFactorField.Layout.Column = ...
    2;

excitationFactorLabel = ...
    uilabel( ...
        factorGrid, ...
        'Text', ...
        'Excitation transformer kTr');

excitationFactorLabel.Layout.Row = ...
    1;

excitationFactorLabel.Layout.Column = ...
    3;

excitationFactorField = ...
    uieditfield( ...
        factorGrid, ...
        'numeric', ...
        'Limits', ...
        [1.85, 1.90], ...
        'Value', ...
        getNumeric( ...
            defaultProject, ...
            'ExcitationTransformerRatingFactor', ...
            1.90));

excitationFactorField.Layout.Row = ...
    1;

excitationFactorField.Layout.Column = ...
    4;

factorNote = ...
    uilabel( ...
        factorGrid, ...
        'Text', ...
        ['Permitted project-configured range: ', ...
         '1.85 to 1.90'], ...
        'FontAngle', ...
        'italic', ...
        'FontColor', ...
        [0.35, 0.35, 0.35]);

factorNote.Layout.Row = ...
    2;

factorNote.Layout.Column = ...
    [1, 4];

%% =========================================================
% Dialog buttons
%% =========================================================

buttonGrid = ...
    uigridlayout( ...
        mainGrid, ...
        [1, 3]);

buttonGrid.Layout.Row = ...
    18;

buttonGrid.Layout.Column = ...
    [1, 3];

buttonGrid.ColumnWidth = { ...
    '1x', ...
    150, ...
    170};

buttonGrid.Padding = ...
    [0, 0, 0, 0];

buttonGrid.ColumnSpacing = ...
    10;

buttonSpacer = ...
    uilabel( ...
        buttonGrid, ...
        'Text', ...
        '');

buttonSpacer.Layout.Column = ...
    1;

cancelButton = ...
    uibutton( ...
        buttonGrid, ...
        'Text', ...
        'Cancel', ...
        'ButtonPushedFcn', ...
        @cancelDialog);

cancelButton.Layout.Column = ...
    2;

generateButton = ...
    uibutton( ...
        buttonGrid, ...
        'Text', ...
        'Generate Report', ...
        'FontWeight', ...
        'bold', ...
        'ButtonPushedFcn', ...
        @acceptDialog);

generateButton.Layout.Column = ...
    3;

%% =========================================================
% Display modal behavior
%% =========================================================

try

    dialogFigure.WindowStyle = ...
        'modal';

catch

    % Some MATLAB releases do not support WindowStyle on
    % uifigure. uiwait below still provides modal behavior.

end

uiwait(dialogFigure);

%% =========================================================
% Nested callbacks
%% =========================================================

    function acceptDialog(~, ~)

        updatedProject = ...
            defaultProject;

        updatedProject.DocumentTitle = ...
            getFieldValue(documentTitleField);

        updatedProject.DocumentNumber = ...
            getFieldValue(documentNumberField);

        updatedProject.Revision = ...
            getFieldValue(revisionField);

        updatedProject.DocumentStatus = ...
            char( ...
                string( ...
                    statusDropdown.Value));

        updatedProject.Language = ...
            char( ...
                string( ...
                    languageDropdown.Value));

        updatedProject.ProjectName = ...
            getFieldValue(projectNameField);

        updatedProject.Client = ...
            getFieldValue(clientField);

        updatedProject.Contractor = ...
            getFieldValue(contractorField);

        updatedProject.ABBProjectNumber = ...
            getFieldValue(abbProjectField);

        updatedProject.CustomerPONumber = ...
            getFieldValue(customerPOField);

        updatedProject.CustomerDocumentNumber = ...
            getFieldValue(customerDocumentField);

        updatedProject.EquipmentName = ...
            getFieldValue(equipmentNameField);

        updatedProject.EquipmentTag = ...
            getFieldValue(equipmentTagField);

        updatedProject.PreparedBy = ...
            getFieldValue(preparedByField);

        updatedProject.ApprovedBy = ...
            getFieldValue(approvedByField);

        updatedProject.ConverterTransformerRatingFactor = ...
            converterFactorField.Value;

        updatedProject.ExcitationTransformerRatingFactor = ...
            excitationFactorField.Value;

        %% Add default document date if needed

        if ~isfield(updatedProject, 'DocumentDate') || ...
                strlength( ...
                    string( ...
                        updatedProject.DocumentDate)) == 0

            updatedProject.DocumentDate = ...
                string(datetime('today'));

        end

        %% Add default confidentiality statement if needed

        if ~isfield(updatedProject, 'Confidentiality') || ...
                strlength( ...
                    strtrim( ...
                        string( ...
                            updatedProject.Confidentiality))) == 0

            updatedProject.Confidentiality = ...
                'ABB internal and authorized project use only';

        end

        %% Validate required fields

        requiredFields = { ...
            'DocumentTitle', ...
            'DocumentNumber', ...
            'Revision', ...
            'ProjectName', ...
            'EquipmentName', ...
            'EquipmentTag', ...
            'PreparedBy'};

        for requiredIndex = 1:numel(requiredFields)

            requiredField = ...
                requiredFields{requiredIndex};

            requiredValue = ...
                strtrim( ...
                    string( ...
                        updatedProject.(requiredField)));

            if strlength(requiredValue) == 0

                uialert( ...
                    dialogFigure, ...
                    sprintf( ...
                        'Required field is empty: %s', ...
                        requiredField), ...
                    'Missing Project Information');

                return

            end

        end

        %% Validate transformer factors

        transformerFactors = [ ...
            updatedProject. ...
            ConverterTransformerRatingFactor, ...
            updatedProject. ...
            ExcitationTransformerRatingFactor];

        if any(~isfinite(transformerFactors)) || ...
                any(transformerFactors < 1.85) || ...
                any(transformerFactors > 1.90)

            uialert( ...
                dialogFigure, ...
                ['Transformer rating factors must be ', ...
                 'between 1.85 and 1.90.'], ...
                'Invalid Transformer Rating Factor');

            return

        end

        %% Return accepted metadata

        Project = ...
            updatedProject;

        accepted = ...
            true;

        if isvalid(dialogFigure)

            uiresume(dialogFigure);

            delete(dialogFigure);

        end

    end


    function cancelDialog(~, ~)

        accepted = ...
            false;

        if isvalid(dialogFigure)

            uiresume(dialogFigure);

            delete(dialogFigure);

        end

    end

end


function field = addTextField( ...
    parentGrid, ...
    rowNumber, ...
    labelText, ...
    defaultValue)
%ADDTEXTFIELD Add a labelled text field to a grid layout.

fieldLabel = ...
    uilabel( ...
        parentGrid, ...
        'Text', ...
        labelText);

fieldLabel.Layout.Row = ...
    rowNumber;

fieldLabel.Layout.Column = ...
    1;

field = ...
    uieditfield( ...
        parentGrid, ...
        'text', ...
        'Value', ...
        char( ...
            string(defaultValue)));

field.Layout.Row = ...
    rowNumber;

field.Layout.Column = ...
    [2, 3];

end


function dropdown = addDropdownField( ...
    parentGrid, ...
    rowNumber, ...
    labelText, ...
    items, ...
    defaultValue)
%ADDDROPDOWNFIELD Add a labelled dropdown to a grid layout.

fieldLabel = ...
    uilabel( ...
        parentGrid, ...
        'Text', ...
        labelText);

fieldLabel.Layout.Row = ...
    rowNumber;

fieldLabel.Layout.Column = ...
    1;

dropdown = ...
    uidropdown( ...
        parentGrid, ...
        'Items', ...
        items);

dropdown.Layout.Row = ...
    rowNumber;

dropdown.Layout.Column = ...
    [2, 3];

defaultText = ...
    char( ...
        string(defaultValue));

matchingIndex = ...
    find( ...
        strcmpi( ...
            defaultText, ...
            items), ...
        1);

if isempty(matchingIndex)

    dropdown.Value = ...
        items{1};

else

    dropdown.Value = ...
        items{matchingIndex};

end

end


function value = getText(S, fieldName)
%GETTEXT Return a structure field as a string.

if isfield(S, fieldName) && ...
        ~isempty(S.(fieldName))

    value = ...
        string(S.(fieldName));

else

    value = ...
        "";

end

end


function value = getNumeric( ...
    S, ...
    fieldName, ...
    defaultValue)
%GETNUMERIC Return a finite numeric scalar or a default value.

if isfield(S, fieldName) && ...
        isnumeric(S.(fieldName)) && ...
        isscalar(S.(fieldName)) && ...
        isfinite(S.(fieldName))

    value = ...
        S.(fieldName);

else

    value = ...
        defaultValue;

end

end


function value = getFieldValue(field)
%GETFIELDVALUE Return trimmed text from a UI edit field.

value = ...
    char( ...
        strtrim( ...
            string( ...
                field.Value)));

end