function Signature = cyclo_case_signature(Input)
%CYCLO_CASE_SIGNATURE Create a reproducible signature for a calculation case.
%
% Signature = cyclo_case_signature(Input)
%
% The signature changes when a relevant engineering input changes.
% Volatile fields such as CaseName and timestamps are excluded.
%
% The result contains:
%   Signature.ID
%   Signature.FullHash
%   Signature.CanonicalJSON
%   Signature.Algorithm
%   Signature.CreatedAt
%
% This function does not modify Input.

arguments

    Input (1,1) struct

end

normalizedInput = ...
    removeVolatileFields(Input);

normalizedInput = ...
    orderfieldsRecursively(normalizedInput);

canonicalJSON = ...
    jsonencode( ...
        normalizedInput, ...
        'PrettyPrint', ...
        false);

fullHash = ...
    calculateSHA256( ...
        unicode2native( ...
            canonicalJSON, ...
            'UTF-8'));

shortHash = ...
    extractBetween( ...
        string(fullHash), ...
        1, ...
        16);

Signature = ...
    struct();

Signature.ID = ...
    "CASE-" + upper(shortHash);

Signature.FullHash = ...
    upper(string(fullHash));

Signature.CanonicalJSON = ...
    string(canonicalJSON);

Signature.Algorithm = ...
    "SHA-256";

Signature.CreatedAt = ...
    datetime( ...
        'now', ...
        'Format', ...
        'yyyy-MM-dd HH:mm:ss');

end

function cleanedInput = removeVolatileFields(Input)

cleanedInput = ...
    Input;

volatileFields = { ...
    'CaseName', ...
    'CaseID', ...
    'CaseSignature', ...
    'CreatedAt', ...
    'Timestamp', ...
    'CalculationTime', ...
    'ResultTime', ...
    'ReportTime'};

for fieldIndex = 1:numel(volatileFields)

    fieldName = ...
        volatileFields{fieldIndex};

    if isfield(cleanedInput, fieldName)

        cleanedInput = ...
            rmfield( ...
                cleanedInput, ...
                fieldName);

    end

end

end

function outputValue = orderfieldsRecursively(inputValue)

if isstruct(inputValue)

    outputValue = ...
        orderfields(inputValue);

    structureFields = ...
        fieldnames(outputValue);

    for structureIndex = 1:numel(outputValue)

        for fieldIndex = 1:numel(structureFields)

            fieldName = ...
                structureFields{fieldIndex};

            outputValue(structureIndex).(fieldName) = ...
                orderfieldsRecursively( ...
                    outputValue(structureIndex).(fieldName));

        end

    end

elseif iscell(inputValue)

    outputValue = ...
        inputValue;

    for cellIndex = 1:numel(inputValue)

        outputValue{cellIndex} = ...
            orderfieldsRecursively( ...
                inputValue{cellIndex});

    end

elseif isdatetime(inputValue)

    outputValue = ...
        string(inputValue);

else

    outputValue = ...
        inputValue;

end

end

function hashText = calculateSHA256(byteVector)

messageDigest = ...
    java.security.MessageDigest.getInstance( ...
        'SHA-256');

messageDigest.update( ...
    uint8(byteVector));

digestBytes = ...
    typecast( ...
        messageDigest.digest(), ...
        'uint8');

hashParts = ...
    compose( ...
        '%02x', ...
        digestBytes);

hashText = ...
    join( ...
        hashParts, ...
        '');

hashText = ...
    hashText{1};

end