function [Voltage, Zero] = ...
    apply_cyclo_zero_intervals(P, Voltage)
%APPLY_CYCLO_ZERO_INTERVALS
% Apply phase-specific zero-current blocking intervals to the
% total cycloconverter output voltage.
%
% This function reproduces the zero-voltage interval logic
% used in the original ABB Scilab simulation.
%
% Inputs:
%   P        Prepared simulation parameter structure
%   Voltage  Structure returned by synthesize_cyclo_voltage
%
% Outputs:
%   Voltage  Updated voltage structure
%   Zero     Zero-current masks and diagnostic information

arguments
    P       (1,1) struct
    Voltage (1,1) struct
end

%% =========================================================
% Validate input dimensions
%% =========================================================

numberOfSamples = numel(Voltage.t);
if ~isfinite(P.f2) || P.f2 <= 0

    error( ...
        'Cyclo:InvalidZeroIntervalMotorFrequency', ...
        'P.f2 must be finite and positive.');

end

if ~isfinite(P.w2) || P.w2 <= 0

    error( ...
        'Cyclo:InvalidZeroIntervalAngularFrequency', ...
        'P.w2 must be finite and positive.');

end

if ~isfinite(P.phi)

    error( ...
        'Cyclo:InvalidZeroIntervalPowerFactorAngle', ...
        'P.phi must be finite.');

end

if ~isfinite(P.tzero) || P.tzero < 0

    error( ...
        'Cyclo:InvalidZeroWindowWidth', ...
        'P.tzero must be finite and non-negative.');

end

if P.tzero >= 1/(2*P.f2)

    error( ...
        'Cyclo:ExcessiveZeroWindowWidth', ...
        ['Each zero-current window must be shorter than ', ...
         'one half of the motor period.']);

end

if ~isfinite(P.dt) || P.dt <= 0

    error( ...
        'Cyclo:InvalidZeroIntervalTimeStep', ...
        'P.dt must be finite and positive.');

end
if numberOfSamples == 0

    error( ...
        'Cyclo:EmptySimulationRecord', ...
        'The voltage simulation record is empty.');

end

if numel(Voltage.uu) ~= numberOfSamples || ...
        numel(Voltage.uv) ~= numberOfSamples || ...
        numel(Voltage.uw) ~= numberOfSamples

    error( ...
        'Cyclo:InconsistentVoltageLengths', ...
        'Output voltage arrays must have equal lengths.');

end
%% =========================================================
% Validate converter-group voltage arrays
%% =========================================================

hasGroupU = ...
    isfield(Voltage, 'groupU');

hasGroupV = ...
    isfield(Voltage, 'groupV');

hasGroupW = ...
    isfield(Voltage, 'groupW');

groupVoltageAvailable = ...
    hasGroupU ...
    && hasGroupV ...
    && hasGroupW;

if any([hasGroupU, hasGroupV, hasGroupW]) && ...
        ~groupVoltageAvailable

    error( ...
        'Cyclo:IncompleteGroupVoltageData', ...
        ['Voltage.groupU, Voltage.groupV, and Voltage.groupW ', ...
         'must either all exist or all be absent.']);

end

if groupVoltageAvailable

    groupVoltageFields = { ...
        'groupU', ...
        'groupV', ...
        'groupW'};

    for fieldIndex = 1:numel(groupVoltageFields)

        fieldName = ...
            groupVoltageFields{fieldIndex};

        if size(Voltage.(fieldName),1) ~= numberOfSamples || ...
                size(Voltage.(fieldName),2) ~= P.TC

            error( ...
                'Cyclo:ZeroIntervalGroupVoltageSizeMismatch', ...
                ['Voltage.%s must have dimensions ', ...
                 '%d x %d.'], ...
                fieldName, ...
                numberOfSamples, ...
                P.TC);

        end

        if any(~isfinite(Voltage.(fieldName)(:)))

            error( ...
                'Cyclo:NonFiniteZeroIntervalGroupVoltage', ...
                'Voltage.%s contains non-finite values.', ...
                fieldName);

        end

    end

end
if any(diff(Voltage.t) <= 0)

    error( ...
        'Cyclo:InvalidTimeVector', ...
        'The simulation time vector must be increasing.');

end

%% =========================================================
% Preserve raw converter voltages
%% =========================================================
%
% Preserve both total and converter-group voltage waveforms
% before applying the zero-current blocking intervals.

Voltage.uuRaw = ...
    Voltage.uu;

Voltage.uvRaw = ...
    Voltage.uv;

Voltage.uwRaw = ...
    Voltage.uw;

if isfield(Voltage, 'groupU') && ...
        isfield(Voltage, 'groupV') && ...
        isfield(Voltage, 'groupW')

    Voltage.groupURaw = ...
        Voltage.groupU;

    Voltage.groupVRaw = ...
        Voltage.groupV;

    Voltage.groupWRaw = ...
        Voltage.groupW;

end

%% =========================================================
% Fundamental quantities
%% =========================================================

t = Voltage.t;

motorPeriod = 1/P.f2;

quarterPeriod = ...
    motorPeriod/4;

threeQuarterPeriod = ...
    3*motorPeriod/4;

powerFactorTimeShift = ...
    P.phi/P.w2;

zeroWindowWidth = ...
    P.tzero;

zeroWindowHalfWidth = ...
    zeroWindowWidth/2;

%% =========================================================
% Phase-U zero-current centers
%% =========================================================

centerU1 = ...
    quarterPeriod ...
    + powerFactorTimeShift;

centerU2 = ...
    threeQuarterPeriod ...
    + powerFactorTimeShift;

%% =========================================================
% Phase-V zero-current centers
%% =========================================================

centerV1 = ...
    quarterPeriod ...
    + powerFactorTimeShift ...
    + (2*pi/3)/P.w2;

centerV2 = ...
    threeQuarterPeriod ...
    + powerFactorTimeShift ...
    + (2*pi/3 - 2*pi)/P.w2;

%% =========================================================
% Phase-W zero-current centers
%% =========================================================

centerW1 = ...
    quarterPeriod ...
    + powerFactorTimeShift ...
    + (-2*pi/3 + 2*pi)/P.w2;

centerW2 = ...
    threeQuarterPeriod ...
    + powerFactorTimeShift ...
    - (2*pi/3)/P.w2;

%% =========================================================
% Normalize zero-current centers to one motor period
%% =========================================================

Zero.centersU = ...
    mod([centerU1, centerU2], motorPeriod);

Zero.centersV = ...
    mod([centerV1, centerV2], motorPeriod);

Zero.centersW = ...
    mod([centerW1, centerW2], motorPeriod);

%% =========================================================
% Generate periodic blocking masks
%% =========================================================

Zero.maskU = ...
    buildPeriodicWindowMask( ...
        t, ...
        Zero.centersU, ...
        zeroWindowHalfWidth, ...
        motorPeriod);

Zero.maskV = ...
    buildPeriodicWindowMask( ...
        t, ...
        Zero.centersV, ...
        zeroWindowHalfWidth, ...
        motorPeriod);

Zero.maskW = ...
    buildPeriodicWindowMask( ...
        t, ...
        Zero.centersW, ...
        zeroWindowHalfWidth, ...
        motorPeriod);

%% =========================================================
% Apply zero-current blocking intervals
%% =========================================================
%
% Apply the blocking masks to every converter-group voltage
% contribution. The total converter voltages are then rebuilt
% from the blocked group voltages.
%
% This preserves:
%
%   Voltage.uu = sum(Voltage.groupU,2)
%   Voltage.uv = sum(Voltage.groupV,2)
%   Voltage.uw = sum(Voltage.groupW,2)

if groupVoltageAvailable
    Voltage.groupU(Zero.maskU,:) = ...
        0;
    Voltage.groupV(Zero.maskV,:) = ...
        0;
    Voltage.groupW(Zero.maskW,:) = ...
        0;
    Voltage.uu = ...
        sum( ...
            Voltage.groupU, ...
            2);
    Voltage.uv = ...
        sum( ...
            Voltage.groupV, ...
            2);
    Voltage.uw = ...
        sum( ...
            Voltage.groupW, ...
            2);
else
    Voltage.uu(Zero.maskU) = ...
        0;
    Voltage.uv(Zero.maskV) = ...
        0;
    Voltage.uw(Zero.maskW) = ...
        0;
end

%% =========================================================
% Recalculate motor voltages
%% =========================================================

Voltage.starPoint = ...
    (Voltage.uu ...
    + Voltage.uv ...
    + Voltage.uw) ...
    / 3;

Voltage.motorPhaseU = ...
    Voltage.uu ...
    - Voltage.starPoint;

Voltage.motorPhaseV = ...
    Voltage.uv ...
    - Voltage.starPoint;

Voltage.motorPhaseW = ...
    Voltage.uw ...
    - Voltage.starPoint;

Voltage.lineUV = ...
    Voltage.uu ...
    - Voltage.uv;

Voltage.lineVW = ...
    Voltage.uv ...
    - Voltage.uw;

Voltage.lineWU = ...
    Voltage.uw ...
    - Voltage.uu;

%% =========================================================
% Zero-current diagnostics
%% =========================================================

Zero.motorPeriod = motorPeriod;

Zero.windowWidth = ...
    zeroWindowWidth;

Zero.windowHalfWidth = ...
    zeroWindowHalfWidth;

Zero.samplesU = ...
    nnz(Zero.maskU);

Zero.samplesV = ...
    nnz(Zero.maskV);

Zero.samplesW = ...
    nnz(Zero.maskW);

Zero.durationU = ...
    Zero.samplesU*P.dt;

Zero.durationV = ...
    Zero.samplesV*P.dt;

Zero.durationW = ...
    Zero.samplesW*P.dt;

Zero.expectedDuration = ...
    2*zeroWindowWidth;
Zero.groupVoltageBlockingApplied = ...
    groupVoltageAvailable;

Zero.modelType = ...
    'Periodic phase-specific zero-current blocking';

Zero.Status = ...
    'Applied and validated';
%% =========================================================
% Validate masks
%% =========================================================

if Zero.samplesU == 0

    error( ...
        'Cyclo:MissingZeroIntervalU', ...
        'No zero-current interval was generated for phase U.');

end

if Zero.samplesV == 0

    error( ...
        'Cyclo:MissingZeroIntervalV', ...
        'No zero-current interval was generated for phase V.');

end

if Zero.samplesW == 0

    error( ...
        'Cyclo:MissingZeroIntervalW', ...
        'No zero-current interval was generated for phase W.');

end

if any(Voltage.uu(Zero.maskU) ~= 0)

    error( ...
        'Cyclo:ZeroSuppressionFailedU', ...
        'Phase-U zero-current suppression failed.');

end

if any(Voltage.uv(Zero.maskV) ~= 0)

    error( ...
        'Cyclo:ZeroSuppressionFailedV', ...
        'Phase-V zero-current suppression failed.');

end

if any(Voltage.uw(Zero.maskW) ~= 0)

    error( ...
        'Cyclo:ZeroSuppressionFailedW', ...
        'Phase-W zero-current suppression failed.');

end
%% =========================================================
% Validate total and group voltage consistency
%% =========================================================

if groupVoltageAvailable

    groupUSum = ...
        sum( ...
            Voltage.groupU, ...
            2);

    groupVSum = ...
        sum( ...
            Voltage.groupV, ...
            2);

    groupWSum = ...
        sum( ...
            Voltage.groupW, ...
            2);

    voltageScale = ...
        max( ...
            1, ...
            max( ...
                abs( ...
                    [ ...
                    Voltage.uu(:)
                    Voltage.uv(:)
                    Voltage.uw(:)])));

    voltageConsistencyTolerance = ...
        1e-10 ...
        * voltageScale;

    if any( ...
            abs(Voltage.uu - groupUSum) ...
            > voltageConsistencyTolerance) || ...
            any( ...
            abs(Voltage.uv - groupVSum) ...
            > voltageConsistencyTolerance) || ...
            any( ...
            abs(Voltage.uw - groupWSum) ...
            > voltageConsistencyTolerance)

        error( ...
            'Cyclo:BlockedGroupVoltageBalanceError', ...
            ['Blocked total converter voltages must equal ', ...
             'the sum of their converter-group contributions.']);

    end

end
end


function mask = buildPeriodicWindowMask( ...
    time, ...
    centers, ...
    halfWidth, ...
    period)
%BUILDPERIODICWINDOWMASK
% Create windows centered at specified periodic positions.
if ~isfinite(halfWidth) || halfWidth < 0

    error( ...
        'Cyclo:InvalidPeriodicWindowHalfWidth', ...
        ['The periodic-window half-width must be finite ', ...
         'and non-negative.']);

end

if ~isfinite(period) || period <= 0

    error( ...
        'Cyclo:InvalidPeriodicWindowPeriod', ...
        'The periodic-window period must be finite and positive.');

end

if any(~isfinite(time(:))) || ...
        any(~isfinite(centers(:)))

    error( ...
        'Cyclo:InvalidPeriodicWindowData', ...
        'Periodic-window times and centers must be finite.');

end
mask = false(size(time));

for centerIndex = 1:numel(centers)

    center = centers(centerIndex);

    periodicDistance = ...
        mod( ...
            time ...
            - center ...
            + period/2, ...
            period) ...
        - period/2;

    mask = ...
        mask ...
        | abs(periodicDistance) <= halfWidth;

end

end