function Harmonics = calculate_cyclo_source_harmonics( ...
    P, ...
    Voltage, ...
    Device)
%CALCULATE_CYCLO_SOURCE_HARMONICS
% Calculate converter-group source-current spectra and
% Scilab-compatible characteristic harmonic amplitudes.
%
% Inputs:
%   P        Prepared simulation parameters
%   Voltage  Stage 3 voltage structure containing time
%   Device   Stage 5 device-current structure
%
% Output:
%   Harmonics
%
% Group spectrum organization:
%   Harmonics.Group(groupNumber)

arguments
    P       (1,1) struct
    Voltage (1,1) struct
    Device  (1,1) struct
end

%% =========================================================
% Required field validation
%% =========================================================

if ~isfield(Voltage,'t')

    error( ...
        'Cyclo:MissingHarmonicTime', ...
        'Voltage.t is required for source-current harmonics.');

end

if ~isfield(Device, 'representativeSourceCurrent')

    error( ...
        'Cyclo:MissingRepresentativeSourceCurrent', ...
        ['Device.representativeSourceCurrent is required ', ...
        'for ABB/Scilab representative source-current ', ...
        'harmonic analysis.']);

end

numberOfGroups = ...
    P.TC;

numberOfSamples = ...
    numel(Voltage.t);

if size(Device.representativeSourceCurrent,1) ~= ...
        numberOfSamples
    error( ...
        'Cyclo:HarmonicCurrentLengthMismatch', ...
        ['Representative source currents and the simulation ', ...
        'time must have identical sample counts.']);
end
if size(Device.representativeSourceCurrent,2) ~= 3
    error( ...
        'Cyclo:HarmonicSourcePhaseMismatch', ...
        'Three representative source phases are required.');
end
if size(Device.representativeSourceCurrent,3) ~= ...
        numberOfGroups
    error( ...
        'Cyclo:HarmonicGroupCountMismatch', ...
        ['The representative source-current converter-group ', ...
        'count is incorrect.']);
end



%% =========================================================
% Scilab characteristic harmonic orders
%% =========================================================

harmonicOrders = [ ...
    1
    5
    7
    11
    13
    17
    19
    23
    25
    29
    31
    35
    37
    41
    43
    47
    49];

numberOfOrders = ...
    numel(harmonicOrders);

sidebandWidth = ...
    5*P.f2;

Harmonics.harmonicOrders = ...
    harmonicOrders;

Harmonics.sidebandWidth = ...
    sidebandWidth;

Harmonics.numberOfGroups = ...
    numberOfGroups;

%% =========================================================
% Converter-group loop
%% =========================================================

for groupNumber = 1:numberOfGroups

    groupCurrent = ...
        reshape( ...
        Device.representativeSourceCurrent( ...
        :, ...
        :, ...
        groupNumber), ...
        numberOfSamples, ...
        3);

    Record = ...
        prepare_cyclo_source_fft_record( ...
        P, ...
        Voltage.t, ...
        groupCurrent);

    %% -----------------------------------------------------
    % FFT
    %% -----------------------------------------------------

    fftA = ...
        fft(Record.currentA);

    fftB = ...
        fft(Record.currentB);

    fftC = ...
        fft(Record.currentC);

    N = ...
        Record.numberOfSamples;

    maximumOneSidedBin = ...
        floor(N/2);

    spectrumIndex = ...
        (1:maximumOneSidedBin+1)';

    frequency = ...
        (spectrumIndex-1) ...
        * Record.frequencyResolution;

    spectrumA = ...
        fftA(spectrumIndex)/N;

    spectrumB = ...
        fftB(spectrumIndex)/N;

    spectrumC = ...
        fftC(spectrumIndex)/N;

    %% One-sided peak spectrum

    if rem(N,2) == 0

        doublingIndex = ...
            2:numel(spectrumA)-1;

    else

        doublingIndex = ...
            2:numel(spectrumA);

    end

    spectrumA(doublingIndex) = ...
        2*spectrumA(doublingIndex);

    spectrumB(doublingIndex) = ...
        2*spectrumB(doublingIndex);

    spectrumC(doublingIndex) = ...
        2*spectrumC(doublingIndex);

    magnitudeA = ...
        abs(spectrumA);

    magnitudeB = ...
        abs(spectrumB);

    magnitudeC = ...
        abs(spectrumC);

    %% -----------------------------------------------------
    % Characteristic harmonic extraction
    %% -----------------------------------------------------

    characteristicAmplitudeA = ...
        zeros(numberOfOrders,1);

    characteristicAmplitudeB = ...
        zeros(numberOfOrders,1);

    characteristicAmplitudeC = ...
        zeros(numberOfOrders,1);

    characteristicFrequencyA = ...
        zeros(numberOfOrders,1);

    characteristicFrequencyB = ...
        zeros(numberOfOrders,1);

    characteristicFrequencyC = ...
        zeros(numberOfOrders,1);

    lowerFrequency = ...
        zeros(numberOfOrders,1);

    upperFrequency = ...
        zeros(numberOfOrders,1);

    for orderIndex = 1:numberOfOrders

        harmonicOrder = ...
            harmonicOrders(orderIndex);

        centerFrequency = ...
            harmonicOrder*P.f1;

        lowerFrequency(orderIndex) = ...
            max( ...
            0, ...
            centerFrequency ...
            - sidebandWidth);

        upperFrequency(orderIndex) = ...
            centerFrequency ...
            + sidebandWidth;

        windowMask = ...
            frequency >= lowerFrequency(orderIndex) ...
            & frequency <= upperFrequency(orderIndex);

        if ~any(windowMask)

            error( ...
                'Cyclo:EmptyHarmonicWindow', ...
                ['No FFT bins were found for harmonic ', ...
                'order %d in converter group %d.'], ...
                harmonicOrder, ...
                groupNumber);

        end

        windowIndex = ...
            find(windowMask);

        [characteristicAmplitudeA(orderIndex),localA] = ...
            max(magnitudeA(windowMask));

        [characteristicAmplitudeB(orderIndex),localB] = ...
            max(magnitudeB(windowMask));

        [characteristicAmplitudeC(orderIndex),localC] = ...
            max(magnitudeC(windowMask));

        characteristicFrequencyA(orderIndex) = ...
            frequency(windowIndex(localA));

        characteristicFrequencyB(orderIndex) = ...
            frequency(windowIndex(localB));

        characteristicFrequencyC(orderIndex) = ...
            frequency(windowIndex(localC));

    end

    %% -----------------------------------------------------
    % Percentage relative to input fundamental
    %% -----------------------------------------------------

    inputFundamentalA = ...
        characteristicAmplitudeA(1);

    inputFundamentalB = ...
        characteristicAmplitudeB(1);

    inputFundamentalC = ...
        characteristicAmplitudeC(1);

    if inputFundamentalA <= 0 || ...
            inputFundamentalB <= 0 || ...
            inputFundamentalC <= 0

        error( ...
            'Cyclo:InvalidInputFundamental', ...
            ['Input-current fundamental amplitude must be ', ...
            'positive for every source phase.']);

    end

    characteristicPercentA = ...
        100 ...
        * characteristicAmplitudeA ...
        / inputFundamentalA;

    characteristicPercentB = ...
        100 ...
        * characteristicAmplitudeB ...
        / inputFundamentalB;

    characteristicPercentC = ...
        100 ...
        * characteristicAmplitudeC ...
        / inputFundamentalC;

    %% -----------------------------------------------------
    % Store group results
    %% -----------------------------------------------------

    G = struct();

    G.Record = ...
        Record;

    G.frequency = ...
        frequency;

    G.spectrumA = ...
        spectrumA;

    G.spectrumB = ...
        spectrumB;

    G.spectrumC = ...
        spectrumC;

    G.magnitudeA = ...
        magnitudeA;

    G.magnitudeB = ...
        magnitudeB;

    G.magnitudeC = ...
        magnitudeC;

    G.harmonicOrders = ...
        harmonicOrders;

    G.lowerFrequency = ...
        lowerFrequency;

    G.upperFrequency = ...
        upperFrequency;

    G.amplitudeA = ...
        characteristicAmplitudeA;

    G.amplitudeB = ...
        characteristicAmplitudeB;

    G.amplitudeC = ...
        characteristicAmplitudeC;

    G.percentA = ...
        characteristicPercentA;

    G.percentB = ...
        characteristicPercentB;

    G.percentC = ...
        characteristicPercentC;

    G.peakFrequencyA = ...
        characteristicFrequencyA;

    G.peakFrequencyB = ...
        characteristicFrequencyB;

    G.peakFrequencyC = ...
        characteristicFrequencyC;

    G.fundamentalA = ...
        inputFundamentalA;

    G.fundamentalB = ...
        inputFundamentalB;

    G.fundamentalC = ...
        inputFundamentalC;

    G.rmsA = ...
        rms(Record.currentA);

    G.rmsB = ...
        rms(Record.currentB);

    G.rmsC = ...
        rms(Record.currentC);

    %% =========================================================
    % Verify consistent group-result structure fields
    %% =========================================================
    %
    % Group 1 defines the structure layout.
    % Every later converter group must contain exactly the same
    % fields before it is added to Harmonics.Group.

    if groupNumber > 1

        existingFields = ...
            fieldnames( ...
            Harmonics.Group(1));

        newFields = ...
            fieldnames(G);

        if ~isequal(existingFields, newFields)

            error( ...
                'Cyclo:HarmonicGroupFieldMismatch', ...
                ['Converter group %d has a different ', ...
                'result structure from converter group 1.'], ...
                groupNumber);

        end

    end

    %% =========================================================
    % Store converter-group result
    %% =========================================================

    Harmonics.Group(groupNumber) = ...
        G;

end

%% =========================================================
% Group-averaged harmonic percentages
%% =========================================================
%
% These are useful diagnostics only. Transformer-primary
% combination will require vector-group referral later.

percentAByGroup = ...
    zeros(numberOfOrders,numberOfGroups);

percentBByGroup = ...
    zeros(numberOfOrders,numberOfGroups);

percentCByGroup = ...
    zeros(numberOfOrders,numberOfGroups);

for groupNumber = 1:numberOfGroups

    percentAByGroup(:,groupNumber) = ...
        Harmonics.Group(groupNumber).percentA;

    percentBByGroup(:,groupNumber) = ...
        Harmonics.Group(groupNumber).percentB;

    percentCByGroup(:,groupNumber) = ...
        Harmonics.Group(groupNumber).percentC;

end

Harmonics.percentAByGroup = ...
    percentAByGroup;

Harmonics.percentBByGroup = ...
    percentBByGroup;

Harmonics.percentCByGroup = ...
    percentCByGroup;

Harmonics.meanPercentA = ...
    mean(percentAByGroup,2);

Harmonics.meanPercentB = ...
    mean(percentBByGroup,2);

Harmonics.meanPercentC = ...
    mean(percentCByGroup,2);
%% =========================================================
% Model status
%% =========================================================

Harmonics.modelType = ...
    'ABB/Scilab representative source-current harmonics';

Harmonics.currentModelStatus = ...
    'Validated representative branch input';

Harmonics.transformerPrimaryStatus = ...
    'Not reconstructed';

Harmonics.Status = ...
    'REPRESENTATIVE BRANCH';

Harmonics.Note = ...
    [ ...
    'The harmonic spectra are calculated from the original ', ...
    'ABB/Scilab representative branch currents. They do not ', ...
    'represent the combined transformer-primary spectrum.' ...
    ];

%% =========================================================
% Validation
%% =========================================================

for groupNumber = 1:numberOfGroups

    G = ...
        Harmonics.Group(groupNumber);

    if any(~isfinite(G.magnitudeA)) || ...
            any(~isfinite(G.magnitudeB)) || ...
            any(~isfinite(G.magnitudeC))

        error( ...
            'Cyclo:NonFiniteSourceSpectrum', ...
            ['Converter group %d contains invalid ', ...
            'spectrum values.'], ...
            groupNumber);

    end

    if any(G.amplitudeA < 0) || ...
            any(G.amplitudeB < 0) || ...
            any(G.amplitudeC < 0)

        error( ...
            'Cyclo:NegativeHarmonicAmplitude', ...
            ['Converter group %d contains a negative ', ...
            'harmonic amplitude.'], ...
            groupNumber);

    end

    if abs(G.percentA(1)-100) > 1e-9 || ...
            abs(G.percentB(1)-100) > 1e-9 || ...
            abs(G.percentC(1)-100) > 1e-9

        error( ...
            'Cyclo:InvalidHarmonicNormalization', ...
            ['Converter group %d fundamental harmonic ', ...
            'percentage must equal 100 percent.'], ...
            groupNumber);

    end

end

end