function Record = prepare_cyclo_source_fft_record( ...
    P, ...
    time, ...
    groupSourceCurrent)
%PREPARE_CYCLO_SOURCE_FFT_RECORD
% Resample converter-group source currents onto a uniform
% time grid spanning exactly one motor period.
%
% Inputs:
%   P                   Prepared simulation parameters
%   time                Original Stage 5 simulation time
%   groupSourceCurrent  N x 3 source-current matrix
%
% Output:
%   Record              Uniform one-period current record
%
% Current columns:
%   Column 1 = source phase A
%   Column 2 = source phase B
%   Column 3 = source phase C

arguments
    P                  (1,1) struct
    time               (:,1) double
    groupSourceCurrent (:,3) double
end

%% =========================================================
% Input validation
%% =========================================================

time = ...
    time(:);

numberOfOriginalSamples = ...
    numel(time);

if numberOfOriginalSamples < 16

    error( ...
        'Cyclo:InsufficientSourceCurrentSamples', ...
        ['The converter source-current record contains ', ...
         'too few samples.']);

end

if size(groupSourceCurrent,1) ~= ...
        numberOfOriginalSamples

    error( ...
        'Cyclo:SourceCurrentLengthMismatch', ...
        ['The source-current record must have the same ', ...
         'number of samples as the time vector.']);

end

if any(~isfinite(time)) || ...
        any(diff(time) <= 0)
    error( ...
        'Cyclo:InvalidSourceCurrentTime', ...
        ['The original simulation time must contain finite ', ...
         'and strictly increasing values.']);
end
if any(~isfinite(groupSourceCurrent(:)))

    error( ...
        'Cyclo:NonFiniteSourceCurrent', ...
        'The source-current record contains invalid values.');

end

%% =========================================================
% Exact one-motor-period FFT grid
%% =========================================================
if ~isfinite(P.f2) || P.f2 <= 0
    error( ...
        'Cyclo:InvalidSourceFftMotorFrequency', ...
        'P.f2 must be finite and positive.');
end
if ~isfinite(P.dt) || P.dt <= 0
    error( ...
        'Cyclo:InvalidSourceFftTimeStep', ...
        'P.dt must be finite and positive.');
end
motorPeriod = ...
    1/P.f2;

numberOfFftSamples = ...
    round( ...
        motorPeriod/P.dt);

if numberOfFftSamples < 16

    error( ...
        'Cyclo:InsufficientSourceFftSamples', ...
        'The source-current FFT record is too short.');

end

fftSampleTime = ...
    motorPeriod ...
    / numberOfFftSamples;

fftTime = ...
    (0:numberOfFftSamples-1)' ...
    * fftSampleTime;

%% =========================================================
% Normalize original record into one period
%% =========================================================

timePeriodic = ...
    mod(time, motorPeriod);

[timeSorted, sortIndex] = ...
    sort(timePeriodic);

currentSorted = ...
    groupSourceCurrent(sortIndex,:);

%% Remove duplicate interpolation positions

[timeUnique, uniqueIndex] = ...
    unique( ...
        timeSorted, ...
        'stable');

currentUnique = ...
    currentSorted(uniqueIndex,:);

if numel(timeUnique) < 2

    error( ...
        'Cyclo:InsufficientSourceInterpolationPoints', ...
        ['At least two unique source-current samples ', ...
         'are required for interpolation.']);

end

%% =========================================================
% Periodic endpoint extension
%% =========================================================

timeExtended = [ ...
    timeUnique(end) - motorPeriod
    timeUnique
    timeUnique(1) + motorPeriod];

currentExtended = [ ...
    currentUnique(end,:)
    currentUnique
    currentUnique(1,:)];

%% =========================================================
% Resample currents
%% =========================================================
%
% The source current is a switched waveform. A zero-order
% hold preserves switching steps and avoids artificial ramps.

Record.currentA = ...
    interp1( ...
        timeExtended, ...
        currentExtended(:,1), ...
        fftTime, ...
        'previous');

Record.currentB = ...
    interp1( ...
        timeExtended, ...
        currentExtended(:,2), ...
        fftTime, ...
        'previous');

Record.currentC = ...
    interp1( ...
        timeExtended, ...
        currentExtended(:,3), ...
        fftTime, ...
        'previous');

%% =========================================================
% Store record properties
%% =========================================================

Record.t = ...
    fftTime;

Record.current = [ ...
    Record.currentA, ...
    Record.currentB, ...
    Record.currentC];

Record.numberOfSamples = ...
    numberOfFftSamples;

Record.sampleTime = ...
    fftSampleTime;

Record.sampleFrequency = ...
    1/fftSampleTime;

Record.recordDuration = ...
    motorPeriod;

Record.frequencyResolution = ...
    1/motorPeriod;

Record.originalSampleCount = ...
    numberOfOriginalSamples;

%% =========================================================
% RMS diagnostics
%% =========================================================

Record.currentRms = [ ...
    rms(Record.currentA), ...
    rms(Record.currentB), ...
    rms(Record.currentC)];

Record.currentPeak = [ ...
    max(abs(Record.currentA)), ...
    max(abs(Record.currentB)), ...
    max(abs(Record.currentC))];

%% =========================================================
% Final validation
%% =========================================================

if any(~isfinite(Record.current(:)))

    error( ...
        'Cyclo:InvalidSourceFftRecord', ...
        'The resampled source-current record is invalid.');

end

frequencyTolerance = ...
    1e-9*max(1,P.f2);

if abs( ...
        Record.frequencyResolution ...
        - P.f2) ...
        > frequencyTolerance

    error( ...
        'Cyclo:SourceFftFrequencyMismatch', ...
        ['The source-current FFT resolution must equal ', ...
         'the motor frequency.']);

end

end