function [Voltage, State] = ...
    synthesize_cyclo_voltage(P, Ref)
%SYNTHESIZE_CYCLO_VOLTAGE
% Generate cycloconverter output-voltage waveforms using the
% ABB-compatible sample-shift method from the original Scilab code.
%
% Supported pulse numbers:
%   6, 12, 18, 24
%
% Inputs:
%   P    Prepared simulation parameter structure
%   Ref  Firing-angle reference structure
%
% Outputs:
%   Voltage  Time, input voltages, output voltages, and angles
%   State    Positive and negative converter phase states
%
% State array organization:
%
%   State.positive( ...
%       sample, sourcePhase, converterGroup, outputPhase)
%
%   State.negative( ...
%       sample, sourcePhase, converterGroup, outputPhase)
%
% sourcePhase:
%   1 = phase A
%   2 = phase B
%   3 = phase C
%
% outputPhase:
%   1 = phase U
%   2 = phase V
%   3 = phase W
%
% Important:
%   The current ABB-compatible voltage algorithm determines
%   one natural positive source phase and one natural negative
%   source phase per sample and converter group.
%
%   These natural selections are repeated across U, V, and W
%   to preserve the four-dimensional interface. They are not
%   independent physical thyristor-conduction states.

arguments
    P   (1,1) struct
    Ref (1,1) struct
end

%% =========================================================
% Dimensions
%% =========================================================

numberOfIntervals = P.numberOfIntervals;
samplesPerInterval = P.samplesPerInterval;
numberOfGroups = P.TC;

totalSamples = ...
    numberOfIntervals ...
    * samplesPerInterval;

%% =========================================================
% Basic consistency checks
%% =========================================================

if numel(Ref.alphaU) ~= numberOfIntervals || ...
        numel(Ref.alphaV) ~= numberOfIntervals || ...
        numel(Ref.alphaW) ~= numberOfIntervals

    error( ...
        'Cyclo:InvalidReferenceLength', ...
        ['The firing-reference lengths must equal ', ...
         'the number of converter intervals.']);

end

if numel(P.groupPhaseShift) ~= numberOfGroups

    error( ...
        'Cyclo:InvalidGroupShiftCount', ...
        ['The number of transformer phase shifts must ', ...
         'equal the number of converter groups.']);

end

%% =========================================================
% Maximum firing-delay samples
%% =========================================================
%
% The maximum possible acos-based firing angle is pi.
% The source arrays must therefore contain additional samples
% to permit delayed indexing without exceeding array bounds.

maximumFiringAngle = pi;

maximumDelaySamples = ...
    ceil( ...
        maximumFiringAngle ...
        / (2*pi*P.f1*P.dt));

sourceSampleCount = ...
    samplesPerInterval ...
    + maximumDelaySamples ...
    + 1;

sourceTime = ...
    (0:sourceSampleCount-1)' ...
    * P.dt;

%% =========================================================
% Preallocate voltage arrays
%% =========================================================

Voltage = struct();

Voltage.t = zeros(totalSamples,1);

Voltage.uu = zeros(totalSamples,1);
Voltage.uv = zeros(totalSamples,1);
Voltage.uw = zeros(totalSamples,1);

% First transformer/converter group source voltages.
% These correspond to the Scilab arrays ua, ub, and uc.

Voltage.ua = zeros(totalSamples,1);
Voltage.ub = zeros(totalSamples,1);
Voltage.uc = zeros(totalSamples,1);

% Firing-angle history in radians.

Voltage.alphaU = zeros(totalSamples,1);
Voltage.alphaV = zeros(totalSamples,1);
Voltage.alphaW = zeros(totalSamples,1);

% Converter interval number for every output sample.

Voltage.intervalIndex = zeros(totalSamples,1);

%% =========================================================
% Preallocate natural source-phase selection arrays
%% =========================================================
%
% Dimensions:
%
%   sample x source phase x converter group x output phase
%
% The selections are repeated across the output-phase
% dimension. They belong to the validated voltage-synthesis
% approximation and are not physical gate or commutation
% states.

State = struct();

%% =========================================================
% Phase-specific converter switching states
%% =========================================================
%
% Dimensions:
%
%   sample x source phase x converter group x output phase
%
% Output phase:
%
%   1 = U
%   2 = V
%   3 = W

State.positive = ...
    false( ...
        totalSamples, ...
        3, ...
        numberOfGroups, ...
        3);

State.negative = ...
    false( ...
        totalSamples, ...
        3, ...
        numberOfGroups, ...
        3);

%% =========================================================
% Optional group-voltage storage
%% =========================================================
%
% Each column stores the contribution of one converter group.

Voltage.groupU = ...
    zeros(totalSamples, numberOfGroups);

Voltage.groupV = ...
    zeros(totalSamples, numberOfGroups);

Voltage.groupW = ...
    zeros(totalSamples, numberOfGroups);

%% =========================================================
% Main converter-interval loop
%% =========================================================

for intervalNumber = 1:numberOfIntervals

    %% -----------------------------------------------------
    % Global sample range
    %% -----------------------------------------------------

    firstSample = ...
        (intervalNumber - 1) ...
        * samplesPerInterval ...
        + 1;

    lastSample = ...
        intervalNumber ...
        * samplesPerInterval;

    globalIndex = ...
        firstSample:lastSample;

    %% -----------------------------------------------------
    % Global time vector
    %% -----------------------------------------------------
    %
    % Scilab:
    %
    % tx = t_(1:Nseg) + (jj-1)/(f1*p)

    intervalStartTime = ...
        (intervalNumber - 1) ...
        / (P.f1 * P.pulseNumber);

    localOutputTime = ...
        (0:samplesPerInterval-1)' ...
        * P.dt;

    Voltage.t(globalIndex) = ...
        intervalStartTime ...
        + localOutputTime;

    Voltage.intervalIndex(globalIndex) = ...
        intervalNumber;

    %% -----------------------------------------------------
    % Firing-angle delays
    %% -----------------------------------------------------

    alphaU = Ref.alphaU(intervalNumber);
    alphaV = Ref.alphaV(intervalNumber);
    alphaW = Ref.alphaW(intervalNumber);

    delayU = round( ...
        alphaU ...
        / (2*pi*P.f1*P.dt));

    delayV = round( ...
        alphaV ...
        / (2*pi*P.f1*P.dt));

    delayW = round( ...
        alphaW ...
        / (2*pi*P.f1*P.dt));

    if any([delayU, delayV, delayW] < 0) || ...
            any([delayU, delayV, delayW] > maximumDelaySamples)

        error( ...
            'Cyclo:InvalidFiringDelay', ...
            ['Calculated firing delay exceeds ', ...
             'the allocated source-voltage range.']);

    end

    Voltage.alphaU(globalIndex) = alphaU;
    Voltage.alphaV(globalIndex) = alphaV;
    Voltage.alphaW(globalIndex) = alphaW;

    %% -----------------------------------------------------
    % Converter source phase progression
    %% -----------------------------------------------------

    converterPhase = ...
        Ref.phiConverter(intervalNumber);

    %% -----------------------------------------------------
    % Converter-group loop
    %% -----------------------------------------------------

    for groupNumber = 1:numberOfGroups

        groupShift = ...
            P.groupPhaseShift(groupNumber);

        %% -------------------------------------------------
        % Generate transformer secondary phase voltages
        %% -------------------------------------------------

        sourceAngle = ...
            P.w1 ...
            * sourceTime ...
            + converterPhase ...
            + groupShift;

        sourceA = ...
            P.U1 ...
            * cos(sourceAngle);

        sourceB = ...
            P.U1 ...
            * cos( ...
                sourceAngle ...
                - 2*pi/3);

        sourceC = ...
            P.U1 ...
            * cos( ...
                sourceAngle ...
                + 2*pi/3);

        sourceVoltage = ...
            [sourceA, sourceB, sourceC];

        %% -------------------------------------------------
        % Store first-group input voltages
        %% -------------------------------------------------

        if groupNumber == 1

            Voltage.ua(globalIndex) = ...
                sourceA(1:samplesPerInterval);

            Voltage.ub(globalIndex) = ...
                sourceB(1:samplesPerInterval);

            Voltage.uc(globalIndex) = ...
                sourceC(1:samplesPerInterval);

        end

        %% -------------------------------------------------
        % Natural positive and negative source phases
        %% -------------------------------------------------
        %
        % The conducting source phases are selected from the
        % undelayed source-voltage progression.
        %
        % The firing angle delays voltage evaluation but does not
        % redefine the natural source-phase sequence.
        
        sourceBase = ...
            sourceVoltage( ...
                1:samplesPerInterval, ...
                :);
        
        [~, positivePhase] = ...
            max( ...
                sourceBase, ...
                [], ...
                2);
        
        [~, negativePhase] = ...
            min( ...
                sourceBase, ...
                [], ...
                2);

        %% -------------------------------------------------
        % Local group voltage contribution (vectorized across samples)
        %% -------------------------------------------------
        %
        % Equivalent to the original per-sample loop: delayU/V/W are
        % per-interval scalars, so the delayed index and the gathered
        % source-voltage sample are computed for every localSample at
        % once via linear indexing, instead of one MATLAB loop
        % iteration per sample. Same formulas, same results, but this
        % was previously the simulation's dominant cost at low motor
        % frequency (samplesPerInterval x numberOfIntervals x TC scalar
        % iterations, e.g. millions of iterations at Creeping speed).

        localSample = (1:samplesPerInterval)';

        delayedIndexU = localSample + delayU;
        delayedIndexV = localSample + delayV;
        delayedIndexW = localSample + delayW;

        sourceRows = size(sourceVoltage, 1);

        positiveU = ...
            sourceVoltage(delayedIndexU + (positivePhase-1)*sourceRows) ...
            - P.UT0;
        positiveV = ...
            sourceVoltage(delayedIndexV + (positivePhase-1)*sourceRows) ...
            - P.UT0;
        positiveW = ...
            sourceVoltage(delayedIndexW + (positivePhase-1)*sourceRows) ...
            - P.UT0;

        negativeU = ...
            sourceVoltage(delayedIndexU + (negativePhase-1)*sourceRows) ...
            + P.UT0;
        negativeV = ...
            sourceVoltage(delayedIndexV + (negativePhase-1)*sourceRows) ...
            + P.UT0;
        negativeW = ...
            sourceVoltage(delayedIndexW + (negativePhase-1)*sourceRows) ...
            + P.UT0;

        groupU = positiveU - negativeU;
        groupV = positiveV - negativeV;
        groupW = positiveW - negativeW;

        %% -------------------------------------------------
        % Store natural source-phase selections (vectorized)
        %% -------------------------------------------------
        %
        % The validated ABB-compatible voltage model determines one
        % natural positive source phase and one natural negative
        % source phase per sample and converter group.
        %
        % The same selections are repeated across U, V, and W to
        % preserve the existing four-dimensional interface.
        %
        % These arrays must not be interpreted as independent
        % physical gate, thyristor-latching, or commutation states.
        %
        % State.positive/negative are [totalSamples x 3 x numberOfGroups
        % x 3] logical arrays; linear indices below follow MATLAB's
        % column-major convention for that shape, one outputPhase at a
        % time (only 3 iterations, not one per sample).

        globalSampleColumn = globalIndex(:);
        stateDim1 = totalSamples;
        stateDim2 = 3;
        stateDim3 = numberOfGroups;

        for outputPhase = 1:3

            positiveLinearIndex = ...
                globalSampleColumn ...
                + (positivePhase-1)*stateDim1 ...
                + (groupNumber-1)*stateDim1*stateDim2 ...
                + (outputPhase-1)*stateDim1*stateDim2*stateDim3;

            negativeLinearIndex = ...
                globalSampleColumn ...
                + (negativePhase-1)*stateDim1 ...
                + (groupNumber-1)*stateDim1*stateDim2 ...
                + (outputPhase-1)*stateDim1*stateDim2*stateDim3;

            State.positive(positiveLinearIndex) = true;
            State.negative(negativeLinearIndex) = true;

        end

        %% -------------------------------------------------
        % Store group contribution
        %% -------------------------------------------------

        Voltage.groupU( ...
            globalIndex, ...
            groupNumber) = groupU;

        Voltage.groupV( ...
            globalIndex, ...
            groupNumber) = groupV;

        Voltage.groupW( ...
            globalIndex, ...
            groupNumber) = groupW;

        %% -------------------------------------------------
        % Add group contribution to total output
        %% -------------------------------------------------

        Voltage.uu(globalIndex) = ...
            Voltage.uu(globalIndex) ...
            + groupU;

        Voltage.uv(globalIndex) = ...
            Voltage.uv(globalIndex) ...
            + groupV;

        Voltage.uw(globalIndex) = ...
            Voltage.uw(globalIndex) ...
            + groupW;

    end

end
%% =========================================================
% State-model classification
%% =========================================================

State.modelType = ...
    'Natural source-phase selection';

State.modelStatus = ...
    'Validated for voltage synthesis';

State.physicalConductionStatus = ...
    'Not validated';

State.sourceCurrentStatus = ...
    'Not validated';

State.outputPhaseSelectionsAreRepeated = ...
    true;

State.note = ...
    [ ...
    'State.positive and State.negative contain the natural ', ...
    'source-phase selections used by the ABB-compatible ', ...
    'sample-shift voltage model. The selections are repeated ', ...
    'across output phases U, V, and W and must not be used ', ...
    'as independent physical conduction states for source ', ...
    'current, commutation, harmonics, or switching losses.' ...
    ];
%% =========================================================
% Degree versions of firing-angle histories
%% =========================================================

Voltage.alphaUDeg = ...
    rad2deg(Voltage.alphaU);

Voltage.alphaVDeg = ...
    rad2deg(Voltage.alphaV);

Voltage.alphaWDeg = ...
    rad2deg(Voltage.alphaW);

%% =========================================================
% Derived output voltages
%% =========================================================

Voltage.starPoint = ...
    (Voltage.uu ...
    + Voltage.uv ...
    + Voltage.uw) ...
    / 3;

Voltage.motorPhaseU = ...
    Voltage.uu ...
    - Voltage.starPoint;

Voltage.motorPhaseV = ...
    Voltage.uv ...
    - Voltage.starPoint;

Voltage.motorPhaseW = ...
    Voltage.uw ...
    - Voltage.starPoint;

Voltage.lineUV = ...
    Voltage.uu ...
    - Voltage.uv;

Voltage.lineVW = ...
    Voltage.uv ...
    - Voltage.uw;

Voltage.lineWU = ...
    Voltage.uw ...
    - Voltage.uu;

%% =========================================================
% Final consistency validation
%% =========================================================

validateVoltageResults( ...
    Voltage, ...
    State, ...
    P);

end


function validateVoltageResults(Voltage, State, P)

expectedSamples = P.totalSamples;
expectedGroups = P.TC;

voltageFields = { ...
    't', ...
    'uu', ...
    'uv', ...
    'uw', ...
    'ua', ...
    'ub', ...
    'uc', ...
    'alphaU', ...
    'alphaV', ...
    'alphaW', ...
    'starPoint', ...
    'motorPhaseU', ...
    'motorPhaseV', ...
    'motorPhaseW', ...
    'lineUV', ...
    'lineVW', ...
    'lineWU'};

for fieldIndex = 1:numel(voltageFields)

    fieldName = voltageFields{fieldIndex};

    if numel(Voltage.(fieldName)) ~= expectedSamples

        error( ...
            'Cyclo:IncorrectVoltageLength', ...
            'Voltage.%s has an incorrect length.', ...
            fieldName);

    end

    if any(~isfinite(Voltage.(fieldName)))

        error( ...
            'Cyclo:NonFiniteVoltageResult', ...
            'Voltage.%s contains non-finite values.', ...
            fieldName);

    end

end
%% =========================================================
% Group-voltage validation
%% =========================================================

groupVoltageFields = { ...
    'groupU', ...
    'groupV', ...
    'groupW'};

for fieldIndex = 1:numel(groupVoltageFields)

    fieldName = ...
        groupVoltageFields{fieldIndex};

    if size(Voltage.(fieldName),1) ~= expectedSamples || ...
            size(Voltage.(fieldName),2) ~= expectedGroups

        error( ...
            'Cyclo:IncorrectGroupVoltageSize', ...
            ['Voltage.%s must have dimensions ', ...
             '%d x %d.'], ...
            fieldName, ...
            expectedSamples, ...
            expectedGroups);

    end

    if any(~isfinite(Voltage.(fieldName)(:)))

        error( ...
            'Cyclo:NonFiniteGroupVoltage', ...
            'Voltage.%s contains non-finite values.', ...
            fieldName);

    end

end
%% =========================================================
% Phase-specific switching-state dimensions
%% =========================================================

positiveStateSizeIsCorrect = ...
    size(State.positive,1) == expectedSamples ...
    && size(State.positive,2) == 3 ...
    && size(State.positive,3) == expectedGroups ...
    && size(State.positive,4) == 3;

negativeStateSizeIsCorrect = ...
    size(State.negative,1) == expectedSamples ...
    && size(State.negative,2) == 3 ...
    && size(State.negative,3) == expectedGroups ...
    && size(State.negative,4) == 3;

if ~positiveStateSizeIsCorrect

    error( ...
        'Cyclo:IncorrectPositiveStateSize', ...
        ['Positive switching states must have dimensions ', ...
         '%d x 3 x %d x 3.'], ...
        expectedSamples, ...
        expectedGroups);

end

if ~negativeStateSizeIsCorrect

    error( ...
        'Cyclo:IncorrectNegativeStateSize', ...
        ['Negative switching states must have dimensions ', ...
         '%d x 3 x %d x 3.'], ...
        expectedSamples, ...
        expectedGroups);

end

positiveStateCount = ...
    sum(State.positive,2);

negativeStateCount = ...
    sum(State.negative,2);

if any(positiveStateCount(:) ~= 1)

    error( ...
        'Cyclo:InvalidPositiveState', ...
        ['Every converter group and output phase must ', ...
         'select exactly one upper source phase.']);

end

if any(negativeStateCount(:) ~= 1)

    error( ...
        'Cyclo:InvalidNegativeState', ...
        ['Every converter group and output phase must ', ...
         'select exactly one lower source phase.']);

end
%% =========================================================
% Validate repeated output-phase state interface
%% =========================================================
%
% The current voltage model intentionally repeats one natural
% source-phase selection across U, V, and W.

positiveU = ...
    State.positive(:,:,:,1);

positiveV = ...
    State.positive(:,:,:,2);

positiveW = ...
    State.positive(:,:,:,3);

negativeU = ...
    State.negative(:,:,:,1);

negativeV = ...
    State.negative(:,:,:,2);

negativeW = ...
    State.negative(:,:,:,3);

if ~isequal(positiveU, positiveV) || ...
        ~isequal(positiveU, positiveW)

    error( ...
        'Cyclo:UnexpectedPositivePhaseSpecificState', ...
        ['The validated sample-shift voltage model expects ', ...
         'the natural positive source-phase selection to be ', ...
         'repeated across U, V, and W.']);

end

if ~isequal(negativeU, negativeV) || ...
        ~isequal(negativeU, negativeW)

    error( ...
        'Cyclo:UnexpectedNegativePhaseSpecificState', ...
        ['The validated sample-shift voltage model expects ', ...
         'the natural negative source-phase selection to be ', ...
         'repeated across U, V, and W.']);

end
if any(diff(Voltage.t) <= 0)

    error( ...
        'Cyclo:InvalidTimeVector', ...
        'The output time vector must be strictly increasing.');

end

end