function Current = calculate_cyclo_motor_current( ...
    P, ...
    Voltage, ...
    Zero)
%CALCULATE_CYCLO_MOTOR_CURRENT
% Reconstruct the motor phase currents using the FFT-based
% method from the original ABB Scilab cycloconverter model.
%
% Inputs:
%   P        Prepared simulation parameters
%   Voltage  Zero-suppressed voltage structure
%   Zero     Zero-current interval masks
%
% Output:
%   Current  Motor current waveforms, spectra, reference
%            currents, and diagnostic values

arguments
    P       (1,1) struct
    Voltage (1,1) struct
    Zero    (1,1) struct
end

%% =========================================================
% Validate required fields
%% =========================================================

requiredVoltageFields = { ...
    't', ...
    'uu', ...
    'uv', ...
    'uw', ...
    'starPoint', ...
    'motorPhaseU', ...
    'motorPhaseV', ...
    'motorPhaseW'};

for fieldIndex = 1:numel(requiredVoltageFields)

    fieldName = requiredVoltageFields{fieldIndex};

    if ~isfield(Voltage, fieldName)

        error( ...
            'Cyclo:MissingVoltageField', ...
            'Voltage is missing required field %s.', ...
            fieldName);

    end

end

requiredZeroFields = { ...
    'maskU', ...
    'maskV', ...
    'maskW', ...
    'centersU', ...
    'centersV', ...
    'centersW'};

for fieldIndex = 1:numel(requiredZeroFields)

    fieldName = ...
        requiredZeroFields{fieldIndex};

    if ~isfield(Zero, fieldName)

        error( ...
            'Cyclo:MissingZeroField', ...
            'Zero is missing required field %s.', ...
            fieldName);

    end

end

%% =========================================================
% Validate simulation grid and zero-current masks
%% =========================================================

numberOfInputSamples = ...
    numel(Voltage.t);

if numberOfInputSamples < 2

    error( ...
        'Cyclo:InsufficientCurrentInputSamples', ...
        ['At least two voltage samples are required for ', ...
         'motor-current reconstruction.']);

end

if any(~isfinite(Voltage.t(:))) || ...
        any(diff(Voltage.t(:)) <= 0)
    error( ...
        'Cyclo:InvalidCurrentInputTimeVector', ...
        ['Voltage.t must contain finite and strictly ', ...
         'increasing sample times.']);
end
zeroMaskFields = { ...
    'maskU', ...
    'maskV', ...
    'maskW'};
for fieldIndex = 1:numel(zeroMaskFields)
    fieldName = ...
        zeroMaskFields{fieldIndex};
    if numel(Zero.(fieldName)) ~= numberOfInputSamples
        error( ...
            'Cyclo:CurrentInputZeroMaskLengthMismatch', ...
             ['Zero.%s must contain %d samples.'], ...
            fieldName, ...
            numberOfInputSamples);
    end
    if ~islogical(Zero.(fieldName))
        error( ...
            'Cyclo:CurrentInputZeroMaskTypeMismatch', ...
            'Zero.%s must be a logical array.', ...
            fieldName);
    end
end
%% =========================================================
% Uniform one-motor-period FFT record
%% =========================================================

Record = ...
    prepare_cyclo_fft_record( ...
        P, ...
        Voltage);

tFft = ...
    Record.t(:);

numberOfFftSamples = ...
    Record.numberOfSamples;

fftSampleTime = ...
    Record.sampleTime;

fftSampleFrequency = ...
    Record.sampleFrequency;

fftRecordDuration = ...
    Record.recordDuration;

frequencyResolution = ...
    Record.frequencyResolution;

%% =========================================================
% Original simulation grid
%% =========================================================
%
% FFT operations use Record.t.
% Reconstructed motor-current waveforms use Voltage.t.

t = ...
    Voltage.t(:);

numberOfSimulationSamples = ...
    numel(t);

if numberOfSimulationSamples < 16

    error( ...
        'Cyclo:InsufficientSimulationSamples', ...
        ['The original converter simulation record ', ...
         'contains too few samples.']);

end

if numberOfFftSamples < 16

    error( ...
        'Cyclo:InsufficientFftSamples', ...
        ['The uniform one-motor-period FFT record ', ...
         'contains too few samples.']);

end

%% =========================================================
% Motor voltages
%% =========================================================

Current.fftRecord = Record;
Current.starPointVoltage = ...
    Record.starPoint;
Current.motorPhaseVoltageU = ...
    Record.motorPhaseU;
Current.motorPhaseVoltageV = ...
    Record.motorPhaseV;
Current.motorPhaseVoltageW = ...
    Record.motorPhaseW;

%% =========================================================
% FFT calculation
%% =========================================================
%
% The FFT is performed on the uniform one-motor-period
% voltage record prepared by prepare_cyclo_fft_record.
%
% Therefore, all FFT sizing and normalization must use:
%
%     numberOfFftSamples
%
% and not:
%
%     numberOfSimulationSamples

fftU = ...
    fft(Current.motorPhaseVoltageU);

fftV = ...
    fft(Current.motorPhaseVoltageV);

fftW = ...
    fft(Current.motorPhaseVoltageW);

%% =========================================================
% One-sided complex spectra
%% =========================================================

maximumOneSidedBin = ...
    floor(numberOfFftSamples/2);

spectrumIndex = ...
    (1:maximumOneSidedBin + 1)';

frequency = ...
    (spectrumIndex - 1) ...
    * frequencyResolution;

%% Normalize FFT coefficients by FFT-record length

complexVoltageU = ...
    fftU(spectrumIndex) ...
    / numberOfFftSamples;

complexVoltageV = ...
    fftV(spectrumIndex) ...
    / numberOfFftSamples;

complexVoltageW = ...
    fftW(spectrumIndex) ...
    / numberOfFftSamples;

%% =========================================================
% Convert to one-sided peak-amplitude spectrum
%% =========================================================
%
% DC is never doubled.
%
% For an even sample count, the Nyquist component is also
% not doubled.
%
% For an odd sample count, every positive-frequency
% component after DC is doubled.

if rem(numberOfFftSamples, 2) == 0

    doublingIndex = ...
        2:numel(complexVoltageU)-1;

else

    doublingIndex = ...
        2:numel(complexVoltageU);

end

complexVoltageU(doublingIndex) = ...
    2*complexVoltageU(doublingIndex);

complexVoltageV(doublingIndex) = ...
    2*complexVoltageV(doublingIndex);

complexVoltageW(doublingIndex) = ...
    2*complexVoltageW(doublingIndex);

%% =========================================================
% Store FFT frequency-domain results
%% =========================================================

Current.frequency = ...
    frequency;

Current.voltageSpectrumU = ...
    complexVoltageU;

Current.voltageSpectrumV = ...
    complexVoltageV;

Current.voltageSpectrumW = ...
    complexVoltageW;

Current.voltageMagnitudeU = ...
    abs(complexVoltageU);

Current.voltageMagnitudeV = ...
    abs(complexVoltageV);

Current.voltageMagnitudeW = ...
    abs(complexVoltageW);

Current.voltageAngleU = ...
    angle(complexVoltageU);

Current.voltageAngleV = ...
    angle(complexVoltageV);

Current.voltageAngleW = ...
    angle(complexVoltageW);

%% =========================================================
% Exact output-frequency harmonic bins
%% =========================================================
%
% The record contains exactly one motor period. Therefore:
%
%   FFT index 1     = DC
%   FFT index h + 1 = h*f2

maximumRequestedHarmonic = 200;

maximumAvailableHarmonic = ...
    numel(frequency) - 1;

maximumHarmonic = min( ...
    maximumRequestedHarmonic, ...
    maximumAvailableHarmonic);

if maximumHarmonic < 2

    error( ...
        'Cyclo:InsufficientHarmonicRange', ...
        'The FFT record has insufficient harmonic bandwidth.');

end

harmonicOrder = ...
    (1:maximumHarmonic)';

harmonicFrequency = ...
    harmonicOrder ...
    * P.f2;

harmonicBin = ...
    harmonicOrder + 1;

Current.harmonicOrder = ...
    harmonicOrder;

Current.harmonicFrequency = ...
    harmonicFrequency;

Current.harmonicBin = ...
    harmonicBin;

%% =========================================================
% Motor voltage harmonic phasors
%% =========================================================

voltageHarmonicU = ...
    complexVoltageU(harmonicBin);

voltageHarmonicV = ...
    complexVoltageV(harmonicBin);

voltageHarmonicW = ...
    complexVoltageW(harmonicBin);

Current.voltageHarmonicU = ...
    voltageHarmonicU;

Current.voltageHarmonicV = ...
    voltageHarmonicV;

Current.voltageHarmonicW = ...
    voltageHarmonicW;

%% =========================================================
% Motor back-EMF components
%% =========================================================
%
% Direct translation of:
%
% Ealfa =
%   Uo/sqrt(2)
%   - Rs*Iref*cosphi
%   + w2*Ls*Iref*sqrt(1-cosphi^2)
%
% Ebeta =
%   -Rs*Iref*sqrt(1-cosphi^2)
%   -w2*Ls*Iref*cosphi

sinPhi = ...
    sqrt( ...
        max( ...
            0, ...
            1 - P.cosphi^2));

Current.Ealpha = ...
    P.Uo/sqrt(2) ...
    - P.Rs ...
    * P.Iref ...
    * P.cosphi ...
    + P.w2 ...
    * P.Ls ...
    * P.Iref ...
    * sinPhi;

Current.Ebeta = ...
    -P.Rs ...
    * P.Iref ...
    * sinPhi ...
    - P.w2 ...
    * P.Ls ...
    * P.Iref ...
    * P.cosphi;

Current.backEmfPhasor = ...
    Current.Ealpha ...
    + 1i*Current.Ebeta;

%% =========================================================
% ABB fundamental correction factor u1x
%% =========================================================
%
% Scilab:
%
% u1x = 4*f2 * (
%   sin((w2Modified+w2)/(4*f2))/(w2Modified+w2)
%   +
%   sin((w2Modified-w2)/(4*f2))/(w2Modified-w2)
%   )
%
% The helper function evaluates sin(a*x)/x safely when
% x approaches zero.

plusFrequency = ...
    P.w2Modified ...
    + P.w2;

minusFrequency = ...
    P.w2Modified ...
    - P.w2;

quarterFrequencyFactor = ...
    1/(4*P.f2);

termPlus = ...
    stableSinOverX( ...
        plusFrequency, ...
        quarterFrequencyFactor);

termMinus = ...
    stableSinOverX( ...
        minusFrequency, ...
        quarterFrequencyFactor);

Current.u1x = ...
    4 ...
    * P.f2 ...
    * (termPlus + termMinus);

if ~isfinite(Current.u1x) || ...
        abs(Current.u1x) < 1e-12

    error( ...
        'Cyclo:InvalidFundamentalCorrection', ...
        'The calculated ABB fundamental correction is invalid.');

end

%% =========================================================
% Harmonic motor-current phasors
%% =========================================================

currentPhasorU = ...
    complex(zeros(maximumHarmonic,1));

currentPhasorV = ...
    complex(zeros(maximumHarmonic,1));

currentPhasorW = ...
    complex(zeros(maximumHarmonic,1));

%% Fundamental phase-U current

fundamentalImpedance = ...
    P.Rs ...
    + 1i*P.w2*P.Ls;

currentPhasorU(1) = ...
    ( ...
    voltageHarmonicU(1) ...
    - sqrt(2) ...
    * Current.backEmfPhasor ...
    ) ...
    / fundamentalImpedance;

currentPhasorU(1) = ...
    currentPhasorU(1) ...
    / Current.u1x ...
    / P.cosphi;

%% Phase-shift the fundamental to phases V and W

currentPhasorV(1) = ...
    currentPhasorU(1) ...
    * exp(-1i*2*pi/3);

currentPhasorW(1) = ...
    currentPhasorU(1) ...
    * exp(1i*2*pi/3);

%% Harmonics 2 to maximumHarmonic

for harmonicIndex = 2:maximumHarmonic

    harmonicNumber = ...
        harmonicOrder(harmonicIndex);

    harmonicImpedance = ...
        P.Rs ...
        + 1i ...
        * harmonicNumber ...
        * P.w2 ...
        * P.Ls;

    currentPhasorU(harmonicIndex) = ...
        voltageHarmonicU(harmonicIndex) ...
        / harmonicImpedance;

    harmonicShift = ...
        harmonicNumber ...
        * 2*pi/3;

    currentPhasorV(harmonicIndex) = ...
        currentPhasorU(harmonicIndex) ...
        * exp(-1i*harmonicShift);

    currentPhasorW(harmonicIndex) = ...
        currentPhasorU(harmonicIndex) ...
        * exp(1i*harmonicShift);

end

Current.currentPhasorU = ...
    currentPhasorU;

Current.currentPhasorV = ...
    currentPhasorV;

Current.currentPhasorW = ...
    currentPhasorW;

Current.currentMagnitudeU = ...
    abs(currentPhasorU);

Current.currentMagnitudeV = ...
    abs(currentPhasorV);

Current.currentMagnitudeW = ...
    abs(currentPhasorW);

Current.currentAngleU = ...
    angle(currentPhasorU);

Current.currentAngleV = ...
    angle(currentPhasorV);

Current.currentAngleW = ...
    angle(currentPhasorW);

%% =========================================================
% Reconstruct non-fundamental currents
%% =========================================================

Current.harmonicCurrentU = ...
    reconstructHarmonicCurrent( ...
        t, ...
        P.w2, ...
        harmonicOrder(2:end), ...
        currentPhasorU(2:end));

Current.harmonicCurrentV = ...
    reconstructHarmonicCurrent( ...
        t, ...
        P.w2, ...
        harmonicOrder(2:end), ...
        currentPhasorV(2:end));

Current.harmonicCurrentW = ...
    reconstructHarmonicCurrent( ...
        t, ...
        P.w2, ...
        harmonicOrder(2:end), ...
        currentPhasorW(2:end));

%% =========================================================
% Reconstruct ABB modified-frequency fundamental
%% =========================================================

Current.fundamentalU = ...
    reconstructModifiedFundamental( ...
        t, ...
        P, ...
        abs(currentPhasorU(1)), ...
        angle(currentPhasorU(1)), ...
        Zero.centersU, ...
        Zero.maskU);

Current.fundamentalV = ...
    reconstructModifiedFundamental( ...
        t, ...
        P, ...
        abs(currentPhasorV(1)), ...
        angle(currentPhasorV(1)), ...
        Zero.centersV, ...
        Zero.maskV);

Current.fundamentalW = ...
    reconstructModifiedFundamental( ...
        t, ...
        P, ...
        abs(currentPhasorW(1)), ...
        angle(currentPhasorW(1)), ...
        Zero.centersW, ...
        Zero.maskW);

%% =========================================================
% Independently reconstructed phase currents
%% =========================================================
%
% Preserve all three independently reconstructed currents
% for diagnostic comparison.
%
% The original Scilab implementation reconstructs only one
% motor phase current. Therefore, phase U remains the
% authoritative ABB-compatible current waveform.

Current.iuIndependent = ...
    Current.fundamentalU ...
    + Current.harmonicCurrentU;

Current.ivIndependent = ...
    Current.fundamentalV ...
    + Current.harmonicCurrentV;

Current.iwIndependent = ...
    Current.fundamentalW ...
    + Current.harmonicCurrentW;

%% Apply independent phase blocking for diagnostics

Current.iuIndependent(Zero.maskU) = 0;
Current.ivIndependent(Zero.maskV) = 0;
Current.iwIndependent(Zero.maskW) = 0;

%% =========================================================
% Final phase-U motor current
%% =========================================================

Current.iu = ...
    Current.iuIndependent;

%% =========================================================
% Balanced three-phase current reconstruction
%% =========================================================
%
% For a balanced three-phase system:
%
%   iv(t) = iu(t - T/3)
%   iw(t) = iu(t + T/3)
%
% where:
%
%   T = 1/f2
%
% The helper uses the convention:
%
%   shiftedSignal(t) = signal(t - timeShift)
%
% Therefore:
%
%   positive shift  -> delayed waveform
%   negative shift  -> advanced waveform

motorPeriod = ...
    1/P.f2;

Current.iv = ...
    periodicTimeShift( ...
        t, ...
        Current.iu, ...
        motorPeriod/3, ...
        motorPeriod);

Current.iw = ...
    periodicTimeShift( ...
        t, ...
        Current.iu, ...
        -motorPeriod/3, ...
        motorPeriod);

%% =========================================================
% Apply phase-specific zero-current blocking
%% =========================================================

Current.iu(Zero.maskU) = 0;
Current.iv(Zero.maskV) = 0;
Current.iw(Zero.maskW) = 0;

%% =========================================================
% Reference currents
%% =========================================================

Current.iuReference = ...
    sqrt(2) ...
    * P.Iref ...
    .* cos( ...
        P.w2*t ...
        - P.phi);

Current.ivReference = ...
    sqrt(2) ...
    * P.Iref ...
    .* cos( ...
        P.w2*t ...
        - P.phi ...
        - 2*pi/3);

Current.iwReference = ...
    sqrt(2) ...
    * P.Iref ...
    .* cos( ...
        P.w2*t ...
        - P.phi ...
        + 2*pi/3);

%% =========================================================
% Current polarity states
%% =========================================================

Current.positivePolarityU = ...
    Current.iu > 0;

Current.negativePolarityU = ...
    Current.iu < 0;

Current.positivePolarityV = ...
    Current.iv > 0;

Current.negativePolarityV = ...
    Current.iv < 0;

Current.positivePolarityW = ...
    Current.iw > 0;

Current.negativePolarityW = ...
    Current.iw < 0;

%% =========================================================
% RMS and current-error diagnostics
%% =========================================================

Current.iuRms = ...
    rms(Current.iu);

Current.ivRms = ...
    rms(Current.iv);

Current.iwRms = ...
    rms(Current.iw);
%% =========================================================
% Independent phase-current RMS diagnostics
%% =========================================================

Current.iuIndependentRms = ...
    rms(Current.iuIndependent);

Current.ivIndependentRms = ...
    rms(Current.ivIndependent);

Current.iwIndependentRms = ...
    rms(Current.iwIndependent);

Current.iuReferenceRms = ...
    rms(Current.iuReference);

Current.ivReferenceRms = ...
    rms(Current.ivReference);

Current.iwReferenceRms = ...
    rms(Current.iwReference);

Current.iuRmsErrorPercent = ...
    100 ...
    * (Current.iuRms - P.Iref) ...
    / P.Iref;

Current.ivRmsErrorPercent = ...
    100 ...
    * (Current.ivRms - P.Iref) ...
    / P.Iref;

Current.iwRmsErrorPercent = ...
    100 ...
    * (Current.iwRms - P.Iref) ...
    / P.Iref;

Current.currentTrackingRmsU = ...
    rms( ...
        Current.iu ...
        - Current.iuReference);

Current.currentTrackingRmsV = ...
    rms( ...
        Current.iv ...
        - Current.ivReference);

Current.currentTrackingRmsW = ...
    rms( ...
        Current.iw ...
        - Current.iwReference);

%% =========================================================
% FFT-grid diagnostics
%% =========================================================

Current.fftSampleTime = ...
    fftSampleTime;

Current.fftSampleFrequency = ...
    fftSampleFrequency;

Current.fftRecordDuration = ...
    fftRecordDuration;

Current.numberOfFftSamples = ...
    numberOfFftSamples;

Current.frequencyResolution = ...
    frequencyResolution;

%% =========================================================
% Original simulation-grid diagnostics
%% =========================================================

Current.simulationSampleTime = ...
    P.dt;

Current.numberOfSimulationSamples = ...
    numberOfSimulationSamples;

Current.simulationDuration = ...
    t(end) ...
    - t(1) ...
    + P.dt;

%% Backward-compatible names

Current.sampleFrequency = ...
    Current.fftSampleFrequency;

Current.recordDuration = ...
    Current.fftRecordDuration;

%% =========================================================
% Grid consistency checks
%% =========================================================

if numel(Current.motorPhaseVoltageU) ~= ...
        numberOfFftSamples

    error( ...
        'Cyclo:VoltageFftGridMismatch', ...
        ['The phase-U FFT voltage contains %d samples, ', ...
         'but the FFT record contains %d samples.'], ...
        numel(Current.motorPhaseVoltageU), ...
        numberOfFftSamples);

end

if numel(Current.motorPhaseVoltageV) ~= ...
        numberOfFftSamples

    error( ...
        'Cyclo:VoltageFftGridMismatchV', ...
        ['The phase-V FFT voltage contains %d samples, ', ...
         'but the FFT record contains %d samples.'], ...
        numel(Current.motorPhaseVoltageV), ...
        numberOfFftSamples);

end

if numel(Current.motorPhaseVoltageW) ~= ...
        numberOfFftSamples

    error( ...
        'Cyclo:VoltageFftGridMismatchW', ...
        ['The phase-W FFT voltage contains %d samples, ', ...
         'but the FFT record contains %d samples.'], ...
        numel(Current.motorPhaseVoltageW), ...
        numberOfFftSamples);

end

if numel(Current.iu) ~= ...
        numberOfSimulationSamples

    error( ...
        'Cyclo:CurrentSimulationGridMismatchU', ...
        ['The phase-U motor current contains %d samples, ', ...
         'but the simulation grid contains %d samples.'], ...
        numel(Current.iu), ...
        numberOfSimulationSamples);

end

if numel(Current.iv) ~= ...
        numberOfSimulationSamples

    error( ...
        'Cyclo:CurrentSimulationGridMismatchV', ...
        ['The phase-V motor current contains %d samples, ', ...
         'but the simulation grid contains %d samples.'], ...
        numel(Current.iv), ...
        numberOfSimulationSamples);

end

if numel(Current.iw) ~= ...
        numberOfSimulationSamples

    error( ...
        'Cyclo:CurrentSimulationGridMismatchW', ...
        ['The phase-W motor current contains %d samples, ', ...
         'but the simulation grid contains %d samples.'], ...
        numel(Current.iw), ...
        numberOfSimulationSamples);

end

%% =========================================================
% Temporary grid report
%% =========================================================

fprintf('\n');
fprintf('GRID CHECK\n');
fprintf('--------------------------------------------\n');

fprintf('FFT voltage samples     : %d\n', ...
    numel(Current.motorPhaseVoltageU));

fprintf('Expected FFT samples    : %d\n', ...
    numberOfFftSamples);

fprintf('Motor current samples   : %d\n', ...
    numel(Current.iu));

fprintf('Simulation samples      : %d\n', ...
    numberOfSimulationSamples);

fprintf('FFT resolution          : %.6f Hz\n', ...
    frequencyResolution);

fprintf('Motor frequency         : %.6f Hz\n', ...
    P.f2);

fprintf('--------------------------------------------\n');

%% =========================================================
% Final validation
%% =========================================================

validateCurrentResults( ...
    Current, ...
    Zero, ...
    numberOfSimulationSamples);


end


function value = stableSinOverX(x, factor)
%STABLESINOVERX
% Evaluate sin(factor*x)/x with the correct limiting value.

tolerance = 1e-10;

if abs(x) < tolerance

    value = factor;

else

    value = sin(factor*x)/x;

end

end


function current = reconstructHarmonicCurrent( ...
    time, ...
    fundamentalAngularFrequency, ...
    harmonicOrder, ...
    currentPhasor)
%RECONSTRUCTHARMONICCURRENT
% Reconstruct a real waveform from peak complex phasors.

current = zeros(size(time));

for harmonicIndex = 1:numel(harmonicOrder)

    harmonicNumber = ...
        harmonicOrder(harmonicIndex);

    amplitude = ...
        abs(currentPhasor(harmonicIndex));

    phase = ...
        angle(currentPhasor(harmonicIndex));

    current = ...
        current ...
        + amplitude ...
        .* cos( ...
            harmonicNumber ...
            * fundamentalAngularFrequency ...
            .* time ...
            + phase);

end

end
function shiftedSignal = periodicTimeShift( ...
    time, ...
    signal, ...
    timeShift, ...
    period)
%PERIODICTIMESHIFT
% Shift a periodic waveform without changing its shape.
%
% Convention:
%
%   shiftedSignal(t) = signal(t - timeShift)
%
% A positive timeShift delays the waveform.
% A negative timeShift advances the waveform.

time = ...
    time(:);

signal = ...
    signal(:);

%% =========================================================
% Input validation
%% =========================================================

if numel(time) ~= numel(signal)

    error( ...
        'Cyclo:PeriodicShiftLengthMismatch', ...
        ['The time and signal vectors must contain ', ...
         'the same number of samples.']);

end

if numel(time) < 2

    error( ...
        'Cyclo:InsufficientPeriodicShiftSamples', ...
        ['At least two samples are required for ', ...
         'periodic signal shifting.']);

end

if period <= 0 || ~isfinite(period)

    error( ...
        'Cyclo:InvalidPeriodicShiftPeriod', ...
        'The periodic signal period must be finite and positive.');

end

if ~isfinite(timeShift)

    error( ...
        'Cyclo:InvalidPeriodicTimeShift', ...
        'The requested time shift must be finite.');

end

if any(~isfinite(time)) || any(~isfinite(signal))

    error( ...
        'Cyclo:InvalidPeriodicShiftInput', ...
        ['The periodic-shift time and signal arrays ', ...
         'must contain finite values.']);

end

%% =========================================================
% Wrap original time positions into one period
%% =========================================================

timePeriodic = ...
    mod(time, period);

%% =========================================================
% Sort wrapped time positions
%% =========================================================

[timeSorted, sortIndex] = ...
    sort(timePeriodic);

signalSorted = ...
    signal(sortIndex);

%% =========================================================
% Remove duplicate interpolation positions
%% =========================================================

[timeUnique, uniqueIndex] = ...
    unique( ...
        timeSorted, ...
        'stable');

signalUnique = ...
    signalSorted(uniqueIndex);

if numel(timeUnique) < 2

    error( ...
        'Cyclo:InsufficientPeriodicShiftPoints', ...
        ['At least two unique periodic time points ', ...
         'are required for interpolation.']);

end

%% =========================================================
% Extend the data periodically at both boundaries
%% =========================================================

timeExtended = [ ...
    timeUnique(end) - period
    timeUnique
    timeUnique(1) + period];

signalExtended = [ ...
    signalUnique(end)
    signalUnique
    signalUnique(1)];

%% =========================================================
% Calculate shifted query positions
%% =========================================================

queryTime = ...
    mod( ...
        timePeriodic ...
        - timeShift, ...
        period);

%% =========================================================
% Interpolate the periodically shifted waveform
%% =========================================================
%
% Linear interpolation is appropriate for the motor-current
% waveform. It avoids the artificial discontinuities that
% would be introduced by nearest-neighbor interpolation.

shiftedSignal = ...
    interp1( ...
        timeExtended, ...
        signalExtended, ...
        queryTime, ...
        'linear');

shiftedSignal = ...
    shiftedSignal(:);

%% =========================================================
% Output validation
%% =========================================================

if numel(shiftedSignal) ~= numel(signal)

    error( ...
        'Cyclo:PeriodicShiftOutputLengthMismatch', ...
        ['The periodically shifted signal has an ', ...
         'incorrect number of samples.']);

end

if any(~isfinite(shiftedSignal))

    error( ...
        'Cyclo:InvalidPeriodicShiftResult', ...
        'Periodic current shifting produced invalid values.');

end

end

function fundamental = reconstructModifiedFundamental( ...
    time, ...
    P, ...
    amplitude, ...
    phase, ...
    zeroCenters, ...
    zeroMask)
%RECONSTRUCTMODIFIEDFUNDAMENTAL
% Reconstruct the ABB modified-frequency fundamental between
% the two zero-current intervals.
%
% This generalized implementation works for phases U, V, and W.

motorPeriod = 1/P.f2;
timeInPeriod = ...
    mod(time, motorPeriod);
centers = ...
    sort(mod(zeroCenters, motorPeriod));
if numel(centers) ~= 2
    error( ...
        'Cyclo:InvalidZeroCenterCount', ...
        'Exactly two zero-current centers are required.');
end
halfWidth = ...
    P.tzero/2;
firstWindowEnd = ...
    centers(1) + halfWidth;
secondWindowEnd = ...
    centers(2) + halfWidth;
fundamental = ...
    zeros(size(time));
beforeFirstWindow = ...
    timeInPeriod ...
    < centers(1) - halfWidth;
betweenWindows = ...
    timeInPeriod ...
    > firstWindowEnd ...
    & timeInPeriod ...
    < centers(2) - halfWidth;
afterSecondWindow = ...
    timeInPeriod ...
    > secondWindowEnd;
fundamental(beforeFirstWindow) = ...
    amplitude ...
    .* cos( ...
        P.w2Modified ...
        .* timeInPeriod(beforeFirstWindow) ...
        + phase);
fundamental(betweenWindows) = ...
    amplitude ...
    .* cos( ...
        P.w2Modified ...
        .* ( ...
            timeInPeriod(betweenWindows) ...
            - firstWindowEnd) ...
        + pi/2 ...
        + phase);
fundamental(afterSecondWindow) = ...
    amplitude ...
    .* cos( ...
        P.w2Modified ...
        .* ( ...
            timeInPeriod(afterSecondWindow) ...
            - secondWindowEnd) ...
        - pi/2 ...
        + phase);
fundamental(zeroMask) = 0;
end
function validateCurrentResults( ...
    Current, ...
    Zero, ...
    expectedSimulationSamples)
%VALIDATECURRENTRESULTS
% Validate current waveforms on the original converter
% simulation time grid.

currentFields = { ...
    'iu', ...
    'iv', ...
    'iw', ...
    'iuIndependent', ...
    'ivIndependent', ...
    'iwIndependent', ...
    'iuReference', ...
    'ivReference', ...
    'iwReference', ...
    'fundamentalU', ...
    'fundamentalV', ...
    'fundamentalW', ...
    'harmonicCurrentU', ...
    'harmonicCurrentV', ...
    'harmonicCurrentW'};

%% =========================================================
% Current waveform lengths and numerical validity
%% =========================================================

for fieldIndex = 1:numel(currentFields)

    fieldName = ...
        currentFields{fieldIndex};

    actualSamples = ...
        numel(Current.(fieldName));

    if actualSamples ~= expectedSimulationSamples

        error( ...
            'Cyclo:IncorrectCurrentLength', ...
            ['Current.%s has an incorrect length. ', ...
             'Expected %d samples but obtained %d.'], ...
            fieldName, ...
            expectedSimulationSamples, ...
            actualSamples);

    end

    if any(~isfinite(Current.(fieldName)))

        error( ...
            'Cyclo:NonFiniteCurrent', ...
            'Current.%s contains non-finite values.', ...
            fieldName);

    end

end

%% =========================================================
% Zero-mask lengths
%% =========================================================

if numel(Zero.maskU) ~= expectedSimulationSamples

    error( ...
        'Cyclo:ZeroMaskLengthMismatchU', ...
        ['Zero.maskU contains %d samples, but the ', ...
         'simulation grid contains %d samples.'], ...
        numel(Zero.maskU), ...
        expectedSimulationSamples);

end

if numel(Zero.maskV) ~= expectedSimulationSamples

    error( ...
        'Cyclo:ZeroMaskLengthMismatchV', ...
        ['Zero.maskV contains %d samples, but the ', ...
         'simulation grid contains %d samples.'], ...
        numel(Zero.maskV), ...
        expectedSimulationSamples);

end

if numel(Zero.maskW) ~= expectedSimulationSamples

    error( ...
        'Cyclo:ZeroMaskLengthMismatchW', ...
        ['Zero.maskW contains %d samples, but the ', ...
         'simulation grid contains %d samples.'], ...
        numel(Zero.maskW), ...
        expectedSimulationSamples);

end

%% =========================================================
% Zero-current suppression checks
%% =========================================================

if any(Current.iu(Zero.maskU) ~= 0)

    error( ...
        'Cyclo:CurrentZeroSuppressionFailedU', ...
        ['Phase-U current is nonzero inside ', ...
         'its blocked interval.']);

end

if any(Current.iv(Zero.maskV) ~= 0)

    error( ...
        'Cyclo:CurrentZeroSuppressionFailedV', ...
        ['Phase-V current is nonzero inside ', ...
         'its blocked interval.']);

end

if any(Current.iw(Zero.maskW) ~= 0)

    error( ...
        'Cyclo:CurrentZeroSuppressionFailedW', ...
        ['Phase-W current is nonzero inside ', ...
         'its blocked interval.']);

end

%% =========================================================
% RMS-current checks
%% =========================================================

if Current.iuRms <= 0 || ...
        Current.ivRms <= 0 || ...
        Current.iwRms <= 0

    error( ...
        'Cyclo:InvalidMotorCurrentRms', ...
        'Calculated motor RMS currents must be positive.');

end
end