function Device = calculate_cyclo_device_currents( ...
    P, ...
    State, ...
    Current)
%CALCULATE_CYCLO_DEVICE_CURRENTS
% Calculate bridge states, individual thyristor currents,
% converter-group input currents, and aggregated transformer
% secondary currents.
%
% Inputs:
%   P        Prepared simulation parameter structure
%   State    Converter source-phase states returned by
%            synthesize_cyclo_voltage
%   Current  Validated motor currents returned by
%            calculate_cyclo_motor_current
%
% Output:
%   Device   Bridge states, thyristor states and currents,
%            group currents, source currents, and diagnostics
%
% Array conventions:
%
%   State.positive( ...
%       sample, sourcePhase, group, outputPhase)
%
%   State.negative( ...
%       sample, sourcePhase, group, outputPhase)
%
%   Device.thyristorState( ...
%       sample, physicalThyristor, group, outputPhase)
%
% Natural source-state interpretation:
%
%   State.positive and State.negative contain one natural
%   upper and one natural lower source-phase selection per
%   sample and converter group.
%
%   The voltage-synthesis function repeats those selections
%   across the U, V, and W output-phase dimension.
%
% Physical thyristor order:
%
%   Positive converter bridge:
%    1 = PT1
%    2 = PT3
%    3 = PT5
%    4 = PT4
%    5 = PT6
%    6 = PT2
%
%   Negative converter bridge:
%    7 = NT1
%    8 = NT3
%    9 = NT5
%   10 = NT4
%   11 = NT6
%   12 = NT2
%
% Output phase:
%
%   1 = U
%   2 = V
%   3 = W

arguments
    P       (1,1) struct
    State   (1,1) struct
    Current (1,1) struct
end

%% =========================================================
% Validate required fields
%% =========================================================

requiredStateFields = { ...
    'positive', ...
    'negative'};

requiredCurrentFields = { ...
    'iu', ...
    'iv', ...
    'iw'};

validateRequiredFields( ...
    State, ...
    requiredStateFields, ...
    'State');

validateRequiredFields( ...
    Current, ...
    requiredCurrentFields, ...
    'Current');

%% =========================================================
% Dimensions
%% =========================================================

numberOfSamples = ...
    numel(Current.iu);

numberOfSourcePhases = ...
    3;

numberOfGroups = ...
    P.TC;

numberOfOutputPhases = ...
    3;

%% =========================================================
% Physical thyristor count per output phase and group
%% =========================================================
%
% Each motor output phase has two complete six-pulse
% converter bridges:
%
%   Positive bridge = 6 thyristors
%   Negative bridge = 6 thyristors
%
% Therefore:
%
%   Total = 12 thyristors per output phase and group

numberOfThyristorsPerBridgePair = ...
    12;

%% =========================================================
% Validate dimensions
%% =========================================================

if numel(Current.iv) ~= numberOfSamples || ...
        numel(Current.iw) ~= numberOfSamples

    error( ...
        'Cyclo:MotorCurrentLengthMismatch', ...
        ['Motor phase-current arrays must contain ', ...
         'the same number of samples.']);

end

if size(State.positive,1) ~= numberOfSamples || ...
        size(State.positive,2) ~= numberOfSourcePhases || ...
        size(State.positive,3) ~= numberOfGroups || ...
        size(State.positive,4) ~= numberOfOutputPhases

    error( ...
        'Cyclo:PositiveStateDimensionMismatch', ...
        ['State.positive must have dimensions ', ...
         '%d x 3 x %d x 3.'], ...
        numberOfSamples, ...
        numberOfGroups);

end

if size(State.negative,1) ~= numberOfSamples || ...
        size(State.negative,2) ~= numberOfSourcePhases || ...
        size(State.negative,3) ~= numberOfGroups || ...
        size(State.negative,4) ~= numberOfOutputPhases

    error( ...
        'Cyclo:NegativeStateDimensionMismatch', ...
        ['State.negative must have dimensions ', ...
         '%d x 3 x %d x 3.'], ...
        numberOfSamples, ...
        numberOfGroups);

end
%% =========================================================
% Validate natural source-phase selections
%% =========================================================

if ~islogical(State.positive) || ...
        ~islogical(State.negative)

    error( ...
        'Cyclo:SourceStateTypeMismatch', ...
        ['State.positive and State.negative must be ', ...
         'logical arrays.']);

end

positiveSelectionCount = ...
    sum( ...
        State.positive, ...
        2);

negativeSelectionCount = ...
    sum( ...
        State.negative, ...
        2);

if any(positiveSelectionCount(:) ~= 1)

    error( ...
        'Cyclo:InvalidPositiveSourceSelection', ...
        ['Exactly one natural positive source phase must ', ...
         'be selected at every sample, group, and output ', ...
         'phase.']);

end

if any(negativeSelectionCount(:) ~= 1)

    error( ...
        'Cyclo:InvalidNegativeSourceSelection', ...
        ['Exactly one natural negative source phase must ', ...
         'be selected at every sample, group, and output ', ...
         'phase.']);

end

identicalSourceSelection = ...
    State.positive ...
    & State.negative;

if any(identicalSourceSelection(:))

    error( ...
        'Cyclo:IdenticalPositiveNegativeSourcePhase', ...
        ['The same source phase cannot be selected as both ', ...
         'the natural upper and lower source phase.']);

end
%% =========================================================
% Standardize motor-current matrix
%% =========================================================
%
% Columns:
%   1 = phase U
%   2 = phase V
%   3 = phase W

motorCurrent = [ ...
    Current.iu(:), ...
    Current.iv(:), ...
    Current.iw(:)];

Device.motorCurrent = ...
    motorCurrent;

Device.outputPhaseNames = ...
    {'U','V','W'};

Device.sourcePhaseNames = ...
    {'A','B','C'};

%% =========================================================
% Physical thyristor order
%% =========================================================
%
% Each converter group and motor output phase contains:
%
%   Positive converter bridge: positions 1 to 6
%   Negative converter bridge: positions 7 to 12
%
% The order inside each six-pulse bridge is:
%
%   Upper devices: T1, T3, T5
%   Lower devices: T4, T6, T2

Device.thyristorOrder = { ...
    'PT1', ...
    'PT3', ...
    'PT5', ...
    'PT4', ...
    'PT6', ...
    'PT2', ...
    'NT1', ...
    'NT3', ...
    'NT5', ...
    'NT4', ...
    'NT6', ...
    'NT2'};
%% =========================================================
% ABB-compatible representative names
%% =========================================================
%
% These names correspond to:
%
%   Converter group 1
%   Motor output phase U
%
% Group and output-phase identification are otherwise stored
% in dimensions 3 and 4 of the device arrays.

Device.abbThyristorOrder = { ...
    'T111', ...
    'T131', ...
    'T151', ...
    'T141', ...
    'T161', ...
    'T121', ...
    'T211', ...
    'T231', ...
    'T251', ...
    'T241', ...
    'T261', ...
    'T221'};
%% =========================================================
% Current-polarity states
%% =========================================================
%
% Positive bridge is enabled only for positive motor current.
% Negative bridge is enabled only for negative motor current.

Device.positivePolarity = ...
    motorCurrent > 0;

Device.negativePolarity = ...
    motorCurrent < 0;

Device.zeroPolarity = ...
    motorCurrent == 0;

%% =========================================================
% Physical six-device bridge-state arrays
%% =========================================================
%
% Dimensions:
%
%   sample x bridge device x group x output phase
%
% Device columns inside each bridge:
%
%   1 = T1
%   2 = T3
%   3 = T5
%   4 = T4
%   5 = T6
%   6 = T2

Device.positiveBridgeState = ...
    false( ...
        numberOfSamples, ...
        6, ...
        numberOfGroups, ...
        numberOfOutputPhases);

Device.negativeBridgeState = ...
    false( ...
        numberOfSamples, ...
        6, ...
        numberOfGroups, ...
        numberOfOutputPhases);
%% =========================================================
% Upper and lower source-phase states
%% =========================================================
%
% Dimensions:
%
%   sample x source phase x group x output phase
%
% Source-phase columns:
%
%   1 = A
%   2 = B
%   3 = C

Device.positiveBridgeUpperState = ...
    false( ...
        numberOfSamples, ...
        numberOfSourcePhases, ...
        numberOfGroups, ...
        numberOfOutputPhases);

Device.positiveBridgeLowerState = ...
    false( ...
        numberOfSamples, ...
        numberOfSourcePhases, ...
        numberOfGroups, ...
        numberOfOutputPhases);

Device.negativeBridgeUpperState = ...
    false( ...
        numberOfSamples, ...
        numberOfSourcePhases, ...
        numberOfGroups, ...
        numberOfOutputPhases);

Device.negativeBridgeLowerState = ...
    false( ...
        numberOfSamples, ...
        numberOfSourcePhases, ...
        numberOfGroups, ...
        numberOfOutputPhases);

%% =========================================================
% Preallocate individual thyristor arrays
%% =========================================================

Device.thyristorState = ...
    false( ...
        numberOfSamples, ...
        numberOfThyristorsPerBridgePair, ...
        numberOfGroups, ...
        numberOfOutputPhases);

Device.thyristorCurrentSigned = ...
    zeros( ...
        numberOfSamples, ...
        numberOfThyristorsPerBridgePair, ...
        numberOfGroups, ...
        numberOfOutputPhases);

Device.thyristorCurrent = ...
    zeros( ...
        numberOfSamples, ...
        numberOfThyristorsPerBridgePair, ...
        numberOfGroups, ...
        numberOfOutputPhases);

%% =========================================================
% Source-side current contribution arrays
%% =========================================================
%
% sourceCurrentContribution(
%     sample,
%     sourcePhase,
%     converterGroup,
%     outputPhase)

Device.sourceCurrentContribution = ...
    zeros( ...
        numberOfSamples, ...
        numberOfSourcePhases, ...
        numberOfGroups, ...
        numberOfOutputPhases);

%% =========================================================
% Main output-phase and converter-group loops
%% =========================================================

for outputPhase = 1:numberOfOutputPhases

    phaseCurrent = ...
        motorCurrent(:,outputPhase);

    positiveCurrentState = ...
        Device.positivePolarity(:,outputPhase);

    negativeCurrentState = ...
        Device.negativePolarity(:,outputPhase);

    for groupNumber = 1:numberOfGroups

        %% -------------------------------------------------
        % Phase-specific source-state extraction
        %% -------------------------------------------------
        %
        % Select the source-phase states belonging to the current
        % motor output phase.
        
        sourcePositive = ...
            reshape( ...
                State.positive( ...
                    :, ...
                    :, ...
                    groupNumber, ...
                    outputPhase), ...
                numberOfSamples, ...
                numberOfSourcePhases);
        
        sourceNegative = ...
            reshape( ...
                State.negative( ...
                    :, ...
                    :, ...
                    groupNumber, ...
                    outputPhase), ...
                numberOfSamples, ...
                numberOfSourcePhases);

        %% -------------------------------------------------
        % Physical positive and negative converter bridges
        %% -------------------------------------------------
        %
        % sourcePositive selects the upper source phase.
        % sourceNegative selects the lower source phase.
        %
        % The sign of the motor phase current determines which
        % complete six-thyristor converter bridge conducts.
        
        positiveBridgeUpperState = ...
            sourcePositive ...
            & positiveCurrentState;
        
        positiveBridgeLowerState = ...
            sourceNegative ...
            & positiveCurrentState;
        
        negativeBridgeUpperState = ...
            sourcePositive ...
            & negativeCurrentState;
        
        negativeBridgeLowerState = ...
            sourceNegative ...
            & negativeCurrentState;
        
        %% -------------------------------------------------
        % Store upper and lower source-phase selections
        %% -------------------------------------------------
        
        Device.positiveBridgeUpperState( ...
            :, :, groupNumber, outputPhase) = ...
            positiveBridgeUpperState;
        
        Device.positiveBridgeLowerState( ...
            :, :, groupNumber, outputPhase) = ...
            positiveBridgeLowerState;
        
        Device.negativeBridgeUpperState( ...
            :, :, groupNumber, outputPhase) = ...
            negativeBridgeUpperState;
        
        Device.negativeBridgeLowerState( ...
            :, :, groupNumber, outputPhase) = ...
            negativeBridgeLowerState;
        
        %% -------------------------------------------------
        % Positive six-thyristor bridge
        %% -------------------------------------------------
        %
        % Columns:
        %   1 = PT1, upper phase A
        %   2 = PT3, upper phase B
        %   3 = PT5, upper phase C
        %   4 = PT4, lower phase A
        %   5 = PT6, lower phase B
        %   6 = PT2, lower phase C
        
        positiveBridgeState = [ ...
            positiveBridgeUpperState(:,1), ...
            positiveBridgeUpperState(:,2), ...
            positiveBridgeUpperState(:,3), ...
            positiveBridgeLowerState(:,1), ...
            positiveBridgeLowerState(:,2), ...
            positiveBridgeLowerState(:,3)];
        
        Device.positiveBridgeState( ...
            :, :, groupNumber, outputPhase) = ...
            positiveBridgeState;
        
        %% -------------------------------------------------
        % Negative six-thyristor bridge
        %% -------------------------------------------------
        %
        % Columns:
        %   1 = NT1, upper phase A
        %   2 = NT3, upper phase B
        %   3 = NT5, upper phase C
        %   4 = NT4, lower phase A
        %   5 = NT6, lower phase B
        %   6 = NT2, lower phase C
        
        negativeBridgeState = [ ...
            negativeBridgeUpperState(:,1), ...
            negativeBridgeUpperState(:,2), ...
            negativeBridgeUpperState(:,3), ...
            negativeBridgeLowerState(:,1), ...
            negativeBridgeLowerState(:,2), ...
            negativeBridgeLowerState(:,3)];
        
        Device.negativeBridgeState( ...
            :, :, groupNumber, outputPhase) = ...
            negativeBridgeState;
        
        %% -------------------------------------------------
        % Map both bridges into the 12-device physical array
        %% -------------------------------------------------
        
        Device.thyristorState( ...
            :, 1:6, groupNumber, outputPhase) = ...
            positiveBridgeState;
        
        Device.thyristorState( ...
            :, 7:12, groupNumber, outputPhase) = ...
            negativeBridgeState;

        %% -------------------------------------------------
        % Individual thyristor current
        %% -------------------------------------------------
        %
        % Signed current preserves converter polarity.
        % Absolute current is used for thermal and loss
        % calculations.

        for thyristorNumber = ...
                1:numberOfThyristorsPerBridgePair

            conductionState = ...
                Device.thyristorState( ...
                    :, ...
                    thyristorNumber, ...
                    groupNumber, ...
                    outputPhase);

            signedThyristorCurrent = ...
                double(conductionState) ...
                .* phaseCurrent;

            Device.thyristorCurrentSigned( ...
                :, ...
                thyristorNumber, ...
                groupNumber, ...
                outputPhase) = ...
                signedThyristorCurrent;

            Device.thyristorCurrent( ...
                :, ...
                thyristorNumber, ...
                groupNumber, ...
                outputPhase) = ...
                abs(signedThyristorCurrent);

        end

        %% -------------------------------------------------
        % Repeated-state U+V+W current contribution
        %% -------------------------------------------------
        %
        % This contribution is retained for backward compatibility.
        %
        % It applies the natural source-phase selections separately
        % to motor phases U, V, and W. Because the selections are
        % repeated across all three output phases, summing these
        % contributions causes balanced-current cancellation.
        %
        % Do not use the resulting aggregate for transformer-current
        % validation. The ABB/Scilab-compatible representative
        % source current is calculated separately below using phase U.

        sourceCurrentContribution = ...
            ( ...
            double(sourcePositive) ...
            - double(sourceNegative) ...
            ) ...
            .* phaseCurrent;

        Device.sourceCurrentContribution( ...
            :, ...
            :, ...
            groupNumber, ...
            outputPhase) = ...
            sourceCurrentContribution;

    end

end
%% =========================================================
% ABB-compatible representative source currents
%% =========================================================
%
% The original Scilab model reconstructs one motor current
% waveform and calculates the converter source currents as:
%
%   iCAR = (stateUpperA - stateLowerA)*i
%   iCAS = (stateUpperB - stateLowerB)*i
%   iCAT = (stateUpperC - stateLowerC)*i
%
% Phase U is the authoritative ABB-compatible motor-current
% waveform in calculate_cyclo_motor_current.
%
% These representative currents must remain separate from
% any simultaneous U+V+W transformer-current aggregation.

Device.representativeSourceCurrent = ...
    zeros( ...
        numberOfSamples, ...
        numberOfSourcePhases, ...
        numberOfGroups);

representativeMotorCurrent = ...
    Current.iu(:);

for groupNumber = 1:numberOfGroups

    representativePositiveState = ...
        reshape( ...
            State.positive( ...
                :, ...
                :, ...
                groupNumber, ...
                1), ...
            numberOfSamples, ...
            numberOfSourcePhases);

    representativeNegativeState = ...
        reshape( ...
            State.negative( ...
                :, ...
                :, ...
                groupNumber, ...
                1), ...
            numberOfSamples, ...
            numberOfSourcePhases);

    Device.representativeSourceCurrent( ...
        :, ...
        :, ...
        groupNumber) = ...
        ( ...
        double(representativePositiveState) ...
        - double(representativeNegativeState)) ...
        .* repmat( ...
            representativeMotorCurrent, ...
            1, ...
            numberOfSourcePhases);

end
%% =========================================================
% Representative group source-phase currents
%% =========================================================

Device.representativeGroupCurrentA = ...
    reshape( ...
        Device.representativeSourceCurrent(:,1,:), ...
        numberOfSamples, ...
        numberOfGroups);

Device.representativeGroupCurrentB = ...
    reshape( ...
        Device.representativeSourceCurrent(:,2,:), ...
        numberOfSamples, ...
        numberOfGroups);

Device.representativeGroupCurrentC = ...
    reshape( ...
        Device.representativeSourceCurrent(:,3,:), ...
        numberOfSamples, ...
        numberOfGroups);

Device.representativeGroupSourceCurrentRms = ...
    zeros( ...
        numberOfSourcePhases, ...
        numberOfGroups);
Device.representativeGroupSourceCurrentPeak = ...
    zeros( ...
        numberOfSourcePhases, ...
        numberOfGroups);
for groupNumber = 1:numberOfGroups

    representativeGroupCurrent = ...
        reshape( ...
            Device.representativeSourceCurrent( ...
                :, ...
                :, ...
                groupNumber), ...
            numberOfSamples, ...
            numberOfSourcePhases);

    Device.representativeGroupSourceCurrentRms( ...
        :, ...
        groupNumber) = ...
        rms( ...
            representativeGroupCurrent, ...
            1).';

    Device.representativeGroupSourceCurrentPeak( ...
        :, ...
        groupNumber) = ...
        max( ...
            abs(representativeGroupCurrent), ...
            [], ...
            1).';

end
%% =========================================================
% Aggregate source currents by converter group
%% =========================================================
%
% Sum contributions from motor phases U, V, and W.
%
% Dimensions:
%
%   sample x source phase x group

Device.groupSourceCurrent = ...
    sum( ...
        Device.sourceCurrentContribution, ...
        4);

%% Explicit group source-phase fields

Device.groupCurrentA = ...
    reshape( ...
        Device.groupSourceCurrent(:,1,:), ...
        numberOfSamples, ...
        numberOfGroups);

Device.groupCurrentB = ...
    reshape( ...
        Device.groupSourceCurrent(:,2,:), ...
        numberOfSamples, ...
        numberOfGroups);

Device.groupCurrentC = ...
    reshape( ...
        Device.groupSourceCurrent(:,3,:), ...
        numberOfSamples, ...
        numberOfGroups);

%% =========================================================
% Total transformer secondary currents
%% =========================================================
%
% These are direct sums across converter groups.
%
% Keep group currents separately because transformer
% secondary windings may be phase shifted and physically
% separate.

Device.totalSourceCurrentA = ...
    sum( ...
        Device.groupCurrentA, ...
        2);

Device.totalSourceCurrentB = ...
    sum( ...
        Device.groupCurrentB, ...
        2);

Device.totalSourceCurrentC = ...
    sum( ...
        Device.groupCurrentC, ...
        2);

%% =========================================================
% Positive and negative bridge currents
%% =========================================================
%
% Values are stored as positive current magnitudes.

Device.positiveBridgeCurrent = ...
    zeros( ...
        numberOfSamples, ...
        numberOfGroups, ...
        numberOfOutputPhases);

Device.negativeBridgeCurrent = ...
    zeros( ...
        numberOfSamples, ...
        numberOfGroups, ...
        numberOfOutputPhases);

for outputPhase = 1:numberOfOutputPhases

    phaseCurrent = ...
        motorCurrent(:,outputPhase);

    positiveMagnitude = ...
        max(phaseCurrent, 0);

    negativeMagnitude = ...
        max(-phaseCurrent, 0);

    for groupNumber = 1:numberOfGroups

        Device.positiveBridgeCurrent( ...
            :, ...
            groupNumber, ...
            outputPhase) = ...
            positiveMagnitude;

        Device.negativeBridgeCurrent( ...
            :, ...
            groupNumber, ...
            outputPhase) = ...
            negativeMagnitude;

    end

end

%% =========================================================
% Thyristor RMS, average, and peak currents
%% =========================================================
%
% Dimensions:
%
%   thyristor x group x output phase

Device.thyristorRmsCurrent = ...
    squeeze( ...
        sqrt( ...
            mean( ...
                Device.thyristorCurrent.^2, ...
                1)));

Device.thyristorAverageCurrent = ...
    squeeze( ...
        mean( ...
            Device.thyristorCurrent, ...
            1));

Device.thyristorPeakCurrent = ...
    squeeze( ...
        max( ...
            Device.thyristorCurrent, ...
            [], ...
            1));

%% Restore dimensions for the one-group case

Device.thyristorRmsCurrent = ...
    reshape( ...
        Device.thyristorRmsCurrent, ...
        numberOfThyristorsPerBridgePair, ...
        numberOfGroups, ...
        numberOfOutputPhases);

Device.thyristorAverageCurrent = ...
    reshape( ...
        Device.thyristorAverageCurrent, ...
        numberOfThyristorsPerBridgePair, ...
        numberOfGroups, ...
        numberOfOutputPhases);

Device.thyristorPeakCurrent = ...
    reshape( ...
        Device.thyristorPeakCurrent, ...
        numberOfThyristorsPerBridgePair, ...
        numberOfGroups, ...
        numberOfOutputPhases);

%% =========================================================
% Source-current RMS and peak values
%% =========================================================

Device.groupSourceCurrentRms = ...
    squeeze( ...
        rms( ...
            Device.groupSourceCurrent, ...
            1));

Device.groupSourceCurrentPeak = ...
    squeeze( ...
        max( ...
            abs(Device.groupSourceCurrent), ...
            [], ...
            1));

Device.groupSourceCurrentRms = ...
    reshape( ...
        Device.groupSourceCurrentRms, ...
        numberOfSourcePhases, ...
        numberOfGroups);

Device.groupSourceCurrentPeak = ...
    reshape( ...
        Device.groupSourceCurrentPeak, ...
        numberOfSourcePhases, ...
        numberOfGroups);

Device.totalSourceCurrentRms = [ ...
    rms(Device.totalSourceCurrentA), ...
    rms(Device.totalSourceCurrentB), ...
    rms(Device.totalSourceCurrentC)];

Device.totalSourceCurrentPeak = [ ...
    max(abs(Device.totalSourceCurrentA)), ...
    max(abs(Device.totalSourceCurrentB)), ...
    max(abs(Device.totalSourceCurrentC))];

%% =========================================================
% Conduction counts
%% =========================================================
%
% Count transitions from OFF to ON and ON to OFF.

Device.turnOnCount = ...
    zeros( ...
        numberOfThyristorsPerBridgePair, ...
        numberOfGroups, ...
        numberOfOutputPhases);

Device.turnOffCount = ...
    zeros( ...
        numberOfThyristorsPerBridgePair, ...
        numberOfGroups, ...
        numberOfOutputPhases);

for outputPhase = 1:numberOfOutputPhases

    for groupNumber = 1:numberOfGroups

        for thyristorNumber = ...
                1:numberOfThyristorsPerBridgePair

            thyristorState = ...
                Device.thyristorState( ...
                    :, ...
                    thyristorNumber, ...
                    groupNumber, ...
                    outputPhase);

            stateDifference = ...
                diff( ...
                    double(thyristorState));

            Device.turnOnCount( ...
                thyristorNumber, ...
                groupNumber, ...
                outputPhase) = ...
                nnz(stateDifference > 0);

            Device.turnOffCount( ...
                thyristorNumber, ...
                groupNumber, ...
                outputPhase) = ...
                nnz(stateDifference < 0);

        end

    end

end

%% =========================================================
% Representative ABB-compatible device fields
%% =========================================================
%
% Converter group 1 and motor output phase U.
%
% Column 1:
%   T111, positive converter bridge
%
% Column 7:
%   T211, negative converter bridge

Device.staT111 = ...
    Device.thyristorState(:,1,1,1);

Device.iT111 = ...
    Device.thyristorCurrent(:,1,1,1);

Device.staT211 = ...
    Device.thyristorState(:,7,1,1);

Device.iT211 = ...
    Device.thyristorCurrent(:,7,1,1);

%% Source currents for group 1 and output phase U

Device.iCAR1 = ...
    Device.representativeGroupCurrentA(:,1);

Device.iCAS1 = ...
    Device.representativeGroupCurrentB(:,1);

Device.iCAT1 = ...
    Device.representativeGroupCurrentC(:,1);
%% =========================================================
% Metadata
%% =========================================================

Device.numberOfSamples = ...
    numberOfSamples;

Device.numberOfGroups = ...
    numberOfGroups;

Device.numberOfOutputPhases = ...
    numberOfOutputPhases;

Device.numberOfThyristorsPerBridgePair = ...
    numberOfThyristorsPerBridgePair;
Device.numberOfThyristorsPerPhysicalBridge = ...
    6;

Device.numberOfPhysicalBridgesPerPhaseGroup = ...
    2;

Device.totalPhysicalThyristors = ...
    numberOfThyristorsPerBridgePair ...
    * numberOfGroups ...
    * numberOfOutputPhases;

Device.expectedPhysicalThyristors = ...
    P.pulseNumber ...
    * 6;

if Device.totalPhysicalThyristors ~= ...
        Device.expectedPhysicalThyristors

    error( ...
        'Cyclo:DeviceThyristorCountMismatch', ...
        ['The explicit model contains %d thyristors, ', ...
         'but the ABB topology requires %d.'], ...
        Device.totalPhysicalThyristors, ...
        Device.expectedPhysicalThyristors);

end

%% =========================================================
% Model-validation status
%% =========================================================

Device.outputVoltageModelStatus = ...
    'Validated';

Device.motorCurrentModelStatus = ...
    'Validated';

Device.physicalTopologyStatus = ...
    'Validated';

Device.deviceCurrentAllocationStatus = ...
    'Validated within natural-selection model';

Device.thyristorCurrentStatus = ...
    'Validated within natural-selection model';

Device.inputConductionStateStatus = ...
    'Provisional';

%% ABB/Scilab-compatible representative source current

Device.representativeSourceCurrentStatus = ...
    'ABB/Scilab compatible';

Device.representativeSourceHarmonicStatus = ...
    'Available for representative converter branch';

%% Full transformer-current status

Device.totalTransformerCurrentStatus = ...
    'Not reconstructed';

Device.sourceCurrentStatus = ...
    'Representative branch only';

%% Rejected U+V+W repeated-state aggregation

Device.aggregatedRepeatedStateCurrentStatus = ...
    'Invalid for transformer-current validation';

Device.aggregatedRepeatedStateCurrentNote = ...
    [ ...
    'This diagnostic sums U, V, and W motor currents using ', ...
    'identical natural source-phase switching functions. ', ...
    'Balanced current cancellation makes it unsuitable for ', ...
    'physical transformer-current calculations.' ...
    ];

Device.sourceHarmonicStatus = ...
    'Not validated for total transformer current';

Device.lossModelStatus = ...
    'Not validated';

Device.sourceCurrentNote = ...
    [ ...
    'The ABB/Scilab-compatible representative source current ', ...
    'uses phase-U motor current and one natural source-phase ', ...
    'selection per converter group. The simultaneous U+V+W ', ...
    'aggregation remains diagnostic only because the same ', ...
    'natural switching states are repeated across all three ', ...
    'output phases.' ...
    ];

%% =========================================================
% Validation
%% =========================================================

validateDeviceCurrents( ...
    Device, ...
    State, ...
    Current, ...
    numberOfSamples, ...
    numberOfGroups);

end


function validateRequiredFields( ...
    S, ...
    requiredFields, ...
    structureName)

for fieldIndex = 1:numel(requiredFields)

    fieldName = ...
        requiredFields{fieldIndex};

    if ~isfield(S, fieldName)

        error( ...
            'Cyclo:MissingDeviceInputField', ...
            '%s is missing required field %s.', ...
            structureName, ...
            fieldName);

    end

end

end


function validateDeviceCurrents( ...
    Device, ...
    State, ...
    Current, ...
    expectedSamples, ...
    expectedGroups)
%VALIDATEDEVICECURRENTS
% Validate the explicit ABB topology consisting of:
%
%   6 thyristors in the positive converter bridge
%   6 thyristors in the negative converter bridge
%
% for every motor output phase and converter group.

%% =========================================================
% 1. Main physical-device array dimensions
%% =========================================================

if size(Device.thyristorState, 1) ~= expectedSamples

    error( ...
        'Cyclo:ThyristorStateLengthMismatch', ...
        ['Thyristor-state sample count is incorrect. ', ...
         'Expected %d samples but obtained %d.'], ...
        expectedSamples, ...
        size(Device.thyristorState, 1));

end

if size(Device.thyristorState, 2) ~= 12

    error( ...
        'Cyclo:ThyristorStateCountMismatch', ...
        ['Twelve physical thyristor states are required ', ...
         'per output phase and converter group. ', ...
         'The current array contains %d device states.'], ...
        size(Device.thyristorState, 2));

end

if size(Device.thyristorState, 3) ~= expectedGroups

    error( ...
        'Cyclo:ThyristorGroupCountMismatch', ...
        ['Expected %d converter groups but obtained %d.'], ...
        expectedGroups, ...
        size(Device.thyristorState, 3));

end

if size(Device.thyristorState, 4) ~= 3

    error( ...
        'Cyclo:ThyristorOutputPhaseCountMismatch', ...
        ['Three motor output phases are required. ', ...
         'The current array contains %d output phases.'], ...
        size(Device.thyristorState, 4));

end

%% =========================================================
% 2. Positive and negative bridge dimensions
%% =========================================================
%
% Each positive and negative converter bridge must contain:
%
%   T1, T3, T5, T4, T6, T2

if size(Device.positiveBridgeState, 1) ~= expectedSamples || ...
        size(Device.positiveBridgeState, 2) ~= 6 || ...
        size(Device.positiveBridgeState, 3) ~= expectedGroups || ...
        size(Device.positiveBridgeState, 4) ~= 3

    error( ...
        'Cyclo:PositiveBridgeDimensionMismatch', ...
        ['Device.positiveBridgeState must have dimensions ', ...
         '%d x 6 x %d x 3.'], ...
        expectedSamples, ...
        expectedGroups);

end

if size(Device.negativeBridgeState, 1) ~= expectedSamples || ...
        size(Device.negativeBridgeState, 2) ~= 6 || ...
        size(Device.negativeBridgeState, 3) ~= expectedGroups || ...
        size(Device.negativeBridgeState, 4) ~= 3

    error( ...
        'Cyclo:NegativeBridgeDimensionMismatch', ...
        ['Device.negativeBridgeState must have dimensions ', ...
         '%d x 6 x %d x 3.'], ...
        expectedSamples, ...
        expectedGroups);

end

%% =========================================================
% 3. Upper and lower selection-array dimensions
%% =========================================================

selectionFields = { ...
    'positiveBridgeUpperState', ...
    'positiveBridgeLowerState', ...
    'negativeBridgeUpperState', ...
    'negativeBridgeLowerState'};

for fieldIndex = 1:numel(selectionFields)

    fieldName = selectionFields{fieldIndex};

    if size(Device.(fieldName), 1) ~= expectedSamples || ...
            size(Device.(fieldName), 2) ~= 3 || ...
            size(Device.(fieldName), 3) ~= expectedGroups || ...
            size(Device.(fieldName), 4) ~= 3

        error( ...
            'Cyclo:BridgeSelectionDimensionMismatch', ...
            ['Device.%s must have dimensions ', ...
             '%d x 3 x %d x 3.'], ...
            fieldName, ...
            expectedSamples, ...
            expectedGroups);

    end

end

%% =========================================================
% 4. Finite-current checks
%% =========================================================

numericFields = { ...
    'thyristorCurrentSigned', ...
    'thyristorCurrent', ...
    'representativeSourceCurrent', ...
    'representativeGroupCurrentA', ...
    'representativeGroupCurrentB', ...
    'representativeGroupCurrentC', ...
    'representativeGroupSourceCurrentRms', ...
    'representativeGroupSourceCurrentPeak', ...
    'sourceCurrentContribution', ...
    'groupSourceCurrent', ...
    'totalSourceCurrentA', ...
    'totalSourceCurrentB', ...
    'totalSourceCurrentC'};

for fieldIndex = 1:numel(numericFields)

    fieldName = numericFields{fieldIndex};

    if any(~isfinite(Device.(fieldName)(:)))

        error( ...
            'Cyclo:NonFiniteDeviceCurrent', ...
            'Device.%s contains non-finite values.', ...
            fieldName);

    end

end

%% =========================================================
% 5. Positive and negative bridge interlock
%% =========================================================
%
% Reduce each six-device bridge to one active/inactive state.
%
% The result dimensions are:
%
%   sample x 1 x group x output phase

positiveBridgeActive = ...
    any( ...
        Device.positiveBridgeState, ...
        2);

negativeBridgeActive = ...
    any( ...
        Device.negativeBridgeState, ...
        2);

simultaneousBridgeConduction = ...
    positiveBridgeActive ...
    & negativeBridgeActive;

if any(simultaneousBridgeConduction(:))

    error( ...
        'Cyclo:SimultaneousBridgeConduction', ...
        ['Positive and negative converter bridges conduct ', ...
         'simultaneously.']);

end

%% =========================================================
% 6. Count conducting devices in each physical bridge
%% =========================================================
%
% A conducting six-pulse bridge must contain:
%
%   one conducting upper thyristor
%   one conducting lower thyristor
%
% Therefore, exactly two thyristors conduct in the selected
% positive or negative bridge.

positiveDeviceCount = ...
    sum( ...
        Device.positiveBridgeState, ...
        2);

negativeDeviceCount = ...
    sum( ...
        Device.negativeBridgeState, ...
        2);

for outputPhase = 1:3

    positiveCurrentMask = ...
        Device.positivePolarity(:, outputPhase);

    negativeCurrentMask = ...
        Device.negativePolarity(:, outputPhase);

    zeroCurrentMask = ...
        Device.zeroPolarity(:, outputPhase);

    for groupNumber = 1:expectedGroups

        positiveCount = ...
            reshape( ...
                positiveDeviceCount( ...
                    :, ...
                    1, ...
                    groupNumber, ...
                    outputPhase), ...
                expectedSamples, ...
                1);

        negativeCount = ...
            reshape( ...
                negativeDeviceCount( ...
                    :, ...
                    1, ...
                    groupNumber, ...
                    outputPhase), ...
                expectedSamples, ...
                1);

        %% Positive motor current

        if any(positiveCount(positiveCurrentMask) ~= 2)

            error( ...
                'Cyclo:InvalidPositiveBridgeDeviceCount', ...
                ['Exactly two positive-bridge thyristors ', ...
                 'must conduct while motor current is positive.']);

        end

        if any(negativeCount(positiveCurrentMask) ~= 0)

            error( ...
                'Cyclo:NegativeBridgeActiveWithPositiveCurrent', ...
                ['The negative converter bridge must be ', ...
                 'blocked while motor current is positive.']);

        end

        %% Negative motor current

        if any(negativeCount(negativeCurrentMask) ~= 2)

            error( ...
                'Cyclo:InvalidNegativeBridgeDeviceCount', ...
                ['Exactly two negative-bridge thyristors ', ...
                 'must conduct while motor current is negative.']);

        end

        if any(positiveCount(negativeCurrentMask) ~= 0)

            error( ...
                'Cyclo:PositiveBridgeActiveWithNegativeCurrent', ...
                ['The positive converter bridge must be ', ...
                 'blocked while motor current is negative.']);

        end

        %% Zero motor current

        if any(positiveCount(zeroCurrentMask) ~= 0) || ...
                any(negativeCount(zeroCurrentMask) ~= 0)

            error( ...
                'Cyclo:BridgeActiveAtZeroCurrent', ...
                ['Both converter bridges must be blocked ', ...
                 'while motor current is zero.']);

        end

    end

end

%% =========================================================
% 7. Verify one upper and one lower device
%% =========================================================

positiveUpperCount = ...
    sum( ...
        Device.positiveBridgeUpperState, ...
        2);

positiveLowerCount = ...
    sum( ...
        Device.positiveBridgeLowerState, ...
        2);

negativeUpperCount = ...
    sum( ...
        Device.negativeBridgeUpperState, ...
        2);

negativeLowerCount = ...
    sum( ...
        Device.negativeBridgeLowerState, ...
        2);

for outputPhase = 1:3

    positiveCurrentMask = ...
        Device.positivePolarity(:, outputPhase);

    negativeCurrentMask = ...
        Device.negativePolarity(:, outputPhase);

    zeroCurrentMask = ...
        Device.zeroPolarity(:, outputPhase);

    for groupNumber = 1:expectedGroups

        positiveUpper = ...
            reshape( ...
                positiveUpperCount( ...
                    :, 1, groupNumber, outputPhase), ...
                expectedSamples, ...
                1);

        positiveLower = ...
            reshape( ...
                positiveLowerCount( ...
                    :, 1, groupNumber, outputPhase), ...
                expectedSamples, ...
                1);

        negativeUpper = ...
            reshape( ...
                negativeUpperCount( ...
                    :, 1, groupNumber, outputPhase), ...
                expectedSamples, ...
                1);

        negativeLower = ...
            reshape( ...
                negativeLowerCount( ...
                    :, 1, groupNumber, outputPhase), ...
                expectedSamples, ...
                1);

        %% Positive bridge arm selection

        if any(positiveUpper(positiveCurrentMask) ~= 1) || ...
                any(positiveLower(positiveCurrentMask) ~= 1)

            error( ...
                'Cyclo:InvalidPositiveBridgeArmSelection', ...
                ['The positive bridge must select exactly ', ...
                 'one upper and one lower thyristor.']);

        end

        %% Negative bridge arm selection

        if any(negativeUpper(negativeCurrentMask) ~= 1) || ...
                any(negativeLower(negativeCurrentMask) ~= 1)

            error( ...
                'Cyclo:InvalidNegativeBridgeArmSelection', ...
                ['The negative bridge must select exactly ', ...
                 'one upper and one lower thyristor.']);

        end

        %% Inactive bridge checks

        if any(positiveUpper(~positiveCurrentMask) ~= 0) || ...
                any(positiveLower(~positiveCurrentMask) ~= 0)

            error( ...
                'Cyclo:UnexpectedPositiveBridgeArmSelection', ...
                ['The positive bridge arm states must be ', ...
                 'zero when positive motor current is absent.']);

        end

        if any(negativeUpper(~negativeCurrentMask) ~= 0) || ...
                any(negativeLower(~negativeCurrentMask) ~= 0)

            error( ...
                'Cyclo:UnexpectedNegativeBridgeArmSelection', ...
                ['The negative bridge arm states must be ', ...
                 'zero when negative motor current is absent.']);

        end

        %% Explicit zero-current check

        if any(positiveUpper(zeroCurrentMask) ~= 0) || ...
                any(positiveLower(zeroCurrentMask) ~= 0) || ...
                any(negativeUpper(zeroCurrentMask) ~= 0) || ...
                any(negativeLower(zeroCurrentMask) ~= 0)

            error( ...
                'Cyclo:BridgeArmActiveAtZeroCurrent', ...
                ['All upper and lower bridge selections must ', ...
                 'be zero while motor current is zero.']);

        end

    end

end

%% =========================================================
% 8. Thyristor-state and current consistency
%% =========================================================

inactiveCurrent = ...
    Device.thyristorCurrent( ...
        ~Device.thyristorState);

if any(inactiveCurrent ~= 0)

    error( ...
        'Cyclo:InactiveThyristorCurrent', ...
        'A blocked thyristor has nonzero current.');

end

if any(Device.thyristorCurrent(:) < 0)

    error( ...
        'Cyclo:NegativeThyristorMagnitude', ...
        'A thyristor current magnitude cannot be negative.');

end

%% Verify active-device current equals motor-current magnitude

motorCurrent = [ ...
    Current.iu(:), ...
    Current.iv(:), ...
    Current.iw(:)];
if any(~isfinite(motorCurrent(:)))

    error( ...
        'Cyclo:NonFiniteMotorCurrentInput', ...
        ['The input motor-current waveforms contain ', ...
         'non-finite values.']);

end
for outputPhase = 1:3

    expectedMagnitude = ...
        abs(motorCurrent(:, outputPhase));

    for groupNumber = 1:expectedGroups

        activeDeviceCurrentSum = ...
            sum( ...
                Device.thyristorCurrent( ...
                    :, ...
                    :, ...
                    groupNumber, ...
                    outputPhase), ...
                2);

        activeDeviceCurrentSum = ...
            reshape( ...
                activeDeviceCurrentSum, ...
                expectedSamples, ...
                1);

        %% Two thyristors carry the full motor phase current

        expectedDeviceCurrentSum = ...
            2 ...
            * expectedMagnitude;

        currentTolerance = ...
            1e-9 ...
            * max( ...
                1, ...
                max(expectedDeviceCurrentSum));

        if any( ...
                abs( ...
                    activeDeviceCurrentSum ...
                    - expectedDeviceCurrentSum) ...
                > currentTolerance)

            error( ...
                'Cyclo:ActiveThyristorCurrentMismatch', ...
                ['The sum of active thyristor currents must ', ...
                 'equal twice the motor-current magnitude.']);

        end

    end

end

%% =========================================================
% 9. Motor-current and source-state consistency
%% =========================================================

if numel(Current.iu) ~= expectedSamples || ...
        numel(Current.iv) ~= expectedSamples || ...
        numel(Current.iw) ~= expectedSamples

    error( ...
        'Cyclo:DeviceMotorCurrentLengthMismatch', ...
        ['Motor currents and device arrays must have ', ...
         'identical sample counts.']);

end

%% =========================================================
% Phase-specific source-state consistency
%% =========================================================
%
% Required dimensions:
%
%   sample x sourcePhase x converterGroup x outputPhase
%
% sourcePhase:
%   1 = A
%   2 = B
%   3 = C
%
% outputPhase:
%   1 = U
%   2 = V
%   3 = W

if size(State.positive,1) ~= expectedSamples || ...
        size(State.negative,1) ~= expectedSamples || ...
        size(State.positive,2) ~= 3 || ...
        size(State.negative,2) ~= 3 || ...
        size(State.positive,3) ~= expectedGroups || ...
        size(State.negative,3) ~= expectedGroups || ...
        size(State.positive,4) ~= 3 || ...
        size(State.negative,4) ~= 3

    error( ...
        'Cyclo:DeviceSourceStateDimensionMismatch', ...
        ['Source states must have dimensions ', ...
         'samples x 3 x groups x 3 output phases.']);

end

if size(State.positive, 2) ~= 3 || ...
        size(State.negative, 2) ~= 3

    error( ...
        'Cyclo:DeviceSourceStatePhaseMismatch', ...
        'Three converter source phases are required.');

end

if size(State.positive, 3) ~= expectedGroups || ...
        size(State.negative, 3) ~= expectedGroups

    error( ...
        'Cyclo:DeviceSourceStateGroupMismatch', ...
        'Source-state converter-group count is incorrect.');

end

%% =========================================================
% 10. Physical ABB topology count
%% =========================================================

if ~isfield(Device, 'totalPhysicalThyristors') || ...
        ~isfield(Device, 'expectedPhysicalThyristors')

    error( ...
        'Cyclo:MissingPhysicalTopologyMetadata', ...
        ['Physical thyristor-count metadata is missing ', ...
         'from the Device structure.']);

end

if Device.totalPhysicalThyristors ~= ...
        Device.expectedPhysicalThyristors

    error( ...
        'Cyclo:ValidatedThyristorCountMismatch', ...
        ['The modeled physical thyristor count does not ', ...
         'match the ABB converter topology.']);

end

end