function figureFile = ...
    generate_cyclo_simulation_voltages_figure( ...
        DesignData, ...
        Report, ...
        outputFolder)
%GENERATE_CYCLO_SIMULATION_VOLTAGES_FIGURE
% Generate Figure B-2 showing Detailed Simulation motor phase
% voltages and line-to-line voltages.
%
% This function performs no voltage calculation. It plots the
% validated arrays stored in DesignData.DetailedSimulation.

arguments
    DesignData   (1,1) struct
    Report       (1,1) struct
    outputFolder (1,1) string
end

%% =========================================================
% Validate structures
%% =========================================================

if ~isfield(DesignData, 'DetailedSimulation')

    error( ...
        'Cyclo:MissingSimulationForVoltageFigure', ...
        'DesignData.DetailedSimulation is required.');

end

S = ...
    DesignData.DetailedSimulation;

if ~isfield(S, 'Voltage') || ...
        ~isstruct(S.Voltage)

    error( ...
        'Cyclo:MissingSimulationVoltageData', ...
        'DetailedSimulation.Voltage is required.');

end

if ~isfield(Report, 'Figures') || ...
        ~isfield( ...
            Report.Figures, ...
            'SimulationVoltages')

    error( ...
        'Cyclo:MissingSimulationVoltageFigureDefinition', ...
        ['The report model does not contain the simulation ', ...
         'voltage figure definition.']);

end

%% =========================================================
% Validate required fields
%% =========================================================

requiredVoltageFields = { ...
    't', ...
    'motorPhaseU', ...
    'motorPhaseV', ...
    'motorPhaseW', ...
    'lineUV', ...
    'lineVW', ...
    'lineWU'};

for fieldIndex = 1:numel(requiredVoltageFields)

    fieldName = ...
        requiredVoltageFields{fieldIndex};

    if ~isfield(S.Voltage, fieldName)

        error( ...
            'Cyclo:MissingSimulationVoltageField', ...
            'DetailedSimulation.Voltage is missing %s.', ...
            fieldName);

    end

end

%% =========================================================
% Retrieve and normalize vectors
%% =========================================================

timeVector = ...
    double(S.Voltage.t(:));

phaseVoltageU = ...
    double(S.Voltage.motorPhaseU(:));

phaseVoltageV = ...
    double(S.Voltage.motorPhaseV(:));

phaseVoltageW = ...
    double(S.Voltage.motorPhaseW(:));

lineVoltageUV = ...
    double(S.Voltage.lineUV(:));

lineVoltageVW = ...
    double(S.Voltage.lineVW(:));

lineVoltageWU = ...
    double(S.Voltage.lineWU(:));

numberOfSamples = ...
    numel(timeVector);

waveformNames = { ...
    'motorPhaseU', ...
    'motorPhaseV', ...
    'motorPhaseW', ...
    'lineUV', ...
    'lineVW', ...
    'lineWU'};

waveforms = { ...
    phaseVoltageU, ...
    phaseVoltageV, ...
    phaseVoltageW, ...
    lineVoltageUV, ...
    lineVoltageVW, ...
    lineVoltageWU};

for waveformIndex = 1:numel(waveforms)

    waveform = ...
        waveforms{waveformIndex};

    if numel(waveform) ~= numberOfSamples

        error( ...
            'Cyclo:SimulationVoltageLengthMismatch', ...
            ['Waveform %s contains %d samples, but the ', ...
             'time vector contains %d samples.'], ...
            waveformNames{waveformIndex}, ...
            numel(waveform), ...
            numberOfSamples);

    end

    if any(~isfinite(waveform))

        error( ...
            'Cyclo:InvalidSimulationVoltageWaveform', ...
            'Waveform %s contains invalid values.', ...
            waveformNames{waveformIndex});

    end

end

if numberOfSamples < 2 || ...
        any(~isfinite(timeVector)) || ...
        any(diff(timeVector) <= 0)

    error( ...
        'Cyclo:InvalidSimulationVoltageTimeVector', ...
        ['The simulation time vector must contain at least ', ...
         'two finite, strictly increasing samples.']);

end

%% =========================================================
% Select readable display interval
%% =========================================================

displayMask = ...
    selectVoltageDisplayMask( ...
        timeVector, ...
        S);

displayTime = ...
    timeVector(displayMask);

displayPhaseU = ...
    phaseVoltageU(displayMask);

displayPhaseV = ...
    phaseVoltageV(displayMask);

displayPhaseW = ...
    phaseVoltageW(displayMask);

displayLineUV = ...
    lineVoltageUV(displayMask);

displayLineVW = ...
    lineVoltageVW(displayMask);

displayLineWU = ...
    lineVoltageWU(displayMask);

%% =========================================================
% Create output path
%% =========================================================

if ~isfolder(outputFolder)

    mkdir(outputFolder);

end

figureFile = ...
    fullfile( ...
        outputFolder, ...
        string( ...
            Report.Figures. ...
            SimulationVoltages.FileName));

%% =========================================================
% Create figure and tiled layout
%% =========================================================

figureHandle = ...
    figure( ...
        'Visible', ...
        'off', ...
        'Color', ...
        'white', ...
        'Position', ...
        [100, 100, 2400, 1600]);

tileLayout = ...
    tiledlayout( ...
        figureHandle, ...
        2, ...
        1, ...
        'TileSpacing', ...
        'compact', ...
        'Padding', ...
        'compact');

%% =========================================================
% Phase-voltage plot
%% =========================================================

phaseAxes = ...
    nexttile( ...
        tileLayout, ...
        1);

phaseAxes.FontName = ...
    'Arial';

phaseAxes.FontSize = ...
    12;

phaseAxes.LineWidth = ...
    1.0;

hold( ...
    phaseAxes, ...
    'on');

grid( ...
    phaseAxes, ...
    'on');

box( ...
    phaseAxes, ...
    'on');

phaseUHandle = ...
    plot( ...
        phaseAxes, ...
        1000*displayTime, ...
        displayPhaseU, ...
        '-', ...
        'Color', ...
        [0.80, 0.00, 0.00], ...
        'LineWidth', ...
        1.5);

phaseVHandle = ...
    plot( ...
        phaseAxes, ...
        1000*displayTime, ...
        displayPhaseV, ...
        '-', ...
        'Color', ...
        [0.00, 0.50, 0.00], ...
        'LineWidth', ...
        1.5);

phaseWHandle = ...
    plot( ...
        phaseAxes, ...
        1000*displayTime, ...
        displayPhaseW, ...
        '-', ...
        'Color', ...
        [0.00, 0.25, 0.80], ...
        'LineWidth', ...
        1.5);

ylabel( ...
    phaseAxes, ...
    'Phase Voltage [V]');

title( ...
    phaseAxes, ...
    'Motor Phase Voltages', ...
    'FontSize', ...
    14, ...
    'FontWeight', ...
    'bold');

phaseLegend = ...
    legend( ...
        phaseAxes, ...
        [ ...
        phaseUHandle, ...
        phaseVHandle, ...
        phaseWHandle], ...
        { ...
        'u_U', ...
        'u_V', ...
        'u_W'}, ...
        'Location', ...
        'northwest');

phaseLegend.FontSize = ...
    10;

phaseLegend.Box = ...
    'on';

phaseMaximum = ...
    max( ...
        abs( ...
            [ ...
            displayPhaseU
            displayPhaseV
            displayPhaseW]));

if phaseMaximum <= 0

    phaseMaximum = ...
        1;

end

ylim( ...
    phaseAxes, ...
    1.10 ...
    * [-phaseMaximum, phaseMaximum]);

xlim( ...
    phaseAxes, ...
    1000 ...
    * [displayTime(1), displayTime(end)]);

hold( ...
    phaseAxes, ...
    'off');

%% =========================================================
% Line-voltage plot
%% =========================================================

lineAxes = ...
    nexttile( ...
        tileLayout, ...
        2);

lineAxes.FontName = ...
    'Arial';

lineAxes.FontSize = ...
    12;

lineAxes.LineWidth = ...
    1.0;

hold( ...
    lineAxes, ...
    'on');

grid( ...
    lineAxes, ...
    'on');

box( ...
    lineAxes, ...
    'on');

lineUVHandle = ...
    plot( ...
        lineAxes, ...
        1000*displayTime, ...
        displayLineUV, ...
        '-', ...
        'Color', ...
        [0.65, 0.00, 0.00], ...
        'LineWidth', ...
        1.4);

lineVWHandle = ...
    plot( ...
        lineAxes, ...
        1000*displayTime, ...
        displayLineVW, ...
        '-', ...
        'Color', ...
        [0.00, 0.42, 0.00], ...
        'LineWidth', ...
        1.4);

lineWUHandle = ...
    plot( ...
        lineAxes, ...
        1000*displayTime, ...
        displayLineWU, ...
        '-', ...
        'Color', ...
        [0.00, 0.18, 0.70], ...
        'LineWidth', ...
        1.4);

xlabel( ...
    lineAxes, ...
    'Time [ms]');

ylabel( ...
    lineAxes, ...
    'Line Voltage [V]');

title( ...
    lineAxes, ...
    'Motor Line-to-Line Voltages', ...
    'FontSize', ...
    14, ...
    'FontWeight', ...
    'bold');

lineLegend = ...
    legend( ...
        lineAxes, ...
        [ ...
        lineUVHandle, ...
        lineVWHandle, ...
        lineWUHandle], ...
        { ...
        'u_{UV}', ...
        'u_{VW}', ...
        'u_{WU}'}, ...
        'Location', ...
        'northwest');

lineLegend.FontSize = ...
    10;

lineLegend.Box = ...
    'on';

lineMaximum = ...
    max( ...
        abs( ...
            [ ...
            displayLineUV
            displayLineVW
            displayLineWU]));

if lineMaximum <= 0

    lineMaximum = ...
        1;

end

ylim( ...
    lineAxes, ...
    1.10 ...
    * [-lineMaximum, lineMaximum]);

xlim( ...
    lineAxes, ...
    1000 ...
    * [displayTime(1), displayTime(end)]);

hold( ...
    lineAxes, ...
    'off');

%% =========================================================
% Link horizontal axes
%% =========================================================

linkaxes( ...
    [phaseAxes, lineAxes], ...
    'x');

%% =========================================================
% Overall title
%% =========================================================

title( ...
    tileLayout, ...
    string( ...
        Report.Figures. ...
        SimulationVoltages.Title), ...
    'FontName', ...
    'Arial', ...
    'FontSize', ...
    17, ...
    'FontWeight', ...
    'bold', ...
    'Interpreter', ...
    'none');

%% =========================================================
% Model-status annotation
%% =========================================================

if isfield(S.Device, 'outputVoltageModelStatus')

    voltageModelStatus = ...
        string( ...
            S.Device.outputVoltageModelStatus);

else

    voltageModelStatus = ...
        "Status not available";

end

annotationText = { ...
    sprintf( ...
        'Pulse number: %d', ...
        getPulseNumber(DesignData)), ...
    sprintf( ...
        'Voltage model: %s', ...
        char(voltageModelStatus)), ...
    sprintf( ...
        'Display interval: %.2f ms', ...
        1000 ...
        * (displayTime(end) - displayTime(1)))};

text( ...
    phaseAxes, ...
    0.99, ...
    0.97, ...
    annotationText, ...
    'Units', ...
    'normalized', ...
    'HorizontalAlignment', ...
    'right', ...
    'VerticalAlignment', ...
    'top', ...
    'FontName', ...
    'Arial', ...
    'FontSize', ...
    10, ...
    'Interpreter', ...
    'none', ...
    'BackgroundColor', ...
    'white', ...
    'EdgeColor', ...
    [0.60, 0.60, 0.60], ...
    'Margin', ...
    5);

%% =========================================================
% Export
%% =========================================================

exportgraphics( ...
    figureHandle, ...
    figureFile, ...
    'Resolution', ...
    300, ...
    'BackgroundColor', ...
    'white');

close( ...
    figureHandle);

if ~isfile(figureFile)

    error( ...
        'Cyclo:SimulationVoltageFigureExportFailure', ...
        ['The Detailed Simulation voltage figure was not ', ...
         'exported.']);

end

end


function displayMask = ...
    selectVoltageDisplayMask( ...
        timeVector, ...
        S)
%SELECTVOLTAGEDISPLAYMASK
% Select several fundamental periods from the end of the
% simulation record.

displayDuration = ...
    [];

if isfield(S, 'Parameters') && ...
        isfield(S.Parameters, 'f1') && ...
        isnumeric(S.Parameters.f1) && ...
        isscalar(S.Parameters.f1) && ...
        isfinite(S.Parameters.f1) && ...
        S.Parameters.f1 > 0

    displayDuration = ...
        4 ...
        / S.Parameters.f1;

end

fullRecordDuration = ...
    timeVector(end) ...
    - timeVector(1);

if isempty(displayDuration) || ...
        displayDuration >= fullRecordDuration

    displayMask = ...
        true(size(timeVector));

    return

end

displayStartTime = ...
    timeVector(end) ...
    - displayDuration;

displayMask = ...
    timeVector >= displayStartTime;

if sum(displayMask) < 10

    displayMask = ...
        true(size(timeVector));

end

end


function pulseNumber = getPulseNumber(DesignData)
%GETPULSENUMBER Return the selected converter pulse number.

if isfield(DesignData, 'Converter') && ...
        isfield(DesignData.Converter, 'pulseNumber') && ...
        isnumeric(DesignData.Converter.pulseNumber) && ...
        isscalar(DesignData.Converter.pulseNumber) && ...
        isfinite(DesignData.Converter.pulseNumber)

    pulseNumber = ...
        DesignData.Converter.pulseNumber;

else

    pulseNumber = ...
        NaN;

end

end