function figureFile = ...
    generate_cyclo_simulation_motor_currents_figure( ...
        DesignData, ...
        Report, ...
        outputFolder)
%GENERATE_CYCLO_SIMULATION_MOTOR_CURRENTS_FIGURE
% Generate Figure B-1 showing the Detailed Simulation motor
% phase-current waveforms and their reference waveforms.
%
% No current calculation is performed here. The function uses
% the validated arrays stored in DesignData.DetailedSimulation.

arguments
    DesignData   (1,1) struct
    Report       (1,1) struct
    outputFolder (1,1) string
end

%% =========================================================
% Validate top-level structures
%% =========================================================

if ~isfield(DesignData, 'DetailedSimulation')

    error( ...
        'Cyclo:MissingSimulationForCurrentFigure', ...
        'DesignData.DetailedSimulation is required.');

end

S = ...
    DesignData.DetailedSimulation;

if ~isfield(S, 'Voltage') || ...
        ~isstruct(S.Voltage)

    error( ...
        'Cyclo:MissingSimulationVoltageSection', ...
        ['DetailedSimulation.Voltage is required for the ', ...
         'simulation time vector.']);

end

if ~isfield(S, 'Current') || ...
        ~isstruct(S.Current)

    error( ...
        'Cyclo:MissingSimulationCurrentSection', ...
        'DetailedSimulation.Current is required.');

end

if ~isfield(Report, 'Figures') || ...
        ~isfield( ...
            Report.Figures, ...
            'SimulationMotorCurrents')

    error( ...
        'Cyclo:MissingSimulationCurrentFigureDefinition', ...
        ['The report model does not contain the simulation ', ...
         'motor-current figure definition.']);

end

%% =========================================================
% Validate required waveform fields
%% =========================================================

requiredCurrentFields = { ...
    'iu', ...
    'iv', ...
    'iw', ...
    'iuReference', ...
    'ivReference', ...
    'iwReference', ...
    'iuRms', ...
    'ivRms', ...
    'iwRms'};

for fieldIndex = 1:numel(requiredCurrentFields)

    fieldName = ...
        requiredCurrentFields{fieldIndex};

    if ~isfield(S.Current, fieldName)

        error( ...
            'Cyclo:MissingSimulationCurrentField', ...
            'DetailedSimulation.Current is missing %s.', ...
            fieldName);

    end

end

if ~isfield(S.Voltage, 't')

    error( ...
        'Cyclo:MissingSimulationTimeVector', ...
        'DetailedSimulation.Voltage.t is required.');

end

%% =========================================================
% Retrieve and normalize vectors
%% =========================================================

timeVector = ...
    double(S.Voltage.t(:));

currentU = ...
    double(S.Current.iu(:));

currentV = ...
    double(S.Current.iv(:));

currentW = ...
    double(S.Current.iw(:));

referenceU = ...
    double(S.Current.iuReference(:));

referenceV = ...
    double(S.Current.ivReference(:));

referenceW = ...
    double(S.Current.iwReference(:));

numberOfSamples = ...
    numel(timeVector);

waveformNames = { ...
    'iu', ...
    'iv', ...
    'iw', ...
    'iuReference', ...
    'ivReference', ...
    'iwReference'};

waveforms = { ...
    currentU, ...
    currentV, ...
    currentW, ...
    referenceU, ...
    referenceV, ...
    referenceW};

for waveformIndex = 1:numel(waveforms)

    waveform = ...
        waveforms{waveformIndex};

    if numel(waveform) ~= numberOfSamples

        error( ...
            'Cyclo:SimulationCurrentLengthMismatch', ...
            ['Waveform %s contains %d samples, but the ', ...
             'simulation time vector contains %d samples.'], ...
            waveformNames{waveformIndex}, ...
            numel(waveform), ...
            numberOfSamples);

    end

    if any(~isfinite(waveform))

        error( ...
            'Cyclo:InvalidSimulationCurrentWaveform', ...
            'Waveform %s contains invalid values.', ...
            waveformNames{waveformIndex});

    end

end

if numberOfSamples < 2 || ...
        any(~isfinite(timeVector)) || ...
        any(diff(timeVector) <= 0)

    error( ...
        'Cyclo:InvalidSimulationTimeVector', ...
        ['The simulation time vector must contain at least ', ...
         'two finite, strictly increasing samples.']);

end

%% =========================================================
% Select a readable display interval
%% =========================================================

displayMask = ...
    selectDisplayMask( ...
        timeVector, ...
        S);

displayTime = ...
    timeVector(displayMask);

displayCurrentU = ...
    currentU(displayMask);

displayCurrentV = ...
    currentV(displayMask);

displayCurrentW = ...
    currentW(displayMask);

displayReferenceU = ...
    referenceU(displayMask);

displayReferenceV = ...
    referenceV(displayMask);

displayReferenceW = ...
    referenceW(displayMask);

%% =========================================================
% Create output folder and file path
%% =========================================================

if ~isfolder(outputFolder)

    mkdir(outputFolder);

end

figureFile = ...
    fullfile( ...
        outputFolder, ...
        string( ...
            Report.Figures. ...
            SimulationMotorCurrents.FileName));

%% =========================================================
% Create figure
%% =========================================================

figureHandle = ...
    figure( ...
        'Visible', ...
        'off', ...
        'Color', ...
        'white', ...
        'Position', ...
        [100, 100, 2400, 1500]);

axesHandle = ...
    axes( ...
        figureHandle, ...
        'Position', ...
        [0.08, 0.12, 0.76, 0.78]);

axesHandle.FontName = ...
    'Arial';

axesHandle.FontSize = ...
    13;

axesHandle.LineWidth = ...
    1.0;

hold( ...
    axesHandle, ...
    'on');

grid( ...
    axesHandle, ...
    'on');

box( ...
    axesHandle, ...
    'on');

%% =========================================================
% Plot reference waveforms
%% =========================================================

referenceUHandle = ...
    plot( ...
        axesHandle, ...
        1000*displayTime, ...
        displayReferenceU, ...
        '--', ...
        'Color', ...
        [0.75, 0.20, 0.20], ...
        'LineWidth', ...
        1.2);

referenceVHandle = ...
    plot( ...
        axesHandle, ...
        1000*displayTime, ...
        displayReferenceV, ...
        '--', ...
        'Color', ...
        [0.20, 0.55, 0.20], ...
        'LineWidth', ...
        1.2);

referenceWHandle = ...
    plot( ...
        axesHandle, ...
        1000*displayTime, ...
        displayReferenceW, ...
        '--', ...
        'Color', ...
        [0.25, 0.35, 0.75], ...
        'LineWidth', ...
        1.2);

%% =========================================================
% Plot reconstructed motor currents
%% =========================================================

currentUHandle = ...
    plot( ...
        axesHandle, ...
        1000*displayTime, ...
        displayCurrentU, ...
        '-', ...
        'Color', ...
        [0.80, 0.00, 0.00], ...
        'LineWidth', ...
        2.0);

currentVHandle = ...
    plot( ...
        axesHandle, ...
        1000*displayTime, ...
        displayCurrentV, ...
        '-', ...
        'Color', ...
        [0.00, 0.50, 0.00], ...
        'LineWidth', ...
        2.0);

currentWHandle = ...
    plot( ...
        axesHandle, ...
        1000*displayTime, ...
        displayCurrentW, ...
        '-', ...
        'Color', ...
        [0.00, 0.25, 0.80], ...
        'LineWidth', ...
        2.0);

%% =========================================================
% Axes and title
%% =========================================================

xlabel( ...
    axesHandle, ...
    'Time [ms]');

ylabel( ...
    axesHandle, ...
    'Motor Phase Current [A]');

title( ...
    axesHandle, ...
    string( ...
        Report.Figures. ...
        SimulationMotorCurrents.Title), ...
    'Interpreter', ...
    'none');

axesHandle.Title.FontSize = ...
    16;

axesHandle.Title.FontWeight = ...
    'bold';

legendHandle = ...
    legend( ...
        axesHandle, ...
        [ ...
        currentUHandle, ...
        currentVHandle, ...
        currentWHandle, ...
        referenceUHandle, ...
        referenceVHandle, ...
        referenceWHandle], ...
        { ...
        'i_u reconstructed', ...
        'i_v reconstructed', ...
        'i_w reconstructed', ...
        'i_u reference', ...
        'i_v reference', ...
        'i_w reference'}, ...
        'Location', ...
        'northwest');

legendHandle.FontSize = ...
    10;

legendHandle.Box = ...
    'on';

%% =========================================================
% Axis limits
%% =========================================================

allDisplayedCurrents = [ ...
    displayCurrentU
    displayCurrentV
    displayCurrentW
    displayReferenceU
    displayReferenceV
    displayReferenceW];

maximumAbsoluteCurrent = ...
    max(abs(allDisplayedCurrents));

if maximumAbsoluteCurrent <= 0

    maximumAbsoluteCurrent = ...
        1;

end

ylim( ...
    axesHandle, ...
    1.12 ...
    * [-maximumAbsoluteCurrent, maximumAbsoluteCurrent]);

xlim( ...
    axesHandle, ...
    1000 ...
    * [displayTime(1), displayTime(end)]);

%% =========================================================
% RMS and validation annotation
%% =========================================================

annotationText = { ...
    sprintf( ...
        'Iu RMS = %.3f A', ...
        S.Current.iuRms), ...
    sprintf( ...
        'Iv RMS = %.3f A', ...
        S.Current.ivRms), ...
    sprintf( ...
        'Iw RMS = %.3f A', ...
        S.Current.iwRms), ...
    sprintf( ...
        'Topology: %s', ...
        char(string(S.PhysicalTopologyStatus)))};

text( ...
    axesHandle, ...
    0.99, ...
    0.97, ...
    annotationText, ...
    'Units', ...
    'normalized', ...
    'HorizontalAlignment', ...
    'right', ...
    'VerticalAlignment', ...
    'top', ...
    'FontName', ...
    'Arial', ...
    'FontSize', ...
    11, ...
    'Interpreter', ...
    'none', ...
    'BackgroundColor', ...
    'white', ...
    'EdgeColor', ...
    [0.60, 0.60, 0.60], ...
    'Margin', ...
    6);

hold( ...
    axesHandle, ...
    'off');

%% =========================================================
% Export
%% =========================================================

exportgraphics( ...
    figureHandle, ...
    figureFile, ...
    'Resolution', ...
    300, ...
    'BackgroundColor', ...
    'white');

close( ...
    figureHandle);

if ~isfile(figureFile)

    error( ...
        'Cyclo:SimulationMotorCurrentFigureExportFailure', ...
        ['The Detailed Simulation motor-current figure ', ...
         'was not exported.']);

end

end


function displayMask = selectDisplayMask(timeVector, S)
%SELECTDISPLAYMASK
% Select several fundamental periods from the end of the
% simulation record to keep switching detail readable.

displayDuration = ...
    [];

if isfield(S, 'Parameters') && ...
        isfield(S.Parameters, 'f1') && ...
        isnumeric(S.Parameters.f1) && ...
        isscalar(S.Parameters.f1) && ...
        isfinite(S.Parameters.f1) && ...
        S.Parameters.f1 > 0

    fundamentalFrequency = ...
        S.Parameters.f1;

    displayDuration = ...
        4 ...
        / fundamentalFrequency;

end

if isempty(displayDuration) || ...
        displayDuration >= ...
        (timeVector(end) - timeVector(1))

    displayMask = ...
        true(size(timeVector));

    return

end

displayStartTime = ...
    timeVector(end) ...
    - displayDuration;

displayMask = ...
    timeVector >= displayStartTime;

if sum(displayMask) < 10

    displayMask = ...
        true(size(timeVector));

end

end