function figureFile = ...
    generate_cyclo_representative_fft_figure( ...
        DesignData, ...
        Report, ...
        outputFolder, ...
        groupToDisplay)
%GENERATE_CYCLO_REPRESENTATIVE_FFT_FIGURE
% Generate the ABB/Scilab representative source-current FFT
% for one converter transformer secondary group.
%
% This spectrum is an individual representative secondary-group
% diagnostic. It is not the combined transformer-primary
% current spectrum.
%
% Inputs:
%   DesignData     Consolidated CycloTool Design Data structure
%   Report         Design report model
%   outputFolder   Folder for the exported PNG
%   groupToDisplay Converter group number, default 1
%
% Output:
%   figureFile     Full path of the exported PNG

arguments
    DesignData     (1,1) struct
    Report         (1,1) struct
    outputFolder   (1,1) string
    groupToDisplay (1,1) double = 1
end

%% =========================================================
% Required-data validation
%% =========================================================

if ~isfield(DesignData, 'DetailedSimulation')

    error( ...
        'Cyclo:MissingDetailedSimulationForFftFigure', ...
        'DesignData.DetailedSimulation is required.');

end

if ~isfield( ...
        DesignData.DetailedSimulation, ...
        'Harmonics')

    error( ...
        'Cyclo:MissingDetailedHarmonicsForFftFigure', ...
        ['DesignData.DetailedSimulation.Harmonics ', ...
         'is required.']);

end

if ~isfield(Report, 'Figures') || ...
        ~isfield( ...
            Report.Figures, ...
            'DetailedFft')

    error( ...
        'Cyclo:MissingDetailedFftFigureDefinition', ...
        ['The report model does not contain the Detailed FFT ', ...
         'figure definition.']);

end

DetailedHarmonics = ...
    DesignData.DetailedSimulation.Harmonics;

if ~isfield(DetailedHarmonics, 'Group') || ...
        isempty(DetailedHarmonics.Group)

    error( ...
        'Cyclo:MissingDetailedFftGroupData', ...
        'The Detailed Simulation contains no FFT group data.');

end

numberOfGroups = ...
    numel(DetailedHarmonics.Group);

if ~isfinite(groupToDisplay) || ...
        groupToDisplay < 1 || ...
        groupToDisplay > numberOfGroups || ...
        groupToDisplay ~= round(groupToDisplay)

    error( ...
        'Cyclo:InvalidDetailedFftGroup', ...
        ['The selected FFT group must be an integer between ', ...
         '1 and %d.'], ...
        numberOfGroups);

end

G = ...
    DetailedHarmonics.Group(groupToDisplay);

requiredGroupFields = { ...
    'frequency', ...
    'magnitudeA', ...
    'harmonicOrders', ...
    'amplitudeA', ...
    'percentA', ...
    'peakFrequencyA', ...
    'rmsA'};

for fieldIndex = 1:numel(requiredGroupFields)

    fieldName = ...
        requiredGroupFields{fieldIndex};

    if ~isfield(G, fieldName)

        error( ...
            'Cyclo:MissingDetailedFftField', ...
            'Detailed FFT group data is missing field %s.', ...
            fieldName);

    end

    if isnumeric(G.(fieldName)) && ...
            any(~isfinite(G.(fieldName)(:)))

        error( ...
            'Cyclo:InvalidDetailedFftField', ...
            'Detailed FFT field %s contains invalid values.', ...
            fieldName);

    end

end

if numel(G.frequency) ~= numel(G.magnitudeA)

    error( ...
        'Cyclo:DetailedFftLengthMismatch', ...
        ['The Detailed FFT frequency and magnitude vectors ', ...
         'must have identical lengths.']);

end

if numel(G.harmonicOrders) ~= numel(G.amplitudeA) || ...
        numel(G.harmonicOrders) ~= numel(G.percentA) || ...
        numel(G.harmonicOrders) ~= numel(G.peakFrequencyA)

    error( ...
        'Cyclo:DetailedFftCharacteristicLengthMismatch', ...
        ['The characteristic harmonic result vectors must ', ...
         'have identical lengths.']);

end

if any(G.frequency(:) < 0) || ...
        any(G.magnitudeA(:) < 0) || ...
        any(G.amplitudeA(:) < 0)

    error( ...
        'Cyclo:NegativeDetailedFftValue', ...
        'FFT frequencies and magnitudes must be non-negative.');

end

%% =========================================================
% Initialize output path
%% =========================================================

if ~isfolder(outputFolder)

    mkdir(outputFolder);

end

figureFile = ...
    fullfile( ...
        outputFolder, ...
        string( ...
            Report.Figures. ...
            DetailedFft.FileName));

%% =========================================================
% Select display range
%% =========================================================

if isfield(DesignData.DetailedSimulation, 'Parameters') && ...
        isfield( ...
            DesignData.DetailedSimulation.Parameters, ...
            'f1')

    supplyFrequency = ...
        DesignData.DetailedSimulation.Parameters.f1;

else

    supplyFrequency = ...
        DesignData.Supply.frequencyHz;

end

maximumDisplayFrequency = ...
    50 ...
    * supplyFrequency;

displayMask = ...
    G.frequency <= maximumDisplayFrequency;

if ~any(displayMask)

    error( ...
        'Cyclo:EmptyDetailedFftDisplayRange', ...
        ['No FFT values are available within the selected ', ...
         'display-frequency range.']);

end

displayFrequency = ...
    G.frequency(displayMask);

displayMagnitude = ...
    G.magnitudeA(displayMask);

characteristicMask = ...
    G.peakFrequencyA <= maximumDisplayFrequency;

%% =========================================================
% Create figure
%% =========================================================

figureHandle = ...
    figure( ...
        'Visible', ...
        'off', ...
        'Color', ...
        'white', ...
        'Position', ...
        [100, 100, 1400, 800]);

axesHandle = ...
    axes( ...
        figureHandle, ...
        'Position', ...
        [0.08, 0.12, 0.76, 0.79]);

axesHandle.FontName = ...
    'Arial';

axesHandle.FontSize = ...
    11;

axesHandle.LineWidth = ...
    1.0;

axesHandle.Color = ...
    'white';

hold( ...
    axesHandle, ...
    'on');

grid( ...
    axesHandle, ...
    'on');

box( ...
    axesHandle, ...
    'on');

%% =========================================================
% Complete representative-group spectrum
%% =========================================================

spectrumHandle = ...
    stem( ...
        axesHandle, ...
        displayFrequency, ...
        displayMagnitude, ...
        'Marker', ...
        'none', ...
        'LineWidth', ...
        0.8, ...
        'Color', ...
        [0.00, 0.45, 0.74]);

%% =========================================================
% Characteristic window maxima
%% =========================================================

characteristicHandle = ...
    stem( ...
        axesHandle, ...
        G.peakFrequencyA(characteristicMask), ...
        G.amplitudeA(characteristicMask), ...
        'r', ...
        'filled', ...
        'LineWidth', ...
        1.3);

characteristicHandle.MarkerSize = ...
    5;

%% =========================================================
% Axes formatting
%% =========================================================

xlabel( ...
    axesHandle, ...
    'Frequency [Hz]');

ylabel( ...
    axesHandle, ...
    'Peak Current [A]');

titleText = ...
    sprintf( ...
        '%s, Group %d, Phase A', ...
        char( ...
            Report.Figures. ...
            DetailedFft.Title), ...
        groupToDisplay);

title( ...
    axesHandle, ...
    titleText, ...
    'Interpreter', ...
    'none');

axesHandle.Title.FontWeight = ...
    'bold';

axesHandle.Title.FontSize = ...
    14;

legend( ...
    axesHandle, ...
    [ ...
    spectrumHandle, ...
    characteristicHandle], ...
    { ...
    'Representative secondary-group spectrum', ...
    'Characteristic window maxima'}, ...
    'Location', ...
    'northeast');

xlim( ...
    axesHandle, ...
    [0, maximumDisplayFrequency]);

maximumMagnitude = ...
    max( ...
        [ ...
        displayMagnitude(:)
        G.amplitudeA(characteristicMask)]);

if maximumMagnitude <= 0

    maximumMagnitude = ...
        1;

end

ylim( ...
    axesHandle, ...
    [0, 1.20*maximumMagnitude]);

%% =========================================================
% Characteristic-order labels
%% =========================================================

labelOffset = ...
    0.018 ...
    * maximumMagnitude;

characteristicIndices = ...
    find(characteristicMask);

for resultIndex = 1:numel(characteristicIndices)

    harmonicIndex = ...
        characteristicIndices(resultIndex);

    frequencyValue = ...
        G.peakFrequencyA(harmonicIndex);

    amplitudeValue = ...
        G.amplitudeA(harmonicIndex);

    harmonicOrder = ...
        G.harmonicOrders(harmonicIndex);

    text( ...
        axesHandle, ...
        frequencyValue, ...
        amplitudeValue + labelOffset, ...
        sprintf( ...
            'h%d', ...
            harmonicOrder), ...
        'HorizontalAlignment', ...
        'center', ...
        'VerticalAlignment', ...
        'bottom', ...
        'Color', ...
        'r', ...
        'FontSize', ...
        8, ...
        'FontWeight', ...
        'bold', ...
        'Interpreter', ...
        'none');

end

%% =========================================================
% Model-boundary annotation
%% =========================================================

modelBoundaryText = { ...
    sprintf( ...
        'Phase-A RMS: %.1f A', ...
        G.rmsA), ...
    sprintf( ...
        'Group: %d of %d', ...
        groupToDisplay, ...
        numberOfGroups), ...
    'Representative secondary group', ...
    'Not transformer-primary spectrum'};

text( ...
    axesHandle, ...
    0.99, ...
    0.5, ...
    modelBoundaryText, ...
    'Units', ...
    'normalized', ...
    'HorizontalAlignment', ...
    'right', ...
    'VerticalAlignment', ...
    'bottom', ...
    'Interpreter', ...
    'none', ...
    'FontSize', ...
    9, ...
    'BackgroundColor', ...
    'white', ...
    'EdgeColor', ...
    [0.60, 0.60, 0.60], ...
    'Margin', ...
    5);

%% =========================================================
% Fundamental-window annotation
%% =========================================================

fundamentalIndex = ...
    find( ...
        G.harmonicOrders == 1, ...
        1);

if ~isempty(fundamentalIndex)

    fundamentalText = ...
        sprintf( ...
            ['Fundamental-window maximum:\n', ...
             '%.1f A peak at %.1f Hz'], ...
            G.amplitudeA(fundamentalIndex), ...
            G.peakFrequencyA(fundamentalIndex));

    text( ...
    axesHandle, ...
    0.99, ...
    0.24, ...
    fundamentalText, ...
    'Units', ...
    'normalized', ...
    'HorizontalAlignment', ...
    'right', ...
    'VerticalAlignment', ...
    'bottom', ...
    'Interpreter', ...
    'none', ...
    'FontSize', ...
    9, ...
    'BackgroundColor', ...
    'white', ...
    'EdgeColor', ...
    [0.75, 0.75, 0.75], ...
    'Margin', ...
    5);

end

hold( ...
    axesHandle, ...
    'off');

%% =========================================================
% Export PNG
%% =========================================================

exportgraphics( ...
    figureHandle, ...
    figureFile, ...
    'Resolution', ...
    300, ...
    'BackgroundColor', ...
    'white');

close( ...
    figureHandle);

if ~isfile(figureFile)

    error( ...
        'Cyclo:RepresentativeFftFigureExportFailure', ...
        'The representative-group FFT figure was not exported.');

end

end