function figureFile = ...
    generate_cyclo_analytical_harmonics_figure( ...
        DesignData, ...
        Report, ...
        outputFolder)
%GENERATE_CYCLO_ANALYTICAL_HARMONICS_FIGURE
% Generate the analytical multi-pulse current-harmonic spectrum
% for the CycloTool Design Data document.
%
% The figure uses the analytical VBA-derived dimensioning model:
%
%   H.HOrder  Harmonic order
%   H.KI      Harmonic current in percent
%   H.IL      Harmonic current in A RMS
%   H.KU      Harmonic voltage in percent
%
% This figure is separate from the Detailed Simulation
% representative secondary-group FFT.

arguments
    DesignData   (1,1) struct
    Report       (1,1) struct
    outputFolder (1,1) string
end

%% =========================================================
% Required-data validation
%% =========================================================

if ~isfield(DesignData, 'Harmonics')

    error( ...
        'Cyclo:MissingAnalyticalHarmonicsForFigure', ...
        'DesignData.Harmonics is required.');

end

if ~isfield(Report, 'Figures') || ...
        ~isfield( ...
            Report.Figures, ...
            'AnalyticalHarmonics')

    error( ...
        'Cyclo:MissingAnalyticalHarmonicFigureDefinition', ...
        ['The report model does not contain the analytical ', ...
         'harmonic figure definition.']);

end

H = ...
    DesignData.Harmonics;

requiredFields = { ...
    'HOrder', ...
    'KI', ...
    'IL', ...
    'KU', ...
    'ku25', ...
    'kuTot', ...
    'THDi'};

for fieldIndex = 1:numel(requiredFields)

    fieldName = ...
        requiredFields{fieldIndex};

    if ~isfield(H, fieldName)

        error( ...
            'Cyclo:MissingAnalyticalHarmonicFigureField', ...
            'Analytical harmonic data is missing field %s.', ...
            fieldName);

    end

    if any( ...
            ~isfinite( ...
                H.(fieldName)(:)))

        error( ...
            'Cyclo:InvalidAnalyticalHarmonicFigureField', ...
            ['Analytical harmonic field %s contains ', ...
             'invalid values.'], ...
            fieldName);

    end

end

numberOfHarmonics = ...
    numel(H.HOrder);

if numberOfHarmonics < 1

    error( ...
        'Cyclo:EmptyAnalyticalHarmonicSpectrum', ...
        'The analytical harmonic spectrum is empty.');

end

if numel(H.KI) ~= numberOfHarmonics || ...
        numel(H.IL) ~= numberOfHarmonics || ...
        numel(H.KU) ~= numberOfHarmonics

    error( ...
        'Cyclo:AnalyticalHarmonicLengthMismatch', ...
        ['The analytical harmonic vectors must have ', ...
         'identical lengths.']);

end

if any(H.HOrder(:) <= 0)

    error( ...
        'Cyclo:InvalidAnalyticalHarmonicOrder', ...
        'All analytical harmonic orders must be positive.');

end

if any(H.IL(:) < 0) || ...
        any(H.KI(:) < 0) || ...
        any(H.KU(:) < 0)

    error( ...
        'Cyclo:NegativeAnalyticalHarmonicResult', ...
        ['Analytical harmonic magnitudes must be ', ...
         'non-negative.']);

end

%% =========================================================
% Initialize output path
%% =========================================================

if ~isfolder(outputFolder)

    mkdir(outputFolder);

end

figureFile = ...
    fullfile( ...
        outputFolder, ...
        string( ...
            Report.Figures. ...
            AnalyticalHarmonics.FileName));

%% =========================================================
% Create figure
%% =========================================================

figureHandle = ...
    figure( ...
        'Visible', ...
        'off', ...
        'Color', ...
        'white', ...
        'Position', ...
        [100, 100, 1400, 800]);

axesHandle = ...
    axes( ...
        figureHandle, ...
        'Position', ...
        [0.08, 0.12, 0.76, 0.79]);

axesHandle.FontName = ...
    'Arial';

axesHandle.FontSize = ...
    11;

axesHandle.LineWidth = ...
    1.0;

axesHandle.Color = ...
    'white';

grid( ...
    axesHandle, ...
    'on');

box( ...
    axesHandle, ...
    'on');

hold( ...
    axesHandle, ...
    'on');

%% =========================================================
% Harmonic-current bar chart
%% =========================================================

barHandle = ...
    bar( ...
        axesHandle, ...
        H.HOrder, ...
        H.IL, ...
        0.72);

barHandle.FaceColor = ...
    [0.00, 0.45, 0.74];

barHandle.EdgeColor = ...
    [0.00, 0.25, 0.45];

barHandle.LineWidth = ...
    0.8;

%% =========================================================
% Axis formatting
%% =========================================================

xlabel( ...
    axesHandle, ...
    'Harmonic Order');

ylabel( ...
    axesHandle, ...
    'Harmonic Current [A RMS]');

title( ...
    axesHandle, ...
    string( ...
        Report.Figures. ...
        AnalyticalHarmonics.Title));

axesHandle.Title.FontWeight = ...
    'bold';

axesHandle.Title.FontSize = ...
    14;

xticks( ...
    axesHandle, ...
    H.HOrder);

xticklabels( ...
    axesHandle, ...
    string(H.HOrder));

xtickangle( ...
    axesHandle, ...
    0);

minimumOrder = ...
    min(H.HOrder);

maximumOrder = ...
    max(H.HOrder);

orderRange = ...
    maximumOrder ...
    - minimumOrder;

if orderRange <= 0

    orderRange = ...
        1;

end

xlim( ...
    axesHandle, ...
    [ ...
    minimumOrder - 0.7, ...
    maximumOrder + 3.5 ...
    ]);

maximumCurrent = ...
    max(H.IL);

if maximumCurrent <= 0

    maximumCurrent = ...
        1;

end

ylim( ...
    axesHandle, ...
    [0, 1.22*maximumCurrent]);

%% =========================================================
% Harmonic value labels
%% =========================================================

labelOffset = ...
    0.018 ...
    * maximumCurrent;

for harmonicIndex = 1:numberOfHarmonics

    labelText = ...
        sprintf( ...
            '%.1f A\n%.1f%%', ...
            H.IL(harmonicIndex), ...
            H.KI(harmonicIndex));

    text( ...
        axesHandle, ...
        H.HOrder(harmonicIndex), ...
        H.IL(harmonicIndex) + labelOffset, ...
        labelText, ...
        'HorizontalAlignment', ...
        'center', ...
        'VerticalAlignment', ...
        'bottom', ...
        'FontSize', ...
        8, ...
        'Color', ...
        [0.10, 0.10, 0.10], ...
        'Interpreter', ...
        'none');

end

%% =========================================================
% Summary annotation
%% =========================================================

summaryText = { ...
    sprintf( ...
        'Current THD = %.2f %%', ...
        H.THDi), ...
    sprintf( ...
        'Voltage distortion to 25th = %.2f %%', ...
        H.ku25), ...
    sprintf( ...
        'Total voltage distortion = %.2f %%', ...
        H.kuTot)};

text( ...
    axesHandle, ...
    0.99, ...
    0.97, ...
    summaryText, ...
    'Units', ...
    'normalized', ...
    'HorizontalAlignment', ...
    'right', ...
    'VerticalAlignment', ...
    'top', ...
    'Interpreter', ...
    'none', ...
    'BackgroundColor', ...
    'white', ...
    'EdgeColor', ...
    [0.60, 0.60, 0.60], ...
    'Margin', ...
    6);

%% =========================================================
% Model annotation
%% =========================================================

pulseNumber = ...
    getPulseNumber(DesignData);

modelText = { ...
    sprintf( ...
        'Pulse number: %d', ...
        pulseNumber), ...
    'Analytical multi-pulse dimensioning model'};

text( ...
    axesHandle, ...
    0.99, ...
    0.73, ...
    modelText, ...
    'Units', ...
    'normalized', ...
    'HorizontalAlignment', ...
    'right', ...
    'VerticalAlignment', ...
    'top', ...
    'Interpreter', ...
    'none', ...
    'BackgroundColor', ...
    'white', ...
    'EdgeColor', ...
    [0.75, 0.75, 0.75], ...
    'Margin', ...
    6);

hold( ...
    axesHandle, ...
    'off');

%% =========================================================
% Export PNG
%% =========================================================

exportgraphics( ...
    figureHandle, ...
    figureFile, ...
    'Resolution', ...
    300, ...
    'BackgroundColor', ...
    'white');

close( ...
    figureHandle);

if ~isfile(figureFile)

    error( ...
        'Cyclo:AnalyticalHarmonicFigureExportFailure', ...
        'The analytical harmonic figure was not exported.');

end

end


function pulseNumber = getPulseNumber(DesignData)

if isfield(DesignData, 'Converter') && ...
        isfield(DesignData.Converter, 'pulseNumber') && ...
        ~isempty(DesignData.Converter.pulseNumber)

    pulseNumber = ...
        DesignData.Converter.pulseNumber;

elseif isfield(DesignData, 'Input') && ...
        isfield(DesignData.Input, 'PulseNumber') && ...
        ~isempty(DesignData.Input.PulseNumber)

    pulseNumber = ...
        DesignData.Input.PulseNumber;

else

    pulseNumber = ...
        NaN;

end

end