function figureFile = ...
    generate_cyclo_simulation_switching_figure( ...
        DesignData, ...
        Report, ...
        outputFolder)
%GENERATE_CYCLO_SIMULATION_SWITCHING_FIGURE
% Generate Figure B-3 showing the Detailed Simulation
% polarity selection, representative physical-device states,
% and representative thyristor switching states.
%
% The function performs no switching calculation. It plots
% the validated logical arrays in DetailedSimulation.Device.

arguments
    DesignData   (1,1) struct
    Report       (1,1) struct
    outputFolder (1,1) string
end

%% =========================================================
% Validate main structures
%% =========================================================

if ~isfield(DesignData, 'DetailedSimulation')

    error( ...
        'Cyclo:MissingSimulationForSwitchingFigure', ...
        'DesignData.DetailedSimulation is required.');

end

S = ...
    DesignData.DetailedSimulation;

if ~isfield(S, 'Voltage') || ...
        ~isstruct(S.Voltage) || ...
        ~isfield(S.Voltage, 't')

    error( ...
        'Cyclo:MissingSwitchingTimeVector', ...
        'DetailedSimulation.Voltage.t is required.');

end

if ~isfield(S, 'Device') || ...
        ~isstruct(S.Device)

    error( ...
        'Cyclo:MissingSwitchingDeviceData', ...
        'DetailedSimulation.Device is required.');

end

if ~isfield(Report, 'Figures') || ...
        ~isfield( ...
            Report.Figures, ...
            'SimulationSwitching')

    error( ...
        'Cyclo:MissingSwitchingFigureDefinition', ...
        ['The report model does not contain the simulation ', ...
         'switching figure definition.']);

end

%% =========================================================
% Validate required device-state fields
%% =========================================================

requiredDeviceFields = { ...
    'positivePolarity', ...
    'negativePolarity', ...
    'zeroPolarity', ...
    'thyristorState', ...
    'staT111', ...
    'staT211'};

for fieldIndex = 1:numel(requiredDeviceFields)

    fieldName = ...
        requiredDeviceFields{fieldIndex};

    if ~isfield(S.Device, fieldName)

        error( ...
            'Cyclo:MissingSwitchingDeviceField', ...
            'DetailedSimulation.Device is missing %s.', ...
            fieldName);

    end

end

%% =========================================================
% Retrieve time and state arrays
%% =========================================================

timeVector = ...
    double(S.Voltage.t(:));

positivePolarity = ...
    logical(S.Device.positivePolarity);

negativePolarity = ...
    logical(S.Device.negativePolarity);

zeroPolarity = ...
    logical(S.Device.zeroPolarity);

thyristorState = ...
    logical(S.Device.thyristorState);

stateT111 = ...
    logical(S.Device.staT111(:));

stateT211 = ...
    logical(S.Device.staT211(:));

numberOfSamples = ...
    numel(timeVector);

%% =========================================================
% Validate time vector
%% =========================================================

if numberOfSamples < 2 || ...
        any(~isfinite(timeVector)) || ...
        any(diff(timeVector) <= 0)

    error( ...
        'Cyclo:InvalidSwitchingTimeVector', ...
        ['The switching time vector must contain at least ', ...
         'two finite, strictly increasing samples.']);

end

%% =========================================================
% Validate polarity-array dimensions
%% =========================================================

expectedPolaritySize = ...
    [numberOfSamples, 3];

if ~isequal( ...
        size(positivePolarity), ...
        expectedPolaritySize)

    error( ...
        'Cyclo:PositivePolaritySizeMismatch', ...
        ['positivePolarity must have dimensions ', ...
         '%d x 3.'], ...
        numberOfSamples);

end

if ~isequal( ...
        size(negativePolarity), ...
        expectedPolaritySize)

    error( ...
        'Cyclo:NegativePolaritySizeMismatch', ...
        ['negativePolarity must have dimensions ', ...
         '%d x 3.'], ...
        numberOfSamples);

end

if ~isequal( ...
        size(zeroPolarity), ...
        expectedPolaritySize)

    error( ...
        'Cyclo:ZeroPolaritySizeMismatch', ...
        ['zeroPolarity must have dimensions ', ...
         '%d x 3.'], ...
        numberOfSamples);

end

%% =========================================================
% Validate thyristor-state dimensions
%% =========================================================

thyristorStateSize = ...
    size(thyristorState);

if numel(thyristorStateSize) < 4

    thyristorStateSize(4) = ...
        1;

end

if thyristorStateSize(1) ~= numberOfSamples || ...
        thyristorStateSize(2) ~= 12 || ...
        thyristorStateSize(3) < 1 || ...
        thyristorStateSize(4) ~= 3

    error( ...
        'Cyclo:ThyristorStateSizeMismatch', ...
        ['thyristorState must have dimensions ', ...
         'time x 12 x groups x 3 output phases.']);

end

if numel(stateT111) ~= numberOfSamples || ...
        numel(stateT211) ~= numberOfSamples

    error( ...
        'Cyclo:RepresentativeThyristorStateLengthMismatch', ...
        ['staT111 and staT211 must match the simulation ', ...
         'time-vector length.']);

end

%% =========================================================
% Select representative group and output phase
%% =========================================================
%
% Group 1 and motor phase U are displayed. The full state
% array remains available in the report traceability package.

groupToDisplay = ...
    1;

outputPhaseToDisplay = ...
    1;

representativeDeviceState = ...
    squeeze( ...
        thyristorState( ...
            :, ...
            :, ...
            groupToDisplay, ...
            outputPhaseToDisplay));

if ~isequal( ...
        size(representativeDeviceState), ...
        [numberOfSamples, 12])

    error( ...
        'Cyclo:RepresentativeDeviceStateSizeMismatch', ...
        ['The selected representative device-state array ', ...
         'does not have dimensions time x 12.']);

end

%% =========================================================
% Select a readable switching interval
%% =========================================================

displayMask = ...
    selectSwitchingDisplayMask( ...
        timeVector, ...
        S);

displayTimeMilliseconds = ...
    1000 ...
    * timeVector(displayMask);

displayPositivePolarity = ...
    positivePolarity(displayMask,:);

displayNegativePolarity = ...
    negativePolarity(displayMask,:);

displayZeroPolarity = ...
    zeroPolarity(displayMask,:);

displayDeviceState = ...
    representativeDeviceState(displayMask,:);

displayT111 = ...
    stateT111(displayMask);

displayT211 = ...
    stateT211(displayMask);

%% =========================================================
% Create output path
%% =========================================================

if ~isfolder(outputFolder)

    mkdir(outputFolder);

end

figureFile = ...
    fullfile( ...
        outputFolder, ...
        string( ...
            Report.Figures. ...
            SimulationSwitching.FileName));

%% =========================================================
% Create figure
%% =========================================================

figureHandle = ...
    figure( ...
        'Visible', ...
        'off', ...
        'Color', ...
        'white', ...
        'Position', ...
        [100, 100, 2400, 1750]);

tileLayout = ...
    tiledlayout( ...
        figureHandle, ...
        3, ...
        1, ...
        'TileSpacing', ...
        'compact', ...
        'Padding', ...
        'compact');

%% =========================================================
% Plot 1: Output-phase polarity selection
%% =========================================================

polarityAxes = ...
    nexttile( ...
        tileLayout, ...
        1);

configureSwitchingAxes( ...
    polarityAxes);

hold( ...
    polarityAxes, ...
    'on');

phaseColors = [ ...
    0.80, 0.00, 0.00
    0.00, 0.50, 0.00
    0.00, 0.25, 0.80];

phaseNames = { ...
    'U', ...
    'V', ...
    'W'};

polarityBaseOffsets = [ ...
    8, ...
    4, ...
    0];

for phaseIndex = 1:3

    positiveTrace = ...
        double( ...
            displayPositivePolarity(:,phaseIndex)) ...
        + polarityBaseOffsets(phaseIndex) ...
        + 2;

    negativeTrace = ...
        double( ...
            displayNegativePolarity(:,phaseIndex)) ...
        + polarityBaseOffsets(phaseIndex) ...
        + 1;

    zeroTrace = ...
        double( ...
            displayZeroPolarity(:,phaseIndex)) ...
        + polarityBaseOffsets(phaseIndex);

    stairs( ...
        polarityAxes, ...
        displayTimeMilliseconds, ...
        positiveTrace, ...
        '-', ...
        'Color', ...
        phaseColors(phaseIndex,:), ...
        'LineWidth', ...
        1.6);

    stairs( ...
        polarityAxes, ...
        displayTimeMilliseconds, ...
        negativeTrace, ...
        '--', ...
        'Color', ...
        phaseColors(phaseIndex,:), ...
        'LineWidth', ...
        1.4);

    stairs( ...
        polarityAxes, ...
        displayTimeMilliseconds, ...
        zeroTrace, ...
        ':', ...
        'Color', ...
        phaseColors(phaseIndex,:), ...
        'LineWidth', ...
        1.4);

end

polarityTickLocations = [ ...
    0.5, 1.5, 2.5, ...
    4.5, 5.5, 6.5, ...
    8.5, 9.5, 10.5];

polarityTickLabels = { ...
    'W Zero', ...
    'W Neg.', ...
    'W Pos.', ...
    'V Zero', ...
    'V Neg.', ...
    'V Pos.', ...
    'U Zero', ...
    'U Neg.', ...
    'U Pos.'};

yticks( ...
    polarityAxes, ...
    polarityTickLocations);

yticklabels( ...
    polarityAxes, ...
    polarityTickLabels);

ylim( ...
    polarityAxes, ...
    [-0.25, 11.25]);

xlim( ...
    polarityAxes, ...
    [ ...
    displayTimeMilliseconds(1), ...
    displayTimeMilliseconds(end)]);

ylabel( ...
    polarityAxes, ...
    'Output Phase State');

title( ...
    polarityAxes, ...
    'Output-Phase Positive, Negative, and Zero Selection', ...
    'FontSize', ...
    14, ...
    'FontWeight', ...
    'bold');

hold( ...
    polarityAxes, ...
    'off');

%% =========================================================
% Plot 2: Representative 12-device switching raster
%% =========================================================

deviceAxes = ...
    nexttile( ...
        tileLayout, ...
        2);

configureSwitchingAxes( ...
    deviceAxes);

imagesc( ...
    deviceAxes, ...
    displayTimeMilliseconds, ...
    1:12, ...
    double(displayDeviceState).');

colormap( ...
    deviceAxes, ...
    [ ...
    1.00, 1.00, 1.00
    0.90, 0.30, 0.05]);

colorbarHandle = ...
    colorbar( ...
        deviceAxes);

colorbarHandle.Ticks = ...
    [0, 1];

colorbarHandle.TickLabels = ...
    {'Blocked', 'Conducting'};

set( ...
    deviceAxes, ...
    'YDir', ...
    'normal');

yticks( ...
    deviceAxes, ...
    1:12);

yticklabels( ...
    deviceAxes, ...
    compose( ...
        'T%d', ...
        1:12));

ylabel( ...
    deviceAxes, ...
    'Physical Device');

title( ...
    deviceAxes, ...
    sprintf( ...
        ['Representative Physical Device States, ', ...
         'Group %d, Motor Phase U'], ...
        groupToDisplay), ...
    'FontSize', ...
    14, ...
    'FontWeight', ...
    'bold');

xlim( ...
    deviceAxes, ...
    [ ...
    displayTimeMilliseconds(1), ...
    displayTimeMilliseconds(end)]);

%% =========================================================
% Plot 3: Representative T111 and T211 states
%% =========================================================

representativeAxes = ...
    nexttile( ...
        tileLayout, ...
        3);

configureSwitchingAxes( ...
    representativeAxes);

hold( ...
    representativeAxes, ...
    'on');

stateT111Handle = ...
    stairs( ...
        representativeAxes, ...
        displayTimeMilliseconds, ...
        double(displayT111) + 2, ...
        '-', ...
        'Color', ...
        [0.80, 0.00, 0.00], ...
        'LineWidth', ...
        2.0);

stateT211Handle = ...
    stairs( ...
        representativeAxes, ...
        displayTimeMilliseconds, ...
        double(displayT211), ...
        '-', ...
        'Color', ...
        [0.00, 0.25, 0.80], ...
        'LineWidth', ...
        2.0);

yticks( ...
    representativeAxes, ...
    [0, 1, 2, 3]);

yticklabels( ...
    representativeAxes, ...
    { ...
    'T211 blocked', ...
    'T211 conducting', ...
    'T111 blocked', ...
    'T111 conducting'});

ylim( ...
    representativeAxes, ...
    [-0.25, 3.25]);

xlim( ...
    representativeAxes, ...
    [ ...
    displayTimeMilliseconds(1), ...
    displayTimeMilliseconds(end)]);

xlabel( ...
    representativeAxes, ...
    'Time [ms]');

ylabel( ...
    representativeAxes, ...
    'Representative State');

title( ...
    representativeAxes, ...
    'Representative T111 and T211 Switching States', ...
    'FontSize', ...
    14, ...
    'FontWeight', ...
    'bold');

representativeLegend = ...
    legend( ...
        representativeAxes, ...
        [ ...
        stateT111Handle, ...
        stateT211Handle], ...
        { ...
        'staT111', ...
        'staT211'}, ...
        'Location', ...
        'northeast');

representativeLegend.FontSize = ...
    10;

hold( ...
    representativeAxes, ...
    'off');

%% =========================================================
% Link horizontal axes
%% =========================================================

linkaxes( ...
    [ ...
    polarityAxes, ...
    deviceAxes, ...
    representativeAxes], ...
    'x');

%% =========================================================
% Overall title
%% =========================================================

title( ...
    tileLayout, ...
    string( ...
        Report.Figures. ...
        SimulationSwitching.Title), ...
    'FontName', ...
    'Arial', ...
    'FontSize', ...
    17, ...
    'FontWeight', ...
    'bold', ...
    'Interpreter', ...
    'none');

%% =========================================================
% Model-status annotation
%% =========================================================

stateStatus = ...
    getOptionalStatus( ...
        S.State, ...
        'modelStatus');

physicalConductionStatus = ...
    getOptionalStatus( ...
        S.State, ...
        'physicalConductionStatus');

annotationText = { ...
    sprintf( ...
        'State model: %s', ...
        char(stateStatus)), ...
    sprintf( ...
        'Physical conduction: %s', ...
        char(physicalConductionStatus)), ...
    sprintf( ...
        'Display interval: %.3f ms', ...
        displayTimeMilliseconds(end) ...
        - displayTimeMilliseconds(1))};

text( ...
    polarityAxes, ...
    0.99, ...
    0.97, ...
    annotationText, ...
    'Units', ...
    'normalized', ...
    'HorizontalAlignment', ...
    'right', ...
    'VerticalAlignment', ...
    'top', ...
    'FontName', ...
    'Arial', ...
    'FontSize', ...
    10, ...
    'Interpreter', ...
    'none', ...
    'BackgroundColor', ...
    'white', ...
    'EdgeColor', ...
    [0.60, 0.60, 0.60], ...
    'Margin', ...
    5);

%% =========================================================
% Export
%% =========================================================

exportgraphics( ...
    figureHandle, ...
    figureFile, ...
    'Resolution', ...
    300, ...
    'BackgroundColor', ...
    'white');

close( ...
    figureHandle);

if ~isfile(figureFile)

    error( ...
        'Cyclo:SimulationSwitchingFigureExportFailure', ...
        ['The Detailed Simulation switching-state figure ', ...
         'was not exported.']);

end

end


function configureSwitchingAxes(axesHandle)
%CONFIGURESWITCHINGAXES Apply common switching-plot formatting.

axesHandle.FontName = ...
    'Arial';

axesHandle.FontSize = ...
    11;

axesHandle.LineWidth = ...
    1.0;

grid( ...
    axesHandle, ...
    'on');

box( ...
    axesHandle, ...
    'on');

end


function displayMask = ...
    selectSwitchingDisplayMask( ...
        timeVector, ...
        S)
%SELECTSWITCHINGDISPLAYMASK
% Select approximately one fundamental period from the end
% of the record. This keeps individual switching events clear.

displayDuration = ...
    [];

if isfield(S, 'Parameters') && ...
        isfield(S.Parameters, 'f1') && ...
        isnumeric(S.Parameters.f1) && ...
        isscalar(S.Parameters.f1) && ...
        isfinite(S.Parameters.f1) && ...
        S.Parameters.f1 > 0

    displayDuration = ...
        1 ...
        / S.Parameters.f1;

end

fullRecordDuration = ...
    timeVector(end) ...
    - timeVector(1);

if isempty(displayDuration) || ...
        displayDuration >= fullRecordDuration

    displayMask = ...
        true(size(timeVector));

    return

end

displayStartTime = ...
    timeVector(end) ...
    - displayDuration;

displayMask = ...
    timeVector >= displayStartTime;

if sum(displayMask) < 100

    displayMask = ...
        true(size(timeVector));

end

end


function value = getOptionalStatus(S, fieldName)
%GETOPTIONALSTATUS Return a status field or fallback text.

if isfield(S, fieldName) && ...
        ~isempty(S.(fieldName))

    value = ...
        string(S.(fieldName));

else

    value = ...
        "Status not available";

end

end