function figureFile = ...
    generate_cyclo_simulation_device_currents_figure( ...
        DesignData, ...
        Report, ...
        outputFolder)
%GENERATE_CYCLO_SIMULATION_DEVICE_CURRENTS_FIGURE
% Generate Figure B-4 showing physical thyristor-current
% allocation from the validated Detailed Simulation.
%
% The figure contains:
%   1. Representative T111 and T211 current waveforms
%   2. Current allocation for twelve physical thyristors
%   3. Per-device RMS, average, and peak currents
%   4. Per-device turn-on and turn-off counts
%
% Displayed selection:
%   Converter group: 1
%   Motor output phase: U
%
% This function does not perform engineering calculations.
% It only visualizes validated DetailedSimulation results.

arguments
    DesignData   (1,1) struct
    Report       (1,1) struct
    outputFolder (1,1) string
end

%% =========================================================
% Initialize output
%% =========================================================

figureFile = ...
    "";

%% =========================================================
% Validate main structures
%% =========================================================

if ~isfield(DesignData, 'DetailedSimulation')

    error( ...
        'Cyclo:MissingSimulationForDeviceCurrentFigure', ...
        'DesignData.DetailedSimulation is required.');

end

S = ...
    DesignData.DetailedSimulation;

if ~isfield(S, 'Voltage') || ...
        ~isstruct(S.Voltage) || ...
        ~isfield(S.Voltage, 't')

    error( ...
        'Cyclo:MissingDeviceCurrentTimeVector', ...
        'DetailedSimulation.Voltage.t is required.');

end

if ~isfield(S, 'Device') || ...
        ~isstruct(S.Device)

    error( ...
        'Cyclo:MissingDeviceCurrentData', ...
        'DetailedSimulation.Device is required.');

end

if ~isfield(Report, 'Figures') || ...
        ~isfield( ...
            Report.Figures, ...
            'SimulationDeviceCurrents')

    error( ...
        'Cyclo:MissingDeviceCurrentFigureDefinition', ...
        ['Report.Figures.SimulationDeviceCurrents ', ...
         'is required.']);

end

if ~isfield( ...
        Report.Figures.SimulationDeviceCurrents, ...
        'FileName')

    error( ...
        'Cyclo:MissingDeviceCurrentFigureFileName', ...
        ['The simulation device-current figure definition ', ...
         'does not contain FileName.']);

end

%% =========================================================
% Validate required Device fields
%% =========================================================

requiredDeviceFields = { ...
    'thyristorCurrent', ...
    'iT111', ...
    'iT211', ...
    'thyristorRmsCurrent', ...
    'thyristorAverageCurrent', ...
    'thyristorPeakCurrent', ...
    'turnOnCount', ...
    'turnOffCount', ...
    'thyristorOrder', ...
    'abbThyristorOrder', ...
    'outputPhaseNames', ...
    'numberOfGroups'};

for fieldIndex = 1:numel(requiredDeviceFields)

    fieldName = ...
        requiredDeviceFields{fieldIndex};

    if ~isfield(S.Device, fieldName)

        error( ...
            'Cyclo:MissingDeviceCurrentFigureField', ...
            'DetailedSimulation.Device is missing %s.', ...
            fieldName);

    end

end

%% =========================================================
% Retrieve and validate time vector
%% =========================================================

timeVector = ...
    double(S.Voltage.t(:));

numberOfTimeSamples = ...
    numel(timeVector);

if numberOfTimeSamples < 2

    error( ...
        'Cyclo:InsufficientDeviceCurrentTimeSamples', ...
        ['The simulation time vector must contain at least ', ...
         'two samples.']);

end

if any(~isfinite(timeVector))

    error( ...
        'Cyclo:InvalidDeviceCurrentTimeValues', ...
        'The simulation time vector contains invalid values.');

end

if any(diff(timeVector) <= 0)

    error( ...
        'Cyclo:NonIncreasingDeviceCurrentTimeVector', ...
        'The simulation time vector must be strictly increasing.');

end

%% =========================================================
% Retrieve device arrays
%% =========================================================

thyristorCurrent = ...
    double(S.Device.thyristorCurrent);

representativeT111Current = ...
    double(S.Device.iT111(:));

representativeT211Current = ...
    double(S.Device.iT211(:));

thyristorRmsCurrent = ...
    double(S.Device.thyristorRmsCurrent);

thyristorAverageCurrent = ...
    double(S.Device.thyristorAverageCurrent);

thyristorPeakCurrent = ...
    double(S.Device.thyristorPeakCurrent);

turnOnCount = ...
    double(S.Device.turnOnCount);

turnOffCount = ...
    double(S.Device.turnOffCount);

numberOfGroups = ...
    double(S.Device.numberOfGroups);

%% =========================================================
% Validate number of groups
%% =========================================================

if ~isscalar(numberOfGroups) || ...
        ~isfinite(numberOfGroups) || ...
        numberOfGroups < 1 || ...
        numberOfGroups ~= round(numberOfGroups)

    error( ...
        'Cyclo:InvalidDeviceCurrentGroupCount', ...
        ['DetailedSimulation.Device.numberOfGroups must be ', ...
         'a positive integer.']);

end

%% =========================================================
% Validate thyristor-current dimensions
%% =========================================================

expectedWaveformDimensions = [ ...
    numberOfTimeSamples, ...
    12, ...
    numberOfGroups, ...
    3];

actualWaveformDimensions = ...
    normalizedSize( ...
        thyristorCurrent, ...
        4);

if ~isequal( ...
        actualWaveformDimensions, ...
        expectedWaveformDimensions)

    error( ...
        'Cyclo:ThyristorCurrentDimensionMismatch', ...
        [ ...
        'thyristorCurrent dimensions are %s. ', ...
        'Expected %d x 12 x %d x 3.' ...
        ], ...
        char( ...
            strjoin( ...
                string(actualWaveformDimensions), ...
                ' x ')), ...
        numberOfTimeSamples, ...
        numberOfGroups);

end

if any(~isfinite(thyristorCurrent(:)))

    error( ...
        'Cyclo:InvalidThyristorCurrentValues', ...
        'thyristorCurrent contains invalid values.');

end

if any(thyristorCurrent(:) < 0)

    error( ...
        'Cyclo:NegativeThyristorCurrentValues', ...
        ['thyristorCurrent contains negative values even ', ...
         'though it represents current magnitude.']);

end

%% =========================================================
% Validate representative current waveforms
%% =========================================================

if numel(representativeT111Current) ~= ...
        numberOfTimeSamples

    error( ...
        'Cyclo:T111CurrentLengthMismatch', ...
        ['iT111 contains %d samples. The time vector ', ...
         'contains %d samples.'], ...
        numel(representativeT111Current), ...
        numberOfTimeSamples);

end

if numel(representativeT211Current) ~= ...
        numberOfTimeSamples

    error( ...
        'Cyclo:T211CurrentLengthMismatch', ...
        ['iT211 contains %d samples. The time vector ', ...
         'contains %d samples.'], ...
        numel(representativeT211Current), ...
        numberOfTimeSamples);

end

if any(~isfinite(representativeT111Current)) || ...
        any(~isfinite(representativeT211Current))

    error( ...
        'Cyclo:InvalidRepresentativeThyristorCurrent', ...
        'The representative thyristor currents are invalid.');

end

%% =========================================================
% Validate summary-array dimensions
%% =========================================================

expectedSummaryDimensions = [ ...
    12, ...
    numberOfGroups, ...
    3];

summaryArrays = { ...
    thyristorRmsCurrent, ...
    thyristorAverageCurrent, ...
    thyristorPeakCurrent, ...
    turnOnCount, ...
    turnOffCount};

summaryArrayNames = { ...
    'thyristorRmsCurrent', ...
    'thyristorAverageCurrent', ...
    'thyristorPeakCurrent', ...
    'turnOnCount', ...
    'turnOffCount'};

for arrayIndex = 1:numel(summaryArrays)

    arrayValue = ...
        summaryArrays{arrayIndex};

    arrayDimensions = ...
        normalizedSize( ...
            arrayValue, ...
            3);

    if ~isequal( ...
            arrayDimensions, ...
            expectedSummaryDimensions)

        error( ...
            'Cyclo:DeviceSummaryDimensionMismatch', ...
            [ ...
            '%s dimensions are %s. ', ...
            'Expected 12 x %d x 3.' ...
            ], ...
            summaryArrayNames{arrayIndex}, ...
            char( ...
                strjoin( ...
                    string(arrayDimensions), ...
                    ' x ')), ...
            numberOfGroups);

    end

    if any(~isfinite(arrayValue(:)))

        error( ...
            'Cyclo:InvalidDeviceSummaryValues', ...
            '%s contains invalid values.', ...
            summaryArrayNames{arrayIndex});

    end

end

if any(thyristorRmsCurrent(:) < 0) || ...
        any(thyristorAverageCurrent(:) < 0) || ...
        any(thyristorPeakCurrent(:) < 0)

    error( ...
        'Cyclo:NegativeDeviceCurrentSummary', ...
        ['RMS, average, and peak current magnitudes must ', ...
         'be non-negative.']);

end

if any(turnOnCount(:) < 0) || ...
        any(turnOffCount(:) < 0)

    error( ...
        'Cyclo:NegativeDeviceSwitchingCount', ...
        'Thyristor switching counts must be non-negative.');

end

%% =========================================================
% Validate identifiers
%% =========================================================

deviceLabels = ...
    string(S.Device.abbThyristorOrder(:));

internalDeviceLabels = ...
    string(S.Device.thyristorOrder(:));

outputPhaseNames = ...
    string(S.Device.outputPhaseNames(:));

if numel(deviceLabels) ~= 12

    error( ...
        'Cyclo:InvalidAbbThyristorOrder', ...
        ['abbThyristorOrder must contain exactly ', ...
         '12 identifiers.']);

end

if numel(internalDeviceLabels) ~= 12

    error( ...
        'Cyclo:InvalidInternalThyristorOrder', ...
        ['thyristorOrder must contain exactly ', ...
         '12 identifiers.']);

end

if numel(outputPhaseNames) ~= 3

    error( ...
        'Cyclo:InvalidDeviceOutputPhaseNames', ...
        'outputPhaseNames must contain three phase names.');

end

%% =========================================================
% Select displayed group and phase
%% =========================================================

groupToDisplay = ...
    1;

outputPhaseToDisplay = ...
    1;

if groupToDisplay > numberOfGroups

    error( ...
        'Cyclo:UnavailableDeviceCurrentGroup', ...
        ['Converter group %d is not available. ', ...
         'The simulation contains %d groups.'], ...
        groupToDisplay, ...
        numberOfGroups);

end

selectedOutputPhaseName = ...
    outputPhaseNames(outputPhaseToDisplay);

%% =========================================================
% Extract selected device-current waveforms
%% =========================================================

selectedDeviceCurrent = ...
    squeeze( ...
        thyristorCurrent( ...
            :, ...
            :, ...
            groupToDisplay, ...
            outputPhaseToDisplay));

selectedDeviceCurrent = ...
    reshape( ...
        selectedDeviceCurrent, ...
        numberOfTimeSamples, ...
        12);

if any(~isfinite(selectedDeviceCurrent(:)))

    error( ...
        'Cyclo:InvalidSelectedDeviceCurrent', ...
        'The selected device-current array contains invalid values.');

end

%% =========================================================
% Extract selected summary values
%% =========================================================

selectedRmsCurrent = ...
    squeeze( ...
        thyristorRmsCurrent( ...
            :, ...
            groupToDisplay, ...
            outputPhaseToDisplay));

selectedAverageCurrent = ...
    squeeze( ...
        thyristorAverageCurrent( ...
            :, ...
            groupToDisplay, ...
            outputPhaseToDisplay));

selectedPeakCurrent = ...
    squeeze( ...
        thyristorPeakCurrent( ...
            :, ...
            groupToDisplay, ...
            outputPhaseToDisplay));

selectedTurnOnCount = ...
    squeeze( ...
        turnOnCount( ...
            :, ...
            groupToDisplay, ...
            outputPhaseToDisplay));

selectedTurnOffCount = ...
    squeeze( ...
        turnOffCount( ...
            :, ...
            groupToDisplay, ...
            outputPhaseToDisplay));

selectedRmsCurrent = ...
    selectedRmsCurrent(:);

selectedAverageCurrent = ...
    selectedAverageCurrent(:);

selectedPeakCurrent = ...
    selectedPeakCurrent(:);

selectedTurnOnCount = ...
    selectedTurnOnCount(:);

selectedTurnOffCount = ...
    selectedTurnOffCount(:);

%% =========================================================
% Select readable time interval
%% =========================================================

displayMask = ...
    selectDeviceCurrentDisplayMask( ...
        timeVector, ...
        S);

if sum(displayMask) < 2

    error( ...
        'Cyclo:InvalidDeviceCurrentDisplayMask', ...
        'The selected display interval contains too few samples.');

end

displayTimeMilliseconds = ...
    1000 ...
    * timeVector(displayMask);

displayT111Current = ...
    representativeT111Current(displayMask);

displayT211Current = ...
    representativeT211Current(displayMask);

displayDeviceCurrent = ...
    selectedDeviceCurrent(displayMask,:);

%% =========================================================
% Initialize output path
%% =========================================================

if ~isfolder(outputFolder)

    mkdir(outputFolder);

end

figureFile = ...
    fullfile( ...
        outputFolder, ...
        string( ...
            Report.Figures. ...
            SimulationDeviceCurrents.FileName));

%% =========================================================
% Create figure
%% =========================================================

figureHandle = ...
    figure( ...
        'Visible', ...
        'off', ...
        'Color', ...
        'white', ...
        'Position', ...
        [100, 100, 2600, 1900]);

figureCleanup = ...
    onCleanup( ...
        @() closeFigureSafely(figureHandle));

tileLayout = ...
    tiledlayout( ...
        figureHandle, ...
        4, ...
        1, ...
        'TileSpacing', ...
        'compact', ...
        'Padding', ...
        'compact');

%% =========================================================
% Plot 1: T111 and T211 current waveforms
%% =========================================================

representativeAxes = ...
    nexttile( ...
        tileLayout, ...
        1);

configureDeviceAxes( ...
    representativeAxes);

hold( ...
    representativeAxes, ...
    'on');

t111Handle = ...
    plot( ...
        representativeAxes, ...
        displayTimeMilliseconds, ...
        displayT111Current, ...
        '-', ...
        'Color', ...
        [0.80, 0.00, 0.00], ...
        'LineWidth', ...
        1.8);

t211Handle = ...
    plot( ...
        representativeAxes, ...
        displayTimeMilliseconds, ...
        displayT211Current, ...
        '-', ...
        'Color', ...
        [0.00, 0.25, 0.80], ...
        'LineWidth', ...
        1.8);

ylabel( ...
    representativeAxes, ...
    'Current [A]');

title( ...
    representativeAxes, ...
    'Representative T111 and T211 Currents', ...
    'FontSize', ...
    14, ...
    'FontWeight', ...
    'bold');

representativeLegend = ...
    legend( ...
        representativeAxes, ...
        [t111Handle, t211Handle], ...
        {'iT111', 'iT211'}, ...
        'Location', ...
        'northwest');

representativeLegend.FontSize = ...
    10;

representativeLegend.Box = ...
    'on';

representativeMaximum = ...
    max( ...
        abs( ...
            [ ...
            displayT111Current
            displayT211Current]));

if representativeMaximum <= 0

    representativeMaximum = ...
        1;

end

ylim( ...
    representativeAxes, ...
    [ ...
    -0.05*representativeMaximum, ...
    1.15*representativeMaximum]);

xlim( ...
    representativeAxes, ...
    [ ...
    displayTimeMilliseconds(1), ...
    displayTimeMilliseconds(end)]);

hold( ...
    representativeAxes, ...
    'off');

%% =========================================================
% Plot 2: Twelve-device current-allocation raster
%% =========================================================

allocationAxes = ...
    nexttile( ...
        tileLayout, ...
        2);

configureDeviceAxes( ...
    allocationAxes);

maximumDisplayedCurrent = ...
    max(displayDeviceCurrent(:));

if maximumDisplayedCurrent <= 0

    maximumDisplayedCurrent = ...
        1;

end

normalizedCurrentRaster = ...
    displayDeviceCurrent.' ...
    / maximumDisplayedCurrent;

imagesc( ...
    allocationAxes, ...
    displayTimeMilliseconds, ...
    1:12, ...
    normalizedCurrentRaster);

set( ...
    allocationAxes, ...
    'YDir', ...
    'normal');

deviceColormap = [ ...
    linspace(1.00, 0.90, 128).', ...
    linspace(1.00, 0.20, 128).', ...
    linspace(1.00, 0.05, 128).'];

colormap( ...
    allocationAxes, ...
    deviceColormap);

caxis( ...
    allocationAxes, ...
    [0, 1]);

allocationColorbar = ...
    colorbar( ...
        allocationAxes);

allocationColorbar.Label.String = ...
    'Current / maximum displayed current';

yticks( ...
    allocationAxes, ...
    1:12);

yticklabels( ...
    allocationAxes, ...
    deviceLabels);

ylabel( ...
    allocationAxes, ...
    'Physical Thyristor');

title( ...
    allocationAxes, ...
    sprintf( ...
        ['Physical Thyristor Current Allocation, ', ...
         'Group %d, Output Phase %s'], ...
        groupToDisplay, ...
        char(selectedOutputPhaseName)), ...
    'FontSize', ...
    14, ...
    'FontWeight', ...
    'bold');

xlim( ...
    allocationAxes, ...
    [ ...
    displayTimeMilliseconds(1), ...
    displayTimeMilliseconds(end)]);

%% =========================================================
% Plot 3: RMS, average, and peak currents
%% =========================================================

summaryAxes = ...
    nexttile( ...
        tileLayout, ...
        3);

configureDeviceAxes( ...
    summaryAxes);

summaryBarHandles = ...
    bar( ...
        summaryAxes, ...
        [ ...
        selectedRmsCurrent, ...
        selectedAverageCurrent, ...
        selectedPeakCurrent], ...
        'grouped');

summaryBarHandles(1).FaceColor = ...
    [0.00, 0.45, 0.74];

summaryBarHandles(2).FaceColor = ...
    [0.47, 0.67, 0.19];

summaryBarHandles(3).FaceColor = ...
    [0.85, 0.33, 0.10];

xticks( ...
    summaryAxes, ...
    1:12);

xticklabels( ...
    summaryAxes, ...
    deviceLabels);

xtickangle( ...
    summaryAxes, ...
    30);

ylabel( ...
    summaryAxes, ...
    'Current [A]');

title( ...
    summaryAxes, ...
    'Per-Device RMS, Average, and Peak Current', ...
    'FontSize', ...
    14, ...
    'FontWeight', ...
    'bold');

summaryLegend = ...
    legend( ...
        summaryAxes, ...
        { ...
        'RMS current', ...
        'Average current', ...
        'Peak current'}, ...
        'Location', ...
        'northwest');

summaryLegend.FontSize = ...
    10;

summaryLegend.Box = ...
    'on';

summaryMaximum = ...
    max( ...
        [ ...
        selectedRmsCurrent
        selectedAverageCurrent
        selectedPeakCurrent]);

if summaryMaximum <= 0

    summaryMaximum = ...
        1;

end

ylim( ...
    summaryAxes, ...
    [0, 1.20*summaryMaximum]);

%% =========================================================
% Plot 4: Turn-on and turn-off counts
%% =========================================================

countAxes = ...
    nexttile( ...
        tileLayout, ...
        4);

configureDeviceAxes( ...
    countAxes);

countBarHandles = ...
    bar( ...
        countAxes, ...
        [ ...
        selectedTurnOnCount, ...
        selectedTurnOffCount], ...
        'grouped');

countBarHandles(1).FaceColor = ...
    [0.15, 0.55, 0.30];

countBarHandles(2).FaceColor = ...
    [0.48, 0.28, 0.62];

xticks( ...
    countAxes, ...
    1:12);

xticklabels( ...
    countAxes, ...
    deviceLabels);

xtickangle( ...
    countAxes, ...
    30);

xlabel( ...
    countAxes, ...
    'Physical Thyristor');

ylabel( ...
    countAxes, ...
    'Switching Count');

title( ...
    countAxes, ...
    'Per-Device Turn-On and Turn-Off Counts', ...
    'FontSize', ...
    14, ...
    'FontWeight', ...
    'bold');

countLegend = ...
    legend( ...
        countAxes, ...
        { ...
        'Turn-on count', ...
        'Turn-off count'}, ...
        'Location', ...
        'northwest');

countLegend.FontSize = ...
    10;

countLegend.Box = ...
    'on';

countMaximum = ...
    max( ...
        [ ...
        selectedTurnOnCount
        selectedTurnOffCount]);

if countMaximum <= 0

    countMaximum = ...
        1;

end

ylim( ...
    countAxes, ...
    [0, 1.20*countMaximum]);

%% =========================================================
% Link waveform time axes
%% =========================================================

linkaxes( ...
    [representativeAxes, allocationAxes], ...
    'x');

%% =========================================================
% Overall figure title
%% =========================================================

title( ...
    tileLayout, ...
    string( ...
        Report.Figures. ...
        SimulationDeviceCurrents.Title), ...
    'FontName', ...
    'Arial', ...
    'FontSize', ...
    17, ...
    'FontWeight', ...
    'bold', ...
    'Interpreter', ...
    'none');

%% =========================================================
% Validation annotation
%% =========================================================

deviceAllocationStatus = ...
    getOptionalDeviceStatus( ...
        S.Device, ...
        'deviceCurrentAllocationStatus');

thyristorCurrentStatus = ...
    getOptionalDeviceStatus( ...
        S.Device, ...
        'thyristorCurrentStatus');

physicalTopologyStatus = ...
    getOptionalDeviceStatus( ...
        S.Device, ...
        'physicalTopologyStatus');

annotationText = { ...
    sprintf( ...
        'Device allocation: %s', ...
        char(deviceAllocationStatus)), ...
    sprintf( ...
        'Thyristor current: %s', ...
        char(thyristorCurrentStatus)), ...
    sprintf( ...
        'Physical topology: %s', ...
        char(physicalTopologyStatus)), ...
    sprintf( ...
        'Display interval: %.3f ms', ...
        displayTimeMilliseconds(end) ...
        - displayTimeMilliseconds(1))};

text( ...
    representativeAxes, ...
    0.99, ...
    0.97, ...
    annotationText, ...
    'Units', ...
    'normalized', ...
    'HorizontalAlignment', ...
    'right', ...
    'VerticalAlignment', ...
    'top', ...
    'FontName', ...
    'Arial', ...
    'FontSize', ...
    9, ...
    'Interpreter', ...
    'none', ...
    'BackgroundColor', ...
    'white', ...
    'EdgeColor', ...
    [0.60, 0.60, 0.60], ...
    'Margin', ...
    5);

%% =========================================================
% Export PNG
%% =========================================================

exportgraphics( ...
    figureHandle, ...
    figureFile, ...
    'Resolution', ...
    300, ...
    'BackgroundColor', ...
    'white');

close( ...
    figureHandle);

figureCleanup = [];

if ~isfile(figureFile)

    error( ...
        'Cyclo:SimulationDeviceCurrentFigureExportFailure', ...
        ['The Detailed Simulation device-current figure ', ...
         'was not exported.']);

end

end


function dimensions = normalizedSize( ...
    value, ...
    numberOfDimensions)
%NORMALIZEDSIZE Return an exact-length dimension vector.

if ~isnumeric(numberOfDimensions) || ...
        ~isscalar(numberOfDimensions) || ...
        ~isfinite(numberOfDimensions) || ...
        numberOfDimensions < 1 || ...
        numberOfDimensions ~= round(numberOfDimensions)

    error( ...
        'Cyclo:InvalidRequestedDimensionCount', ...
        ['The requested number of dimensions must be a ', ...
         'positive integer.']);

end

dimensions = ...
    size(value);

if numel(dimensions) < numberOfDimensions

    dimensions = [ ...
        dimensions, ...
        ones( ...
            1, ...
            numberOfDimensions - numel(dimensions))];

elseif numel(dimensions) > numberOfDimensions

    trailingDimensions = ...
        dimensions(numberOfDimensions+1:end);

    if any(trailingDimensions ~= 1)

        error( ...
            'Cyclo:UnexpectedArrayDimensions', ...
            ['The array contains unexpected non-singleton ', ...
             'dimensions after dimension %d.'], ...
            numberOfDimensions);

    end

    dimensions = ...
        dimensions(1:numberOfDimensions);

end

dimensions = ...
    double(dimensions);

end


function configureDeviceAxes(axesHandle)
%CONFIGUREDEVICEAXES Apply common plot formatting.

axesHandle.FontName = ...
    'Arial';

axesHandle.FontSize = ...
    11;

axesHandle.LineWidth = ...
    1.0;

grid( ...
    axesHandle, ...
    'on');

box( ...
    axesHandle, ...
    'on');

end


function displayMask = ...
    selectDeviceCurrentDisplayMask( ...
        timeVector, ...
        S)
%SELECTDEVICECURRENTDISPLAYMASK
% Select one fundamental period from the end of the simulation
% record so individual device-current pulses remain readable.

displayDuration = ...
    [];

if isfield(S, 'Parameters') && ...
        isfield(S.Parameters, 'f1') && ...
        isnumeric(S.Parameters.f1) && ...
        isscalar(S.Parameters.f1) && ...
        isfinite(S.Parameters.f1) && ...
        S.Parameters.f1 > 0

    displayDuration = ...
        1 ...
        / S.Parameters.f1;

end

fullRecordDuration = ...
    timeVector(end) ...
    - timeVector(1);

if isempty(displayDuration) || ...
        displayDuration >= fullRecordDuration

    displayMask = ...
        true(size(timeVector));

    return

end

displayStartTime = ...
    timeVector(end) ...
    - displayDuration;

displayMask = ...
    timeVector >= displayStartTime;

if sum(displayMask) < 100

    displayMask = ...
        true(size(timeVector));

end

end


function value = ...
    getOptionalDeviceStatus( ...
        S, ...
        fieldName)
%GETOPTIONALDEVICESTATUS Return status or fallback text.

if isfield(S, fieldName) && ...
        ~isempty(S.(fieldName))

    value = ...
        string(S.(fieldName));

else

    value = ...
        "Status not available";

end

end


function closeFigureSafely(figureHandle)
%CLOSEFIGURESAFELY Close a valid figure after an error.

try

    if ~isempty(figureHandle) && ...
            isgraphics( ...
                figureHandle, ...
                'figure')

        close(figureHandle);

    end

catch

    % Preserve the original plotting or export error.

end

end