%% =========================================================
% Inspect Detailed Simulation switching data
%% =========================================================

Cache = ...
    evalin( ...
        'base', ...
        'CycloToolDesignDataCache');

S = ...
    Cache.DetailedSimulation;

assert( ...
    isfield(S, 'State') && ...
    isstruct(S.State), ...
    'DetailedSimulation.State is missing or invalid.');

assert( ...
    isfield(S.State, 'positive'), ...
    'DetailedSimulation.State.positive is missing.');

assert( ...
    isfield(S.State, 'negative'), ...
    'DetailedSimulation.State.negative is missing.');

assert( ...
    isfield(S, 'Zero'), ...
    'DetailedSimulation.Zero is missing.');

assert( ...
    isfield(S, 'Voltage') && ...
    isfield(S.Voltage, 't'), ...
    'DetailedSimulation.Voltage.t is missing.');

numberOfTimeSamples = ...
    numel(S.Voltage.t);

%% =========================================================
% Main switching values
%% =========================================================

switchingNames = { ...
    'State.positive', ...
    'State.negative', ...
    'Zero'};

switchingValues = { ...
    S.State.positive, ...
    S.State.negative, ...
    S.Zero};

fprintf('\n');
fprintf('DETAILED SIMULATION SWITCHING INVENTORY\n');
fprintf('============================================================\n');
fprintf('Simulation time samples: %d\n', ...
    numberOfTimeSamples);

for valueIndex = 1:numel(switchingValues)

    valueName = ...
        switchingNames{valueIndex};

    value = ...
        switchingValues{valueIndex};

    valueSize = ...
        size(value);

    sizeText = ...
        strjoin( ...
            string(valueSize), ...
            ' x ');

    fprintf('\n');
    fprintf('%s\n', upper(valueName));
    fprintf('------------------------------------------------------------\n');

    fprintf( ...
        '%-32s %-12s %s\n', ...
        valueName, ...
        class(value), ...
        char(sizeText));

    if isstruct(value)

        if isscalar(value)

            nestedFields = ...
                fieldnames(value);

            for fieldIndex = 1:numel(nestedFields)

                fieldName = ...
                    nestedFields{fieldIndex};

                fieldValue = ...
                    value.(fieldName);

                fieldSize = ...
                    size(fieldValue);

                fieldSizeText = ...
                    strjoin( ...
                        string(fieldSize), ...
                        ' x ');

                containsTimeDimension = ...
                    any(fieldSize == numberOfTimeSamples);

                fprintf( ...
                    '  %-30s %-12s %-16s Time dimension: %d\n', ...
                    fieldName, ...
                    class(fieldValue), ...
                    char(fieldSizeText), ...
                    containsTimeDimension);

            end

        else

            fprintf( ...
                '  Structure array elements: %d\n', ...
                numel(value));

        end

    elseif islogical(value)

        containsTimeDimension = ...
            any(valueSize == numberOfTimeSamples);

        fprintf( ...
            '  True values             : %d\n', ...
            nnz(value));

        fprintf( ...
            '  False values            : %d\n', ...
            numel(value) - nnz(value));

        fprintf( ...
            '  Time dimension present  : %d\n', ...
            containsTimeDimension);

    elseif isnumeric(value)

        finiteValues = ...
            value(isfinite(value));

        containsTimeDimension = ...
            any(valueSize == numberOfTimeSamples);

        if isempty(finiteValues)

            fprintf('  No finite values.\n');

        else

            fprintf( ...
                '  Minimum                 : %.6g\n', ...
                min(finiteValues(:)));

            fprintf( ...
                '  Maximum                 : %.6g\n', ...
                max(finiteValues(:)));

        end

        fprintf( ...
            '  Time dimension present  : %d\n', ...
            containsTimeDimension);

    end

end

%% =========================================================
% Device switching arrays
%% =========================================================

deviceStateFields = { ...
    'positivePolarity', ...
    'negativePolarity', ...
    'zeroPolarity', ...
    'positiveBridgeState', ...
    'negativeBridgeState', ...
    'positiveBridgeUpperState', ...
    'positiveBridgeLowerState', ...
    'negativeBridgeUpperState', ...
    'negativeBridgeLowerState', ...
    'thyristorState', ...
    'staT111', ...
    'staT211'};

fprintf('\n');
fprintf('DEVICE SWITCHING ARRAYS\n');
fprintf('============================================================\n');

for fieldIndex = 1:numel(deviceStateFields)

    fieldName = ...
        deviceStateFields{fieldIndex};

    if ~isfield(S.Device, fieldName)

        fprintf( ...
            '%-34s MISSING\n', ...
            fieldName);

        continue

    end

    fieldValue = ...
        S.Device.(fieldName);

    fieldSize = ...
        size(fieldValue);

    sizeText = ...
        strjoin( ...
            string(fieldSize), ...
            ' x ');

    containsTimeDimension = ...
        any(fieldSize == numberOfTimeSamples);

    fprintf( ...
        '%-34s %-12s %-18s Time dimension: %d\n', ...
        fieldName, ...
        class(fieldValue), ...
        char(sizeText), ...
        containsTimeDimension);

end

fprintf('============================================================\n');
fprintf('Switching-state inventory: PASS\n');

%% =========================================================
% Save inventory metadata
%% =========================================================

switchingFieldInventory = ...
    struct();

switchingFieldInventory.NumberOfTimeSamples = ...
    numberOfTimeSamples;

switchingFieldInventory.PositiveClass = ...
    class(S.State.positive);

switchingFieldInventory.PositiveSize = ...
    size(S.State.positive);

switchingFieldInventory.NegativeClass = ...
    class(S.State.negative);

switchingFieldInventory.NegativeSize = ...
    size(S.State.negative);

switchingFieldInventory.ZeroClass = ...
    class(S.Zero);

switchingFieldInventory.ZeroSize = ...
    size(S.Zero);

if isstruct(S.Zero)

    switchingFieldInventory.ZeroFields = ...
        fieldnames(S.Zero);

else

    switchingFieldInventory.ZeroFields = ...
        {};

end

switchingFieldInventory.DeviceStateFields = ...
    deviceStateFields;

save( ...
    'DetailedSimulation_SwitchingInventory.mat', ...
    'switchingFieldInventory');

fprintf('Switching inventory file saved: PASS\n');