function P = prepare_cyclo_simulation_inputs(Input, R, Thy)
%PREPARE_CYCLO_SIMULATION_INPUTS
% Prepare and validate all parameters required by the
% ABB-compatible detailed cycloconverter simulation.
%
% Inputs:
%   Input  Structure created by CycloGUI/buildInput
%   R      Result structure returned by cyclo_dimensioning
%   Thy    Selected thyristor database entry
%
% Output:
%   P      Validated simulation parameter structure

arguments
    Input (1,1) struct
    R     (1,1) struct
    Thy   (1,1) struct
end

%% =========================================================
% Required input validation
%% =========================================================

requiredInputFields = { ...
    'fL', ...
    'n_nom', ...
    'PolePairs', ...
    'UM', ...
    'IM', ...
    'Rs', ...
    'Ls', ...
    'cosphi_M', ...
    'PulseNumber', ...
    'a_Nmin', ...
    'gamma0', ...
    'SC_min', ...
    'SC_max', ...
    'ZeroCrossCurrent', ...
    'ZeroCrossT2'};

requiredResultFields = { ...
    'Uv0N', ...
    'I1S'};

requiredThyristorFields = { ...
    'Type', ...
    'UT0', ...
    'Csnub', ...
    'VT1', ...
    'VT2', ...
    'VT3', ...
    'ON1', ...
    'ON2', ...
    'ON3', ...
    'OFF1', ...
    'OFF2', ...
    'OFF3'};

validateRequiredFields( ...
    Input, ...
    requiredInputFields, ...
    'Input');

validateRequiredFields( ...
    R, ...
    requiredResultFields, ...
    'R');

validateRequiredFields( ...
    Thy, ...
    requiredThyristorFields, ...
    'Thy');

%% =========================================================
% Network
%% =========================================================

P.f1 = Input.fL;
P.w1 = 2*pi*P.f1;

if isfield(Input, 'CaseName') && ...
        strcmpi(Input.CaseName, 'SCmax')

    P.networkCase = 'SCmax';
    P.SC = Input.SC_max;

else

    P.networkCase = 'SCmin';
    P.SC = Input.SC_min;

end

%% =========================================================
% Motor
%% =========================================================

P.nNom = Input.n_nom;
P.polePairs = Input.PolePairs;

P.f2 = ...
    P.nNom ...
    * P.polePairs ...
    / 60;

P.w2 = 2*pi*P.f2;

P.Um = Input.UM;
P.Im = Input.IM;
P.Iref = Input.IM;

P.Rs = Input.Rs;

% Input.Ls is already converted from mH to H
% inside CycloGUI/buildInput.
P.Ls = Input.Ls;

P.cosphi = Input.cosphi_M;

P.phi = acos( ...
    max(-1, min(1, P.cosphi)));

%% =========================================================
% Converter
%% =========================================================

P.pulseNumber = Input.PulseNumber;
P.TC = P.pulseNumber / 6;
% Input.a_Nmin is converted from degrees to radians inside
% CycloGUI/buildInput. Therefore, no further conversion is
% required here.
P.alphaMin = ...
    Input.a_Nmin;
P.gamma0 = deg2rad(Input.gamma0);

%% Confirmed mappings from the dimensioning result

P.Uv = R.Uv0N;
P.Itr = R.I1S;

%% Motor and converter phase peak voltages

P.Uo = ...
    P.Um ...
    / sqrt(3) ...
    * sqrt(2);

%% =========================================================
% Converter apparent-power reference
%% =========================================================

P.Str = ...
    sqrt(3) ...
    * P.Uv ...
    * P.Itr ...
    * P.TC;

%% =========================================================
% Equivalent network impedance from short-circuit power
%% =========================================================
%
% For a balanced three-phase system:
%
%       Zsc = ULL^2 / Ssc
%
% This first ABB-compatible implementation uses the
% impedance derived from the selected short-circuit power.

P.Zsc_ohm = ...
    P.Uv^2 ...
    / P.SC;

P.Zsc_pu_group = ...
    sqrt(3) ...
    * P.Uv ...
    * P.Itr ...
    / P.SC;

%% =========================================================
% Effective converter source voltage
%% =========================================================
%
% Scilab form:
%
% U1 = (Uv/sqrt(3)
%       - Ztrsc*Iref*sqrt(6)/pi)*sqrt(2)
%
% In this first version, Ztrsc is represented by the
% network equivalent impedance obtained from SCmin/SCmax.

P.U1 = ...
    (P.Uv/sqrt(3) ...
    - P.Zsc_ohm ...
    * P.Iref ...
    * sqrt(6)/pi) ...
    * sqrt(2);

%% =========================================================
% Zero-current interval
%% =========================================================

P.zeroCrossCurrent = Input.ZeroCrossCurrent;
P.T2 = Input.ZeroCrossT2;

P.zeroCurrentRatio = ...
    P.zeroCrossCurrent ...
    / (sqrt(2) * P.Iref);
%% Validate zero-current inputs before calling acos

if ~isfinite(P.zeroCurrentRatio) || ...
        P.zeroCurrentRatio < 0 || ...
        P.zeroCurrentRatio >= 1

    error( ...
        'Cyclo:InvalidZeroCrossCurrent', ...
        ['Zero-crossing current must satisfy ', ...
         '0 <= Izero < sqrt(2)*Iref.']);

end

if ~isfinite(P.T2) || P.T2 < 0

    error( ...
        'Cyclo:InvalidZeroCrossingTime', ...
        ['The additional zero-current time T2 must be ', ...
         'finite and non-negative.']);

end

P.tzero = ...
    2 ...
    * (pi/2 ...
    - acos(P.zeroCurrentRatio)) ...
    / P.w2 ...
    + P.T2;

P.w2Modified = ...
    2*pi ...
    / (1/P.f2 - 2*P.tzero);

%% =========================================================
% Thyristor parameters
%% =========================================================

P.thyristorType = Thy.Type;

P.UT0 = Thy.UT0;
P.Csnub = Thy.Csnub;

P.VT = [ ...
    Thy.VT1, ...
    Thy.VT2, ...
    Thy.VT3];

P.Eon = [ ...
    Thy.ON1, ...
    Thy.ON2, ...
    Thy.ON3];

P.Eoff = [ ...
    Thy.OFF1, ...
    Thy.OFF2, ...
    Thy.OFF3];

%% =========================================================
% Numerical settings
%% =========================================================

P.dt = 1e-6;

P.numberOfIntervals = ...
    ceil( ...
        P.f1 ...
        / P.f2 ...
        * P.pulseNumber);

P.samplesPerInterval = ...
    floor( ...
        1 ...
        / (2 ...
        * P.f1 ...
        * P.pulseNumber ...
        * P.dt) ...
        - 1);

P.totalSamples = ...
    P.numberOfIntervals ...
    * P.samplesPerInterval;

%% Transformer/converter group phase shifts
%
% 6 pulse:   0 degrees
% 12 pulse:  0, -30 degrees
% 18 pulse:  0, -20, -40 degrees
% 24 pulse:  0, -15, -30, -45 degrees

P.groupPhaseShift = ...
    -(0:P.TC-1) ...
    * 2*pi ...
    / P.pulseNumber;
%% =========================================================
% Parameter metadata
%% =========================================================

P.angleUnit = ...
    'rad';

P.timeUnit = ...
    's';

P.voltageUnit = ...
    'V';

P.currentUnit = ...
    'A';

P.inductanceUnit = ...
    'H';

P.shortCircuitPowerUnit = ...
    'VA';

P.parameterStatus = ...
    'Prepared and validated';
%% =========================================================
% Validation
%% =========================================================

validatePreparedParameters(P);

end


function validateRequiredFields(S, requiredFields, structureName)

for fieldIndex = 1:numel(requiredFields)

    fieldName = requiredFields{fieldIndex};

    if ~isfield(S, fieldName)

        error( ...
            'Cyclo:MissingSimulationField', ...
            '%s is missing required field %s.', ...
            structureName, ...
            fieldName);

    end

end

end


function validatePreparedParameters(P)
%% =========================================================
% Scalar and finite-value validation
%% =========================================================

scalarNumericFields = { ...
    'f1', ...
    'f2', ...
    'w1', ...
    'w2', ...
    'nNom', ...
    'polePairs', ...
    'Um', ...
    'Im', ...
    'Iref', ...
    'Rs', ...
    'Ls', ...
    'cosphi', ...
    'phi', ...
    'pulseNumber', ...
    'TC', ...
    'alphaMin', ...
    'gamma0', ...
    'Uv', ...
    'Itr', ...
    'Uo', ...
    'Str', ...
    'SC', ...
    'Zsc_ohm', ...
    'Zsc_pu_group', ...
    'U1', ...
    'zeroCrossCurrent', ...
    'T2', ...
    'zeroCurrentRatio', ...
    'tzero', ...
    'w2Modified', ...
    'UT0', ...
    'Csnub', ...
    'dt', ...
    'numberOfIntervals', ...
    'samplesPerInterval', ...
    'totalSamples'};

for fieldIndex = 1:numel(scalarNumericFields)

    fieldName = ...
        scalarNumericFields{fieldIndex};

    fieldValue = ...
        P.(fieldName);

    if ~isnumeric(fieldValue) || ...
            ~isscalar(fieldValue) || ...
            ~isfinite(fieldValue)

        error( ...
            'Cyclo:InvalidPreparedScalar', ...
            ['Prepared parameter P.%s must be a finite ', ...
             'numeric scalar.'], ...
            fieldName);

    end

end
%% =========================================================
% Thyristor coefficient-vector validation
%% =========================================================

coefficientFields = { ...
    'VT', ...
    'Eon', ...
    'Eoff'};

for fieldIndex = 1:numel(coefficientFields)

    fieldName = ...
        coefficientFields{fieldIndex};

    coefficientVector = ...
        P.(fieldName);

    if ~isnumeric(coefficientVector) || ...
            numel(coefficientVector) ~= 3 || ...
            any(~isfinite(coefficientVector(:)))

        error( ...
            'Cyclo:InvalidThyristorCoefficientVector', ...
            ['Prepared parameter P.%s must contain exactly ', ...
             'three finite numeric coefficients.'], ...
            fieldName);

    end

end

if P.UT0 < 0

    error( ...
        'Cyclo:InvalidThresholdVoltage', ...
        'The thyristor threshold voltage UT0 cannot be negative.');

end

if P.Csnub < 0

    error( ...
        'Cyclo:InvalidSnubberCapacitance', ...
        'The snubber capacitance Csnub cannot be negative.');

end
if ~ismember(P.pulseNumber, [6, 12, 18, 24])

    error( ...
        'Cyclo:UnsupportedPulseNumber', ...
        ['Detailed simulation supports pulse numbers ', ...
         '6, 12, 18, and 24.']);

end

if mod(P.pulseNumber, 6) ~= 0

    error( ...
        'Cyclo:InvalidPulseNumber', ...
        'Pulse number must be a multiple of six.');

end
if P.TC ~= round(P.TC) || P.TC < 1

    error( ...
        'Cyclo:InvalidConverterGroupCount', ...
        ['The converter-group count P.TC must be a positive ', ...
         'integer.']);
end

if numel(P.groupPhaseShift) ~= P.TC

    error( ...
        'Cyclo:GroupPhaseShiftCountMismatch', ...
        ['The transformer phase-shift vector must contain ', ...
         'one value per converter group.']);

end

if any(~isfinite(P.groupPhaseShift))

    error( ...
        'Cyclo:InvalidGroupPhaseShift', ...
        'Transformer group phase shifts must be finite.');

end
if P.f1 <= 0 || P.f2 <= 0

    error( ...
        'Cyclo:InvalidFrequency', ...
        'Input and motor frequencies must be positive.');

end

if P.f2 >= P.f1

    error( ...
        'Cyclo:InvalidFrequencyRatio', ...
        ['Motor frequency must be lower than ', ...
         'the converter input frequency.']);

end

if P.Um <= 0 || P.Uv <= 0 || P.U1 <= 0

    error( ...
        'Cyclo:InvalidVoltage', ...
        ['Motor voltage, converter voltage, and calculated ', ...
         'source voltage must be positive.']);

end

if P.Im <= 0 || P.Itr <= 0

    error( ...
        'Cyclo:InvalidCurrent', ...
        'Motor and converter currents must be positive.');

end

if P.SC <= 0

    error( ...
        'Cyclo:InvalidShortCircuitPower', ...
        'Selected short-circuit power must be positive.');

end

if P.Rs < 0 || P.Ls <= 0

    error( ...
        'Cyclo:InvalidMotorImpedance', ...
        'Rs must be non-negative and Ls must be positive.');

end

if P.cosphi <= 0 || P.cosphi > 1

    error( ...
        'Cyclo:InvalidPowerFactor', ...
        'Power factor must satisfy 0 < cos(phi) <= 1.');

end

if P.alphaMin < 0 || P.alphaMin >= pi

    error( ...
        'Cyclo:InvalidMinimumFiringAngle', ...
        ['Minimum firing angle must satisfy ', ...
         '0 <= alphaMin < pi.']);

end
if P.gamma0 < 0 || P.gamma0 >= pi

    error( ...
        'Cyclo:InvalidExtinctionAngle', ...
        ['The extinction margin gamma0 must satisfy ', ...
         '0 <= gamma0 < pi.']);

end

if P.zeroCrossCurrent < 0 || ...
        P.zeroCurrentRatio < 0 || ...
        P.zeroCurrentRatio >= 1

    error( ...
        'Cyclo:InvalidZeroCrossCurrent', ...
        ['Zero-crossing current must satisfy ', ...
         '0 <= Izero < sqrt(2)*Iref.']);

end
if P.T2 < 0

    error( ...
        'Cyclo:InvalidZeroCrossingTime', ...
        'The additional zero-current time T2 cannot be negative.');

end

if P.tzero < 0 || ~isfinite(P.tzero)

    error( ...
        'Cyclo:InvalidCalculatedZeroTime', ...
        ['The calculated zero-current interval must be ', ...
         'finite and non-negative.']);

end

if P.w2Modified <= 0 || ~isfinite(P.w2Modified)

    error( ...
        'Cyclo:InvalidModifiedMotorFrequency', ...
        ['The modified motor angular frequency must be ', ...
         'finite and positive.']);

end

if 2*P.tzero >= 1/P.f2

    error( ...
        'Cyclo:InvalidZeroCurrentInterval', ...
        ['The combined zero-current intervals are ', ...
         'too long for one motor period.']);

end
if P.dt <= 0

    error( ...
        'Cyclo:InvalidSimulationTimeStep', ...
        'The simulation time step P.dt must be positive.');

end
if P.samplesPerInterval < 1

    error( ...
        'Cyclo:InvalidTimeStep', ...
        'The selected time step is too large.');

end
if P.numberOfIntervals < 1 || ...
        P.numberOfIntervals ~= round(P.numberOfIntervals)

    error( ...
        'Cyclo:InvalidIntervalCount', ...
        ['The number of converter intervals must be a ', ...
         'positive integer.']);

end
if P.samplesPerInterval ~= round(P.samplesPerInterval)

    error( ...
        'Cyclo:InvalidSamplesPerInterval', ...
        'Samples per converter interval must be an integer.');

end
if P.totalSamples < 1 || ...
        P.totalSamples ~= round(P.totalSamples)

    error( ...
        'Cyclo:InvalidTotalSampleCount', ...
        'The total sample count must be a positive integer.');

end
if P.totalSamples ~= ...
        P.numberOfIntervals * P.samplesPerInterval

    error( ...
        'Cyclo:TotalSampleCountMismatch', ...
        ['The total sample count must equal the interval ', ...
         'count multiplied by samples per interval.']);

end
if P.totalSamples < 100

    error( ...
        'Cyclo:InsufficientSamples', ...
        'The simulation record contains too few samples.');

end

end