function Loss = calculate_cyclo_converter_losses( ...
    P, ...
    Voltage, ...
    Current, ...
    Device, ...
    Thy)
%CALCULATE_CYCLO_CONVERTER_LOSSES
% Calculate thyristor conduction loss, turn-on loss,
% turn-off loss, snubber loss, and total converter loss.
%
% The calculation follows the original ABB Scilab loss model
% while also calculating every modeled thyristor explicitly.
%
% Inputs:
%   P        Prepared simulation parameters
%   Voltage  Cycloconverter voltage structure
%   Current  Motor-current structure
%   Device   Stage 5 device-current structure
%   Thy      Selected thyristor database entry
%
% Output:
%   Loss     Device, group, phase, and total loss results
%
% Device array organization:
%
%   sample x thyristor x group x output phase
%
% Physical thyristor order:
%
%   Positive converter bridge:
%    1 = PT1
%    2 = PT3
%    3 = PT5
%    4 = PT4
%    5 = PT6
%    6 = PT2
%
%   Negative converter bridge:
%    7 = NT1
%    8 = NT3
%    9 = NT5
%   10 = NT4
%   11 = NT6
%   12 = NT2

arguments
    P       (1,1) struct
    Voltage (1,1) struct
    Current (1,1) struct
    Device  (1,1) struct
    Thy     (1,1) struct
end

%% =========================================================
% Required field validation
%% =========================================================

requiredThyristorFields = { ...
    'Type', ...
    'VT1', ...
    'VT2', ...
    'VT3', ...
    'ON1', ...
    'ON2', ...
    'ON3', ...
    'OFF1', ...
    'OFF2', ...
    'OFF3', ...
    'Csnub'};

for fieldIndex = 1:numel(requiredThyristorFields)

    fieldName = ...
        requiredThyristorFields{fieldIndex};

    if ~isfield(Thy, fieldName)

        error( ...
            'Cyclo:MissingLossCoefficient', ...
            'Thyristor %s is missing field %s.', ...
            Thy.Type, ...
            fieldName);

    end

end

requiredDeviceFields = { ...
    'thyristorState', ...
    'thyristorCurrent', ...
    'turnOnCount', ...
    'turnOffCount'};

for fieldIndex = 1:numel(requiredDeviceFields)

    fieldName = ...
        requiredDeviceFields{fieldIndex};

    if ~isfield(Device, fieldName)

        error( ...
            'Cyclo:MissingDeviceLossField', ...
            'Device is missing required field %s.', ...
            fieldName);

    end

end

if ~isfield(Voltage, 't')

    error( ...
        'Cyclo:MissingLossTimeVector', ...
        'Voltage.t is required for the loss calculation.');

end

%% =========================================================
% Dimensions
%% =========================================================

numberOfSamples = ...
    numel(Voltage.t);

numberOfThyristors = ...
    12;

numberOfGroups = ...
    P.TC;

numberOfOutputPhases = ...
    3;

expectedStateSize = [ ...
    numberOfSamples, ...
    numberOfThyristors, ...
    numberOfGroups, ...
    numberOfOutputPhases];

if size(Device.thyristorState,1) ~= ...
        expectedStateSize(1) || ...
        size(Device.thyristorState,2) ~= ...
        expectedStateSize(2) || ...
        size(Device.thyristorState,3) ~= ...
        expectedStateSize(3) || ...
        size(Device.thyristorState,4) ~= ...
        expectedStateSize(4)

    error( ...
        'Cyclo:LossStateDimensionMismatch', ...
        ['Thyristor-state dimensions do not match ', ...
         'the converter configuration.']);

end

if size(Device.thyristorCurrent,1) ~= ...
        numberOfSamples || ...
        size(Device.thyristorCurrent,2) ~= ...
        numberOfThyristors || ...
        size(Device.thyristorCurrent,3) ~= ...
        numberOfGroups || ...
        size(Device.thyristorCurrent,4) ~= ...
        numberOfOutputPhases

    error( ...
        'Cyclo:LossCurrentDimensionMismatch', ...
        ['Thyristor-current dimensions do not match ', ...
         'the converter configuration.']);

end

%% =========================================================
% Time quantities
%% =========================================================

simulationDuration = ...
    Voltage.t(end) ...
    - Voltage.t(1) ...
    + P.dt;

if simulationDuration <= 0

    error( ...
        'Cyclo:InvalidLossSimulationDuration', ...
        'The loss simulation duration must be positive.');

end

motorPeriod = ...
    1/P.f2;

periodScalingFactor = ...
    motorPeriod ...
    / simulationDuration;

%% =========================================================
% Loss coefficients
%% =========================================================

Loss.VTCoefficients = [ ...
    Thy.VT1, ...
    Thy.VT2, ...
    Thy.VT3];

Loss.turnOnCoefficients = [ ...
    Thy.ON1, ...
    Thy.ON2, ...
    Thy.ON3];

Loss.turnOffCoefficients = [ ...
    Thy.OFF1, ...
    Thy.OFF2, ...
    Thy.OFF3];

Loss.thyristorType = ...
    Thy.Type;

Loss.thyristorOrder = ...
    Device.thyristorOrder;

%% =========================================================
% Preallocate per-device result arrays
%% =========================================================
%
% Dimensions:
%
%   thyristor x group x output phase

resultSize = [ ...
    numberOfThyristors, ...
    numberOfGroups, ...
    numberOfOutputPhases];

Loss.conductionEnergy = ...
    zeros(resultSize);

Loss.turnOnEnergy = ...
    zeros(resultSize);

Loss.turnOffEnergy = ...
    zeros(resultSize);

Loss.conductionPower = ...
    zeros(resultSize);

Loss.turnOnPower = ...
    zeros(resultSize);

Loss.turnOffPower = ...
    zeros(resultSize);

Loss.totalDevicePower = ...
    zeros(resultSize);

Loss.turnOnCount = ...
    zeros(resultSize);

Loss.turnOffCount = ...
    zeros(resultSize);

Loss.minimumForwardDrop = ...
    zeros(resultSize);

Loss.maximumForwardDrop = ...
    zeros(resultSize);

%% =========================================================
% Turn-off voltage
%% =========================================================
%
% Direct translation of the Scilab expression:
%
%   Uv * sqrt(2)

turnOffVoltage = ...
    P.Uv ...
    * sqrt(2);

Loss.turnOffVoltage = ...
    turnOffVoltage;

%% =========================================================
% Main device-loss loop
%% =========================================================

for outputPhase = 1:numberOfOutputPhases

    for groupNumber = 1:numberOfGroups

        for thyristorNumber = 1:numberOfThyristors

            state = ...
                Device.thyristorState( ...
                    :, ...
                    thyristorNumber, ...
                    groupNumber, ...
                    outputPhase);

            current = ...
                Device.thyristorCurrent( ...
                    :, ...
                    thyristorNumber, ...
                    groupNumber, ...
                    outputPhase);

            state = ...
                logical(state(:));

            current = ...
                current(:);

            %% ---------------------------------------------
            % Conduction voltage
            %% ---------------------------------------------

            forwardVoltage = ...
                Thy.VT1 ...
                .* current.^2 ...
                + Thy.VT2 ...
                .* current ...
                + Thy.VT3;

            % The fitted polynomial is used only while the
            % thyristor conducts.

            forwardVoltage(~state) = 0;

            %% Protect against nonphysical negative values

            forwardVoltage = ...
                max( ...
                    forwardVoltage, ...
                    0);

            conductionPowerWaveform = ...
                forwardVoltage ...
                .* current;

            conductionEnergy = ...
                sum(conductionPowerWaveform) ...
                * P.dt;

            %% ---------------------------------------------
            % Switching transitions
            %% ---------------------------------------------

            stateDifference = ...
                diff( ...
                    [false; state]);

            turnOnIndex = ...
                find(stateDifference > 0);

            turnOffIndex = ...
                find(stateDifference < 0);

            %% Include possible transition at record boundary
            %
            % The waveform represents one periodic operating
            % cycle. If the device is on at the end and off
            % at the beginning, include the boundary turn-off.
            % If it is off at the end and on at the beginning,
            % include the boundary turn-on.

            if state(end) && ~state(1)

                turnOffIndex = [ ...
                    turnOffIndex
                    numberOfSamples];

            elseif ~state(end) && state(1)

                turnOnIndex = [ ...
                    turnOnIndex
                    1];

            end

            turnOnIndex = ...
                unique(turnOnIndex);

            turnOffIndex = ...
                unique(turnOffIndex);

            %% ---------------------------------------------
            % Turn-on energy
            %% ---------------------------------------------

            if isempty(turnOnIndex)

                turnOnEnergy = 0;

            else

                turnOnCurrent = ...
                    current(turnOnIndex);

                turnOnEnergyVector = ...
                    Thy.ON1 ...
                    .* turnOnCurrent.^2 ...
                    + Thy.ON2 ...
                    .* turnOnCurrent ...
                    + Thy.ON3;

                % Fitted switching-energy equations should
                % not produce negative physical energy.

                turnOnEnergyVector = ...
                    max( ...
                        turnOnEnergyVector, ...
                        0);

                turnOnEnergy = ...
                    sum(turnOnEnergyVector);

            end

            %% ---------------------------------------------
            % Turn-off energy
            %% ---------------------------------------------

            if isempty(turnOffIndex)

                turnOffEnergy = 0;

            else

                turnOffEnergyPerEvent = ...
                    Thy.OFF1 ...
                    * turnOffVoltage^2 ...
                    + Thy.OFF2 ...
                    * turnOffVoltage ...
                    + Thy.OFF3;

                turnOffEnergyPerEvent = ...
                    max( ...
                        turnOffEnergyPerEvent, ...
                        0);

                turnOffEnergy = ...
                    numel(turnOffIndex) ...
                    * turnOffEnergyPerEvent;

            end

            %% ---------------------------------------------
            % Convert record energy to average power
            %% ---------------------------------------------

            conductionPower = ...
                conductionEnergy ...
                / simulationDuration;

            turnOnPower = ...
                turnOnEnergy ...
                / simulationDuration;

            turnOffPower = ...
                turnOffEnergy ...
                / simulationDuration;

            totalDevicePower = ...
                conductionPower ...
                + turnOnPower ...
                + turnOffPower;

            %% ---------------------------------------------
            % Store results
            %% ---------------------------------------------

            Loss.conductionEnergy( ...
                thyristorNumber, ...
                groupNumber, ...
                outputPhase) = ...
                conductionEnergy;

            Loss.turnOnEnergy( ...
                thyristorNumber, ...
                groupNumber, ...
                outputPhase) = ...
                turnOnEnergy;

            Loss.turnOffEnergy( ...
                thyristorNumber, ...
                groupNumber, ...
                outputPhase) = ...
                turnOffEnergy;

            Loss.conductionPower( ...
                thyristorNumber, ...
                groupNumber, ...
                outputPhase) = ...
                conductionPower;

            Loss.turnOnPower( ...
                thyristorNumber, ...
                groupNumber, ...
                outputPhase) = ...
                turnOnPower;

            Loss.turnOffPower( ...
                thyristorNumber, ...
                groupNumber, ...
                outputPhase) = ...
                turnOffPower;

            Loss.totalDevicePower( ...
                thyristorNumber, ...
                groupNumber, ...
                outputPhase) = ...
                totalDevicePower;

            Loss.turnOnCount( ...
                thyristorNumber, ...
                groupNumber, ...
                outputPhase) = ...
                numel(turnOnIndex);

            Loss.turnOffCount( ...
                thyristorNumber, ...
                groupNumber, ...
                outputPhase) = ...
                numel(turnOffIndex);

            conductingVoltage = ...
                forwardVoltage(state);

            if isempty(conductingVoltage)

                Loss.minimumForwardDrop( ...
                    thyristorNumber, ...
                    groupNumber, ...
                    outputPhase) = 0;

                Loss.maximumForwardDrop( ...
                    thyristorNumber, ...
                    groupNumber, ...
                    outputPhase) = 0;

            else

                Loss.minimumForwardDrop( ...
                    thyristorNumber, ...
                    groupNumber, ...
                    outputPhase) = ...
                    min(conductingVoltage);

                Loss.maximumForwardDrop( ...
                    thyristorNumber, ...
                    groupNumber, ...
                    outputPhase) = ...
                    max(conductingVoltage);

            end

        end

    end

end

%% =========================================================
% Aggregate loss by converter group
%% =========================================================

Loss.groupConductionPower = ...
    reshape( ...
        sum( ...
            sum( ...
                Loss.conductionPower, ...
                1), ...
            3), ...
        numberOfGroups, ...
        1);

Loss.groupTurnOnPower = ...
    reshape( ...
        sum( ...
            sum( ...
                Loss.turnOnPower, ...
                1), ...
            3), ...
        numberOfGroups, ...
        1);

Loss.groupTurnOffPower = ...
    reshape( ...
        sum( ...
            sum( ...
                Loss.turnOffPower, ...
                1), ...
            3), ...
        numberOfGroups, ...
        1);

Loss.groupThyristorPower = ...
    Loss.groupConductionPower ...
    + Loss.groupTurnOnPower ...
    + Loss.groupTurnOffPower;

%% =========================================================
% Aggregate loss by output phase
%% =========================================================

Loss.phaseConductionPower = ...
    reshape( ...
        sum( ...
            sum( ...
                Loss.conductionPower, ...
                1), ...
            2), ...
        numberOfOutputPhases, ...
        1);

Loss.phaseTurnOnPower = ...
    reshape( ...
        sum( ...
            sum( ...
                Loss.turnOnPower, ...
                1), ...
            2), ...
        numberOfOutputPhases, ...
        1);

Loss.phaseTurnOffPower = ...
    reshape( ...
        sum( ...
            sum( ...
                Loss.turnOffPower, ...
                1), ...
            2), ...
        numberOfOutputPhases, ...
        1);

Loss.phaseThyristorPower = ...
    Loss.phaseConductionPower ...
    + Loss.phaseTurnOnPower ...
    + Loss.phaseTurnOffPower;

%% =========================================================
% Total thyristor losses
%% =========================================================

Loss.totalConductionPower = ...
    sum( ...
        Loss.conductionPower(:));

Loss.totalTurnOnPower = ...
    sum( ...
        Loss.turnOnPower(:));

Loss.totalTurnOffPower = ...
    sum( ...
        Loss.turnOffPower(:));

Loss.totalThyristorPower = ...
    Loss.totalConductionPower ...
    + Loss.totalTurnOnPower ...
    + Loss.totalTurnOffPower;

%% =========================================================
% Snubber loss
%% =========================================================
%
% Direct translation of:
%
% psnub =
%   p*6/2
%   *1.75*f1*Csnub
%   *(Uv*sqrt(2))^2
%
% The result is in watts when:
%   f1     is in Hz
%   Csnub  is in farads
%   Uv     is in volts

numberOfSnubberBranches = ...
    P.pulseNumber ...
    * 6 ...
    / 2;

Loss.numberOfSnubberBranches = ...
    numberOfSnubberBranches;

Loss.snubberPower = ...
    numberOfSnubberBranches ...
    * 1.75 ...
    * P.f1 ...
    * Thy.Csnub ...
    * turnOffVoltage^2;

%% =========================================================
% Total converter loss
%% =========================================================

Loss.totalConverterPower = ...
    Loss.totalThyristorPower ...
    + Loss.snubberPower;

%% =========================================================
% kW outputs
%% =========================================================

Loss.totalConductionPowerkW = ...
    Loss.totalConductionPower ...
    / 1000;

Loss.totalTurnOnPowerkW = ...
    Loss.totalTurnOnPower ...
    / 1000;

Loss.totalTurnOffPowerkW = ...
    Loss.totalTurnOffPower ...
    / 1000;

Loss.totalThyristorPowerkW = ...
    Loss.totalThyristorPower ...
    / 1000;

Loss.snubberPowerkW = ...
    Loss.snubberPower ...
    / 1000;

Loss.totalConverterPowerkW = ...
    Loss.totalConverterPower ...
    / 1000;

Loss.groupConductionPowerkW = ...
    Loss.groupConductionPower ...
    / 1000;

Loss.groupTurnOnPowerkW = ...
    Loss.groupTurnOnPower ...
    / 1000;

Loss.groupTurnOffPowerkW = ...
    Loss.groupTurnOffPower ...
    / 1000;

Loss.groupThyristorPowerkW = ...
    Loss.groupThyristorPower ...
    / 1000;

%% =========================================================
% Representative T111 result
%% =========================================================

Loss.T111.conductionPower = ...
    Loss.conductionPower(1,1,1);

Loss.T111.turnOnPower = ...
    Loss.turnOnPower(1,1,1);

Loss.T111.turnOffPower = ...
    Loss.turnOffPower(1,1,1);

Loss.T111.totalPower = ...
    Loss.totalDevicePower(1,1,1);

Loss.T111.turnOnCount = ...
    Loss.turnOnCount(1,1,1);

Loss.T111.turnOffCount = ...
    Loss.turnOffCount(1,1,1);

Loss.T111.currentRms = ...
    Device.thyristorRmsCurrent(1,1,1);

Loss.T111.currentAverage = ...
    Device.thyristorAverageCurrent(1,1,1);

Loss.T111.currentPeak = ...
    Device.thyristorPeakCurrent(1,1,1);
%% =========================================================
% Scilab representative-device scaling diagnostic
%% =========================================================

Loss.scilabScaleCount = ...
    P.pulseNumber * 6;

Loss.scilabScaledConductionPower = ...
    Loss.T111.conductionPower ...
    * Loss.scilabScaleCount;

Loss.scilabScaledTurnOnPower = ...
    Loss.T111.turnOnPower ...
    * Loss.scilabScaleCount;

Loss.scilabScaledTurnOffPower = ...
    Loss.T111.turnOffPower ...
    * Loss.scilabScaleCount;

Loss.scilabScaledThyristorPower = ...
    Loss.scilabScaledConductionPower ...
    + Loss.scilabScaledTurnOnPower ...
    + Loss.scilabScaledTurnOffPower;

Loss.explicitTurnOnEventCount = ...
    sum(Loss.turnOnCount(:));

Loss.explicitTurnOffEventCount = ...
    sum(Loss.turnOffCount(:));

Loss.scilabScaledTurnOnEventCount = ...
    Loss.T111.turnOnCount ...
    * Loss.scilabScaleCount;

Loss.scilabScaledTurnOffEventCount = ...
    Loss.T111.turnOffCount ...
    * Loss.scilabScaleCount;

Loss.conductionScaleRatio = ...
    Loss.scilabScaledConductionPower ...
    / max(Loss.totalConductionPower, eps);

Loss.turnOnScaleRatio = ...
    Loss.scilabScaledTurnOnPower ...
    / max(Loss.totalTurnOnPower, eps);

Loss.turnOffScaleRatio = ...
    Loss.scilabScaledTurnOffPower ...
    / max(Loss.totalTurnOffPower, eps);
%% =========================================================
% Metadata
%% =========================================================

Loss.simulationDuration = ...
    simulationDuration;

Loss.motorPeriod = ...
    motorPeriod;

Loss.periodScalingFactor = ...
    periodScalingFactor;

Loss.numberOfGroups = ...
    numberOfGroups;

Loss.numberOfOutputPhases = ...
    numberOfOutputPhases;

Loss.numberOfThyristorsPerBridgePair = ...
    numberOfThyristors;

Loss.totalModeledThyristors = ...
    numberOfThyristors ...
    * numberOfGroups ...
    * numberOfOutputPhases;
expectedPhysicalThyristors = ...
    P.pulseNumber ...
    * 6;

if Loss.totalModeledThyristors ~= ...
        expectedPhysicalThyristors

    error( ...
        'Cyclo:LossPhysicalThyristorCountMismatch', ...
        ['The loss model contains %d physical thyristors, ', ...
         'but the converter topology requires %d.'], ...
        Loss.totalModeledThyristors, ...
        expectedPhysicalThyristors);

end

Loss.expectedPhysicalThyristors = ...
    expectedPhysicalThyristors;

%% =========================================================
% Validation
%% =========================================================

numericFields = { ...
    'conductionPower', ...
    'turnOnPower', ...
    'turnOffPower', ...
    'totalDevicePower', ...
    'groupConductionPower', ...
    'groupTurnOnPower', ...
    'groupTurnOffPower', ...
    'totalConductionPower', ...
    'totalTurnOnPower', ...
    'totalTurnOffPower', ...
    'totalThyristorPower', ...
    'snubberPower', ...
    'totalConverterPower'};

for fieldIndex = 1:numel(numericFields)

    fieldName = ...
        numericFields{fieldIndex};

    if any(~isfinite(Loss.(fieldName)(:)))

        error( ...
            'Cyclo:NonFiniteConverterLoss', ...
            'Loss.%s contains invalid values.', ...
            fieldName);

    end

    if any(Loss.(fieldName)(:) < 0)

        error( ...
            'Cyclo:NegativeConverterLoss', ...
            'Loss.%s contains negative physical loss.', ...
            fieldName);

    end

end

if Loss.totalConverterPower <= 0

    error( ...
        'Cyclo:NonPositiveTotalLoss', ...
        'Total converter loss must be positive.');

end

if abs( ...
        Loss.totalConverterPower ...
        - ( ...
        Loss.totalThyristorPower ...
        + Loss.snubberPower)) ...
        > 1e-9 ...
        * max(1,Loss.totalConverterPower)

    error( ...
        'Cyclo:ConverterLossBalanceError', ...
        'The converter-loss balance is inconsistent.');

end

end