function FanDB = DCS880_FanDatabase()
%DCS880_FANDATABASE  Cooling fan ratings matched to each DCS880 frame size.
%
%   FanDB = DCS880_FanDatabase() returns a struct array, one entry per
%   frame size, with fields:
%     Size, Fan, Frequency, Voltage, Connection, Power, Current,
%     BlockingCurrent
%
%   excitation_calculation.m looks up the entry matching the DCS880
%   frame size chosen by DCS880_FieldDatabase.
%
%   Data values are unchanged from the original.

FanDB = [ ...
    struct( ...
        'Size', 'H4', ...
        'Fan', 'W2E200', ...
        'Frequency', 50, ...
        'Voltage', 230, ...
        'Connection', '1~', ...
        'Power', 64, ...
        'Current', 0.29, ...
        'BlockingCurrent', 0.7) ...
    struct( ...
        'Size', 'H6', ...
        'Fan', 'R2E250-RB', ...
        'Frequency', 50, ...
        'Voltage', 230, ...
        'Connection', '1~', ...
        'Power', 227, ...
        'Current', 1.1, ...
        'BlockingCurrent', 3.1) ...
    struct( ...
        'Size', 'H7', ...
        'Fan', 'GR28C-2DK', ...
        'Frequency', 50, ...
        'Voltage', 400, ...
        'Connection', 'Delta/Y', ...
        'Power', 660, ...
        'Current', 1.4, ...
        'BlockingCurrent', 8.0) ...
    struct( ...
        'Size', 'H8', ...
        'Fan', 'GR35C-2DD', ...
        'Frequency', 50, ...
        'Voltage', 400, ...
        'Connection', 'Delta', ...
        'Power', 2100, ...
        'Current', 4.0, ...
        'BlockingCurrent', 17.0) ...
    ];

%% Validation: warn if a DCS880 frame size has no matching fan entry
FieldDB = DCS880_FieldDatabase();
missingSizes = setdiff(unique({FieldDB.Size}), {FanDB.Size});
if ~isempty(missingSizes)
    warning('DCS880_FanDatabase:MissingSize', ...
        'No fan entry for frame size(s): %s', strjoin(missingSizes, ', '));
end

end
