function FanDB = DCS880_FanDatabase()
%DCS880_FANDATABASE  Cooling fan ratings matched to each DCS880 frame size.
%
%   FanDB = DCS880_FanDatabase() returns a struct array, one entry per
%   frame-Size/Frequency combination, with fields:
%     Size, Frequency, Fan, Voltage, Tolerance, Connection, Power,
%     Current, BlockingCurrent
%
%   excitation_calculation.m looks up the entry matching BOTH the DCS880
%   frame size chosen by DCS880_FieldDatabase AND the supply frequency
%   (Input.FanFrequency).
%
%   Source: user-supplied reference workbook "Excitation_design.xlsx",
%   sheet "Excitation", table AE7:AL18 (columns Size/Frequency/Voltage/
%   Tolerance/Connection/Power/Current/BlockingCurrent). That table has
%   NO "Fan model" column -- the Fan part-number strings below (e.g.
%   'R2E250-RB') are carried over unverified from the tool's original,
%   pre-audit database and could not be cross-checked against this
%   reference document. The workbook's own table also has NO row at all
%   for frame sizes H3 or H4 (any Size/Frequency), for any voltage class:
%   consult the ABB DCS880 hardware manual to confirm actual fan
%   requirements for those sizes -- this tool does not guess a value.
%
%   H7 @ 50 Hz has a workbook-listed dual rating depending on fan wiring
%   (Delta vs. Y connection): Power 660/600 W, Current 1.4/0.8 A,
%   BlockingCurrent 8.0/2.8 A. The Delta values are used as the primary
%   Power/Current/BlockingCurrent (matching the tool's pre-existing
%   default); the Y-connection alternative is retained in the *_Y fields
%   for reference.

FanDB = [ ...
    struct( ...
        'Size', 'H6', ...
        'Frequency', 50, ...
        'Fan', 'R2E250-RB', ...
        'Voltage', '230', ...
        'Tolerance', '+/-10', ...
        'Connection', '1~', ...
        'Power', 227, ...
        'Current', 1.1, ...
        'BlockingCurrent', 3.1, ...
        'Power_Y', NaN, 'Current_Y', NaN, 'BlockingCurrent_Y', NaN) ...
    struct( ...
        'Size', 'H6', ...
        'Frequency', 60, ...
        'Fan', '', ...
        'Voltage', '230', ...
        'Tolerance', '+/-10', ...
        'Connection', '1~', ...
        'Power', 390, ...
        'Current', 1.7, ...
        'BlockingCurrent', 3.1, ...
        'Power_Y', NaN, 'Current_Y', NaN, 'BlockingCurrent_Y', NaN) ...
    struct( ...
        'Size', 'H7', ...
        'Frequency', 50, ...
        'Fan', 'GR28C-2DK', ...
        'Voltage', '400-500', ...
        'Tolerance', '+/-10', ...
        'Connection', 'Delta/Y', ...
        'Power', 660, ...
        'Current', 1.4, ...
        'BlockingCurrent', 8.0, ...
        'Power_Y', 600, 'Current_Y', 0.8, 'BlockingCurrent_Y', 2.8) ...
    struct( ...
        'Size', 'H7', ...
        'Frequency', 60, ...
        'Fan', '', ...
        'Voltage', '460', ...
        'Tolerance', '+/-10', ...
        'Connection', 'Delta', ...
        'Power', 1100, ...
        'Current', 1.8, ...
        'BlockingCurrent', 8, ...
        'Power_Y', NaN, 'Current_Y', NaN, 'BlockingCurrent_Y', NaN) ...
    struct( ...
        'Size', 'H8', ...
        'Frequency', 50, ...
        'Fan', 'GR35C-2DD', ...
        'Voltage', '400-500', ...
        'Tolerance', '+5/-10', ...
        'Connection', 'Delta', ...
        'Power', 2100, ...
        'Current', 4.0, ...
        'BlockingCurrent', 17.0, ...      % workbook: '>17' A
        'Power_Y', NaN, 'Current_Y', NaN, 'BlockingCurrent_Y', NaN) ...
    struct( ...
        'Size', 'H8', ...
        'Frequency', 60, ...
        'Fan', '', ...
        'Voltage', '400-500', ...
        'Tolerance', '+/-10', ...
        'Connection', 'Delta', ...
        'Power', 3000, ...
        'Current', 5.3, ...
        'BlockingCurrent', 15.0, ...      % workbook: '>15' A
        'Power_Y', NaN, 'Current_Y', NaN, 'BlockingCurrent_Y', NaN) ...
    ];

%% No blanket "missing size" warning here: DCS880_FieldDatabase lists
%% frame sizes (H3, H4) that permanently have no fan entry, by design --
%% see the header note above. Warning unconditionally on every call
%% (every excitation_calculation() run, whether or not the design
%% actually selects H3/H4) would just be noise. The relevant,
%% context-aware warning already exists where it belongs: excitation_
%% calculation.m's sizeExcitationChain() only warns (via R.FanWarning /
%% E.Warning) when a design's OWN DCS880 selection actually lands on a
%% Size/Frequency combination this table has no entry for.

end
