function DB = OV_ThyristorDatabase()
%OV_THYRISTORDATABASE  Thyristor ratings used by the overvoltage-protection
%calculation (VDRM, VT0, rT, thermal resistances, DeltaTheta).
%
%   DB = OV_ThyristorDatabase() returns a struct array, one entry per
%   thyristor type, with fields:
%     Type, VDRM, VT0, rT, Rth_jc, Rth_ch, Rth_ha, DeltaTheta
%
%   Data values are unchanged from the original.

DB(1) = struct( ...
    'Type', '3in_2800V', ...
    'VDRM', 2800, ...
    'VT0', 0.85, ...
    'rT', 1.6e-4, ...
    'Rth_jc', 0.0120, ...
    'Rth_ch', 0.0050, ...
    'Rth_ha', 0.0120, ...
    'DeltaTheta', 70);

DB(2) = struct( ...
    'Type', '4in_5200V', ...
    'VDRM', 5200, ...
    'VT0', 1.03, ...
    'rT', 1.7e-4, ...
    'Rth_jc', 0.0057, ...
    'Rth_ch', 0.0010, ...
    'Rth_ha', 0.0068, ...
    'DeltaTheta', 70);

DB(3) = struct( ...
    'Type', '4in_6500V', ...
    'VDRM', 6500, ...
    'VT0', 1.02, ...
    'rT', 2.9e-4, ...
    'Rth_jc', 0.0057, ...
    'Rth_ch', 0.0010, ...
    'Rth_ha', 0.0068, ...
    'DeltaTheta', 70);

%% Validation: catch a malformed entry before it reaches the calculation
requiredFields = {'Type','VDRM','VT0','rT','Rth_jc','Rth_ch','Rth_ha','DeltaTheta'};
for k = 1:numel(DB)
    missing = requiredFields(~isfield(DB(k), requiredFields));
    if ~isempty(missing)
        error('OV_ThyristorDatabase:MissingFields', ...
            'Entry %d (%s) is missing field(s): %s', ...
            k, DB(k).Type, strjoin(missing, ', '));
    end
end

end
