function PeakSel = PeakSelectionDialog()

PeakSel = [];

d = uifigure( ...
    'Name','Peak Operating Point', ...
    'Position',[500 300 400 250], ...
    'WindowStyle','modal');

uilabel(d,...
    'Text','I1S Operating Point',...
    'Position',[20 180 150 22]);

ddI1S = uidropdown(d,...
    'Items',{'nom','ovld','start'},...
    'Value','nom',...
    'Position',[180 180 150 22]);

uilabel(d,...
    'Text','IM Operating Point',...
    'Position',[20 130 150 22]);

ddIM = uidropdown(d,...
    'Items',{'nom','ovld','ovld_ul','start'},...
    'Value','nom',...
    'Position',[180 130 150 22]);

uilabel(d,...
    'Text','uL Operating Point',...
    'Position',[20 80 150 22]);

dduL = uidropdown(d,...
    'Items',{'nom','unity'},...
    'Value','nom',...
    'Position',[180 80 150 22]);

uibutton(d,...
    'Text','OK',...
    'Position',[150 20 100 30],...
    'ButtonPushedFcn',@okFcn);

uiwait(d);

    function okFcn(~,~)

        PeakSel = struct();

        PeakSel.I1S = ddI1S.Value;
        PeakSel.IM  = ddIM.Value;
        PeakSel.uL  = dduL.Value;

        uiresume(d);
        delete(d);

    end

end